#ifndef GUARD_CONSTANTS_BATTLE_TENT_H
#define GUARD_CONSTANTS_BATTLE_TENT_H

#define TENT_MIN_LEVEL 30

// The number of battles in each Battle Tent challenge.
// Battle Tent equivalent of FRONTIER_STAGES_PER_CHALLENGE.
#define TENT_STAGES_PER_CHALLENGE  3

#define FUCHSIA_TENT_FUNC_INIT                0
#define FUCHSIA_TENT_FUNC_GET_PRIZE           1
#define FUCHSIA_TENT_FUNC_SET_PRIZE           2
#define FUCHSIA_TENT_FUNC_SET_OPPONENT_GFX    3
#define FUCHSIA_TENT_FUNC_GET_OPPONENT_INTRO  4
#define FUCHSIA_TENT_FUNC_SAVE                5
#define FUCHSIA_TENT_FUNC_SET_RANDOM_PRIZE    6
#define FUCHSIA_TENT_FUNC_GIVE_PRIZE          7

#define SAFFRON_TENT_FUNC_INIT               0
#define SAFFRON_TENT_FUNC_GET_PRIZE          1
#define SAFFRON_TENT_FUNC_SET_PRIZE          2
#define SAFFRON_TENT_FUNC_SAVE               3
#define SAFFRON_TENT_FUNC_SET_RANDOM_PRIZE   4
#define SAFFRON_TENT_FUNC_GIVE_PRIZE         5
#define SAFFRON_TENT_FUNC_GET_OPPONENT_NAME  6

#define CERULEAN_TENT_FUNC_INIT                    0
#define CERULEAN_TENT_FUNC_GET_PRIZE               1
#define CERULEAN_TENT_FUNC_SET_PRIZE               2
#define CERULEAN_TENT_FUNC_SAVE                    3
#define CERULEAN_TENT_FUNC_SET_RANDOM_PRIZE        4
#define CERULEAN_TENT_FUNC_GIVE_PRIZE              5
#define CERULEAN_TENT_FUNC_SELECT_RENT_MONS        6
#define CERULEAN_TENT_FUNC_SWAP_RENT_MONS          7
#define CERULEAN_TENT_FUNC_GENERATE_OPPONENT_MONS  8
#define CERULEAN_TENT_FUNC_GENERATE_RENTAL_MONS    9

#endif // GUARD_CONSTANTS_BATTLE_TENT_H
