#ifndef GUARD_HOLD_EFFECTS_H
#define GUARD_HOLD_EFFECTS_H

#define HOLD_EFFECT_NONE            0
#define HOLD_EFFECT_RESTORE_HP      1
#define HOLD_EFFECT_CURE_PAR        2
#define HOLD_EFFECT_CURE_SLP        3
#define HOLD_EFFECT_CURE_PSN        4
#define HOLD_EFFECT_CURE_BRN        5
#define HOLD_EFFECT_CURE_FRZ        6
#define HOLD_EFFECT_RESTORE_PP      7
#define HOLD_EFFECT_CURE_CONFUSION  8
#define HOLD_EFFECT_CURE_STATUS     9
#define HOLD_EFFECT_CONFUSE_SPICY  10
#define HOLD_EFFECT_CONFUSE_DRY    11
#define HOLD_EFFECT_CONFUSE_SWEET  12
#define HOLD_EFFECT_CONFUSE_BITTER 13
#define HOLD_EFFECT_CONFUSE_SOUR   14
#define HOLD_EFFECT_ATTACK_UP      15
#define HOLD_EFFECT_DEFENSE_UP     16
#define HOLD_EFFECT_SPEED_UP       17
#define HOLD_EFFECT_SP_ATTACK_UP   18
#define HOLD_EFFECT_SP_DEFENSE_UP  19
#define HOLD_EFFECT_CRITICAL_UP    20
#define HOLD_EFFECT_RANDOM_STAT_UP 21
#define HOLD_EFFECT_EVASION_UP     22
#define HOLD_EFFECT_RESTORE_STATS  23
#define HOLD_EFFECT_MACHO_BRACE    24
#define HOLD_EFFECT_EXP_SHARE      25
#define HOLD_EFFECT_QUICK_CLAW     26
#define HOLD_EFFECT_FRIENDSHIP_UP  27
#define HOLD_EFFECT_MENTAL_HERB    28
#define HOLD_EFFECT_CHOICE_BAND    29
#define HOLD_EFFECT_FLINCH         30
#define HOLD_EFFECT_BUG_POWER      31
#define HOLD_EFFECT_DOUBLE_PRIZE   32
#define HOLD_EFFECT_REPEL          33
#define HOLD_EFFECT_CAN_ALWAYS_RUN 34
#define HOLD_EFFECT_PREVENT_EVOLVE 35
#define HOLD_EFFECT_FOCUS_BAND     36
#define HOLD_EFFECT_LUCKY_EGG      37
#define HOLD_EFFECT_SCOPE_LENS     38
#define HOLD_EFFECT_STEEL_POWER    39
#define HOLD_EFFECT_LEFTOVERS      40
#define HOLD_EFFECT_DRAGON_SCALE   41
#define HOLD_EFFECT_LIGHT_BALL     42
#define HOLD_EFFECT_GROUND_POWER   43
#define HOLD_EFFECT_ROCK_POWER     44
#define HOLD_EFFECT_GRASS_POWER    45
#define HOLD_EFFECT_DARK_POWER     46
#define HOLD_EFFECT_FIGHTING_POWER 47
#define HOLD_EFFECT_ELECTRIC_POWER 48
#define HOLD_EFFECT_WATER_POWER    49
#define HOLD_EFFECT_FLYING_POWER   50
#define HOLD_EFFECT_POISON_POWER   51
#define HOLD_EFFECT_ICE_POWER      52
#define HOLD_EFFECT_GHOST_POWER    53
#define HOLD_EFFECT_PSYCHIC_POWER  54
#define HOLD_EFFECT_FIRE_POWER     55
#define HOLD_EFFECT_DRAGON_POWER   56
#define HOLD_EFFECT_NORMAL_POWER   57
#define HOLD_EFFECT_UPGRADE        58
#define HOLD_EFFECT_SHELL_BELL     59
#define HOLD_EFFECT_LUCKY_PUNCH    60
#define HOLD_EFFECT_METAL_POWDER   61
#define HOLD_EFFECT_THICK_CLUB     62
#define HOLD_EFFECT_LEEK           63

// Gen4 hold effects
#define HOLD_EFFECT_CHOICE_SCARF   64
#define HOLD_EFFECT_CHOICE_SPECS   65
#define HOLD_EFFECT_DAMP_ROCK      66
#define HOLD_EFFECT_GRIP_CLAW      67
#define HOLD_EFFECT_HEAT_ROCK      68
#define HOLD_EFFECT_ICY_ROCK       69
#define HOLD_EFFECT_LIGHT_CLAY     70
#define HOLD_EFFECT_SMOOTH_ROCK    71
#define HOLD_EFFECT_POWER_HERB     72
#define HOLD_EFFECT_BIG_ROOT       73
#define HOLD_EFFECT_EXPERT_BELT    74
#define HOLD_EFFECT_LIFE_ORB       75
#define HOLD_EFFECT_METRONOME      76
#define HOLD_EFFECT_MUSCLE_BAND    77
#define HOLD_EFFECT_WIDE_LENS      78
#define HOLD_EFFECT_WISE_GLASSES   79
#define HOLD_EFFECT_ZOOM_LENS      80
#define HOLD_EFFECT_LAGGING_TAIL   81
#define HOLD_EFFECT_FOCUS_SASH     82
#define HOLD_EFFECT_FLAME_ORB      83
#define HOLD_EFFECT_TOXIC_ORB      84
#define HOLD_EFFECT_STICKY_BARB    85
#define HOLD_EFFECT_IRON_BALL      86
#define HOLD_EFFECT_BLACK_SLUDGE   87
#define HOLD_EFFECT_DESTINY_KNOT   88
#define HOLD_EFFECT_SHED_SHELL     89
#define HOLD_EFFECT_QUICK_POWDER   90
#define HOLD_EFFECT_ENIGMA_BERRY   91
#define HOLD_EFFECT_RESIST_BERRY   92
#define HOLD_EFFECT_POWER_ITEM     93
#define HOLD_EFFECT_RESTORE_PCT_HP 94
#define HOLD_EFFECT_MICLE_BERRY    95
#define HOLD_EFFECT_CUSTAP_BERRY   96
#define HOLD_EFFECT_JABOCA_BERRY   97
#define HOLD_EFFECT_ROWAP_BERRY    98
#define HOLD_EFFECT_KEE_BERRY      99
#define HOLD_EFFECT_MARANGA_BERRY  100

// Gen5 hold effects
#define HOLD_EFFECT_FLOAT_STONE    101
#define HOLD_EFFECT_EVIOLITE       102
#define HOLD_EFFECT_ASSAULT_VEST   103
#define HOLD_EFFECT_GEMS           104
#define HOLD_EFFECT_ROCKY_HELMET   105
#define HOLD_EFFECT_AIR_BALLOON    106
#define HOLD_EFFECT_RED_CARD       107
#define HOLD_EFFECT_RING_TARGET    108
#define HOLD_EFFECT_BINDING_BAND   109
#define HOLD_EFFECT_EJECT_BUTTON   110
#define HOLD_EFFECT_ABSORB_BULB    111
#define HOLD_EFFECT_CELL_BATTERY   112

// Gen6 hold effects
#define HOLD_EFFECT_FAIRY_POWER     113
#define HOLD_EFFECT_SAFETY_GOGGLES  114
#define HOLD_EFFECT_LUMINOUS_MOSS   115
#define HOLD_EFFECT_SNOWBALL        116
#define HOLD_EFFECT_WEAKNESS_POLICY 117

// Gen7 hold effects
#define HOLD_EFFECT_PROTECTIVE_PADS  118
#define HOLD_EFFECT_TERRAIN_EXTENDER 119
#define HOLD_EFFECT_SEEDS            120
#define HOLD_EFFECT_ADRENALINE_ORB   121

#define HOLD_EFFECT_CHOICE(holdEffect)((holdEffect == HOLD_EFFECT_CHOICE_BAND || holdEffect == HOLD_EFFECT_CHOICE_SCARF || holdEffect == HOLD_EFFECT_CHOICE_SPECS))

// Terrain seed params
#define HOLD_EFFECT_PARAM_ELECTRIC_TERRAIN  0
#define HOLD_EFFECT_PARAM_GRASSY_TERRAIN    1
#define HOLD_EFFECT_PARAM_MISTY_TERRAIN     2
#define HOLD_EFFECT_PARAM_PSYCHIC_TERRAIN   3

#endif // GUARD_HOLD_EFFECTS_H
