#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_Link
#define MAP_TRADE_CENTER        (0 | (0 << 8))
#define MAP_UNION_ROOM          (1 | (0 << 8))
#define MAP_RECORD_CORNER       (2 | (0 << 8))
#define MAP_BATTLE_COLOSSEUM_2P (3 | (0 << 8))
#define MAP_BATTLE_COLOSSEUM_4P (4 | (0 << 8))

// gMapGroup_Dungeons
#define MAP_VIRIDIAN_FOREST                     (0 | (1 << 8))
#define MAP_MT_MOON_1F                          (1 | (1 << 8))
#define MAP_MT_MOON_B1F                         (2 | (1 << 8))
#define MAP_MT_MOON_B2F                         (3 | (1 << 8))
#define MAP_SSANNE_EXTERIOR                     (4 | (1 << 8))
#define MAP_SSANNE_1F_CORRIDOR                  (5 | (1 << 8))
#define MAP_SSANNE_2F_CORRIDOR                  (6 | (1 << 8))
#define MAP_SSANNE_3F_CORRIDOR                  (7 | (1 << 8))
#define MAP_SSANNE_B1F_CORRIDOR                 (8 | (1 << 8))
#define MAP_SSANNE_DECK                         (9 | (1 << 8))
#define MAP_SSANNE_KITCHEN                      (10 | (1 << 8))
#define MAP_SSANNE_CAPTAINS_OFFICE              (11 | (1 << 8))
#define MAP_SSANNE_1F_ROOM1                     (12 | (1 << 8))
#define MAP_SSANNE_1F_ROOM2                     (13 | (1 << 8))
#define MAP_SSANNE_1F_ROOM3                     (14 | (1 << 8))
#define MAP_SSANNE_1F_ROOM4                     (15 | (1 << 8))
#define MAP_SSANNE_1F_ROOM5                     (16 | (1 << 8))
#define MAP_SSANNE_1F_ROOM6                     (17 | (1 << 8))
#define MAP_SSANNE_1F_ROOM7                     (18 | (1 << 8))
#define MAP_SSANNE_2F_ROOM1                     (19 | (1 << 8))
#define MAP_SSANNE_2F_ROOM2                     (20 | (1 << 8))
#define MAP_SSANNE_2F_ROOM3                     (21 | (1 << 8))
#define MAP_SSANNE_2F_ROOM4                     (22 | (1 << 8))
#define MAP_SSANNE_2F_ROOM5                     (23 | (1 << 8))
#define MAP_SSANNE_2F_ROOM6                     (24 | (1 << 8))
#define MAP_SSANNE_B1F_ROOM1                    (25 | (1 << 8))
#define MAP_SSANNE_B1F_ROOM2                    (26 | (1 << 8))
#define MAP_SSANNE_B1F_ROOM3                    (27 | (1 << 8))
#define MAP_SSANNE_B1F_ROOM4                    (28 | (1 << 8))
#define MAP_SSANNE_B1F_ROOM5                    (29 | (1 << 8))
#define MAP_DIGLETTS_CAVE_NORTH_ENTRANCE        (30 | (1 << 8))
#define MAP_DIGLETTS_CAVE_B1F                   (31 | (1 << 8))
#define MAP_DIGLETTS_CAVE_SOUTH_ENTRANCE        (32 | (1 << 8))
#define MAP_ROCK_TUNNEL_1F                      (33 | (1 << 8))
#define MAP_ROCK_TUNNEL_B1F                     (34 | (1 << 8))
#define MAP_POKEMON_TOWER_1F                    (35 | (1 << 8))
#define MAP_POKEMON_TOWER_2F                    (36 | (1 << 8))
#define MAP_POKEMON_TOWER_3F                    (37 | (1 << 8))
#define MAP_POKEMON_TOWER_4F                    (38 | (1 << 8))
#define MAP_POKEMON_TOWER_5F                    (39 | (1 << 8))
#define MAP_POKEMON_TOWER_6F                    (40 | (1 << 8))
#define MAP_POKEMON_TOWER_7F                    (41 | (1 << 8))
#define MAP_UNDERGROUND_PATH_NORTH_ENTRANCE     (42 | (1 << 8))
#define MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL (43 | (1 << 8))
#define MAP_UNDERGROUND_PATH_SOUTH_ENTRANCE     (44 | (1 << 8))
#define MAP_UNDERGROUND_PATH_WEST_ENTRANCE      (45 | (1 << 8))
#define MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL   (46 | (1 << 8))
#define MAP_UNDERGROUND_PATH_EAST_ENTRANCE      (47 | (1 << 8))
#define MAP_ROCKET_HIDEOUT_B1F                  (48 | (1 << 8))
#define MAP_ROCKET_HIDEOUT_B2F                  (49 | (1 << 8))
#define MAP_ROCKET_HIDEOUT_B3F                  (50 | (1 << 8))
#define MAP_ROCKET_HIDEOUT_B4F                  (51 | (1 << 8))
#define MAP_ROCKET_HIDEOUT_ELEVATOR             (52 | (1 << 8))
#define MAP_SILPH_CO_1F                         (53 | (1 << 8))
#define MAP_SILPH_CO_2F                         (54 | (1 << 8))
#define MAP_SILPH_CO_3F                         (55 | (1 << 8))
#define MAP_SILPH_CO_4F                         (56 | (1 << 8))
#define MAP_SILPH_CO_5F                         (57 | (1 << 8))
#define MAP_SILPH_CO_6F                         (58 | (1 << 8))
#define MAP_SILPH_CO_7F                         (59 | (1 << 8))
#define MAP_SILPH_CO_8F                         (60 | (1 << 8))
#define MAP_SILPH_CO_9F                         (61 | (1 << 8))
#define MAP_SILPH_CO_10F                        (62 | (1 << 8))
#define MAP_SILPH_CO_11F                        (63 | (1 << 8))
#define MAP_SILPH_CO_ELEVATOR                   (64 | (1 << 8))
#define MAP_SEAFOAM_ISLANDS_1F                  (65 | (1 << 8))
#define MAP_SEAFOAM_ISLANDS_B1F                 (66 | (1 << 8))
#define MAP_SEAFOAM_ISLANDS_B2F                 (67 | (1 << 8))
#define MAP_SEAFOAM_ISLANDS_B3F                 (68 | (1 << 8))
#define MAP_SEAFOAM_ISLANDS_B4F                 (69 | (1 << 8))
#define MAP_POWER_PLANT                         (70 | (1 << 8))
#define MAP_POKEMON_MANSION_1F                  (71 | (1 << 8))
#define MAP_POKEMON_MANSION_2F                  (72 | (1 << 8))
#define MAP_POKEMON_MANSION_3F                  (73 | (1 << 8))
#define MAP_POKEMON_MANSION_B1F                 (74 | (1 << 8))
#define MAP_VICTORY_ROAD_1F                     (75 | (1 << 8))
#define MAP_VICTORY_ROAD_2F                     (76 | (1 << 8))
#define MAP_VICTORY_ROAD_3F                     (77 | (1 << 8))
#define MAP_CERULEAN_CAVE_1F                    (78 | (1 << 8))
#define MAP_CERULEAN_CAVE_2F                    (79 | (1 << 8))
#define MAP_CERULEAN_CAVE_B1F                   (80 | (1 << 8))

// gMapGroup_Dungeons2
#define MAP_MT_EMBER_EXTERIOR             (0 | (2 << 8))
#define MAP_MT_EMBER_SUMMIT_PATH_1F       (1 | (2 << 8))
#define MAP_MT_EMBER_SUMMIT_PATH_2F       (2 | (2 << 8))
#define MAP_MT_EMBER_SUMMIT_PATH_3F       (3 | (2 << 8))
#define MAP_MT_EMBER_SUMMIT               (4 | (2 << 8))
#define MAP_MT_EMBER_RUBY_PATH_1F         (5 | (2 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B1F        (6 | (2 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B2F        (7 | (2 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B3F        (8 | (2 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B4F        (9 | (2 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B5F        (10 | (2 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B1F_STAIRS (11 | (2 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B2F_STAIRS (12 | (2 << 8))
#define MAP_BERRY_FOREST                  (13 | (2 << 8))
#define MAP_ICEFALL_CAVE_ENTRANCE         (14 | (2 << 8))
#define MAP_ICEFALL_CAVE_1F               (15 | (2 << 8))
#define MAP_ICEFALL_CAVE_B1F              (16 | (2 << 8))
#define MAP_ICEFALL_CAVE_BACK             (17 | (2 << 8))
#define MAP_ROCKET_WAREHOUSE              (18 | (2 << 8))
#define MAP_LOST_CAVE_ENTRANCE            (19 | (2 << 8))
#define MAP_LOST_CAVE_ROOM1               (20 | (2 << 8))
#define MAP_LOST_CAVE_ROOM2               (21 | (2 << 8))
#define MAP_LOST_CAVE_ROOM3               (22 | (2 << 8))
#define MAP_LOST_CAVE_ROOM4               (23 | (2 << 8))
#define MAP_LOST_CAVE_ROOM5               (24 | (2 << 8))
#define MAP_LOST_CAVE_ROOM6               (25 | (2 << 8))
#define MAP_LOST_CAVE_ROOM7               (26 | (2 << 8))
#define MAP_LOST_CAVE_ROOM8               (27 | (2 << 8))
#define MAP_LOST_CAVE_ROOM9               (28 | (2 << 8))
#define MAP_LOST_CAVE_ROOM10              (29 | (2 << 8))
#define MAP_LOST_CAVE_ROOM11              (30 | (2 << 8))
#define MAP_LOST_CAVE_ROOM12              (31 | (2 << 8))
#define MAP_LOST_CAVE_ROOM13              (32 | (2 << 8))
#define MAP_LOST_CAVE_ROOM14              (33 | (2 << 8))
#define MAP_DOTTED_HOLE_1F                (34 | (2 << 8))
#define MAP_DOTTED_HOLE_B1F               (35 | (2 << 8))
#define MAP_DOTTED_HOLE_B2F               (36 | (2 << 8))
#define MAP_DOTTED_HOLE_B3F               (37 | (2 << 8))
#define MAP_DOTTED_HOLE_B4F               (38 | (2 << 8))
#define MAP_DOTTED_HOLE_SAPPHIRE_ROOM     (39 | (2 << 8))
#define MAP_PATTERN_BUSH                  (40 | (2 << 8))
#define MAP_ALTERING_CAVE                 (41 | (2 << 8))
#define MAP_SEVAULT_CANYON_TANOBY_KEY     (42 | (2 << 8))
#define MAP_TANOBY_RUINS_MONEAN_CHAMBER   (43 | (2 << 8))
#define MAP_TANOBY_RUINS_LIPTOO_CHAMBER   (44 | (2 << 8))
#define MAP_TANOBY_RUINS_WEEPTH_CHAMBER   (45 | (2 << 8))
#define MAP_TANOBY_RUINS_DILFORD_CHAMBER  (46 | (2 << 8))
#define MAP_TANOBY_RUINS_SCUFIB_CHAMBER   (47 | (2 << 8))
#define MAP_TANOBY_RUINS_RIXY_CHAMBER     (48 | (2 << 8))
#define MAP_TANOBY_RUINS_VIAPOIS_CHAMBER  (49 | (2 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_CENTER                              (0 | (3 << 8))
#define MAP_SAFARI_ZONE_EAST                                (1 | (3 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (2 | (3 << 8))
#define MAP_SAFARI_ZONE_WEST                                (3 | (3 << 8))
#define MAP_SAFARI_ZONE_CENTER_REST_HOUSE                   (4 | (3 << 8))
#define MAP_SAFARI_ZONE_EAST_REST_HOUSE                     (5 | (3 << 8))
#define MAP_SAFARI_ZONE_NORTH_REST_HOUSE                    (6 | (3 << 8))
#define MAP_SAFARI_ZONE_WEST_REST_HOUSE                     (7 | (3 << 8))
#define MAP_SAFARI_ZONE_SECRET_HOUSE                        (8 | (3 << 8))
#define MAP_TRAINER_TOWER_LOBBY                             (9 | (3 << 8))
#define MAP_TRAINER_TOWER_1F                                (10 | (3 << 8))
#define MAP_TRAINER_TOWER_2F                                (11 | (3 << 8))
#define MAP_TRAINER_TOWER_3F                                (12 | (3 << 8))
#define MAP_TRAINER_TOWER_4F                                (13 | (3 << 8))
#define MAP_TRAINER_TOWER_ROOF                              (14 | (3 << 8))
#define MAP_TRAINER_TOWER_ELEVATOR                          (15 | (3 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (16 | (3 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (17 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (18 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (19 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (20 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (21 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (22 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (23 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (24 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (25 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (26 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (27 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (28 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (29 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (30 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (31 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (32 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (33 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01                         (34 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02                         (35 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03                         (36 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04                         (37 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05                         (38 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06                         (39 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07                         (40 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08                         (41 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09                         (42 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10                         (43 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11                         (44 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12                         (45 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13                         (46 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14                         (47 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15                         (48 | (3 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16                         (49 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (50 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (51 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (52 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (53 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (54 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (55 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (56 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (57 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (58 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (59 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (60 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (61 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (62 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (63 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (64 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (65 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (66 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (67 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (68 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (69 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (70 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (71 | (3 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (72 | (3 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (73 | (3 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (74 | (3 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (75 | (3 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (76 | (3 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (77 | (3 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (78 | (3 << 8))
#define MAP_ARTISAN_CAVE_B1F                                (79 | (3 << 8))
#define MAP_ARTISAN_CAVE_1F                                 (80 | (3 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (81 | (3 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (82 | (3 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (83 | (3 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (84 | (3 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (85 | (3 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (86 | (3 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (87 | (3 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (88 | (3 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (89 | (3 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (90 | (3 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (91 | (3 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (92 | (3 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (93 | (3 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (94 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (95 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (96 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (97 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (98 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (99 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (100 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (101 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (102 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (103 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (104 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (105 | (3 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (106 | (3 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (107 | (3 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (108 | (3 << 8))

// gMapGroup_DynamicArea
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY        (0 | (4 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR     (1 | (4 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM  (2 | (4 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (3 | (4 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (4 | (4 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (5 | (4 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY        (6 | (4 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR     (7 | (4 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM  (8 | (4 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (9 | (4 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (10 | (4 << 8))
#define MAP_CONTEST_HALL                            (11 | (4 << 8))
#define MAP_CONTEST_HALL_BEAUTY                     (12 | (4 << 8))
#define MAP_CONTEST_HALL_TOUGH                      (13 | (4 << 8))
#define MAP_CONTEST_HALL_COOL                       (14 | (4 << 8))
#define MAP_CONTEST_HALL_SMART                      (15 | (4 << 8))
#define MAP_CONTEST_HALL_CUTE                       (16 | (4 << 8))
#define MAP_TRICK_HOUSE_ENTRANCE                    (17 | (4 << 8))
#define MAP_TRICK_HOUSE_END                         (18 | (4 << 8))
#define MAP_TRICK_HOUSE_CORRIDOR                    (19 | (4 << 8))
#define MAP_TRICK_HOUSE_PUZZLE1                     (20 | (4 << 8))
#define MAP_TRICK_HOUSE_PUZZLE2                     (21 | (4 << 8))
#define MAP_TRICK_HOUSE_PUZZLE3                     (22 | (4 << 8))
#define MAP_TRICK_HOUSE_PUZZLE4                     (23 | (4 << 8))
#define MAP_TRICK_HOUSE_PUZZLE5                     (24 | (4 << 8))
#define MAP_TRICK_HOUSE_PUZZLE6                     (25 | (4 << 8))
#define MAP_TRICK_HOUSE_PUZZLE7                     (26 | (4 << 8))
#define MAP_TRICK_HOUSE_PUZZLE8                     (27 | (4 << 8))
#define MAP_SECRET_BASE_RED_CAVE1                   (28 | (4 << 8))
#define MAP_SECRET_BASE_RED_CAVE2                   (29 | (4 << 8))
#define MAP_SECRET_BASE_RED_CAVE3                   (30 | (4 << 8))
#define MAP_SECRET_BASE_RED_CAVE4                   (31 | (4 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1                 (32 | (4 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2                 (33 | (4 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3                 (34 | (4 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4                 (35 | (4 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1                  (36 | (4 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2                  (37 | (4 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3                  (38 | (4 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4                  (39 | (4 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1                (40 | (4 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2                (41 | (4 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3                (42 | (4 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4                (43 | (4 << 8))
#define MAP_SECRET_BASE_TREE1                       (44 | (4 << 8))
#define MAP_SECRET_BASE_TREE2                       (45 | (4 << 8))
#define MAP_SECRET_BASE_TREE3                       (46 | (4 << 8))
#define MAP_SECRET_BASE_TREE4                       (47 | (4 << 8))
#define MAP_SECRET_BASE_SHRUB1                      (48 | (4 << 8))
#define MAP_SECRET_BASE_SHRUB2                      (49 | (4 << 8))
#define MAP_SECRET_BASE_SHRUB3                      (50 | (4 << 8))
#define MAP_SECRET_BASE_SHRUB4                      (51 | (4 << 8))

// gMapGroup_TownsAndRoutes
#define MAP_PALLET_TOWN             (0 | (5 << 8))
#define MAP_VIRIDIAN_CITY           (1 | (5 << 8))
#define MAP_PEWTER_CITY             (2 | (5 << 8))
#define MAP_CERULEAN_CITY           (3 | (5 << 8))
#define MAP_VERMILION_CITY          (4 | (5 << 8))
#define MAP_LAVENDER_TOWN           (5 | (5 << 8))
#define MAP_CELADON_CITY            (6 | (5 << 8))
#define MAP_FUCHSIA_CITY            (7 | (5 << 8))
#define MAP_SAFFRON_CITY            (8 | (5 << 8))
#define MAP_CINNABAR_ISLAND         (9 | (5 << 8))
#define MAP_INDIGO_PLATEAU          (10 | (5 << 8))
#define MAP_ONE_ISLAND              (11 | (5 << 8))
#define MAP_TWO_ISLAND              (12 | (5 << 8))
#define MAP_THREE_ISLAND            (13 | (5 << 8))
#define MAP_FOUR_ISLAND             (14 | (5 << 8))
#define MAP_FIVE_ISLAND             (15 | (5 << 8))
#define MAP_SIX_ISLAND              (16 | (5 << 8))
#define MAP_SEVEN_ISLAND            (17 | (5 << 8))
#define MAP_ROUTE1                  (18 | (5 << 8))
#define MAP_ROUTE2                  (19 | (5 << 8))
#define MAP_ROUTE3                  (20 | (5 << 8))
#define MAP_ROUTE4                  (21 | (5 << 8))
#define MAP_ROUTE5                  (22 | (5 << 8))
#define MAP_ROUTE6                  (23 | (5 << 8))
#define MAP_ROUTE7                  (24 | (5 << 8))
#define MAP_ROUTE8                  (25 | (5 << 8))
#define MAP_ROUTE9                  (26 | (5 << 8))
#define MAP_ROUTE10                 (27 | (5 << 8))
#define MAP_ROUTE11                 (28 | (5 << 8))
#define MAP_ROUTE12                 (29 | (5 << 8))
#define MAP_ROUTE13                 (30 | (5 << 8))
#define MAP_ROUTE14                 (31 | (5 << 8))
#define MAP_ROUTE15                 (32 | (5 << 8))
#define MAP_ROUTE16                 (33 | (5 << 8))
#define MAP_ROUTE17                 (34 | (5 << 8))
#define MAP_ROUTE18                 (35 | (5 << 8))
#define MAP_ROUTE19                 (36 | (5 << 8))
#define MAP_ROUTE20                 (37 | (5 << 8))
#define MAP_ROUTE21                 (38 | (5 << 8))
#define MAP_ROUTE22                 (39 | (5 << 8))
#define MAP_ROUTE23                 (40 | (5 << 8))
#define MAP_ROUTE24                 (41 | (5 << 8))
#define MAP_ROUTE25                 (42 | (5 << 8))
#define MAP_TREASURE_BEACH          (43 | (5 << 8))
#define MAP_KINDLE_ROAD             (44 | (5 << 8))
#define MAP_KINDLE_ROAD_EMBER_SPA   (45 | (5 << 8))
#define MAP_CAPE_BRINK              (46 | (5 << 8))
#define MAP_THREE_ISLAND_PORT       (47 | (5 << 8))
#define MAP_THREE_ISLAND_PATH       (48 | (5 << 8))
#define MAP_BOND_BRIDGE             (49 | (5 << 8))
#define MAP_FIVE_ISLAND_MEADOW      (50 | (5 << 8))
#define MAP_MEMORIAL_PILLAR         (51 | (5 << 8))
#define MAP_WATER_LABYRINTH         (52 | (5 << 8))
#define MAP_RESORT_GORGEOUS         (53 | (5 << 8))
#define MAP_WATER_PATH              (54 | (5 << 8))
#define MAP_RUIN_VALLEY             (55 | (5 << 8))
#define MAP_GREEN_PATH              (56 | (5 << 8))
#define MAP_OUTCAST_ISLAND          (57 | (5 << 8))
#define MAP_TRAINER_TOWER_EXTERIOR  (58 | (5 << 8))
#define MAP_SEVAULT_CANYON_ENTRANCE (59 | (5 << 8))
#define MAP_SEVAULT_CANYON          (60 | (5 << 8))
#define MAP_TANOBY_RUINS            (61 | (5 << 8))

// gMapGroup_IndoorPallet
#define MAP_PLAYERS_HOUSE_1F   (0 | (6 << 8))
#define MAP_PLAYERS_HOUSE_2F   (1 | (6 << 8))
#define MAP_RIVALS_HOUSE       (2 | (6 << 8))
#define MAP_PROFESSOR_OAKS_LAB (3 | (6 << 8))

// gMapGroup_IndoorViridian
#define MAP_VIRIDIAN_CITY_POKEMON_CENTER_1F (0 | (7 << 8))
#define MAP_VIRIDIAN_CITY_POKEMON_CENTER_2F (1 | (7 << 8))
#define MAP_VIRIDIAN_CITY_MART              (2 | (7 << 8))
#define MAP_VIRIDIAN_CITY_GYM               (3 | (7 << 8))
#define MAP_VIRIDIAN_CITY_HOUSE1            (4 | (7 << 8))
#define MAP_VIRIDIAN_CITY_HOUSE2            (5 | (7 << 8))

// gMapGroup_IndoorPewter
#define MAP_PEWTER_CITY_POKEMON_CENTER_1F (0 | (8 << 8))
#define MAP_PEWTER_CITY_POKEMON_CENTER_2F (1 | (8 << 8))
#define MAP_PEWTER_CITY_MART              (2 | (8 << 8))
#define MAP_PEWTER_CITY_GYM               (3 | (8 << 8))
#define MAP_PEWTER_CITY_MUSEUM_1F         (4 | (8 << 8))
#define MAP_PEWTER_CITY_MUSEUM_2F         (5 | (8 << 8))
#define MAP_PEWTER_CITY_HOUSE1            (6 | (8 << 8))
#define MAP_PEWTER_CITY_HOUSE2            (7 | (8 << 8))

// gMapGroup_IndoorCerulean
#define MAP_CERULEAN_CITY_POKEMON_CENTER_1F (0 | (9 << 8))
#define MAP_CERULEAN_CITY_POKEMON_CENTER_2F (1 | (9 << 8))
#define MAP_CERULEAN_CITY_MART              (2 | (9 << 8))
#define MAP_CERULEAN_CITY_GYM               (3 | (9 << 8))
#define MAP_CERULEAN_CITY_BIKE_SHOP         (4 | (9 << 8))
#define MAP_CERULEAN_CITY_HOUSE1            (5 | (9 << 8))
#define MAP_CERULEAN_CITY_HOUSE2            (6 | (9 << 8))
#define MAP_CERULEAN_CITY_HOUSE3            (7 | (9 << 8))
#define MAP_CERULEAN_CITY_HOUSE4            (8 | (9 << 8))
#define MAP_CERULEAN_CITY_HOUSE5            (9 | (9 << 8))

// gMapGroup_IndoorVermilion
#define MAP_VERMILION_CITY_POKEMON_CENTER_1F (0 | (10 << 8))
#define MAP_VERMILION_CITY_POKEMON_CENTER_2F (1 | (10 << 8))
#define MAP_VERMILION_CITY_MART              (2 | (10 << 8))
#define MAP_VERMILION_CITY_GYM               (3 | (10 << 8))
#define MAP_VERMILION_CITY_POKEMON_FAN_CLUB  (4 | (10 << 8))
#define MAP_VERMILION_CITY_HOUSE1            (5 | (10 << 8))
#define MAP_VERMILION_CITY_HOUSE2            (6 | (10 << 8))
#define MAP_VERMILION_CITY_HOUSE3            (7 | (10 << 8))

// gMapGroup_IndoorLavender
#define MAP_LAVENDER_TOWN_POKEMON_CENTER_1F       (0 | (11 << 8))
#define MAP_LAVENDER_TOWN_POKEMON_CENTER_2F       (1 | (11 << 8))
#define MAP_LAVENDER_TOWN_MART                    (2 | (11 << 8))
#define MAP_LAVENDER_TOWN_VOLUNTEER_POKEMON_HOUSE (3 | (11 << 8))
#define MAP_LAVENDER_TOWN_HOUSE1                  (4 | (11 << 8))
#define MAP_LAVENDER_TOWN_HOUSE2                  (5 | (11 << 8))

// gMapGroup_IndoorCeladon
#define MAP_CELADON_CITY_POKEMON_CENTER_1F         (0 | (12 << 8))
#define MAP_CELADON_CITY_POKEMON_CENTER_2F         (1 | (12 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_1F       (2 | (12 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_2F       (3 | (12 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_3F       (4 | (12 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_4F       (5 | (12 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_5F       (6 | (12 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_ROOFTOP  (7 | (12 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_ELEVATOR (8 | (12 << 8))
#define MAP_CELADON_CITY_GYM                       (9 | (12 << 8))
#define MAP_CELADON_CITY_GAME_CORNER               (10 | (12 << 8))
#define MAP_CELADON_CITY_GAME_CORNER_PRIZE_ROOM    (11 | (12 << 8))
#define MAP_CELADON_CITY_RESTAURANT                (12 | (12 << 8))
#define MAP_CELADON_CITY_HOTEL                     (13 | (12 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_1F           (14 | (12 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_2F           (15 | (12 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_3F           (16 | (12 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_ROOF         (17 | (12 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_ROOF_ROOM    (18 | (12 << 8))
#define MAP_CELADON_CITY_HOUSE1                    (19 | (12 << 8))

// gMapGroup_IndoorFuchsia
#define MAP_FUCHSIA_CITY_POKEMON_CENTER_1F    (0 | (13 << 8))
#define MAP_FUCHSIA_CITY_POKEMON_CENTER_2F    (1 | (13 << 8))
#define MAP_FUCHSIA_CITY_MART                 (2 | (13 << 8))
#define MAP_FUCHSIA_CITY_GYM                  (3 | (13 << 8))
#define MAP_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE (4 | (13 << 8))
#define MAP_FUCHSIA_CITY_SAFARI_ZONE_OFFICE   (5 | (13 << 8))
#define MAP_FUCHSIA_CITY_WARDENS_HOUSE        (6 | (13 << 8))
#define MAP_FUCHSIA_CITY_HOUSE1               (7 | (13 << 8))
#define MAP_FUCHSIA_CITY_HOUSE2               (8 | (13 << 8))
#define MAP_FUCHSIA_CITY_HOUSE3               (9 | (13 << 8))

// gMapGroup_IndoorSaffron
#define MAP_SAFFRON_CITY_POKEMON_CENTER_1F        (0 | (14 << 8))
#define MAP_SAFFRON_CITY_POKEMON_CENTER_2F        (1 | (14 << 8))
#define MAP_SAFFRON_CITY_MART                     (2 | (14 << 8))
#define MAP_SAFFRON_CITY_GYM                      (3 | (14 << 8))
#define MAP_SAFFRON_CITY_DOJO                     (4 | (14 << 8))
#define MAP_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB (5 | (14 << 8))
#define MAP_SAFFRON_CITY_COPYCATS_HOUSE_1F        (6 | (14 << 8))
#define MAP_SAFFRON_CITY_COPYCATS_HOUSE_2F        (7 | (14 << 8))
#define MAP_SAFFRON_CITY_MR_PSYCHICS_HOUSE        (8 | (14 << 8))
#define MAP_SAFFRON_CITY_HOUSE1                   (9 | (14 << 8))

// gMapGroup_IndoorCinnabar
#define MAP_CINNABAR_ISLAND_POKEMON_CENTER_1F (0 | (15 << 8))
#define MAP_CINNABAR_ISLAND_POKEMON_CENTER_2F (1 | (15 << 8))
#define MAP_CINNABAR_ISLAND_MART              (2 | (15 << 8))
#define MAP_CINNABAR_ISLAND_GYM               (3 | (15 << 8))
#define MAP_POKEMON_LAB_ENTRANCE              (4 | (15 << 8))
#define MAP_POKEMON_LAB_LOUNGE                (5 | (15 << 8))
#define MAP_POKEMON_LAB_RESEARCH_ROOM         (6 | (15 << 8))
#define MAP_POKEMON_LAB_EXPERIMENT_ROOM       (7 | (15 << 8))

// gMapGroup_IndoorIndigoPlateau
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F (0 | (16 << 8))
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_2F (1 | (16 << 8))
#define MAP_POKEMON_LEAGUE_LORELEIS_ROOM     (2 | (16 << 8))
#define MAP_POKEMON_LEAGUE_BRUNOS_ROOM       (3 | (16 << 8))
#define MAP_POKEMON_LEAGUE_AGATHAS_ROOM      (4 | (16 << 8))
#define MAP_POKEMON_LEAGUE_LANCES_ROOM       (5 | (16 << 8))
#define MAP_POKEMON_LEAGUE_CHAMPIONS_ROOM    (6 | (16 << 8))
#define MAP_POKEMON_LEAGUE_HALL_OF_FAME      (7 | (16 << 8))

// gMapGroup_IndoorOneIsland
#define MAP_ONE_ISLAND_POKEMON_CENTER_1F (0 | (17 << 8))
#define MAP_ONE_ISLAND_POKEMON_CENTER_2F (1 | (17 << 8))
#define MAP_ONE_ISLAND_HARBOR            (2 | (17 << 8))
#define MAP_ONE_ISLAND_HOUSE1            (3 | (17 << 8))
#define MAP_ONE_ISLAND_HOUSE2            (4 | (17 << 8))

// gMapGroup_IndoorTwoIsland
#define MAP_TWO_ISLAND_POKEMON_CENTER_1F (0 | (18 << 8))
#define MAP_TWO_ISLAND_POKEMON_CENTER_2F (1 | (18 << 8))
#define MAP_TWO_ISLAND_HARBOR            (2 | (18 << 8))
#define MAP_TWO_ISLAND_GAME_CORNER       (3 | (18 << 8))
#define MAP_TWO_ISLAND_HOUSE             (4 | (18 << 8))

// gMapGroup_IndoorThreeIsland
#define MAP_THREE_ISLAND_POKEMON_CENTER_1F (0 | (19 << 8))
#define MAP_THREE_ISLAND_POKEMON_CENTER_2F (1 | (19 << 8))
#define MAP_THREE_ISLAND_MART              (2 | (19 << 8))
#define MAP_THREE_ISLAND_HOUSE1            (3 | (19 << 8))
#define MAP_THREE_ISLAND_HOUSE2            (4 | (19 << 8))
#define MAP_THREE_ISLAND_HOUSE3            (5 | (19 << 8))
#define MAP_THREE_ISLAND_HOUSE4            (6 | (19 << 8))
#define MAP_THREE_ISLAND_HOUSE5            (7 | (19 << 8))

// gMapGroup_IndoorFourIsland
#define MAP_FOUR_ISLAND_POKEMON_CENTER_1F (0 | (20 << 8))
#define MAP_FOUR_ISLAND_POKEMON_CENTER_2F (1 | (20 << 8))
#define MAP_FOUR_ISLAND_MART              (2 | (20 << 8))
#define MAP_FOUR_ISLAND_HARBOR            (3 | (20 << 8))
#define MAP_FOUR_ISLAND_POKEMON_DAY_CARE  (4 | (20 << 8))
#define MAP_FOUR_ISLAND_LORELEIS_HOUSE    (5 | (20 << 8))
#define MAP_FOUR_ISLAND_HOUSE1            (6 | (20 << 8))
#define MAP_FOUR_ISLAND_HOUSE2            (7 | (20 << 8))

// gMapGroup_IndoorFiveIsland
#define MAP_FIVE_ISLAND_POKEMON_CENTER_1F (0 | (21 << 8))
#define MAP_FIVE_ISLAND_POKEMON_CENTER_2F (1 | (21 << 8))
#define MAP_FIVE_ISLAND_HARBOR            (2 | (21 << 8))
#define MAP_FIVE_ISLAND_HOUSE1            (3 | (21 << 8))
#define MAP_FIVE_ISLAND_HOUSE2            (4 | (21 << 8))

// gMapGroup_IndoorSixIsland
#define MAP_SIX_ISLAND_POKEMON_CENTER_1F (0 | (22 << 8))
#define MAP_SIX_ISLAND_POKEMON_CENTER_2F (1 | (22 << 8))
#define MAP_SIX_ISLAND_MART              (2 | (22 << 8))
#define MAP_SIX_ISLAND_HARBOR            (3 | (22 << 8))
#define MAP_SIX_ISLAND_HOUSE             (4 | (22 << 8))

// gMapGroup_IndoorSevenIsland
#define MAP_SEVEN_ISLAND_POKEMON_CENTER_1F (0 | (23 << 8))
#define MAP_SEVEN_ISLAND_POKEMON_CENTER_2F (1 | (23 << 8))
#define MAP_SEVEN_ISLAND_MART              (2 | (23 << 8))
#define MAP_SEVEN_ISLAND_HARBOR            (3 | (23 << 8))
#define MAP_SEVEN_ISLAND_HOUSE_ROOM1       (4 | (23 << 8))
#define MAP_SEVEN_ISLAND_HOUSE_ROOM2       (5 | (23 << 8))

// gMapGroup_IndoorRoute2
#define MAP_VIRIDIAN_FOREST_NORTH_ENTRANCE (0 | (24 << 8))
#define MAP_VIRIDIAN_FOREST_SOUTH_ENTRANCE (1 | (24 << 8))
#define MAP_ROUTE2_EAST_BUILDING           (2 | (24 << 8))
#define MAP_ROUTE2_HOUSE1                  (3 | (24 << 8))

// gMapGroup_IndoorRoute4
#define MAP_ROUTE4_POKEMON_CENTER_1F (0 | (25 << 8))
#define MAP_ROUTE4_POKEMON_CENTER_2F (1 | (25 << 8))

// gMapGroup_IndoorRoute5
#define MAP_ROUTE5_POKEMON_DAY_CARE (0 | (26 << 8))
#define MAP_ROUTE5_SOUTH_ENTRANCE   (1 | (26 << 8))

// gMapGroup_IndoorRoute6
#define MAP_ROUTE6_NORTH_ENTRANCE (0 | (27 << 8))

// gMapGroup_IndoorRoute7
#define MAP_ROUTE7_EAST_ENTRANCE (0 | (28 << 8))

// gMapGroup_IndoorRoute8
#define MAP_ROUTE8_WEST_ENTRANCE (0 | (29 << 8))

// gMapGroup_IndoorRoute10
#define MAP_ROUTE10_POKEMON_CENTER_1F (0 | (30 << 8))
#define MAP_ROUTE10_POKEMON_CENTER_2F (1 | (30 << 8))

// gMapGroup_IndoorRoute11
#define MAP_ROUTE11_EAST_ENTRANCE_1F (0 | (31 << 8))
#define MAP_ROUTE11_EAST_ENTRANCE_2F (1 | (31 << 8))

// gMapGroup_IndoorRoute12
#define MAP_ROUTE12_NORTH_ENTRANCE_1F (0 | (32 << 8))
#define MAP_ROUTE12_NORTH_ENTRANCE_2F (1 | (32 << 8))
#define MAP_ROUTE12_FISHING_HOUSE     (2 | (32 << 8))

// gMapGroup_IndoorRoute15
#define MAP_ROUTE15_WEST_ENTRANCE_1F (0 | (33 << 8))
#define MAP_ROUTE15_WEST_ENTRANCE_2F (1 | (33 << 8))

// gMapGroup_IndoorRoute16
#define MAP_ROUTE16_NORTH_ENTRANCE_1F (0 | (34 << 8))
#define MAP_ROUTE16_NORTH_ENTRANCE_2F (1 | (34 << 8))
#define MAP_ROUTE16_HOUSE1            (2 | (34 << 8))

// gMapGroup_IndoorRoute18
#define MAP_ROUTE18_EAST_ENTRANCE_1F (0 | (35 << 8))
#define MAP_ROUTE18_EAST_ENTRANCE_2F (1 | (35 << 8))

// gMapGroup_IndoorRoute22
#define MAP_ROUTE22_NORTH_ENTRANCE (0 | (36 << 8))

// gMapGroup_IndoorRoute25
#define MAP_SEA_COTTAGE (0 | (37 << 8))

// gMapGroup_IndoorTwoIslandRoute
#define MAP_CAPE_BRINK_HOUSE (0 | (38 << 8))

// gMapGroup_IndoorThreeIslandRoute
#define MAP_THREE_ISLAND_HARBOR (0 | (39 << 8))

// gMapGroup_IndoorFiveIslandRoute
#define MAP_RESORT_GORGEOUS_HOUSE (0 | (40 << 8))

// gMapGroup_IndoorSixIslandRoute
#define MAP_WATER_PATH_HOUSE1 (0 | (41 << 8))
#define MAP_WATER_PATH_HOUSE2 (1 | (41 << 8))

// gMapGroup_IndoorSevenIslandRoute
#define MAP_SEVAULT_CANYON_HOUSE (0 | (42 << 8))

#define MAP_GROUPS_COUNT 43

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
