#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_Link
#define MAP_TRADE_CENTER        (0 | (0 << 8))
#define MAP_UNION_ROOM          (1 | (0 << 8))
#define MAP_RECORD_CORNER       (2 | (0 << 8))
#define MAP_BATTLE_COLOSSEUM_2P (3 | (0 << 8))
#define MAP_BATTLE_COLOSSEUM_4P (4 | (0 << 8))

// gMapGroup_Dungeons
#define MAP_VIRIDIAN_FOREST                     (0 | (1 << 8))
#define MAP_MT_MOON_1F                          (1 | (1 << 8))
#define MAP_MT_MOON_B1F                         (2 | (1 << 8))
#define MAP_MT_MOON_B2F                         (3 | (1 << 8))
#define MAP_SSANNE_EXTERIOR                     (4 | (1 << 8))
#define MAP_SSANNE_1F_CORRIDOR                  (5 | (1 << 8))
#define MAP_SSANNE_2F_CORRIDOR                  (6 | (1 << 8))
#define MAP_SSANNE_3F_CORRIDOR                  (7 | (1 << 8))
#define MAP_SSANNE_B1F_CORRIDOR                 (8 | (1 << 8))
#define MAP_SSANNE_DECK                         (9 | (1 << 8))
#define MAP_SSANNE_KITCHEN                      (10 | (1 << 8))
#define MAP_SSANNE_CAPTAINS_OFFICE              (11 | (1 << 8))
#define MAP_SSANNE_1F_ROOM1                     (12 | (1 << 8))
#define MAP_SSANNE_1F_ROOM2                     (13 | (1 << 8))
#define MAP_SSANNE_1F_ROOM3                     (14 | (1 << 8))
#define MAP_SSANNE_1F_ROOM4                     (15 | (1 << 8))
#define MAP_SSANNE_1F_ROOM5                     (16 | (1 << 8))
#define MAP_SSANNE_1F_ROOM6                     (17 | (1 << 8))
#define MAP_SSANNE_1F_ROOM7                     (18 | (1 << 8))
#define MAP_SSANNE_2F_ROOM1                     (19 | (1 << 8))
#define MAP_SSANNE_2F_ROOM2                     (20 | (1 << 8))
#define MAP_SSANNE_2F_ROOM3                     (21 | (1 << 8))
#define MAP_SSANNE_2F_ROOM4                     (22 | (1 << 8))
#define MAP_SSANNE_2F_ROOM5                     (23 | (1 << 8))
#define MAP_SSANNE_2F_ROOM6                     (24 | (1 << 8))
#define MAP_SSANNE_B1F_ROOM1                    (25 | (1 << 8))
#define MAP_SSANNE_B1F_ROOM2                    (26 | (1 << 8))
#define MAP_SSANNE_B1F_ROOM3                    (27 | (1 << 8))
#define MAP_SSANNE_B1F_ROOM4                    (28 | (1 << 8))
#define MAP_SSANNE_B1F_ROOM5                    (29 | (1 << 8))
#define MAP_DIGLETTS_CAVE_NORTH_ENTRANCE        (30 | (1 << 8))
#define MAP_DIGLETTS_CAVE_B1F                   (31 | (1 << 8))
#define MAP_DIGLETTS_CAVE_SOUTH_ENTRANCE        (32 | (1 << 8))
#define MAP_ROCK_TUNNEL_1F                      (33 | (1 << 8))
#define MAP_ROCK_TUNNEL_B1F                     (34 | (1 << 8))
#define MAP_POKEMON_TOWER_1F                    (35 | (1 << 8))
#define MAP_POKEMON_TOWER_2F                    (36 | (1 << 8))
#define MAP_POKEMON_TOWER_3F                    (37 | (1 << 8))
#define MAP_POKEMON_TOWER_4F                    (38 | (1 << 8))
#define MAP_POKEMON_TOWER_5F                    (39 | (1 << 8))
#define MAP_POKEMON_TOWER_6F                    (40 | (1 << 8))
#define MAP_POKEMON_TOWER_7F                    (41 | (1 << 8))
#define MAP_UNDERGROUND_PATH_NORTH_ENTRANCE     (42 | (1 << 8))
#define MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL (43 | (1 << 8))
#define MAP_UNDERGROUND_PATH_SOUTH_ENTRANCE     (44 | (1 << 8))
#define MAP_UNDERGROUND_PATH_WEST_ENTRANCE      (45 | (1 << 8))
#define MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL   (46 | (1 << 8))
#define MAP_UNDERGROUND_PATH_EAST_ENTRANCE      (47 | (1 << 8))
#define MAP_ROCKET_HIDEOUT_B1F                  (48 | (1 << 8))
#define MAP_ROCKET_HIDEOUT_B2F                  (49 | (1 << 8))
#define MAP_ROCKET_HIDEOUT_B3F                  (50 | (1 << 8))
#define MAP_ROCKET_HIDEOUT_B4F                  (51 | (1 << 8))
#define MAP_ROCKET_HIDEOUT_ELEVATOR             (52 | (1 << 8))
#define MAP_SILPH_CO_1F                         (53 | (1 << 8))
#define MAP_SILPH_CO_2F                         (54 | (1 << 8))
#define MAP_SILPH_CO_3F                         (55 | (1 << 8))
#define MAP_SILPH_CO_4F                         (56 | (1 << 8))
#define MAP_SILPH_CO_5F                         (57 | (1 << 8))
#define MAP_SILPH_CO_6F                         (58 | (1 << 8))
#define MAP_SILPH_CO_7F                         (59 | (1 << 8))
#define MAP_SILPH_CO_8F                         (60 | (1 << 8))
#define MAP_SILPH_CO_9F                         (61 | (1 << 8))
#define MAP_SILPH_CO_10F                        (62 | (1 << 8))
#define MAP_SILPH_CO_11F                        (63 | (1 << 8))
#define MAP_SILPH_CO_ELEVATOR                   (64 | (1 << 8))
#define MAP_SEAFOAM_ISLANDS_1F                  (65 | (1 << 8))
#define MAP_SEAFOAM_ISLANDS_B1F                 (66 | (1 << 8))
#define MAP_SEAFOAM_ISLANDS_B2F                 (67 | (1 << 8))
#define MAP_SEAFOAM_ISLANDS_B3F                 (68 | (1 << 8))
#define MAP_SEAFOAM_ISLANDS_B4F                 (69 | (1 << 8))
#define MAP_POWER_PLANT                         (70 | (1 << 8))
#define MAP_POKEMON_MANSION_1F                  (71 | (1 << 8))
#define MAP_POKEMON_MANSION_2F                  (72 | (1 << 8))
#define MAP_POKEMON_MANSION_3F                  (73 | (1 << 8))
#define MAP_POKEMON_MANSION_B1F                 (74 | (1 << 8))
#define MAP_VICTORY_ROAD_1F                     (75 | (1 << 8))
#define MAP_VICTORY_ROAD_2F                     (76 | (1 << 8))
#define MAP_VICTORY_ROAD_3F                     (77 | (1 << 8))
#define MAP_CERULEAN_CAVE_1F                    (78 | (1 << 8))
#define MAP_CERULEAN_CAVE_2F                    (79 | (1 << 8))
#define MAP_CERULEAN_CAVE_B1F                   (80 | (1 << 8))

// gMapGroup_Dungeons2
#define MAP_MT_EMBER_EXTERIOR             (0 | (2 << 8))
#define MAP_MT_EMBER_SUMMIT_PATH_1F       (1 | (2 << 8))
#define MAP_MT_EMBER_SUMMIT_PATH_2F       (2 | (2 << 8))
#define MAP_MT_EMBER_SUMMIT_PATH_3F       (3 | (2 << 8))
#define MAP_MT_EMBER_SUMMIT               (4 | (2 << 8))
#define MAP_MT_EMBER_RUBY_PATH_1F         (5 | (2 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B1F        (6 | (2 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B2F        (7 | (2 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B3F        (8 | (2 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B4F        (9 | (2 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B5F        (10 | (2 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B1F_STAIRS (11 | (2 << 8))
#define MAP_MT_EMBER_RUBY_PATH_B2F_STAIRS (12 | (2 << 8))
#define MAP_BERRY_FOREST                  (13 | (2 << 8))
#define MAP_ICEFALL_CAVE_ENTRANCE         (14 | (2 << 8))
#define MAP_ICEFALL_CAVE_1F               (15 | (2 << 8))
#define MAP_ICEFALL_CAVE_B1F              (16 | (2 << 8))
#define MAP_ICEFALL_CAVE_BACK             (17 | (2 << 8))
#define MAP_ROCKET_WAREHOUSE              (18 | (2 << 8))
#define MAP_LOST_CAVE_ENTRANCE            (19 | (2 << 8))
#define MAP_LOST_CAVE_ROOM1               (20 | (2 << 8))
#define MAP_LOST_CAVE_ROOM2               (21 | (2 << 8))
#define MAP_LOST_CAVE_ROOM3               (22 | (2 << 8))
#define MAP_LOST_CAVE_ROOM4               (23 | (2 << 8))
#define MAP_LOST_CAVE_ROOM5               (24 | (2 << 8))
#define MAP_LOST_CAVE_ROOM6               (25 | (2 << 8))
#define MAP_LOST_CAVE_ROOM7               (26 | (2 << 8))
#define MAP_LOST_CAVE_ROOM8               (27 | (2 << 8))
#define MAP_LOST_CAVE_ROOM9               (28 | (2 << 8))
#define MAP_LOST_CAVE_ROOM10              (29 | (2 << 8))
#define MAP_LOST_CAVE_ROOM11              (30 | (2 << 8))
#define MAP_LOST_CAVE_ROOM12              (31 | (2 << 8))
#define MAP_LOST_CAVE_ROOM13              (32 | (2 << 8))
#define MAP_LOST_CAVE_ROOM14              (33 | (2 << 8))
#define MAP_DOTTED_HOLE_1F                (34 | (2 << 8))
#define MAP_DOTTED_HOLE_B1F               (35 | (2 << 8))
#define MAP_DOTTED_HOLE_B2F               (36 | (2 << 8))
#define MAP_DOTTED_HOLE_B3F               (37 | (2 << 8))
#define MAP_DOTTED_HOLE_B4F               (38 | (2 << 8))
#define MAP_DOTTED_HOLE_SAPPHIRE_ROOM     (39 | (2 << 8))
#define MAP_PATTERN_BUSH                  (40 | (2 << 8))
#define MAP_ALTERING_CAVE                 (41 | (2 << 8))
#define MAP_SEVAULT_CANYON_TANOBY_KEY     (42 | (2 << 8))
#define MAP_TANOBY_RUINS_MONEAN_CHAMBER   (43 | (2 << 8))
#define MAP_TANOBY_RUINS_LIPTOO_CHAMBER   (44 | (2 << 8))
#define MAP_TANOBY_RUINS_WEEPTH_CHAMBER   (45 | (2 << 8))
#define MAP_TANOBY_RUINS_DILFORD_CHAMBER  (46 | (2 << 8))
#define MAP_TANOBY_RUINS_SCUFIB_CHAMBER   (47 | (2 << 8))
#define MAP_TANOBY_RUINS_RIXY_CHAMBER     (48 | (2 << 8))
#define MAP_TANOBY_RUINS_VIAPOIS_CHAMBER  (49 | (2 << 8))

// gMapGroup_SpecialArea
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (0 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (1 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (2 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (3 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (4 | (3 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (5 | (3 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (6 | (3 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (7 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (8 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (9 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (10 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (11 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (12 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (13 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (14 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (15 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (16 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (17 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (18 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (19 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (20 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (21 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (22 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (23 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (24 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (25 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (26 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (27 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (28 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (29 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (30 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (31 | (3 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (32 | (3 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (33 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (34 | (3 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (35 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (36 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (37 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (38 | (3 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (39 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (40 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (41 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (42 | (3 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (43 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (44 | (3 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (45 | (3 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (46 | (3 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (47 | (3 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (48 | (3 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (49 | (3 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (50 | (3 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (51 | (3 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (52 | (3 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (53 | (3 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (54 | (3 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (55 | (3 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (56 | (3 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (57 | (3 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (58 | (3 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (59 | (3 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (60 | (3 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (61 | (3 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (62 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (63 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (64 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (65 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (66 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (67 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (68 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (69 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (70 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (71 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (72 | (3 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (73 | (3 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (74 | (3 << 8))
#define MAP_SAFARI_ZONE_CENTER                              (75 | (3 << 8))
#define MAP_SAFARI_ZONE_EAST                                (76 | (3 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (77 | (3 << 8))
#define MAP_SAFARI_ZONE_WEST                                (78 | (3 << 8))
#define MAP_SAFARI_ZONE_CENTER_REST_HOUSE                   (79 | (3 << 8))
#define MAP_SAFARI_ZONE_EAST_REST_HOUSE                     (80 | (3 << 8))
#define MAP_SAFARI_ZONE_NORTH_REST_HOUSE                    (81 | (3 << 8))
#define MAP_SAFARI_ZONE_WEST_REST_HOUSE                     (82 | (3 << 8))
#define MAP_SAFARI_ZONE_SECRET_HOUSE                        (83 | (3 << 8))
#define MAP_TRAINER_TOWER_LOBBY                             (84 | (3 << 8))
#define MAP_TRAINER_TOWER_1F                                (85 | (3 << 8))
#define MAP_TRAINER_TOWER_2F                                (86 | (3 << 8))
#define MAP_TRAINER_TOWER_3F                                (87 | (3 << 8))
#define MAP_TRAINER_TOWER_4F                                (88 | (3 << 8))
#define MAP_TRAINER_TOWER_ROOF                              (89 | (3 << 8))
#define MAP_TRAINER_TOWER_ELEVATOR                          (90 | (3 << 8))

// gMapGroup_DynamicArea
#define MAP_SECRET_BASE_RED_CAVE1              (0 | (4 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1            (1 | (4 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1             (2 | (4 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1           (3 | (4 << 8))
#define MAP_SECRET_BASE_TREE1                  (4 | (4 << 8))
#define MAP_SECRET_BASE_SHRUB1                 (5 | (4 << 8))
#define MAP_SECRET_BASE_RED_CAVE2              (6 | (4 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2            (7 | (4 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2             (8 | (4 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2           (9 | (4 << 8))
#define MAP_SECRET_BASE_TREE2                  (10 | (4 << 8))
#define MAP_SECRET_BASE_SHRUB2                 (11 | (4 << 8))
#define MAP_SECRET_BASE_RED_CAVE3              (12 | (4 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3            (13 | (4 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3             (14 | (4 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3           (15 | (4 << 8))
#define MAP_SECRET_BASE_TREE3                  (16 | (4 << 8))
#define MAP_SECRET_BASE_SHRUB3                 (17 | (4 << 8))
#define MAP_SECRET_BASE_RED_CAVE4              (18 | (4 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4            (19 | (4 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4             (20 | (4 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4           (21 | (4 << 8))
#define MAP_SECRET_BASE_TREE4                  (22 | (4 << 8))
#define MAP_SECRET_BASE_SHRUB4                 (23 | (4 << 8))
#define MAP_CONTEST_HALL                       (24 | (4 << 8))
#define MAP_UNUSED_CONTEST_HALL1               (25 | (4 << 8))
#define MAP_UNUSED_CONTEST_HALL2               (26 | (4 << 8))
#define MAP_UNUSED_CONTEST_HALL3               (27 | (4 << 8))
#define MAP_UNUSED_CONTEST_HALL4               (28 | (4 << 8))
#define MAP_UNUSED_CONTEST_HALL5               (29 | (4 << 8))
#define MAP_UNUSED_CONTEST_HALL6               (30 | (4 << 8))
#define MAP_CONTEST_HALL_BEAUTY                (31 | (4 << 8))
#define MAP_CONTEST_HALL_TOUGH                 (32 | (4 << 8))
#define MAP_CONTEST_HALL_COOL                  (33 | (4 << 8))
#define MAP_CONTEST_HALL_SMART                 (34 | (4 << 8))
#define MAP_CONTEST_HALL_CUTE                  (35 | (4 << 8))
#define MAP_INSIDE_OF_TRUCK                    (36 | (4 << 8))
#define MAP_SS_TIDAL_CORRIDOR                  (37 | (4 << 8))
#define MAP_SS_TIDAL_LOWER_DECK                (38 | (4 << 8))
#define MAP_SS_TIDAL_ROOMS                     (39 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01            (40 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02            (41 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03            (42 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04            (43 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05            (44 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06            (45 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07            (46 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08            (47 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09            (48 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10            (49 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11            (50 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12            (51 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13            (52 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14            (53 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15            (54 | (4 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16            (55 | (4 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM  (56 | (4 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM     (57 | (4 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM    (58 | (4 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM     (59 | (4 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM (60 | (4 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM    (61 | (4 << 8))
#define MAP_ISLAND_CAVE                        (62 | (4 << 8))
#define MAP_ANCIENT_TOMB                       (63 | (4 << 8))
#define MAP_SCORCHED_SLAB                      (64 | (4 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                (65 | (4 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                 (66 | (4 << 8))
#define MAP_SKY_PILLAR_1F                      (67 | (4 << 8))
#define MAP_SKY_PILLAR_2F                      (68 | (4 << 8))
#define MAP_SKY_PILLAR_3F                      (69 | (4 << 8))
#define MAP_SKY_PILLAR_4F                      (70 | (4 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM       (71 | (4 << 8))
#define MAP_SKY_PILLAR_5F                      (72 | (4 << 8))
#define MAP_SKY_PILLAR_TOP                     (73 | (4 << 8))
#define MAP_DESERT_UNDERPASS                   (74 | (4 << 8))
#define MAP_ARTISAN_CAVE_B1F                   (75 | (4 << 8))
#define MAP_ARTISAN_CAVE_1F                    (76 | (4 << 8))
#define MAP_UNDERWATER_MARINE_CAVE             (77 | (4 << 8))
#define MAP_MARINE_CAVE_ENTRANCE               (78 | (4 << 8))
#define MAP_MARINE_CAVE_END                    (79 | (4 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                (80 | (4 << 8))
#define MAP_TERRA_CAVE_END                     (81 | (4 << 8))

// gMapGroup_TownsAndRoutes
#define MAP_PETALBURG_CITY          (0 | (5 << 8))
#define MAP_SLATEPORT_CITY          (1 | (5 << 8))
#define MAP_MAUVILLE_CITY           (2 | (5 << 8))
#define MAP_RUSTBORO_CITY           (3 | (5 << 8))
#define MAP_FORTREE_CITY            (4 | (5 << 8))
#define MAP_LILYCOVE_CITY           (5 | (5 << 8))
#define MAP_MOSSDEEP_CITY           (6 | (5 << 8))
#define MAP_SOOTOPOLIS_CITY         (7 | (5 << 8))
#define MAP_EVER_GRANDE_CITY        (8 | (5 << 8))
#define MAP_LITTLEROOT_TOWN         (9 | (5 << 8))
#define MAP_LAVARIDGE_TOWN          (10 | (5 << 8))
#define MAP_FALLARBOR_TOWN          (11 | (5 << 8))
#define MAP_VERDANTURF_TOWN         (12 | (5 << 8))
#define MAP_PACIFIDLOG_TOWN         (13 | (5 << 8))
#define MAP_ROUTE115                (14 | (5 << 8))
#define MAP_ROUTE116                (15 | (5 << 8))
#define MAP_ROUTE117                (16 | (5 << 8))
#define MAP_ROUTE118                (17 | (5 << 8))
#define MAP_ROUTE119                (18 | (5 << 8))
#define MAP_ROUTE120                (19 | (5 << 8))
#define MAP_ROUTE121                (20 | (5 << 8))
#define MAP_ROUTE122                (21 | (5 << 8))
#define MAP_ROUTE123                (22 | (5 << 8))
#define MAP_ROUTE124                (23 | (5 << 8))
#define MAP_ROUTE125                (24 | (5 << 8))
#define MAP_ROUTE126                (25 | (5 << 8))
#define MAP_ROUTE130                (26 | (5 << 8))
#define MAP_ROUTE131                (27 | (5 << 8))
#define MAP_ROUTE132                (28 | (5 << 8))
#define MAP_ROUTE133                (29 | (5 << 8))
#define MAP_PALLET_TOWN             (30 | (5 << 8))
#define MAP_VIRIDIAN_CITY           (31 | (5 << 8))
#define MAP_PEWTER_CITY             (32 | (5 << 8))
#define MAP_CERULEAN_CITY           (33 | (5 << 8))
#define MAP_VERMILION_CITY          (34 | (5 << 8))
#define MAP_LAVENDER_TOWN           (35 | (5 << 8))
#define MAP_CELADON_CITY            (36 | (5 << 8))
#define MAP_FUCHSIA_CITY            (37 | (5 << 8))
#define MAP_SAFFRON_CITY            (38 | (5 << 8))
#define MAP_CINNABAR_ISLAND         (39 | (5 << 8))
#define MAP_INDIGO_PLATEAU          (40 | (5 << 8))
#define MAP_ONE_ISLAND              (41 | (5 << 8))
#define MAP_TWO_ISLAND              (42 | (5 << 8))
#define MAP_THREE_ISLAND            (43 | (5 << 8))
#define MAP_FOUR_ISLAND             (44 | (5 << 8))
#define MAP_FIVE_ISLAND             (45 | (5 << 8))
#define MAP_SIX_ISLAND              (46 | (5 << 8))
#define MAP_SEVEN_ISLAND            (47 | (5 << 8))
#define MAP_ROUTE1                  (48 | (5 << 8))
#define MAP_ROUTE2                  (49 | (5 << 8))
#define MAP_ROUTE3                  (50 | (5 << 8))
#define MAP_ROUTE4                  (51 | (5 << 8))
#define MAP_ROUTE5                  (52 | (5 << 8))
#define MAP_ROUTE6                  (53 | (5 << 8))
#define MAP_ROUTE7                  (54 | (5 << 8))
#define MAP_ROUTE8                  (55 | (5 << 8))
#define MAP_ROUTE9                  (56 | (5 << 8))
#define MAP_ROUTE10                 (57 | (5 << 8))
#define MAP_ROUTE11                 (58 | (5 << 8))
#define MAP_ROUTE12                 (59 | (5 << 8))
#define MAP_ROUTE13                 (60 | (5 << 8))
#define MAP_ROUTE14                 (61 | (5 << 8))
#define MAP_ROUTE15                 (62 | (5 << 8))
#define MAP_ROUTE16                 (63 | (5 << 8))
#define MAP_ROUTE17                 (64 | (5 << 8))
#define MAP_ROUTE18                 (65 | (5 << 8))
#define MAP_ROUTE19                 (66 | (5 << 8))
#define MAP_ROUTE20                 (67 | (5 << 8))
#define MAP_ROUTE21                 (68 | (5 << 8))
#define MAP_ROUTE22                 (69 | (5 << 8))
#define MAP_ROUTE23                 (70 | (5 << 8))
#define MAP_ROUTE24                 (71 | (5 << 8))
#define MAP_ROUTE25                 (72 | (5 << 8))
#define MAP_TREASURE_BEACH          (73 | (5 << 8))
#define MAP_KINDLE_ROAD             (74 | (5 << 8))
#define MAP_KINDLE_ROAD_EMBER_SPA   (75 | (5 << 8))
#define MAP_CAPE_BRINK              (76 | (5 << 8))
#define MAP_THREE_ISLAND_PORT       (77 | (5 << 8))
#define MAP_THREE_ISLAND_PATH       (78 | (5 << 8))
#define MAP_BOND_BRIDGE             (79 | (5 << 8))
#define MAP_FIVE_ISLAND_MEADOW      (80 | (5 << 8))
#define MAP_MEMORIAL_PILLAR         (81 | (5 << 8))
#define MAP_WATER_LABYRINTH         (82 | (5 << 8))
#define MAP_RESORT_GORGEOUS         (83 | (5 << 8))
#define MAP_WATER_PATH              (84 | (5 << 8))
#define MAP_RUIN_VALLEY             (85 | (5 << 8))
#define MAP_GREEN_PATH              (86 | (5 << 8))
#define MAP_OUTCAST_ISLAND          (87 | (5 << 8))
#define MAP_TRAINER_TOWER_EXTERIOR  (88 | (5 << 8))
#define MAP_SEVAULT_CANYON_ENTRANCE (89 | (5 << 8))
#define MAP_SEVAULT_CANYON          (90 | (5 << 8))
#define MAP_TANOBY_RUINS            (91 | (5 << 8))

// gMapGroup_IndoorPallet
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (6 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (6 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (6 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (6 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (6 << 8))
#define MAP_PLAYERS_HOUSE_1F                     (5 | (6 << 8))
#define MAP_PLAYERS_HOUSE_2F                     (6 | (6 << 8))
#define MAP_RIVALS_HOUSE                         (7 | (6 << 8))
#define MAP_PROFESSOR_OAKS_LAB                   (8 | (6 << 8))

// gMapGroup_IndoorViridian
#define MAP_VIRIDIAN_CITY_POKEMON_CENTER_1F (0 | (7 << 8))
#define MAP_VIRIDIAN_CITY_POKEMON_CENTER_2F (1 | (7 << 8))
#define MAP_VIRIDIAN_CITY_MART              (2 | (7 << 8))
#define MAP_VIRIDIAN_CITY_GYM               (3 | (7 << 8))
#define MAP_VIRIDIAN_CITY_HOUSE1            (4 | (7 << 8))
#define MAP_VIRIDIAN_CITY_HOUSE2            (5 | (7 << 8))

// gMapGroup_IndoorPewter
#define MAP_PEWTER_CITY_POKEMON_CENTER_1F (0 | (8 << 8))
#define MAP_PEWTER_CITY_POKEMON_CENTER_2F (1 | (8 << 8))
#define MAP_PEWTER_CITY_MART              (2 | (8 << 8))
#define MAP_PEWTER_CITY_GYM               (3 | (8 << 8))
#define MAP_PEWTER_CITY_MUSEUM_1F         (4 | (8 << 8))
#define MAP_PEWTER_CITY_MUSEUM_2F         (5 | (8 << 8))
#define MAP_PEWTER_CITY_HOUSE1            (6 | (8 << 8))
#define MAP_PEWTER_CITY_HOUSE2            (7 | (8 << 8))

// gMapGroup_IndoorCerulean
#define MAP_LAVARIDGE_TOWN_HERB_SHOP         (0 | (9 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F            (1 | (9 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F           (2 | (9 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE             (3 | (9 << 8))
#define MAP_LAVARIDGE_TOWN_MART              (4 | (9 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (5 | (9 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (6 | (9 << 8))
#define MAP_CERULEAN_CITY_POKEMON_CENTER_1F  (7 | (9 << 8))
#define MAP_CERULEAN_CITY_POKEMON_CENTER_2F  (8 | (9 << 8))
#define MAP_CERULEAN_CITY_MART               (9 | (9 << 8))
#define MAP_CERULEAN_CITY_GYM                (10 | (9 << 8))
#define MAP_CERULEAN_CITY_BIKE_SHOP          (11 | (9 << 8))
#define MAP_CERULEAN_CITY_HOUSE1             (12 | (9 << 8))
#define MAP_CERULEAN_CITY_HOUSE2             (13 | (9 << 8))
#define MAP_CERULEAN_CITY_HOUSE3             (14 | (9 << 8))
#define MAP_CERULEAN_CITY_HOUSE4             (15 | (9 << 8))
#define MAP_CERULEAN_CITY_HOUSE5             (16 | (9 << 8))

// gMapGroup_IndoorVermilion
#define MAP_FALLARBOR_TOWN_MART                    (0 | (10 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (10 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (10 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (10 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (10 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (10 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (10 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (10 << 8))
#define MAP_VERMILION_CITY_POKEMON_CENTER_1F       (8 | (10 << 8))
#define MAP_VERMILION_CITY_POKEMON_CENTER_2F       (9 | (10 << 8))
#define MAP_VERMILION_CITY_MART                    (10 | (10 << 8))
#define MAP_VERMILION_CITY_GYM                     (11 | (10 << 8))
#define MAP_VERMILION_CITY_POKEMON_FAN_CLUB        (12 | (10 << 8))
#define MAP_VERMILION_CITY_HOUSE1                  (13 | (10 << 8))
#define MAP_VERMILION_CITY_HOUSE2                  (14 | (10 << 8))
#define MAP_VERMILION_CITY_HOUSE3                  (15 | (10 << 8))

// gMapGroup_IndoorLavender
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (11 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (11 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (11 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (11 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (11 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (11 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (11 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (11 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (11 << 8))
#define MAP_LAVENDER_TOWN_POKEMON_CENTER_1F         (9 | (11 << 8))
#define MAP_LAVENDER_TOWN_POKEMON_CENTER_2F         (10 | (11 << 8))
#define MAP_LAVENDER_TOWN_MART                      (11 | (11 << 8))
#define MAP_LAVENDER_TOWN_VOLUNTEER_POKEMON_HOUSE   (12 | (11 << 8))
#define MAP_LAVENDER_TOWN_HOUSE1                    (13 | (11 << 8))
#define MAP_LAVENDER_TOWN_HOUSE2                    (14 | (11 << 8))

// gMapGroup_IndoorCeladon
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F      (0 | (12 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F      (1 | (12 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1                 (2 | (12 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2                 (3 | (12 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3                 (4 | (12 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4                 (5 | (12 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5                 (6 | (12 << 8))
#define MAP_CELADON_CITY_POKEMON_CENTER_1F         (7 | (12 << 8))
#define MAP_CELADON_CITY_POKEMON_CENTER_2F         (8 | (12 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_1F       (9 | (12 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_2F       (10 | (12 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_3F       (11 | (12 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_4F       (12 | (12 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_5F       (13 | (12 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_ROOFTOP  (14 | (12 << 8))
#define MAP_CELADON_CITY_DEPARTMENT_STORE_ELEVATOR (15 | (12 << 8))
#define MAP_CELADON_CITY_GYM                       (16 | (12 << 8))
#define MAP_CELADON_CITY_GAME_CORNER               (17 | (12 << 8))
#define MAP_CELADON_CITY_GAME_CORNER_PRIZE_ROOM    (18 | (12 << 8))
#define MAP_CELADON_CITY_RESTAURANT                (19 | (12 << 8))
#define MAP_CELADON_CITY_HOTEL                     (20 | (12 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_1F           (21 | (12 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_2F           (22 | (12 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_3F           (23 | (12 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_ROOF         (24 | (12 << 8))
#define MAP_CELADON_CITY_CONDOMINIUMS_ROOF_ROOM    (25 | (12 << 8))
#define MAP_CELADON_CITY_HOUSE1                    (26 | (12 << 8))

// gMapGroup_IndoorFuchsia
#define MAP_PETALBURG_CITY_WALLYS_HOUSE       (0 | (13 << 8))
#define MAP_PETALBURG_CITY_GYM                (1 | (13 << 8))
#define MAP_PETALBURG_CITY_HOUSE1             (2 | (13 << 8))
#define MAP_PETALBURG_CITY_HOUSE2             (3 | (13 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F  (4 | (13 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F  (5 | (13 << 8))
#define MAP_PETALBURG_CITY_MART               (6 | (13 << 8))
#define MAP_FUCHSIA_CITY_POKEMON_CENTER_1F    (7 | (13 << 8))
#define MAP_FUCHSIA_CITY_POKEMON_CENTER_2F    (8 | (13 << 8))
#define MAP_FUCHSIA_CITY_MART                 (9 | (13 << 8))
#define MAP_FUCHSIA_CITY_GYM                  (10 | (13 << 8))
#define MAP_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE (11 | (13 << 8))
#define MAP_FUCHSIA_CITY_SAFARI_ZONE_OFFICE   (12 | (13 << 8))
#define MAP_FUCHSIA_CITY_WARDENS_HOUSE        (13 | (13 << 8))
#define MAP_FUCHSIA_CITY_HOUSE1               (14 | (13 << 8))
#define MAP_FUCHSIA_CITY_HOUSE2               (15 | (13 << 8))
#define MAP_FUCHSIA_CITY_HOUSE3               (16 | (13 << 8))

// gMapGroup_IndoorSaffron
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (14 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (14 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (14 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (14 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (14 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (14 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (14 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (14 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (14 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                  (9 | (14 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (10 | (14 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F       (11 | (14 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (12 | (14 << 8))
#define MAP_SLATEPORT_CITY_MART                    (13 | (14 << 8))
#define MAP_SAFFRON_CITY_POKEMON_CENTER_1F         (14 | (14 << 8))
#define MAP_SAFFRON_CITY_POKEMON_CENTER_2F         (15 | (14 << 8))
#define MAP_SAFFRON_CITY_MART                      (16 | (14 << 8))
#define MAP_SAFFRON_CITY_GYM                       (17 | (14 << 8))
#define MAP_SAFFRON_CITY_DOJO                      (18 | (14 << 8))
#define MAP_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB  (19 | (14 << 8))
#define MAP_SAFFRON_CITY_COPYCATS_HOUSE_1F         (20 | (14 << 8))
#define MAP_SAFFRON_CITY_COPYCATS_HOUSE_2F         (21 | (14 << 8))
#define MAP_SAFFRON_CITY_MR_PSYCHICS_HOUSE         (22 | (14 << 8))
#define MAP_SAFFRON_CITY_HOUSE1                    (23 | (14 << 8))

// gMapGroup_IndoorCinnabar
#define MAP_MAUVILLE_CITY_GYM                 (0 | (15 << 8))
#define MAP_MAUVILLE_CITY_BIKE_SHOP           (1 | (15 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1              (2 | (15 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER         (3 | (15 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2              (4 | (15 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F   (5 | (15 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F   (6 | (15 << 8))
#define MAP_MAUVILLE_CITY_MART                (7 | (15 << 8))
#define MAP_CINNABAR_ISLAND_POKEMON_CENTER_1F (8 | (15 << 8))
#define MAP_CINNABAR_ISLAND_POKEMON_CENTER_2F (9 | (15 << 8))
#define MAP_CINNABAR_ISLAND_MART              (10 | (15 << 8))
#define MAP_CINNABAR_ISLAND_GYM               (11 | (15 << 8))
#define MAP_POKEMON_LAB_ENTRANCE              (12 | (15 << 8))
#define MAP_POKEMON_LAB_LOUNGE                (13 | (15 << 8))
#define MAP_POKEMON_LAB_RESEARCH_ROOM         (14 | (15 << 8))
#define MAP_POKEMON_LAB_EXPERIMENT_ROOM       (15 | (15 << 8))

// gMapGroup_IndoorIndigoPlateau
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F      (0 | (16 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F      (1 | (16 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F      (2 | (16 << 8))
#define MAP_RUSTBORO_CITY_GYM                (3 | (16 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL     (4 | (16 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F  (5 | (16 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F  (6 | (16 << 8))
#define MAP_RUSTBORO_CITY_MART               (7 | (16 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F           (8 | (16 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F           (9 | (16 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1             (10 | (16 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE      (11 | (16 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2             (12 | (16 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F           (13 | (16 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F           (14 | (16 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F           (15 | (16 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3             (16 | (16 << 8))
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F (17 | (16 << 8))
#define MAP_INDIGO_PLATEAU_POKEMON_CENTER_2F (18 | (16 << 8))
#define MAP_POKEMON_LEAGUE_LORELEIS_ROOM     (19 | (16 << 8))
#define MAP_POKEMON_LEAGUE_BRUNOS_ROOM       (20 | (16 << 8))
#define MAP_POKEMON_LEAGUE_AGATHAS_ROOM      (21 | (16 << 8))
#define MAP_POKEMON_LEAGUE_LANCES_ROOM       (22 | (16 << 8))
#define MAP_POKEMON_LEAGUE_CHAMPIONS_ROOM    (23 | (16 << 8))
#define MAP_POKEMON_LEAGUE_HALL_OF_FAME      (24 | (16 << 8))

// gMapGroup_IndoorOneIsland
#define MAP_FORTREE_CITY_HOUSE1            (0 | (17 << 8))
#define MAP_FORTREE_CITY_GYM               (1 | (17 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (2 | (17 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (3 | (17 << 8))
#define MAP_FORTREE_CITY_MART              (4 | (17 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (5 | (17 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (6 | (17 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (7 | (17 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (8 | (17 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (9 | (17 << 8))
#define MAP_ONE_ISLAND_POKEMON_CENTER_1F   (10 | (17 << 8))
#define MAP_ONE_ISLAND_POKEMON_CENTER_2F   (11 | (17 << 8))
#define MAP_ONE_ISLAND_HARBOR              (12 | (17 << 8))
#define MAP_ONE_ISLAND_HOUSE1              (13 | (17 << 8))
#define MAP_ONE_ISLAND_HOUSE2              (14 | (17 << 8))

// gMapGroup_IndoorTwoIsland
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (18 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (18 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (18 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (18 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (18 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (18 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         (6 | (18 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         (7 | (18 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (8 | (18 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                    (9 | (18 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (10 | (18 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (11 | (18 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (12 | (18 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (13 | (18 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (14 | (18 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (15 | (18 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (16 | (18 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (17 | (18 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (18 | (18 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (19 | (18 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (20 | (18 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (21 | (18 << 8))
#define MAP_TWO_ISLAND_POKEMON_CENTER_1F            (22 | (18 << 8))
#define MAP_TWO_ISLAND_POKEMON_CENTER_2F            (23 | (18 << 8))
#define MAP_TWO_ISLAND_HARBOR                       (24 | (18 << 8))
#define MAP_TWO_ISLAND_GAME_CORNER                  (25 | (18 << 8))
#define MAP_TWO_ISLAND_HOUSE                        (26 | (18 << 8))

// gMapGroup_IndoorThreeIsland
#define MAP_MOSSDEEP_CITY_GYM               (0 | (19 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1            (1 | (19 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (2 | (19 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (3 | (19 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (4 | (19 << 8))
#define MAP_MOSSDEEP_CITY_MART              (5 | (19 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (6 | (19 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (7 | (19 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (8 | (19 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (9 | (19 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (10 | (19 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (11 | (19 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (12 | (19 << 8))
#define MAP_THREE_ISLAND_POKEMON_CENTER_1F  (13 | (19 << 8))
#define MAP_THREE_ISLAND_POKEMON_CENTER_2F  (14 | (19 << 8))
#define MAP_THREE_ISLAND_MART               (15 | (19 << 8))
#define MAP_THREE_ISLAND_HOUSE1             (16 | (19 << 8))
#define MAP_THREE_ISLAND_HOUSE2             (17 | (19 << 8))
#define MAP_THREE_ISLAND_HOUSE3             (18 | (19 << 8))
#define MAP_THREE_ISLAND_HOUSE4             (19 | (19 << 8))
#define MAP_THREE_ISLAND_HOUSE5             (20 | (19 << 8))

// gMapGroup_IndoorFourIsland
#define MAP_SOOTOPOLIS_CITY_GYM_1F                   (0 | (20 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F                  (1 | (20 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F        (2 | (20 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F        (3 | (20 << 8))
#define MAP_SOOTOPOLIS_CITY_MART                     (4 | (20 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (5 | (20 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (6 | (20 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (7 | (20 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (8 | (20 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (9 | (20 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (10 | (20 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (11 | (20 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (12 | (20 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (13 | (20 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (14 | (20 << 8))
#define MAP_FOUR_ISLAND_POKEMON_CENTER_1F            (15 | (20 << 8))
#define MAP_FOUR_ISLAND_POKEMON_CENTER_2F            (16 | (20 << 8))
#define MAP_FOUR_ISLAND_MART                         (17 | (20 << 8))
#define MAP_FOUR_ISLAND_HARBOR                       (18 | (20 << 8))
#define MAP_FOUR_ISLAND_POKEMON_DAY_CARE             (19 | (20 << 8))
#define MAP_FOUR_ISLAND_LORELEIS_HOUSE               (20 | (20 << 8))
#define MAP_FOUR_ISLAND_HOUSE1                       (21 | (20 << 8))
#define MAP_FOUR_ISLAND_HOUSE2                       (22 | (20 << 8))

// gMapGroup_IndoorFiveIsland
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (21 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (21 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (21 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (21 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (21 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (21 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (21 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (21 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (21 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (21 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (21 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (21 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (21 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (21 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (21 << 8))
#define MAP_FIVE_ISLAND_POKEMON_CENTER_1F      (15 | (21 << 8))
#define MAP_FIVE_ISLAND_POKEMON_CENTER_2F      (16 | (21 << 8))
#define MAP_FIVE_ISLAND_HARBOR                 (17 | (21 << 8))
#define MAP_FIVE_ISLAND_HOUSE1                 (18 | (21 << 8))
#define MAP_FIVE_ISLAND_HOUSE2                 (19 | (21 << 8))

// gMapGroup_IndoorSixIsland
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (22 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (22 << 8))
#define MAP_SIX_ISLAND_POKEMON_CENTER_1F      (2 | (22 << 8))
#define MAP_SIX_ISLAND_POKEMON_CENTER_2F      (3 | (22 << 8))
#define MAP_SIX_ISLAND_MART                   (4 | (22 << 8))
#define MAP_SIX_ISLAND_HARBOR                 (5 | (22 << 8))
#define MAP_SIX_ISLAND_HOUSE                  (6 | (22 << 8))

// gMapGroup_IndoorSevenIsland
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (23 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (23 << 8))
#define MAP_SEVEN_ISLAND_POKEMON_CENTER_1F   (2 | (23 << 8))
#define MAP_SEVEN_ISLAND_POKEMON_CENTER_2F   (3 | (23 << 8))
#define MAP_SEVEN_ISLAND_MART                (4 | (23 << 8))
#define MAP_SEVEN_ISLAND_HARBOR              (5 | (23 << 8))
#define MAP_SEVEN_ISLAND_HOUSE_ROOM1         (6 | (23 << 8))
#define MAP_SEVEN_ISLAND_HOUSE_ROOM2         (7 | (23 << 8))

// gMapGroup_IndoorRoute2
#define MAP_ROUTE112_CABLE_CAR_STATION     (0 | (24 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION   (1 | (24 << 8))
#define MAP_VIRIDIAN_FOREST_NORTH_ENTRANCE (2 | (24 << 8))
#define MAP_VIRIDIAN_FOREST_SOUTH_ENTRANCE (3 | (24 << 8))
#define MAP_ROUTE2_EAST_BUILDING           (4 | (24 << 8))
#define MAP_ROUTE2_HOUSE1                  (5 | (24 << 8))

// gMapGroup_IndoorRoute4
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (25 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (25 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (25 << 8))
#define MAP_ROUTE4_POKEMON_CENTER_1F       (3 | (25 << 8))
#define MAP_ROUTE4_POKEMON_CENTER_2F       (4 | (25 << 8))

// gMapGroup_IndoorRoute5
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (26 << 8))
#define MAP_ROUTE5_POKEMON_DAY_CARE       (1 | (26 << 8))
#define MAP_ROUTE5_SOUTH_ENTRANCE         (2 | (26 << 8))

// gMapGroup_IndoorRoute6
#define MAP_ROUTE6_NORTH_ENTRANCE (0 | (27 << 8))

// gMapGroup_IndoorRoute7
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (28 << 8))
#define MAP_ROUTE7_EAST_ENTRANCE      (1 | (28 << 8))

// gMapGroup_IndoorRoute8
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (29 << 8))
#define MAP_ROUTE8_WEST_ENTRANCE          (1 | (29 << 8))

// gMapGroup_IndoorRoute10
#define MAP_ROUTE104_PROTOTYPE                          (0 | (30 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (30 << 8))
#define MAP_ROUTE10_POKEMON_CENTER_1F                   (2 | (30 << 8))
#define MAP_ROUTE10_POKEMON_CENTER_2F                   (3 | (30 << 8))

// gMapGroup_IndoorRoute11
#define MAP_ROUTE109_SEASHORE_HOUSE  (0 | (31 << 8))
#define MAP_ROUTE11_EAST_ENTRANCE_1F (1 | (31 << 8))
#define MAP_ROUTE11_EAST_ENTRANCE_2F (2 | (31 << 8))

// gMapGroup_IndoorRoute12
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (0 | (32 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (1 | (32 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (2 | (32 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (3 | (32 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (4 | (32 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (5 | (32 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (6 | (32 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (7 | (32 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (8 | (32 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (9 | (32 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (10 | (32 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (11 | (32 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (12 | (32 << 8))
#define MAP_ROUTE12_NORTH_ENTRANCE_1F                    (13 | (32 << 8))
#define MAP_ROUTE12_NORTH_ENTRANCE_2F                    (14 | (32 << 8))
#define MAP_ROUTE12_FISHING_HOUSE                        (15 | (32 << 8))

// gMapGroup_IndoorRoute15
#define MAP_ROUTE113_GLASS_WORKSHOP  (0 | (33 << 8))
#define MAP_ROUTE15_WEST_ENTRANCE_1F (1 | (33 << 8))
#define MAP_ROUTE15_WEST_ENTRANCE_2F (2 | (33 << 8))

// gMapGroup_IndoorRoute16
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (34 << 8))
#define MAP_ROUTE16_NORTH_ENTRANCE_1F    (1 | (34 << 8))
#define MAP_ROUTE16_NORTH_ENTRANCE_2F    (2 | (34 << 8))
#define MAP_ROUTE16_HOUSE1               (3 | (34 << 8))

// gMapGroup_IndoorRoute18
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (35 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (35 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (35 << 8))
#define MAP_ROUTE18_EAST_ENTRANCE_1F      (3 | (35 << 8))
#define MAP_ROUTE18_EAST_ENTRANCE_2F      (4 | (35 << 8))

// gMapGroup_IndoorRoute22
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0 | (36 << 8))
#define MAP_ROUTE22_NORTH_ENTRANCE                 (1 | (36 << 8))

// gMapGroup_IndoorRoute25
#define MAP_SEA_COTTAGE (0 | (37 << 8))

// gMapGroup_IndoorTwoIslandRoute
#define MAP_CAPE_BRINK_HOUSE (0 | (38 << 8))

// gMapGroup_IndoorThreeIslandRoute
#define MAP_THREE_ISLAND_HARBOR (0 | (39 << 8))

// gMapGroup_IndoorFiveIslandRoute
#define MAP_RESORT_GORGEOUS_HOUSE (0 | (40 << 8))

// gMapGroup_IndoorSixIslandRoute
#define MAP_WATER_PATH_HOUSE1 (0 | (41 << 8))
#define MAP_WATER_PATH_HOUSE2 (1 | (41 << 8))

// gMapGroup_IndoorSevenIslandRoute
#define MAP_SEVAULT_CANYON_HOUSE (0 | (42 << 8))

#define MAP_GROUPS_COUNT 43

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
