#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#define TRAINER_NONE                               0
#define TRAINER_AROMA_LADY_MIAH                    1
#define TRAINER_AROMA_LADY_NIKKI                   2
#define TRAINER_AROMA_LADY_ROSE                    3
#define TRAINER_AROMA_LADY_VIOLET                  4
#define TRAINER_BEAUTY_BRIDGET                     5
#define TRAINER_BEAUTY_GRACE                       6
#define TRAINER_BEAUTY_GRACE_2                     7
#define TRAINER_BEAUTY_GRACE_3                     8
#define TRAINER_BEAUTY_GRACE_4                     9
#define TRAINER_BEAUTY_GRACE_5                    10
#define TRAINER_BEAUTY_LOLA                       11
#define TRAINER_BEAUTY_LORI                       12
#define TRAINER_BEAUTY_OLIVIA                     13
#define TRAINER_BEAUTY_SHEILA                     14
#define TRAINER_BEAUTY_SHEILA_2                   15
#define TRAINER_BEAUTY_SHEILA_3                   16
#define TRAINER_BEAUTY_SHEILA_4                   17
#define TRAINER_BEAUTY_SHEILA_5                   18
#define TRAINER_BEAUTY_TAMIA                      19
#define TRAINER_BIKER_ALEX                        20
#define TRAINER_BIKER_BILLY                       21
#define TRAINER_BIKER_ERNEST                      22
#define TRAINER_BIKER_GERALD                      23
#define TRAINER_BIKER_GOON                        24
#define TRAINER_BIKER_GOON_2                      25
#define TRAINER_BIKER_GOON_3                      26
#define TRAINER_BIKER_HIDEO                       27
#define TRAINER_BIKER_ISAAC                       28
#define TRAINER_BIKER_JARED                       29
#define TRAINER_BIKER_JAREN                       30
#define TRAINER_BIKER_JAREN_2                     31
#define TRAINER_BIKER_JAREN_3                     32
#define TRAINER_BIKER_JAREN_4                     33
#define TRAINER_BIKER_JAREN_5                     34
#define TRAINER_BIKER_JAXON                       35
#define TRAINER_BIKER_JAXON_2                     36
#define TRAINER_BIKER_JAXON_3                     37
#define TRAINER_BIKER_JAXON_4                     38
#define TRAINER_BIKER_JAXON_5                     39
#define TRAINER_BIKER_LAO                         40
#define TRAINER_BIKER_LUKAS                       41
#define TRAINER_BIKER_LUKAS_2                     42
#define TRAINER_BIKER_LUKAS_3                     43
#define TRAINER_BIKER_LUKAS_4                     44
#define TRAINER_BIKER_LUKAS_5                     45
#define TRAINER_BIKER_MALIK                       46
#define TRAINER_BIKER_NIKOLAS                     47
#define TRAINER_BIKER_RICARDO                     48
#define TRAINER_BIKER_RUBEN                       49
#define TRAINER_BIKER_RUBEN_2                     50
#define TRAINER_BIKER_RUBEN_3                     51
#define TRAINER_BIKER_RUBEN_4                     52
#define TRAINER_BIKER_RUBEN_5                     53
#define TRAINER_BIKER_WILLIAM                     54
#define TRAINER_BIKER_VIRGIL                      55
#define TRAINER_BIRD_KEEPER_BECK                  56
#define TRAINER_BIRD_KEEPER_BENNY                 57
#define TRAINER_BIRD_KEEPER_BENNY_2               58
#define TRAINER_BIRD_KEEPER_BENNY_3               59
#define TRAINER_BIRD_KEEPER_BENNY_4               60
#define TRAINER_BIRD_KEEPER_BENNY_5               61
#define TRAINER_BIRD_KEEPER_CARTER                62
#define TRAINER_BIRD_KEEPER_CHAZ                  63
#define TRAINER_BIRD_KEEPER_CHAZ_2                64
#define TRAINER_BIRD_KEEPER_CHAZ_3                65
#define TRAINER_BIRD_KEEPER_CHAZ_4                66
#define TRAINER_BIRD_KEEPER_CHAZ_5                67
#define TRAINER_BIRD_KEEPER_CHESTER               68
#define TRAINER_BIRD_KEEPER_CHESTER_2             69
#define TRAINER_BIRD_KEEPER_CHESTER_3             70
#define TRAINER_BIRD_KEEPER_CHESTER_4             71
#define TRAINER_BIRD_KEEPER_CHESTER_5             72
#define TRAINER_BIRD_KEEPER_DONALD                73
#define TRAINER_BIRD_KEEPER_EDWIN                 74
#define TRAINER_BIRD_KEEPER_HAROLD                75
#define TRAINER_BIRD_KEEPER_JACOB                 76
#define TRAINER_BIRD_KEEPER_JACOB_2               77
#define TRAINER_BIRD_KEEPER_JACOB_3               78
#define TRAINER_BIRD_KEEPER_JACOB_4               79
#define TRAINER_BIRD_KEEPER_JACOB_5               80
#define TRAINER_BIRD_KEEPER_MARLON                81
#define TRAINER_BIRD_KEEPER_MARLON_2              82
#define TRAINER_BIRD_KEEPER_MARLON_3              83
#define TRAINER_BIRD_KEEPER_MARLON_4              84
#define TRAINER_BIRD_KEEPER_MARLON_5              85
#define TRAINER_BIRD_KEEPER_MILO                  86
#define TRAINER_BIRD_KEEPER_MILO_2                87
#define TRAINER_BIRD_KEEPER_MILO_3                88
#define TRAINER_BIRD_KEEPER_MILO_4                89
#define TRAINER_BIRD_KEEPER_MILO_5                90
#define TRAINER_BIRD_KEEPER_MITCH                 91
#define TRAINER_BIRD_KEEPER_PERRY                 92
#define TRAINER_BIRD_KEEPER_RAMIRO                93
#define TRAINER_BIRD_KEEPER_ROBERT                94
#define TRAINER_BIRD_KEEPER_ROBERT_2              95
#define TRAINER_BIRD_KEEPER_ROBERT_3              96
#define TRAINER_BIRD_KEEPER_ROBERT_4              97
#define TRAINER_BIRD_KEEPER_ROBERT_5              98
#define TRAINER_BIRD_KEEPER_ROGER                 99
#define TRAINER_BIRD_KEEPER_SEBASTIAN            100
#define TRAINER_BIRD_KEEPER_WILTON               101
#define TRAINER_BLACK_BELT_AARON                 102
#define TRAINER_BLACK_BELT_ATSUSHI               103
#define TRAINER_BLACK_BELT_DAISUKE               104
#define TRAINER_BLACK_BELT_HIDEKI                105
#define TRAINER_BLACK_BELT_HITOSHI               106
#define TRAINER_BLACK_BELT_HUGH                  107
#define TRAINER_BLACK_BELT_HUGH_2                108
#define TRAINER_BLACK_BELT_HUGH_3                109
#define TRAINER_BLACK_BELT_HUGH_4                110
#define TRAINER_BLACK_BELT_HUGH_5                111
#define TRAINER_BLACK_BELT_KIYO                  112
#define TRAINER_BLACK_BELT_KOICHI                113
#define TRAINER_BLACK_BELT_MIKE                  114
#define TRAINER_BLACK_BELT_SHEA                  115
#define TRAINER_BLACK_BELT_SHEA_2                116
#define TRAINER_BLACK_BELT_SHEA_3                117
#define TRAINER_BLACK_BELT_SHEA_4                118
#define TRAINER_BLACK_BELT_SHEA_5                119
#define TRAINER_BLACK_BELT_TAKASHI               120
#define TRAINER_BUG_CATCHER_ANTHONY              121
#define TRAINER_BUG_CATCHER_BRENT                122
#define TRAINER_BUG_CATCHER_CALE                 123
#define TRAINER_BUG_CATCHER_CHARLIE              124
#define TRAINER_BUG_CATCHER_COLTON               125
#define TRAINER_BUG_CATCHER_COLTON_2             126
#define TRAINER_BUG_CATCHER_COLTON_3             127
#define TRAINER_BUG_CATCHER_COLTON_4             128
#define TRAINER_BUG_CATCHER_COLTON_5             129
#define TRAINER_BUG_CATCHER_CONNER               130
#define TRAINER_BUG_CATCHER_DOUG                 131
#define TRAINER_BUG_CATCHER_ELIJAH               132
#define TRAINER_BUG_CATCHER_GARRET               133
#define TRAINER_BUG_CATCHER_GREG                 134
#define TRAINER_BUG_CATCHER_JAMES                135
#define TRAINER_BUG_CATCHER_JONAH                136
#define TRAINER_BUG_CATCHER_KENT                 137
#define TRAINER_BUG_CATCHER_KEIGO                138
#define TRAINER_BUG_CATCHER_RICK                 139
#define TRAINER_BUG_CATCHER_ROBBY                140
#define TRAINER_BUG_CATCHER_SAMMY                141
#define TRAINER_BUG_CATCHER_VANCE                142
#define TRAINER_BURGLAR_ARNIE                    143
#define TRAINER_BURGLAR_DUSTY                    144
#define TRAINER_BURGLAR_LEWIS                    145
#define TRAINER_BURGLAR_QUINN                    146
#define TRAINER_BURGLAR_RAMON                    147
#define TRAINER_BURGLAR_SIMON                    148
#define TRAINER_CAMPER_BRYCE                     149
#define TRAINER_CAMPER_CHRIS                     150
#define TRAINER_CAMPER_CHRIS_2                   151
#define TRAINER_CAMPER_CHRIS_3                   152
#define TRAINER_CAMPER_CHRIS_4                   153
#define TRAINER_CAMPER_CHRIS_5                   154
#define TRAINER_CAMPER_DREW                      155
#define TRAINER_CAMPER_ETHAN                     156
#define TRAINER_CAMPER_FLINT                     157
#define TRAINER_CAMPER_JEFF                      158
#define TRAINER_CAMPER_JEFF_2                    159
#define TRAINER_CAMPER_JEFF_3                    160
#define TRAINER_CAMPER_JEFF_4                    161
#define TRAINER_CAMPER_JEFF_5                    162
#define TRAINER_CAMPER_JUSTIN                    163
#define TRAINER_CAMPER_LIAM                      164
#define TRAINER_CAMPER_RICKY                     165
#define TRAINER_CAMPER_RICKY_2                   166
#define TRAINER_CAMPER_RICKY_3                   167
#define TRAINER_CAMPER_RICKY_4                   168
#define TRAINER_CAMPER_RICKY_5                   169
#define TRAINER_CAMPER_RILEY                     170
#define TRAINER_CAMPER_SHANE                     171
#define TRAINER_CHANNELER_AMANDA                 172
#define TRAINER_CHANNELER_ANGELICA               173
#define TRAINER_CHANNELER_CARLY                  174
#define TRAINER_CHANNELER_EMILIA                 175
#define TRAINER_CHANNELER_HOPE                   176
#define TRAINER_CHANNELER_JANAE                  177
#define TRAINER_CHANNELER_JENNIFER               178
#define TRAINER_CHANNELER_JODY                   179
#define TRAINER_CHANNELER_KARINA                 180
#define TRAINER_CHANNELER_LAUREL                 181
#define TRAINER_CHANNELER_PATRICIA               182
#define TRAINER_CHANNELER_PAULA                  183
#define TRAINER_CHANNELER_TAMMY                  184
#define TRAINER_CHANNELER_RUTH                   185
#define TRAINER_CHANNELER_STACY                  186
#define TRAINER_CHANNELER_TASHA                  187
#define TRAINER_COOLTRAINER_ALEXA                188
#define TRAINER_COOLTRAINER_CAROLINE             189
#define TRAINER_COOLTRAINER_COLBY                190
#define TRAINER_COOLTRAINER_GEORGE               191
#define TRAINER_COOLTRAINER_LEROY                192
#define TRAINER_COOLTRAINER_LEROY_2              193
#define TRAINER_COOLTRAINER_LEROY_3              194
#define TRAINER_COOLTRAINER_LEROY_4              195
#define TRAINER_COOLTRAINER_LEROY_5              196
#define TRAINER_COOLTRAINER_MARY                 197
#define TRAINER_COOLTRAINER_MICHELLE             198
#define TRAINER_COOLTRAINER_MICHELLE_2           199
#define TRAINER_COOLTRAINER_MICHELLE_3           200
#define TRAINER_COOLTRAINER_MICHELLE_4           201
#define TRAINER_COOLTRAINER_MICHELLE_5           202
#define TRAINER_COOLTRAINER_NAOMI                203
#define TRAINER_COOLTRAINER_ROLANDO              204
#define TRAINER_COOLTRAINER_SAMUEL               205
#define TRAINER_COOLTRAINER_WARREN               206
#define TRAINER_COOLTRAINER_YUJI                 207
#define TRAINER_COOL_COUPLE_LEX_NYA              208
#define TRAINER_COOL_COUPLE_RAY_TYRA             209
#define TRAINER_CRUSH_GIRL_CYNDY                 210
#define TRAINER_CRUSH_GIRL_JOCELYN               211
#define TRAINER_CRUSH_GIRL_SHARON                212
#define TRAINER_CRUSH_GIRL_SHARON_2              213
#define TRAINER_CRUSH_GIRL_SHARON_3              214
#define TRAINER_CRUSH_GIRL_SHARON_4              215
#define TRAINER_CRUSH_GIRL_SHARON_5              216
#define TRAINER_CRUSH_GIRL_TANYA                 217
#define TRAINER_CRUSH_GIRL_TANYA_2               218
#define TRAINER_CRUSH_GIRL_TANYA_3               219
#define TRAINER_CRUSH_GIRL_TANYA_4               220
#define TRAINER_CRUSH_GIRL_TANYA_5               221
#define TRAINER_CRUSH_KIN_MIK_KIA                222
#define TRAINER_CRUSH_KIN_MIK_KIA_2              223
#define TRAINER_CRUSH_KIN_MIK_KIA_3              224
#define TRAINER_CRUSH_KIN_MIK_KIA_4              225
#define TRAINER_CRUSH_KIN_MIK_KIA_5              226
#define TRAINER_CRUSH_KIN_RON_MYA                227
#define TRAINER_CRUSH_KIN_RON_MYA_2              228
#define TRAINER_CRUSH_KIN_RON_MYA_3              229
#define TRAINER_CRUSH_KIN_RON_MYA_4              230
#define TRAINER_CRUSH_KIN_RON_MYA_5              231
#define TRAINER_CUE_BALL_CAMRON                  232
#define TRAINER_CUE_BALL_CAMRON_2                233
#define TRAINER_CUE_BALL_CAMRON_3                234
#define TRAINER_CUE_BALL_CAMRON_4                235
#define TRAINER_CUE_BALL_CAMRON_5                236
#define TRAINER_CUE_BALL_COREY                   237
#define TRAINER_CUE_BALL_COREY_2                 238
#define TRAINER_CUE_BALL_COREY_3                 239
#define TRAINER_CUE_BALL_COREY_4                 240
#define TRAINER_CUE_BALL_COREY_5                 241
#define TRAINER_CUE_BALL_ISAIAH                  242
#define TRAINER_CUE_BALL_ISAIAH_2                243
#define TRAINER_CUE_BALL_ISAIAH_3                244
#define TRAINER_CUE_BALL_ISAIAH_4                245
#define TRAINER_CUE_BALL_ISAIAH_5                246
#define TRAINER_CUE_BALL_JAMAL                   247
#define TRAINER_CUE_BALL_KOJI                    248
#define TRAINER_CUE_BALL_LUKE                    249
#define TRAINER_CUE_BALL_PAXTON                  250
#define TRAINER_CUE_BALL_RAUL                    251
#define TRAINER_CUE_BALL_ZEEK                    252
#define TRAINER_ENGINEER_BAILY                   253
#define TRAINER_ENGINEER_BERNIE                  254
#define TRAINER_ENGINEER_BERNIE_2                255
#define TRAINER_ENGINEER_BERNIE_3                256
#define TRAINER_ENGINEER_BERNIE_4                257
#define TRAINER_ENGINEER_BERNIE_5                258
#define TRAINER_ENGINEER_BRAXTON                 259
#define TRAINER_FISHERMAN_ANDREW                 260
#define TRAINER_FISHERMAN_BARNY                  261
#define TRAINER_FISHERMAN_CHIP                   262
#define TRAINER_FISHERMAN_CLAUDE                 263
#define TRAINER_FISHERMAN_DALE                   264
#define TRAINER_FISHERMAN_ELLIOT                 265
#define TRAINER_FISHERMAN_ELLIOT_2               266
#define TRAINER_FISHERMAN_ELLIOT_3               267
#define TRAINER_FISHERMAN_ELLIOT_4               268
#define TRAINER_FISHERMAN_ELLIOT_5               269
#define TRAINER_FISHERMAN_HANK                   270
#define TRAINER_FISHERMAN_NED                    271
#define TRAINER_FISHERMAN_NOLAN                  272
#define TRAINER_FISHERMAN_RONALD                 273
#define TRAINER_FISHERMAN_TOMMY                  274
#define TRAINER_FISHERMAN_TYLOR                  275
#define TRAINER_FISHERMAN_WADE                   276
#define TRAINER_FISHERMAN_WADE_2                 277
#define TRAINER_FISHERMAN_WADE_3                 278
#define TRAINER_FISHERMAN_WADE_4                 279
#define TRAINER_FISHERMAN_WADE_5                 280
#define TRAINER_GAMBLER_DARIAN                   281
#define TRAINER_GAMBLER_DARIAN_2                 282
#define TRAINER_GAMBLER_DARIAN_3                 283
#define TRAINER_GAMBLER_DARIAN_4                 284
#define TRAINER_GAMBLER_DARIAN_5                 285
#define TRAINER_GAMBLER_DIRK                     286
#define TRAINER_GAMBLER_HUGO                     287
#define TRAINER_GAMBLER_JASPER                   288
#define TRAINER_GAMBLER_RICH                     289
#define TRAINER_GAMBLER_RICH_2                   290
#define TRAINER_GAMBLER_RICH_3                   291
#define TRAINER_GAMBLER_RICH_4                   292
#define TRAINER_GAMBLER_RICH_5                   293
#define TRAINER_GAMBLER_STAN                     294
#define TRAINER_GENTLEMAN_ARTHUR                 295
#define TRAINER_GENTLEMAN_BROOKS                 296
#define TRAINER_GENTLEMAN_CLIFFORD               297
#define TRAINER_GENTLEMAN_LAMAR                  298
#define TRAINER_GENTLEMAN_THOMAS                 299
#define TRAINER_GENTLEMAN_TUCKER                 300
#define TRAINER_HIKER_ALAN                       301
#define TRAINER_HIKER_ALLEN                      302
#define TRAINER_HIKER_BRICE                      303
#define TRAINER_HIKER_CLARK                      304
#define TRAINER_HIKER_DARYL                      305
#define TRAINER_HIKER_DUDLEY                     306
#define TRAINER_HIKER_EARL                       307
#define TRAINER_HIKER_EARL_2                     308
#define TRAINER_HIKER_EARL_3                     309
#define TRAINER_HIKER_EARL_4                     310
#define TRAINER_HIKER_EARL_5                     311
#define TRAINER_HIKER_ERIC                       312
#define TRAINER_HIKER_FRANKLIN                   313
#define TRAINER_HIKER_FRANKLIN_2                 314
#define TRAINER_HIKER_FRANKLIN_3                 315
#define TRAINER_HIKER_FRANKLIN_4                 316
#define TRAINER_HIKER_FRANKLIN_5                 317
#define TRAINER_HIKER_JEREMY                     318
#define TRAINER_HIKER_JEREMY_2                   319
#define TRAINER_HIKER_JEREMY_3                   320
#define TRAINER_HIKER_JEREMY_4                   321
#define TRAINER_HIKER_JEREMY_5                   322
#define TRAINER_HIKER_LENNY                      323
#define TRAINER_HIKER_LUCAS                      324
#define TRAINER_HIKER_MARCOS                     325
#define TRAINER_HIKER_NOB                        326
#define TRAINER_HIKER_OLIVER                     327
#define TRAINER_HIKER_TRENT                      328
#define TRAINER_HIKER_TRENT_2                    329
#define TRAINER_HIKER_TRENT_3                    330
#define TRAINER_HIKER_TRENT_4                    331
#define TRAINER_HIKER_TRENT_5                    332
#define TRAINER_HIKER_WAYNE                      333
#define TRAINER_JUGGLER_DALTON                   334
#define TRAINER_JUGGLER_EDWARD                   335
#define TRAINER_JUGGLER_GREGORY                  336
#define TRAINER_JUGGLER_KAYDEN                   337
#define TRAINER_JUGGLER_KIRK                     338
#define TRAINER_JUGGLER_MASON                    339
#define TRAINER_JUGGLER_MASON_2                  340
#define TRAINER_JUGGLER_MASON_3                  341
#define TRAINER_JUGGLER_MASON_4                  342
#define TRAINER_JUGGLER_MASON_5                  343
#define TRAINER_JUGGLER_NATE                     344
#define TRAINER_JUGGLER_NELSON                   345
#define TRAINER_JUGGLER_SHAWN                    346
#define TRAINER_LADY_GILLIAN                     347
#define TRAINER_LADY_JACKI                       348
#define TRAINER_LADY_SELPHY                      349
#define TRAINER_LASS_ALI                         350
#define TRAINER_LASS_ANDREA                      351
#define TRAINER_LASS_ANN                         352
#define TRAINER_LASS_CRISSY                      353
#define TRAINER_LASS_DALIA                       354
#define TRAINER_LASS_DAWN                        355
#define TRAINER_LASS_HALEY                       356
#define TRAINER_LASS_IRIS                        357
#define TRAINER_LASS_JANICE                      358
#define TRAINER_LASS_JANICE_2                    359
#define TRAINER_LASS_JANICE_3                    360
#define TRAINER_LASS_JANICE_4                    361
#define TRAINER_LASS_JANICE_5                    362
#define TRAINER_LASS_JOANA                       363
#define TRAINER_LASS_JULIA                       364
#define TRAINER_LASS_KAY                         365
#define TRAINER_LASS_LISA                        366
#define TRAINER_LASS_MEGAN                       367
#define TRAINER_LASS_MEGAN_2                     368
#define TRAINER_LASS_MEGAN_3                     369
#define TRAINER_LASS_MEGAN_4                     370
#define TRAINER_LASS_MEGAN_5                     371
#define TRAINER_LASS_MIRIAM                      372
#define TRAINER_LASS_PAIGE                       373
#define TRAINER_LASS_RELI                        374
#define TRAINER_LASS_RELI_2                      375
#define TRAINER_LASS_RELI_3                      376
#define TRAINER_LASS_RELI_4                      377
#define TRAINER_LASS_RELI_5                      378
#define TRAINER_LASS_ROBIN                       379
#define TRAINER_LASS_SALLY                       380
#define TRAINER_LEADER_BROCK                     381
#define TRAINER_LEADER_BROCK_2                   382
#define TRAINER_LEADER_BROCK_3                   383
#define TRAINER_LEADER_BROCK_4                   384
#define TRAINER_LEADER_BROCK_5                   385
#define TRAINER_LEADER_MISTY                     386
#define TRAINER_LEADER_MISTY_2                   387
#define TRAINER_LEADER_MISTY_3                   388
#define TRAINER_LEADER_MISTY_4                   389
#define TRAINER_LEADER_MISTY_5                   390
#define TRAINER_LEADER_LT_SURGE                  391
#define TRAINER_LEADER_LT_SURGE_2                392
#define TRAINER_LEADER_LT_SURGE_3                393
#define TRAINER_LEADER_LT_SURGE_4                394
#define TRAINER_LEADER_LT_SURGE_5                395
#define TRAINER_LEADER_ERIKA                     396
#define TRAINER_LEADER_ERIKA_2                   397
#define TRAINER_LEADER_ERIKA_3                   398
#define TRAINER_LEADER_ERIKA_4                   399
#define TRAINER_LEADER_ERIKA_5                   400
#define TRAINER_LEADER_KOGA                      401
#define TRAINER_LEADER_KOGA_2                    402
#define TRAINER_LEADER_KOGA_3                    403
#define TRAINER_LEADER_KOGA_4                    404
#define TRAINER_LEADER_KOGA_5                    405
#define TRAINER_LEADER_SABRINA                   406
#define TRAINER_LEADER_SABRINA_2                 407
#define TRAINER_LEADER_SABRINA_3                 408
#define TRAINER_LEADER_SABRINA_4                 409
#define TRAINER_LEADER_SABRINA_5                 410
#define TRAINER_LEADER_BLAINE                    411
#define TRAINER_LEADER_BLAINE_2                  412
#define TRAINER_LEADER_BLAINE_3                  413
#define TRAINER_LEADER_BLAINE_4                  414
#define TRAINER_LEADER_BLAINE_5                  415
#define TRAINER_BOSS_GIOVANNI                    416
#define TRAINER_BOSS_GIOVANNI_2                  417
#define TRAINER_LEADER_GIOVANNI                  418
#define TRAINER_PAINTER_CELINA                   419
#define TRAINER_PAINTER_DAISY                    420
#define TRAINER_PAINTER_EDNA                     421
#define TRAINER_PAINTER_RAYNA                    422
#define TRAINER_PAINTER_RAYNA_2                  423
#define TRAINER_PAINTER_RAYNA_3                  424
#define TRAINER_PAINTER_RAYNA_4                  425
#define TRAINER_PAINTER_RAYNA_5                  426
#define TRAINER_PICNICKER_ALICIA                 427
#define TRAINER_PICNICKER_ALMA                   428
#define TRAINER_PICNICKER_ARIANA                 429
#define TRAINER_PICNICKER_BECKY                  430
#define TRAINER_PICNICKER_BECKY_2                431
#define TRAINER_PICNICKER_BECKY_3                432
#define TRAINER_PICNICKER_BECKY_4                433
#define TRAINER_PICNICKER_BECKY_5                434
#define TRAINER_PICNICKER_CAITLIN                435
#define TRAINER_PICNICKER_CAITLIN_2              436
#define TRAINER_PICNICKER_CAITLIN_3              437
#define TRAINER_PICNICKER_CAITLIN_4              438
#define TRAINER_PICNICKER_CAITLIN_5              439
#define TRAINER_PICNICKER_CAROL                  440
#define TRAINER_PICNICKER_CELIA                  441
#define TRAINER_PICNICKER_CLAIRE                 442
#define TRAINER_PICNICKER_DANA                   443
#define TRAINER_PICNICKER_DIANA                  444
#define TRAINER_PICNICKER_GWEN                   445
#define TRAINER_PICNICKER_HEIDI                  446
#define TRAINER_PICNICKER_IRENE                  447
#define TRAINER_PICNICKER_ISABELLE               448
#define TRAINER_PICNICKER_ISABELLE_2             449
#define TRAINER_PICNICKER_ISABELLE_3             450
#define TRAINER_PICNICKER_ISABELLE_4             451
#define TRAINER_PICNICKER_ISABELLE_5             452
#define TRAINER_PICNICKER_KELSEY                 453
#define TRAINER_PICNICKER_KELSEY_2               454
#define TRAINER_PICNICKER_KELSEY_3               455
#define TRAINER_PICNICKER_KELSEY_4               456
#define TRAINER_PICNICKER_KELSEY_5               457
#define TRAINER_PICNICKER_KINDRA                 458
#define TRAINER_PICNICKER_LEAH                   459
#define TRAINER_PICNICKER_MARCY                  460
#define TRAINER_PICNICKER_MARTHA                 461
#define TRAINER_PICNICKER_MISSY                  462
#define TRAINER_PICNICKER_MISSY_2                463
#define TRAINER_PICNICKER_MISSY_3                464
#define TRAINER_PICNICKER_MISSY_4                465
#define TRAINER_PICNICKER_MISSY_5                466
#define TRAINER_PICNICKER_NANCY                  467
#define TRAINER_PICNICKER_SOFIA                  468
#define TRAINER_PICNICKER_SUSIE                  469
#define TRAINER_PICNICKER_SUSIE_2                470
#define TRAINER_PICNICKER_SUSIE_3                471
#define TRAINER_PICNICKER_SUSIE_4                472
#define TRAINER_PICNICKER_SUSIE_5                473
#define TRAINER_PICNICKER_TINA                   474
#define TRAINER_PICNICKER_VALERIE                475
#define TRAINER_PICNICKER_YAZMIN                 476
#define TRAINER_PKMN_BREEDER_ALIZE               477
#define TRAINER_PKMN_BREEDER_ALIZE_2             478
#define TRAINER_PKMN_BREEDER_ALIZE_3             479
#define TRAINER_PKMN_BREEDER_ALIZE_4             480
#define TRAINER_PKMN_BREEDER_ALIZE_5             481
#define TRAINER_PKMN_BREEDER_ALLISON             482
#define TRAINER_PKMN_BREEDER_BETHANY             483
#define TRAINER_PKMN_RANGER_BETH                 484
#define TRAINER_PKMN_RANGER_JACKSON              485
#define TRAINER_PKMN_RANGER_KATELYN              486
#define TRAINER_PKMN_RANGER_KATELYN_2            487
#define TRAINER_PKMN_RANGER_KATELYN_3            488
#define TRAINER_PKMN_RANGER_KATELYN_4            489
#define TRAINER_PKMN_RANGER_KATELYN_5            490
#define TRAINER_PKMN_RANGER_LOGAN                491
#define TRAINER_PKMN_RANGER_MADELINE             492
#define TRAINER_PKMN_RANGER_MADELINE_2           493
#define TRAINER_PKMN_RANGER_MADELINE_3           494
#define TRAINER_PKMN_RANGER_MADELINE_4           495
#define TRAINER_PKMN_RANGER_MADELINE_5           496
#define TRAINER_PKMN_RANGER_NICOLAS              497
#define TRAINER_PKMN_RANGER_NICOLAS_2            498
#define TRAINER_PKMN_RANGER_NICOLAS_3            499
#define TRAINER_PKMN_RANGER_NICOLAS_4            500
#define TRAINER_PKMN_RANGER_NICOLAS_5            501
#define TRAINER_POKEMANIAC_ASHTON                502
#define TRAINER_POKEMANIAC_COOPER                503
#define TRAINER_POKEMANIAC_DAWSON                504
#define TRAINER_POKEMANIAC_HECTOR                505
#define TRAINER_POKEMANIAC_HECTOR_2              506
#define TRAINER_POKEMANIAC_HECTOR_3              507
#define TRAINER_POKEMANIAC_HECTOR_4              508
#define TRAINER_POKEMANIAC_HECTOR_5              509
#define TRAINER_POKEMANIAC_HERMAN                510
#define TRAINER_POKEMANIAC_HERMAN_2              511
#define TRAINER_POKEMANIAC_HERMAN_3              512
#define TRAINER_POKEMANIAC_HERMAN_4              513
#define TRAINER_POKEMANIAC_HERMAN_5              514
#define TRAINER_POKEMANIAC_MARK                  515
#define TRAINER_POKEMANIAC_MARK_2                516
#define TRAINER_POKEMANIAC_MARK_3                517
#define TRAINER_POKEMANIAC_MARK_4                518
#define TRAINER_POKEMANIAC_MARK_5                519
#define TRAINER_POKEMANIAC_STEVE                 520
#define TRAINER_POKEMANIAC_WINSTON               521
#define TRAINER_PSYCHIC_CAMERON                  522
#define TRAINER_PSYCHIC_DARIO                    523
#define TRAINER_PSYCHIC_DARIO_2                  524
#define TRAINER_PSYCHIC_DARIO_3                  525
#define TRAINER_PSYCHIC_DARIO_4                  526
#define TRAINER_PSYCHIC_DARIO_5                  527
#define TRAINER_PSYCHIC_JACLYN                   528
#define TRAINER_PSYCHIC_JACLYN_2                 529
#define TRAINER_PSYCHIC_JACLYN_3                 530
#define TRAINER_PSYCHIC_JACLYN_4                 531
#define TRAINER_PSYCHIC_JACLYN_5                 532
#define TRAINER_PSYCHIC_JOHAN                    533
#define TRAINER_PSYCHIC_LAURA                    534
#define TRAINER_PSYCHIC_PRESTON                  535
#define TRAINER_PSYCHIC_RODETTE                  536
#define TRAINER_PSYCHIC_RODETTE_2                537
#define TRAINER_PSYCHIC_RODETTE_3                538
#define TRAINER_PSYCHIC_RODETTE_4                539
#define TRAINER_PSYCHIC_RODETTE_5                540
#define TRAINER_PSYCHIC_TYRON                    541
#define TRAINER_RIVAL_OAKS_LAB_SQUIRTLE          542
#define TRAINER_RIVAL_OAKS_LAB_BULBASAUR         543
#define TRAINER_RIVAL_OAKS_LAB_CHARMANDER        544
#define TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE     545
#define TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR    546
#define TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER   547
#define TRAINER_RIVAL_CERULEAN_SQUIRTLE          548
#define TRAINER_RIVAL_CERULEAN_BULBASAUR         549
#define TRAINER_RIVAL_CERULEAN_CHARMANDER        550
#define TRAINER_RIVAL_SS_ANNE_SQUIRTLE           551
#define TRAINER_RIVAL_SS_ANNE_BULBASAUR          552
#define TRAINER_RIVAL_SS_ANNE_CHARMANDER         553
#define TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE     554
#define TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR    555
#define TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER   556
#define TRAINER_RIVAL_SILPH_SQUIRTLE             557
#define TRAINER_RIVAL_SILPH_BULBASAUR            558
#define TRAINER_RIVAL_SILPH_CHARMANDER           559
#define TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE      560
#define TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR     561
#define TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER    562
#define TRAINER_ROCKER_LUCA                      563
#define TRAINER_ROCKER_LUCA_2                    564
#define TRAINER_ROCKER_LUCA_3                    565
#define TRAINER_ROCKER_LUCA_4                    566
#define TRAINER_ROCKER_LUCA_5                    567
#define TRAINER_RUIN_MANIAC_BENJAMIN             568
#define TRAINER_RUIN_MANIAC_BRANDON              569
#define TRAINER_RUIN_MANIAC_FOSTER               570
#define TRAINER_RUIN_MANIAC_LARRY                571
#define TRAINER_RUIN_MANIAC_LARRY_2              572
#define TRAINER_RUIN_MANIAC_LARRY_3              573
#define TRAINER_RUIN_MANIAC_LARRY_4              574
#define TRAINER_RUIN_MANIAC_LARRY_5              575
#define TRAINER_RUIN_MANIAC_LAWSON               576
#define TRAINER_RUIN_MANIAC_LAYTON               577
#define TRAINER_RUIN_MANIAC_STANLY               578
#define TRAINER_SAILOR_DUNCAN                    579
#define TRAINER_SAILOR_DWAYNE                    580
#define TRAINER_SAILOR_DYLAN                     581
#define TRAINER_SAILOR_EDMOND                    582
#define TRAINER_SAILOR_HUEY                      583
#define TRAINER_SAILOR_LEONARD                   584
#define TRAINER_SAILOR_PHILLIP                   585
#define TRAINER_SAILOR_TREVOR                    586
#define TRAINER_SCIENTIST_BEAU                   587
#define TRAINER_SCIENTIST_BRAYDON                588
#define TRAINER_SCIENTIST_CONNOR                 589
#define TRAINER_SCIENTIST_ED                     590
#define TRAINER_SCIENTIST_GIDEON                 591
#define TRAINER_SCIENTIST_IVAN                   592
#define TRAINER_SCIENTIST_JERRY                  593
#define TRAINER_SCIENTIST_JOSE                   594
#define TRAINER_SCIENTIST_JOSHUA                 595
#define TRAINER_SCIENTIST_PARKER                 596
#define TRAINER_SCIENTIST_RODNEY                 597
#define TRAINER_SCIENTIST_TAYLOR                 598
#define TRAINER_SCIENTIST_TED                    599
#define TRAINER_SCIENTIST_TRAVIS                 600
#define TRAINER_SIS_AND_BRO_AVA_GEB              601
#define TRAINER_SIS_AND_BRO_LIA_LUC              602
#define TRAINER_SIS_AND_BRO_LIL_IAN              603
#define TRAINER_SIS_AND_BRO_LIL_IAN_2            604
#define TRAINER_SIS_AND_BRO_LIL_IAN_3            605
#define TRAINER_SIS_AND_BRO_LIL_IAN_4            606
#define TRAINER_SIS_AND_BRO_LIL_IAN_5            607
#define TRAINER_SUPER_NERD_AIDAN                 608
#define TRAINER_SUPER_NERD_AVERY                 609
#define TRAINER_SUPER_NERD_DEREK                 610
#define TRAINER_SUPER_NERD_ERIK                  611
#define TRAINER_SUPER_NERD_GLENN                 612
#define TRAINER_SUPER_NERD_JOVAN                 613
#define TRAINER_SUPER_NERD_LESLIE                614
#define TRAINER_SUPER_NERD_MIGUEL                615
#define TRAINER_SUPER_NERD_ZAC                   616
#define TRAINER_SWIMMER_FEMALE_ABIGAIL           617
#define TRAINER_SWIMMER_FEMALE_ALICE             618
#define TRAINER_SWIMMER_FEMALE_ALICE_2           619
#define TRAINER_SWIMMER_FEMALE_ALICE_3           620
#define TRAINER_SWIMMER_FEMALE_ALICE_4           621
#define TRAINER_SWIMMER_FEMALE_ALICE_5           622
#define TRAINER_SWIMMER_FEMALE_AMARA             623
#define TRAINER_SWIMMER_FEMALE_ANYA              624
#define TRAINER_SWIMMER_FEMALE_CONNIE            625
#define TRAINER_SWIMMER_FEMALE_DENISE            626
#define TRAINER_SWIMMER_FEMALE_MARIA             627
#define TRAINER_SWIMMER_FEMALE_MELISSA           628
#define TRAINER_SWIMMER_FEMALE_MELISSA_2         629
#define TRAINER_SWIMMER_FEMALE_MELISSA_3         630
#define TRAINER_SWIMMER_FEMALE_MELISSA_4         631
#define TRAINER_SWIMMER_FEMALE_MELISSA_5         632
#define TRAINER_SWIMMER_FEMALE_NICOLE            633
#define TRAINER_SWIMMER_FEMALE_NICOLE_2          634
#define TRAINER_SWIMMER_FEMALE_NICOLE_3          635
#define TRAINER_SWIMMER_FEMALE_NICOLE_4          636
#define TRAINER_SWIMMER_FEMALE_NICOLE_5          637
#define TRAINER_SWIMMER_FEMALE_NORA              638
#define TRAINER_SWIMMER_FEMALE_SHIRLEY           639
#define TRAINER_SWIMMER_FEMALE_TIFFANY           640
#define TRAINER_SWIMMER_FEMALE_TISHA             641
#define TRAINER_SWIMMER_MALE_AXLE                642
#define TRAINER_SWIMMER_MALE_BARRY               643
#define TRAINER_SWIMMER_MALE_DARRIN              644
#define TRAINER_SWIMMER_MALE_DARRIN_2            645
#define TRAINER_SWIMMER_MALE_DARRIN_3            646
#define TRAINER_SWIMMER_MALE_DARRIN_4            647
#define TRAINER_SWIMMER_MALE_DARRIN_5            648
#define TRAINER_SWIMMER_MALE_DAVID               649
#define TRAINER_SWIMMER_MALE_DEAN                650
#define TRAINER_SWIMMER_MALE_DOUGLAS             651
#define TRAINER_SWIMMER_MALE_FINN                652
#define TRAINER_SWIMMER_MALE_FINN_2              653
#define TRAINER_SWIMMER_MALE_FINN_3              654
#define TRAINER_SWIMMER_MALE_FINN_4              655
#define TRAINER_SWIMMER_MALE_FINN_5              656
#define TRAINER_SWIMMER_MALE_GARRETT             657
#define TRAINER_SWIMMER_MALE_JACK                658
#define TRAINER_SWIMMER_MALE_JACK_2              659
#define TRAINER_SWIMMER_MALE_JACK_3              660
#define TRAINER_SWIMMER_MALE_JACK_4              661
#define TRAINER_SWIMMER_MALE_JACK_5              662
#define TRAINER_SWIMMER_MALE_JEROME              663
#define TRAINER_SWIMMER_MALE_LUIS                664
#define TRAINER_SWIMMER_MALE_MATTHEW             665
#define TRAINER_SWIMMER_MALE_MATTHEW_2           666
#define TRAINER_SWIMMER_MALE_MATTHEW_3           667
#define TRAINER_SWIMMER_MALE_MATTHEW_4           668
#define TRAINER_SWIMMER_MALE_MATTHEW_5           669
#define TRAINER_SWIMMER_MALE_MYMO                670
#define TRAINER_SWIMMER_MALE_REECE               671
#define TRAINER_SWIMMER_MALE_RICHARD             672
#define TRAINER_SWIMMER_MALE_ROLAND              673
#define TRAINER_SWIMMER_MALE_SAMIR               674
#define TRAINER_SWIMMER_MALE_SAMIR_2             675
#define TRAINER_SWIMMER_MALE_SAMIR_3             676
#define TRAINER_SWIMMER_MALE_SAMIR_4             677
#define TRAINER_SWIMMER_MALE_SAMIR_5             678
#define TRAINER_SWIMMER_MALE_SPENCER             679
#define TRAINER_SWIMMER_MALE_TOBY                680
#define TRAINER_SWIMMER_MALE_TONY                681
#define TRAINER_SWIMMER_MALE_TONY_2              682
#define TRAINER_SWIMMER_MALE_TONY_3              683
#define TRAINER_SWIMMER_MALE_TONY_4              684
#define TRAINER_SWIMMER_MALE_TONY_5              685
#define TRAINER_TAMER_COLE                       686
#define TRAINER_TAMER_EDGAR                      687
#define TRAINER_TAMER_EVAN                       688
#define TRAINER_TAMER_JASON                      689
#define TRAINER_TAMER_PHIL                       690
#define TRAINER_TAMER_VINCENT                    691
#define TRAINER_TEAM_ROCKET_ADMIN                692
#define TRAINER_TEAM_ROCKET_ADMIN_2              693
#define TRAINER_TEAM_ROCKET_GRUNT                694
#define TRAINER_TEAM_ROCKET_GRUNT_2              695
#define TRAINER_TEAM_ROCKET_GRUNT_3              696
#define TRAINER_TEAM_ROCKET_GRUNT_4              697
#define TRAINER_TEAM_ROCKET_GRUNT_5              698
#define TRAINER_TEAM_ROCKET_GRUNT_6              699
#define TRAINER_TEAM_ROCKET_GRUNT_7              700
#define TRAINER_TEAM_ROCKET_GRUNT_8              701
#define TRAINER_TEAM_ROCKET_GRUNT_9              702
#define TRAINER_TEAM_ROCKET_GRUNT_10             703
#define TRAINER_TEAM_ROCKET_GRUNT_11             704
#define TRAINER_TEAM_ROCKET_GRUNT_12             705
#define TRAINER_TEAM_ROCKET_GRUNT_13             706
#define TRAINER_TEAM_ROCKET_GRUNT_14             707
#define TRAINER_TEAM_ROCKET_GRUNT_15             708
#define TRAINER_TEAM_ROCKET_GRUNT_16             709
#define TRAINER_TEAM_ROCKET_GRUNT_17             710
#define TRAINER_TEAM_ROCKET_GRUNT_18             711
#define TRAINER_TEAM_ROCKET_GRUNT_19             712
#define TRAINER_TEAM_ROCKET_GRUNT_20             713
#define TRAINER_TEAM_ROCKET_GRUNT_21             714
#define TRAINER_TEAM_ROCKET_GRUNT_23             715
#define TRAINER_TEAM_ROCKET_GRUNT_24             716
#define TRAINER_TEAM_ROCKET_GRUNT_25             717
#define TRAINER_TEAM_ROCKET_GRUNT_26             718
#define TRAINER_TEAM_ROCKET_GRUNT_27             719
#define TRAINER_TEAM_ROCKET_GRUNT_28             720
#define TRAINER_TEAM_ROCKET_GRUNT_29             721
#define TRAINER_TEAM_ROCKET_GRUNT_30             722
#define TRAINER_TEAM_ROCKET_GRUNT_31             723
#define TRAINER_TEAM_ROCKET_GRUNT_32             724
#define TRAINER_TEAM_ROCKET_GRUNT_33             725
#define TRAINER_TEAM_ROCKET_GRUNT_34             726
#define TRAINER_TEAM_ROCKET_GRUNT_35             727
#define TRAINER_TEAM_ROCKET_GRUNT_36             728
#define TRAINER_TEAM_ROCKET_GRUNT_37             729
#define TRAINER_TEAM_ROCKET_GRUNT_38             730
#define TRAINER_TEAM_ROCKET_GRUNT_39             731
#define TRAINER_TEAM_ROCKET_GRUNT_40             732
#define TRAINER_TEAM_ROCKET_GRUNT_41             733
#define TRAINER_TEAM_ROCKET_GRUNT_42             734
#define TRAINER_TEAM_ROCKET_GRUNT_43             735
#define TRAINER_TEAM_ROCKET_GRUNT_44             736
#define TRAINER_TEAM_ROCKET_GRUNT_45             737
#define TRAINER_TEAM_ROCKET_GRUNT_46             738
#define TRAINER_TEAM_ROCKET_GRUNT_47             739
#define TRAINER_TEAM_ROCKET_GRUNT_48             740
#define TRAINER_TEAM_ROCKET_GRUNT_49             741
#define TRAINER_TEAM_ROCKET_GRUNT_50             742
#define TRAINER_TEAM_ROCKET_GRUNT_51             743
#define TRAINER_TUBER_ALEXIS                     744
#define TRAINER_TUBER_AMIRA                      745
#define TRAINER_TUBER_AMIRA_2                    746
#define TRAINER_TUBER_AMIRA_3                    747
#define TRAINER_TUBER_AMIRA_4                    748
#define TRAINER_TUBER_AMIRA_5                    749
#define TRAINER_TWINS_ELI_ANNE                   750
#define TRAINER_TWINS_ELI_ANNE_2                 751
#define TRAINER_TWINS_ELI_ANNE_3                 752
#define TRAINER_TWINS_ELI_ANNE_4                 753
#define TRAINER_TWINS_ELI_ANNE_5                 754
#define TRAINER_TWINS_JOY_MEG                    755
#define TRAINER_TWINS_JOY_MEG_2                  756
#define TRAINER_TWINS_JOY_MEG_3                  757
#define TRAINER_TWINS_JOY_MEG_4                  758
#define TRAINER_TWINS_JOY_MEG_5                  759
#define TRAINER_TWINS_KIRI_JAN                   760
#define TRAINER_TWINS_MIU_MIA                    761
#define TRAINER_YOUNG_COUPLE_EVE_JON             762
#define TRAINER_YOUNG_COUPLE_GIA_JES             763
#define TRAINER_YOUNG_COUPLE_GIA_JES_2           764
#define TRAINER_YOUNG_COUPLE_GIA_JES_3           765
#define TRAINER_YOUNG_COUPLE_GIA_JES_4           766
#define TRAINER_YOUNG_COUPLE_GIA_JES_5           767
#define TRAINER_YOUNG_COUPLE_LEA_JED             768
#define TRAINER_YOUNGSTER_BEN                    769
#define TRAINER_YOUNGSTER_BEN_2                  770
#define TRAINER_YOUNGSTER_BEN_3                  771
#define TRAINER_YOUNGSTER_BEN_4                  772
#define TRAINER_YOUNGSTER_BEN_5                  773
#define TRAINER_YOUNGSTER_CALVIN                 774
#define TRAINER_YOUNGSTER_CHAD                   775
#define TRAINER_YOUNGSTER_CHAD_2                 776
#define TRAINER_YOUNGSTER_CHAD_3                 777
#define TRAINER_YOUNGSTER_CHAD_4                 778
#define TRAINER_YOUNGSTER_CHAD_5                 779
#define TRAINER_YOUNGSTER_CORDELL                780
#define TRAINER_YOUNGSTER_DAN                    781
#define TRAINER_YOUNGSTER_DAVE                   782
#define TRAINER_YOUNGSTER_DESTIN                 783
#define TRAINER_YOUNGSTER_DESTIN_2               784
#define TRAINER_YOUNGSTER_DESTIN_3               785
#define TRAINER_YOUNGSTER_DESTIN_4               786
#define TRAINER_YOUNGSTER_DESTIN_5               787
#define TRAINER_YOUNGSTER_DILLON                 788
#define TRAINER_YOUNGSTER_EDDIE                  789
#define TRAINER_YOUNGSTER_JOEY                   790
#define TRAINER_YOUNGSTER_JOHNSON                791
#define TRAINER_YOUNGSTER_JOSH                   792
#define TRAINER_YOUNGSTER_NASH                   793
#define TRAINER_YOUNGSTER_TIMMY                  794
#define TRAINER_YOUNGSTER_TIMMY_2                795
#define TRAINER_YOUNGSTER_TIMMY_3                796
#define TRAINER_YOUNGSTER_TIMMY_4                797
#define TRAINER_YOUNGSTER_TIMMY_5                798
#define TRAINER_YOUNGSTER_TYLER                  799
#define TRAINER_YOUNGSTER_YASU                   800
#define TRAINER_YOUNGSTER_YASU_2                 801
#define TRAINER_YOUNGSTER_YASU_3                 802
#define TRAINER_YOUNGSTER_YASU_4                 803
#define TRAINER_YOUNGSTER_YASU_5                 804
#define TRAINER_ELITE_FOUR_LORELEI               805
#define TRAINER_ELITE_FOUR_LORELEI_2             806
#define TRAINER_ELITE_FOUR_BRUNO                 807
#define TRAINER_ELITE_FOUR_BRUNO_2               808
#define TRAINER_ELITE_FOUR_AGATHA                809
#define TRAINER_ELITE_FOUR_AGATHA_2              810
#define TRAINER_ELITE_FOUR_LANCE                 811
#define TRAINER_ELITE_FOUR_LANCE_2               812
#define TRAINER_CHAMPION_FIRST_SQUIRTLE          813
#define TRAINER_CHAMPION_REMATCH_SQUIRTLE        814
#define TRAINER_CHAMPION_FIRST_BULBASAUR         815
#define TRAINER_CHAMPION_REMATCH_BULBASAUR       816
#define TRAINER_CHAMPION_FIRST_CHARMANDER        817
#define TRAINER_CHAMPION_REMATCH_CHARMANDER      818
#define TRAINER_HELENE                      819
#define TRAINER_MARLENE                     820
#define TRAINER_DEVAN                       821
#define TRAINER_JOHNSON                     822
#define TRAINER_MELINA                      823
#define TRAINER_BRANDI                      824
#define TRAINER_AISHA                       825
#define TRAINER_MAKAYLA                     826
#define TRAINER_FABIAN                      827
#define TRAINER_DAYTON                      828
#define TRAINER_RACHEL                      829
#define TRAINER_LEONEL                      830
#define TRAINER_CALLIE                      831
#define TRAINER_CALE                        832
#define TRAINER_MYLES                       833
#define TRAINER_PAT                         834
#define TRAINER_CRISTIN_1                   835
#define TRAINER_MAY_RUSTBORO_TREECKO        836
#define TRAINER_MAY_RUSTBORO_TORCHIC        837
#define TRAINER_ANGELO                      838
#define TRAINER_DARIUS                      839
#define TRAINER_STEVEN                      840
#define TRAINER_ANABEL                      841
#define TRAINER_TUCKER                      842
#define TRAINER_SPENSER                     843
#define TRAINER_GRETA                       844
#define TRAINER_NOLAND                      845
#define TRAINER_LUCY                        846
#define TRAINER_BRANDON                     847
#define TRAINER_MARIELA                     848
#define TRAINER_ALVARO                      849
#define TRAINER_EVERETT                     850
#define TRAINER_RED                         851
#define TRAINER_LEAF                        852
#define TRAINER_BRENDAN_PLACEHOLDER         853
#define TRAINER_MAY_PLACEHOLDER             854

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      855
#define MAX_TRAINERS_COUNT                  864

#endif  // GUARD_CONSTANTS_OPPONENTS_H
