#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#define TRAINER_NONE                               0
#define TRAINER_AROMA_LADY_GEORGIA                 1
#define TRAINER_AROMA_LADY_MIAH                    2
#define TRAINER_AROMA_LADY_NIKKI                   3
#define TRAINER_AROMA_LADY_ROSE                    4
#define TRAINER_AROMA_LADY_VIOLET                  5
#define TRAINER_BEAUTY_BRIDGET                     6
#define TRAINER_BEAUTY_GRACE                       7
#define TRAINER_BEAUTY_GRACE_2                     8
#define TRAINER_BEAUTY_GRACE_3                     9
#define TRAINER_BEAUTY_GRACE_4                    10
#define TRAINER_BEAUTY_GRACE_5                    11
#define TRAINER_BEAUTY_LOLA                       12
#define TRAINER_BEAUTY_LORI                       13
#define TRAINER_BEAUTY_OLIVIA                     14
#define TRAINER_BEAUTY_SHEILA                     15
#define TRAINER_BEAUTY_SHEILA_2                   16
#define TRAINER_BEAUTY_SHEILA_3                   17
#define TRAINER_BEAUTY_SHEILA_4                   18
#define TRAINER_BEAUTY_SHEILA_5                   19
#define TRAINER_BEAUTY_TAMIA                      20
#define TRAINER_BIKER_ALEX                        21
#define TRAINER_BIKER_BILLY                       22
#define TRAINER_BIKER_ERNEST                      23
#define TRAINER_BIKER_GERALD                      24
#define TRAINER_BIKER_GOON                        25
#define TRAINER_BIKER_GOON_2                      26
#define TRAINER_BIKER_GOON_3                      27
#define TRAINER_BIKER_HIDEO                       28
#define TRAINER_BIKER_ISAAC                       29
#define TRAINER_BIKER_JARED                       30
#define TRAINER_BIKER_JAREN                       31
#define TRAINER_BIKER_JAREN_2                     32
#define TRAINER_BIKER_JAREN_3                     33
#define TRAINER_BIKER_JAREN_4                     34
#define TRAINER_BIKER_JAREN_5                     35
#define TRAINER_BIKER_JAXON                       36
#define TRAINER_BIKER_JAXON_2                     37
#define TRAINER_BIKER_JAXON_3                     38
#define TRAINER_BIKER_JAXON_4                     39
#define TRAINER_BIKER_JAXON_5                     40
#define TRAINER_BIKER_LAO                         41
#define TRAINER_BIKER_LUKAS                       42
#define TRAINER_BIKER_LUKAS_2                     43
#define TRAINER_BIKER_LUKAS_3                     44
#define TRAINER_BIKER_LUKAS_4                     45
#define TRAINER_BIKER_LUKAS_5                     46
#define TRAINER_BIKER_MALIK                       47
#define TRAINER_BIKER_NIKOLAS                     48
#define TRAINER_BIKER_RICARDO                     49
#define TRAINER_BIKER_RUBEN                       50
#define TRAINER_BIKER_RUBEN_2                     51
#define TRAINER_BIKER_RUBEN_3                     52
#define TRAINER_BIKER_RUBEN_4                     53
#define TRAINER_BIKER_RUBEN_5                     54
#define TRAINER_BIKER_WILLIAM                     55
#define TRAINER_BIKER_VIRGIL                      56
#define TRAINER_BIRD_KEEPER_BECK                  57
#define TRAINER_BIRD_KEEPER_BENNY                 58
#define TRAINER_BIRD_KEEPER_BENNY_2               59
#define TRAINER_BIRD_KEEPER_BENNY_3               60
#define TRAINER_BIRD_KEEPER_BENNY_4               61
#define TRAINER_BIRD_KEEPER_BENNY_5               62
#define TRAINER_BIRD_KEEPER_CARTER                63
#define TRAINER_BIRD_KEEPER_CHAZ                  64
#define TRAINER_BIRD_KEEPER_CHAZ_2                65
#define TRAINER_BIRD_KEEPER_CHAZ_3                66
#define TRAINER_BIRD_KEEPER_CHAZ_4                67
#define TRAINER_BIRD_KEEPER_CHAZ_5                68
#define TRAINER_BIRD_KEEPER_CHESTER               69
#define TRAINER_BIRD_KEEPER_CHESTER_2             70
#define TRAINER_BIRD_KEEPER_CHESTER_3             71
#define TRAINER_BIRD_KEEPER_CHESTER_4             72
#define TRAINER_BIRD_KEEPER_CHESTER_5             73
#define TRAINER_BIRD_KEEPER_DONALD                74
#define TRAINER_BIRD_KEEPER_EDWIN                 75
#define TRAINER_BIRD_KEEPER_ELIJAH                76
#define TRAINER_BIRD_KEEPER_HAROLD                77
#define TRAINER_BIRD_KEEPER_JACOB                 78
#define TRAINER_BIRD_KEEPER_JACOB_2               79
#define TRAINER_BIRD_KEEPER_JACOB_3               80
#define TRAINER_BIRD_KEEPER_JACOB_4               81
#define TRAINER_BIRD_KEEPER_JACOB_5               82
#define TRAINER_BIRD_KEEPER_MARLON                83
#define TRAINER_BIRD_KEEPER_MARLON_2              84
#define TRAINER_BIRD_KEEPER_MARLON_3              85
#define TRAINER_BIRD_KEEPER_MARLON_4              86
#define TRAINER_BIRD_KEEPER_MARLON_5              87
#define TRAINER_BIRD_KEEPER_MILO                  88
#define TRAINER_BIRD_KEEPER_MILO_2                89
#define TRAINER_BIRD_KEEPER_MILO_3                90
#define TRAINER_BIRD_KEEPER_MILO_4                91
#define TRAINER_BIRD_KEEPER_MILO_5                92
#define TRAINER_BIRD_KEEPER_MITCH                 93
#define TRAINER_BIRD_KEEPER_PERRY                 94
#define TRAINER_BIRD_KEEPER_RAMIRO                95
#define TRAINER_BIRD_KEEPER_ROBERT                96
#define TRAINER_BIRD_KEEPER_ROBERT_2              97
#define TRAINER_BIRD_KEEPER_ROBERT_3              98
#define TRAINER_BIRD_KEEPER_ROBERT_4              99
#define TRAINER_BIRD_KEEPER_ROBERT_5             100
#define TRAINER_BIRD_KEEPER_ROGER                101
#define TRAINER_BIRD_KEEPER_SEBASTIAN            102
#define TRAINER_BIRD_KEEPER_WILTON               103
#define TRAINER_BLACK_BELT_AARON                 104
#define TRAINER_BLACK_BELT_ATSUSHI               105
#define TRAINER_BLACK_BELT_DAISUKE               106
#define TRAINER_BLACK_BELT_HIDEKI                107
#define TRAINER_BLACK_BELT_HITOSHI               108
#define TRAINER_BLACK_BELT_HUGH                  109
#define TRAINER_BLACK_BELT_HUGH_2                110
#define TRAINER_BLACK_BELT_HUGH_3                111
#define TRAINER_BLACK_BELT_HUGH_4                112
#define TRAINER_BLACK_BELT_HUGH_5                113
#define TRAINER_BLACK_BELT_KIYO                  114
#define TRAINER_BLACK_BELT_KOICHI                115
#define TRAINER_BLACK_BELT_MIKE                  116
#define TRAINER_BLACK_BELT_SHEA                  117
#define TRAINER_BLACK_BELT_SHEA_2                118
#define TRAINER_BLACK_BELT_SHEA_3                119
#define TRAINER_BLACK_BELT_SHEA_4                120
#define TRAINER_BLACK_BELT_SHEA_5                121
#define TRAINER_BLACK_BELT_TAKASHI               122
#define TRAINER_BLACK_BELT_YUJI                  123
#define TRAINER_BUG_CATCHER_ANTHONY              124
#define TRAINER_BUG_CATCHER_BRENT                125
#define TRAINER_BUG_CATCHER_CALE                 126
#define TRAINER_BUG_CATCHER_CHARLIE              127
#define TRAINER_BUG_CATCHER_COLTON               128
#define TRAINER_BUG_CATCHER_COLTON_2             129
#define TRAINER_BUG_CATCHER_COLTON_3             130
#define TRAINER_BUG_CATCHER_COLTON_4             131
#define TRAINER_BUG_CATCHER_COLTON_5             132
#define TRAINER_BUG_CATCHER_CONNER               133
#define TRAINER_BUG_CATCHER_DOUG                 134
#define TRAINER_BUG_CATCHER_ELIJAH               135
#define TRAINER_BUG_CATCHER_GARRET               136
#define TRAINER_BUG_CATCHER_GREG                 137
#define TRAINER_BUG_CATCHER_JAMES                138
#define TRAINER_BUG_CATCHER_JONAH                139
#define TRAINER_BUG_CATCHER_KENT                 140
#define TRAINER_BUG_CATCHER_KEIGO                141
#define TRAINER_BUG_CATCHER_RICK                 142
#define TRAINER_BUG_CATCHER_ROBBY                143
#define TRAINER_BUG_CATCHER_SAMMY                144
#define TRAINER_BUG_CATCHER_VANCE                145
#define TRAINER_BURGLAR_ARNIE                    146
#define TRAINER_BURGLAR_DUSTY                    147
#define TRAINER_BURGLAR_LEWIS                    148
#define TRAINER_BURGLAR_QUINN                    149
#define TRAINER_BURGLAR_RAMON                    150
#define TRAINER_BURGLAR_SIMON                    151
#define TRAINER_CAMPER_BRYCE                     152
#define TRAINER_CAMPER_CHRIS                     153
#define TRAINER_CAMPER_CHRIS_2                   154
#define TRAINER_CAMPER_CHRIS_3                   155
#define TRAINER_CAMPER_CHRIS_4                   156
#define TRAINER_CAMPER_CHRIS_5                   157
#define TRAINER_CAMPER_DREW                      158
#define TRAINER_CAMPER_ETHAN                     159
#define TRAINER_CAMPER_FLINT                     160
#define TRAINER_CAMPER_JEFF                      161
#define TRAINER_CAMPER_JEFF_2                    162
#define TRAINER_CAMPER_JEFF_3                    163
#define TRAINER_CAMPER_JEFF_4                    164
#define TRAINER_CAMPER_JEFF_5                    165
#define TRAINER_CAMPER_JUSTIN                    166
#define TRAINER_CAMPER_LARRY                     167
#define TRAINER_CAMPER_LIAM                      168
#define TRAINER_CAMPER_RICKY                     169
#define TRAINER_CAMPER_RICKY_2                   170
#define TRAINER_CAMPER_RICKY_3                   171
#define TRAINER_CAMPER_RICKY_4                   172
#define TRAINER_CAMPER_RICKY_5                   173
#define TRAINER_CAMPER_RILEY                     174
#define TRAINER_CAMPER_SHANE                     175
#define TRAINER_CHANNELER_AMANDA                 176
#define TRAINER_CHANNELER_ANGELICA               177
#define TRAINER_CHANNELER_CARLY                  178
#define TRAINER_CHANNELER_EMILIA                 179
#define TRAINER_CHANNELER_HOPE                   180
#define TRAINER_CHANNELER_JANAE                  181
#define TRAINER_CHANNELER_JENNIFER               182
#define TRAINER_CHANNELER_JODY                   183
#define TRAINER_CHANNELER_KARINA                 184
#define TRAINER_CHANNELER_LAUREL                 185
#define TRAINER_CHANNELER_PATRICIA               186
#define TRAINER_CHANNELER_PAULA                  187
#define TRAINER_CHANNELER_RUTH                   188
#define TRAINER_CHANNELER_STACY                  189
#define TRAINER_CHANNELER_TAMMY                  190
#define TRAINER_CHANNELER_TASHA                  191
#define TRAINER_CHANNELER_VALERIE                192
#define TRAINER_COOLTRAINER_ALEXA                193
#define TRAINER_COOLTRAINER_BRAXTON              194
#define TRAINER_COOLTRAINER_CAROLINE             195
#define TRAINER_COOLTRAINER_COLBY                196
#define TRAINER_COOLTRAINER_GEORGE               197
#define TRAINER_COOLTRAINER_KEIRA                198
#define TRAINER_COOLTRAINER_LEROY                199
#define TRAINER_COOLTRAINER_LEROY_2              200
#define TRAINER_COOLTRAINER_LEROY_3              201
#define TRAINER_COOLTRAINER_LEROY_4              202
#define TRAINER_COOLTRAINER_LEROY_5              203
#define TRAINER_COOLTRAINER_MARY                 204
#define TRAINER_COOLTRAINER_MICHELLE             205
#define TRAINER_COOLTRAINER_MICHELLE_2           206
#define TRAINER_COOLTRAINER_MICHELLE_3           207
#define TRAINER_COOLTRAINER_MICHELLE_4           208
#define TRAINER_COOLTRAINER_MICHELLE_5           209
#define TRAINER_COOLTRAINER_NAOMI                210
#define TRAINER_COOLTRAINER_ROLANDO              211
#define TRAINER_COOLTRAINER_SAMUEL               212
#define TRAINER_COOLTRAINER_VINCENT              213
#define TRAINER_COOLTRAINER_WARREN               214
#define TRAINER_COOLTRAINER_YUJI                 215
#define TRAINER_COOL_COUPLE_LEX_NYA              216
#define TRAINER_COOL_COUPLE_RAY_TYRA             217
#define TRAINER_CRUSH_GIRL_CORA                  218
#define TRAINER_CRUSH_GIRL_CYNDY                 219
#define TRAINER_CRUSH_GIRL_JOCELYN               220
#define TRAINER_CRUSH_GIRL_PAULA                 221
#define TRAINER_CRUSH_GIRL_SHARON                222
#define TRAINER_CRUSH_GIRL_SHARON_2              223
#define TRAINER_CRUSH_GIRL_SHARON_3              224
#define TRAINER_CRUSH_GIRL_SHARON_4              225
#define TRAINER_CRUSH_GIRL_SHARON_5              226
#define TRAINER_CRUSH_GIRL_TANYA                 227
#define TRAINER_CRUSH_GIRL_TANYA_2               228
#define TRAINER_CRUSH_GIRL_TANYA_3               229
#define TRAINER_CRUSH_GIRL_TANYA_4               230
#define TRAINER_CRUSH_GIRL_TANYA_5               231
#define TRAINER_CRUSH_KIN_MIK_KIA                232
#define TRAINER_CRUSH_KIN_MIK_KIA_2              233
#define TRAINER_CRUSH_KIN_MIK_KIA_3              234
#define TRAINER_CRUSH_KIN_MIK_KIA_4              235
#define TRAINER_CRUSH_KIN_MIK_KIA_5              236
#define TRAINER_CRUSH_KIN_RON_MYA                237
#define TRAINER_CRUSH_KIN_RON_MYA_2              238
#define TRAINER_CRUSH_KIN_RON_MYA_3              239
#define TRAINER_CRUSH_KIN_RON_MYA_4              240
#define TRAINER_CRUSH_KIN_RON_MYA_5              241
#define TRAINER_CUE_BALL_CAMRON                  242
#define TRAINER_CUE_BALL_CAMRON_2                243
#define TRAINER_CUE_BALL_CAMRON_3                244
#define TRAINER_CUE_BALL_CAMRON_4                245
#define TRAINER_CUE_BALL_CAMRON_5                246
#define TRAINER_CUE_BALL_COREY                   247
#define TRAINER_CUE_BALL_COREY_2                 248
#define TRAINER_CUE_BALL_COREY_3                 249
#define TRAINER_CUE_BALL_COREY_4                 250
#define TRAINER_CUE_BALL_COREY_5                 251
#define TRAINER_CUE_BALL_ISAIAH                  252
#define TRAINER_CUE_BALL_ISAIAH_2                253
#define TRAINER_CUE_BALL_ISAIAH_3                254
#define TRAINER_CUE_BALL_ISAIAH_4                255
#define TRAINER_CUE_BALL_ISAIAH_5                256
#define TRAINER_CUE_BALL_JAMAL                   257
#define TRAINER_CUE_BALL_KOJI                    258
#define TRAINER_CUE_BALL_LUKE                    259
#define TRAINER_CUE_BALL_PAXTON                  260
#define TRAINER_CUE_BALL_RAUL                    261
#define TRAINER_CUE_BALL_ZEEK                    262
#define TRAINER_ENGINEER_BAILY                   263
#define TRAINER_ENGINEER_BERNIE                  264
#define TRAINER_ENGINEER_BERNIE_2                265
#define TRAINER_ENGINEER_BERNIE_3                266
#define TRAINER_ENGINEER_BERNIE_4                267
#define TRAINER_ENGINEER_BERNIE_5                268
#define TRAINER_ENGINEER_BRAXTON                 269
#define TRAINER_FISHERMAN_ANDREW                 270
#define TRAINER_FISHERMAN_BARNY                  271
#define TRAINER_FISHERMAN_CHIP                   272
#define TRAINER_FISHERMAN_CLAUDE                 273
#define TRAINER_FISHERMAN_DALE                   274
#define TRAINER_FISHERMAN_ELLIOT                 275
#define TRAINER_FISHERMAN_ELLIOT_2               276
#define TRAINER_FISHERMAN_ELLIOT_3               277
#define TRAINER_FISHERMAN_ELLIOT_4               278
#define TRAINER_FISHERMAN_ELLIOT_5               279
#define TRAINER_FISHERMAN_HANK                   280
#define TRAINER_FISHERMAN_NED                    281
#define TRAINER_FISHERMAN_NOLAN                  282
#define TRAINER_FISHERMAN_RONALD                 283
#define TRAINER_FISHERMAN_TOMMY                  284
#define TRAINER_FISHERMAN_TYLOR                  285
#define TRAINER_FISHERMAN_WADE                   286
#define TRAINER_FISHERMAN_WADE_2                 287
#define TRAINER_FISHERMAN_WADE_3                 288
#define TRAINER_FISHERMAN_WADE_4                 289
#define TRAINER_FISHERMAN_WADE_5                 290
#define TRAINER_GAMBLER_DARIAN                   291
#define TRAINER_GAMBLER_DARIAN_2                 292
#define TRAINER_GAMBLER_DARIAN_3                 293
#define TRAINER_GAMBLER_DARIAN_4                 294
#define TRAINER_GAMBLER_DARIAN_5                 295
#define TRAINER_GAMBLER_DIRK                     296
#define TRAINER_GAMBLER_HUGO                     297
#define TRAINER_GAMBLER_JASPER                   298
#define TRAINER_GAMBLER_RICH                     299
#define TRAINER_GAMBLER_RICH_2                   300
#define TRAINER_GAMBLER_RICH_3                   301
#define TRAINER_GAMBLER_RICH_4                   302
#define TRAINER_GAMBLER_RICH_5                   303
#define TRAINER_GAMBLER_STAN                     304
#define TRAINER_GENTLEMAN_ARTHUR                 305
#define TRAINER_GENTLEMAN_BROOKS                 306
#define TRAINER_GENTLEMAN_CLIFFORD               307
#define TRAINER_GENTLEMEN_EVERETT                308
#define TRAINER_GENTLEMAN_LAMAR                  309
#define TRAINER_GENTLEMAN_THOMAS                 310
#define TRAINER_GENTLEMAN_TUCKER                 311
#define TRAINER_HIKER_ALAN                       312
#define TRAINER_HIKER_ALLEN                      313
#define TRAINER_HIKER_BRICE                      314
#define TRAINER_HIKER_CLARK                      315
#define TRAINER_HIKER_DARYL                      316
#define TRAINER_HIKER_DUDLEY                     317
#define TRAINER_HIKER_EARL                       318
#define TRAINER_HIKER_EARL_2                     319
#define TRAINER_HIKER_EARL_3                     320
#define TRAINER_HIKER_EARL_4                     321
#define TRAINER_HIKER_EARL_5                     322
#define TRAINER_HIKER_ERIC                       323
#define TRAINER_HIKER_FRANKLIN                   324
#define TRAINER_HIKER_FRANKLIN_2                 325
#define TRAINER_HIKER_FRANKLIN_3                 326
#define TRAINER_HIKER_FRANKLIN_4                 327
#define TRAINER_HIKER_FRANKLIN_5                 328
#define TRAINER_HIKER_JEREMY                     329
#define TRAINER_HIKER_JEREMY_2                   330
#define TRAINER_HIKER_JEREMY_3                   331
#define TRAINER_HIKER_JEREMY_4                   332
#define TRAINER_HIKER_JEREMY_5                   333
#define TRAINER_HIKER_LENNY                      334
#define TRAINER_HIKER_LUCAS                      335
#define TRAINER_HIKER_MARCOS                     336
#define TRAINER_HIKER_NOB                        337
#define TRAINER_HIKER_OLIVER                     338
#define TRAINER_HIKER_SAWYER                     339
#define TRAINER_HIKER_TRENT                      340
#define TRAINER_HIKER_TRENT_2                    341
#define TRAINER_HIKER_TRENT_3                    342
#define TRAINER_HIKER_TRENT_4                    343
#define TRAINER_HIKER_TRENT_5                    344
#define TRAINER_HIKER_WAYNE                      345
#define TRAINER_JUGGLER_DALTON                   346
#define TRAINER_JUGGLER_EDWARD                   347
#define TRAINER_JUGGLER_GREGORY                  348
#define TRAINER_JUGGLER_KAYDEN                   349
#define TRAINER_JUGGLER_KIRK                     350
#define TRAINER_JUGGLER_MASON                    351
#define TRAINER_JUGGLER_MASON_2                  352
#define TRAINER_JUGGLER_MASON_3                  353
#define TRAINER_JUGGLER_MASON_4                  354
#define TRAINER_JUGGLER_MASON_5                  355
#define TRAINER_JUGGLER_NATE                     356
#define TRAINER_JUGGLER_NELSON                   357
#define TRAINER_JUGGLER_SHAWN                    358
#define TRAINER_LADY_GILLIAN                     359
#define TRAINER_LADY_JACKI                       360
#define TRAINER_LADY_SELPHY                      361
#define TRAINER_LASS_ALI                         362
#define TRAINER_LASS_ANDREA                      363
#define TRAINER_LASS_ANN                         364
#define TRAINER_LASS_CRISSY                      365
#define TRAINER_LASS_DALIA                       366
#define TRAINER_LASS_DAWN                        367
#define TRAINER_LASS_HALEY                       368
#define TRAINER_LASS_IRIS                        369
#define TRAINER_LASS_JANICE                      370
#define TRAINER_LASS_JANICE_2                    371
#define TRAINER_LASS_JANICE_3                    372
#define TRAINER_LASS_JANICE_4                    373
#define TRAINER_LASS_JANICE_5                    374
#define TRAINER_LASS_JOANA                       375
#define TRAINER_LASS_JULIA                       376
#define TRAINER_LASS_KAY                         377
#define TRAINER_LASS_KRISE                       378
#define TRAINER_LASS_LISA                        379
#define TRAINER_LASS_MEGAN                       380
#define TRAINER_LASS_MEGAN_2                     381
#define TRAINER_LASS_MEGAN_3                     382
#define TRAINER_LASS_MEGAN_4                     383
#define TRAINER_LASS_MEGAN_5                     384
#define TRAINER_LASS_MIRIAM                      385
#define TRAINER_LASS_PAIGE                       386
#define TRAINER_LASS_RELI                        387
#define TRAINER_LASS_RELI_2                      388
#define TRAINER_LASS_RELI_3                      389
#define TRAINER_LASS_RELI_4                      390
#define TRAINER_LASS_RELI_5                      391
#define TRAINER_LASS_ROBIN                       392
#define TRAINER_LASS_SALLY                       393
#define TRAINER_LASS_TIANA                       394
#define TRAINER_LEADER_BROCK                     395
#define TRAINER_LEADER_BROCK_2                   396
#define TRAINER_LEADER_BROCK_3                   397
#define TRAINER_LEADER_BROCK_4                   398
#define TRAINER_LEADER_BROCK_5                   399
#define TRAINER_LEADER_MISTY                     400
#define TRAINER_LEADER_MISTY_2                   401
#define TRAINER_LEADER_MISTY_3                   402
#define TRAINER_LEADER_MISTY_4                   403
#define TRAINER_LEADER_MISTY_5                   404
#define TRAINER_LEADER_LT_SURGE                  405
#define TRAINER_LEADER_LT_SURGE_2                406
#define TRAINER_LEADER_LT_SURGE_3                407
#define TRAINER_LEADER_LT_SURGE_4                408
#define TRAINER_LEADER_LT_SURGE_5                409
#define TRAINER_LEADER_ERIKA                     410
#define TRAINER_LEADER_ERIKA_2                   411
#define TRAINER_LEADER_ERIKA_3                   412
#define TRAINER_LEADER_ERIKA_4                   413
#define TRAINER_LEADER_ERIKA_5                   414
#define TRAINER_LEADER_KOGA                      415
#define TRAINER_LEADER_KOGA_2                    416
#define TRAINER_LEADER_KOGA_3                    417
#define TRAINER_LEADER_KOGA_4                    418
#define TRAINER_LEADER_KOGA_5                    419
#define TRAINER_LEADER_SABRINA                   420
#define TRAINER_LEADER_SABRINA_2                 421
#define TRAINER_LEADER_SABRINA_3                 422
#define TRAINER_LEADER_SABRINA_4                 423
#define TRAINER_LEADER_SABRINA_5                 424
#define TRAINER_LEADER_BLAINE                    425
#define TRAINER_LEADER_BLAINE_2                  426
#define TRAINER_LEADER_BLAINE_3                  427
#define TRAINER_LEADER_BLAINE_4                  428
#define TRAINER_LEADER_BLAINE_5                  429
#define TRAINER_BOSS_GIOVANNI                    430
#define TRAINER_BOSS_GIOVANNI_2                  431
#define TRAINER_LEADER_GIOVANNI                  432
#define TRAINER_PAINTER_CELINA                   433
#define TRAINER_PAINTER_DAISY                    434
#define TRAINER_PAINTER_EDNA                     435
#define TRAINER_PAINTER_RAYNA                    436
#define TRAINER_PAINTER_RAYNA_2                  437
#define TRAINER_PAINTER_RAYNA_3                  438
#define TRAINER_PAINTER_RAYNA_4                  439
#define TRAINER_PAINTER_RAYNA_5                  440
#define TRAINER_PICNICKER_ALICIA                 441
#define TRAINER_PICNICKER_ALMA                   442
#define TRAINER_PICNICKER_ARIANA                 443
#define TRAINER_PICNICKER_BECKY                  444
#define TRAINER_PICNICKER_BECKY_2                445
#define TRAINER_PICNICKER_BECKY_3                446
#define TRAINER_PICNICKER_BECKY_4                447
#define TRAINER_PICNICKER_BECKY_5                448
#define TRAINER_PICNICKER_CAITLIN                449
#define TRAINER_PICNICKER_CAITLIN_2              450
#define TRAINER_PICNICKER_CAITLIN_3              451
#define TRAINER_PICNICKER_CAITLIN_4              452
#define TRAINER_PICNICKER_CAITLIN_5              453
#define TRAINER_PICNICKER_CAROL                  454
#define TRAINER_PICNICKER_CELIA                  455
#define TRAINER_PICNICKER_CHARLOTTE              456
#define TRAINER_PICNICKER_CLAIRE                 457
#define TRAINER_PICNICKER_DANA                   458
#define TRAINER_PICNICKER_DIANA                  459
#define TRAINER_PICNICKER_GWEN                   460
#define TRAINER_PICNICKER_HEIDI                  461
#define TRAINER_PICNICKER_IRENE                  462
#define TRAINER_PICNICKER_ISABELLE               463
#define TRAINER_PICNICKER_ISABELLE_2             464
#define TRAINER_PICNICKER_ISABELLE_3             465
#define TRAINER_PICNICKER_ISABELLE_4             466
#define TRAINER_PICNICKER_ISABELLE_5             467
#define TRAINER_PICNICKER_KELSEY                 468
#define TRAINER_PICNICKER_KELSEY_2               469
#define TRAINER_PICNICKER_KELSEY_3               470
#define TRAINER_PICNICKER_KELSEY_4               471
#define TRAINER_PICNICKER_KELSEY_5               472
#define TRAINER_PICNICKER_KINDRA                 473
#define TRAINER_PICNICKER_LEAH                   474
#define TRAINER_PICNICKER_MARCY                  475
#define TRAINER_PICNICKER_MARTHA                 476
#define TRAINER_PICNICKER_MISSY                  477
#define TRAINER_PICNICKER_MISSY_2                478
#define TRAINER_PICNICKER_MISSY_3                479
#define TRAINER_PICNICKER_MISSY_4                480
#define TRAINER_PICNICKER_MISSY_5                481
#define TRAINER_PICNICKER_NANCY                  482
#define TRAINER_PICNICKER_SOFIA                  483
#define TRAINER_PICNICKER_SUSIE                  484
#define TRAINER_PICNICKER_SUSIE_2                485
#define TRAINER_PICNICKER_SUSIE_3                486
#define TRAINER_PICNICKER_SUSIE_4                487
#define TRAINER_PICNICKER_SUSIE_5                488
#define TRAINER_PICNICKER_TINA                   489
#define TRAINER_PICNICKER_VALERIE                490
#define TRAINER_PICNICKER_YAZMIN                 491
#define TRAINER_PKMN_BREEDER_ALIZE               492
#define TRAINER_PKMN_BREEDER_ALIZE_2             493
#define TRAINER_PKMN_BREEDER_ALIZE_3             494
#define TRAINER_PKMN_BREEDER_ALIZE_4             495
#define TRAINER_PKMN_BREEDER_ALIZE_5             496
#define TRAINER_PKMN_BREEDER_ALLISON             497
#define TRAINER_PKMN_BREEDER_BETHANY             498
#define TRAINER_PKMN_RANGER_BETH                 499
#define TRAINER_PKMN_RANGER_JACKSON              500
#define TRAINER_PKMN_RANGER_KATELYN              501
#define TRAINER_PKMN_RANGER_KATELYN_2            502
#define TRAINER_PKMN_RANGER_KATELYN_3            503
#define TRAINER_PKMN_RANGER_KATELYN_4            504
#define TRAINER_PKMN_RANGER_KATELYN_5            505
#define TRAINER_PKMN_RANGER_LOGAN                506
#define TRAINER_PKMN_RANGER_MADELINE             507
#define TRAINER_PKMN_RANGER_MADELINE_2           508
#define TRAINER_PKMN_RANGER_MADELINE_3           509
#define TRAINER_PKMN_RANGER_MADELINE_4           510
#define TRAINER_PKMN_RANGER_MADELINE_5           511
#define TRAINER_PKMN_RANGER_NICOLAS              512
#define TRAINER_PKMN_RANGER_NICOLAS_2            513
#define TRAINER_PKMN_RANGER_NICOLAS_3            514
#define TRAINER_PKMN_RANGER_NICOLAS_4            515
#define TRAINER_PKMN_RANGER_NICOLAS_5            516
#define TRAINER_PKMN_RANGER_SEBASTIAN            517
#define TRAINER_PKMN_RANGER_SOPHIA               518
#define TRAINER_POKEMANIAC_ASHTON                519
#define TRAINER_POKEMANIAC_COOPER                520
#define TRAINER_POKEMANIAC_DAWSON                521
#define TRAINER_POKEMANIAC_HECTOR                522
#define TRAINER_POKEMANIAC_HECTOR_2              523
#define TRAINER_POKEMANIAC_HECTOR_3              524
#define TRAINER_POKEMANIAC_HECTOR_4              525
#define TRAINER_POKEMANIAC_HECTOR_5              526
#define TRAINER_POKEMANIAC_HERMAN                527
#define TRAINER_POKEMANIAC_HERMAN_2              528
#define TRAINER_POKEMANIAC_HERMAN_3              529
#define TRAINER_POKEMANIAC_HERMAN_4              530
#define TRAINER_POKEMANIAC_HERMAN_5              531
#define TRAINER_POKEMANIAC_MARK                  532
#define TRAINER_POKEMANIAC_MARK_2                533
#define TRAINER_POKEMANIAC_MARK_3                534
#define TRAINER_POKEMANIAC_MARK_4                535
#define TRAINER_POKEMANIAC_MARK_5                536
#define TRAINER_POKEMANIAC_STEVE                 537
#define TRAINER_POKEMANIAC_WINSTON               538
#define TRAINER_PSYCHIC_ALEXIS                   539
#define TRAINER_PSYCHIC_ALVARO                   540
#define TRAINER_PSYCHIC_CAMERON                  541
#define TRAINER_PSYCHIC_DARIO                    542
#define TRAINER_PSYCHIC_DARIO_2                  543
#define TRAINER_PSYCHIC_DARIO_3                  544
#define TRAINER_PSYCHIC_DARIO_4                  545
#define TRAINER_PSYCHIC_DARIO_5                  546
#define TRAINER_PSYCHIC_JACLYN                   547
#define TRAINER_PSYCHIC_JACLYN_2                 548
#define TRAINER_PSYCHIC_JACLYN_3                 549
#define TRAINER_PSYCHIC_JACLYN_4                 550
#define TRAINER_PSYCHIC_JACLYN_5                 551
#define TRAINER_PSYCHIC_JOHAN                    552
#define TRAINER_PSYCHIC_JOSHUA                   553
#define TRAINER_PSYCHIC_LAURA                    554
#define TRAINER_PSYCHIC_MARIELA                  555
#define TRAINER_PSYCHIC_PRESTON                  556
#define TRAINER_PSYCHIC_RODETTE                  557
#define TRAINER_PSYCHIC_RODETTE_2                558
#define TRAINER_PSYCHIC_RODETTE_3                559
#define TRAINER_PSYCHIC_RODETTE_4                560
#define TRAINER_PSYCHIC_RODETTE_5                561
#define TRAINER_PSYCHIC_TYRON                    562
#define TRAINER_RIVAL_OAKS_LAB_SQUIRTLE          563
#define TRAINER_RIVAL_OAKS_LAB_BULBASAUR         564
#define TRAINER_RIVAL_OAKS_LAB_CHARMANDER        565
#define TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE     566
#define TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR    567
#define TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER   568
#define TRAINER_RIVAL_CERULEAN_SQUIRTLE          569
#define TRAINER_RIVAL_CERULEAN_BULBASAUR         570
#define TRAINER_RIVAL_CERULEAN_CHARMANDER        571
#define TRAINER_RIVAL_SS_ANNE_SQUIRTLE           572
#define TRAINER_RIVAL_SS_ANNE_BULBASAUR          573
#define TRAINER_RIVAL_SS_ANNE_CHARMANDER         574
#define TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE     575
#define TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR    576
#define TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER   577
#define TRAINER_RIVAL_SILPH_SQUIRTLE             578
#define TRAINER_RIVAL_SILPH_BULBASAUR            579
#define TRAINER_RIVAL_SILPH_CHARMANDER           580
#define TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE      581
#define TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR     582
#define TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER    583
#define TRAINER_ROCKER_LUCA                      584
#define TRAINER_ROCKER_LUCA_2                    585
#define TRAINER_ROCKER_LUCA_3                    586
#define TRAINER_ROCKER_LUCA_4                    587
#define TRAINER_ROCKER_LUCA_5                    588
#define TRAINER_RUIN_MANIAC_BENJAMIN             589
#define TRAINER_RUIN_MANIAC_BRANDON              590
#define TRAINER_RUIN_MANIAC_FOSTER               591
#define TRAINER_RUIN_MANIAC_LARRY                592
#define TRAINER_RUIN_MANIAC_LARRY_2              593
#define TRAINER_RUIN_MANIAC_LARRY_3              594
#define TRAINER_RUIN_MANIAC_LARRY_4              595
#define TRAINER_RUIN_MANIAC_LARRY_5              596
#define TRAINER_RUIN_MANIAC_LAWSON               597
#define TRAINER_RUIN_MANIAC_LAYTON               598
#define TRAINER_RUIN_MANIAC_STANLY               599
#define TRAINER_SAILOR_DUNCAN                    600
#define TRAINER_SAILOR_DWAYNE                    601
#define TRAINER_SAILOR_DYLAN                     602
#define TRAINER_SAILOR_EDMOND                    603
#define TRAINER_SAILOR_HUEY                      604
#define TRAINER_SAILOR_LEONARD                   605
#define TRAINER_SAILOR_PHILLIP                   606
#define TRAINER_SAILOR_TREVOR                    607
#define TRAINER_SCIENTIST_BEAU                   608
#define TRAINER_SCIENTIST_BRAYDON                609
#define TRAINER_SCIENTIST_CONNOR                 610
#define TRAINER_SCIENTIST_ED                     611
#define TRAINER_SCIENTIST_GIDEON                 612
#define TRAINER_SCIENTIST_IVAN                   613
#define TRAINER_SCIENTIST_JERRY                  614
#define TRAINER_SCIENTIST_JOSE                   615
#define TRAINER_SCIENTIST_JOSHUA                 616
#define TRAINER_SCIENTIST_PARKER                 617
#define TRAINER_SCIENTIST_RODNEY                 618
#define TRAINER_SCIENTIST_TAYLOR                 619
#define TRAINER_SCIENTIST_TED                    620
#define TRAINER_SCIENTIST_TRAVIS                 621
#define TRAINER_SIS_AND_BRO_AVA_GEB              622
#define TRAINER_SIS_AND_BRO_LIA_LUC              623
#define TRAINER_SIS_AND_BRO_LIL_IAN              624
#define TRAINER_SIS_AND_BRO_LIL_IAN_2            625
#define TRAINER_SIS_AND_BRO_LIL_IAN_3            626
#define TRAINER_SIS_AND_BRO_LIL_IAN_4            627
#define TRAINER_SIS_AND_BRO_LIL_IAN_5            628
#define TRAINER_SUPER_NERD_AIDAN                 629
#define TRAINER_SUPER_NERD_AVERY                 630
#define TRAINER_SUPER_NERD_DEREK                 631
#define TRAINER_SUPER_NERD_ERIK                  632
#define TRAINER_SUPER_NERD_GLENN                 633
#define TRAINER_SUPER_NERD_JOVAN                 634
#define TRAINER_SUPER_NERD_LESLIE                635
#define TRAINER_SUPER_NERD_MIGUEL                636
#define TRAINER_SUPER_NERD_PAUL                  637
#define TRAINER_SUPER_NERD_TED                   638
#define TRAINER_SUPER_NERD_ZAC                   639
#define TRAINER_SWIMMER_FEMALE_ABIGAIL           640
#define TRAINER_SWIMMER_FEMALE_ALICE             641
#define TRAINER_SWIMMER_FEMALE_ALICE_2           642
#define TRAINER_SWIMMER_FEMALE_ALICE_3           643
#define TRAINER_SWIMMER_FEMALE_ALICE_4           644
#define TRAINER_SWIMMER_FEMALE_ALICE_5           645
#define TRAINER_SWIMMER_FEMALE_AMARA             646
#define TRAINER_SWIMMER_FEMALE_ANYA              647
#define TRAINER_SWIMMER_FEMALE_CONNIE            648
#define TRAINER_SWIMMER_FEMALE_DENISE            649
#define TRAINER_SWIMMER_FEMALE_MARIA             650
#define TRAINER_SWIMMER_FEMALE_MELISSA           651
#define TRAINER_SWIMMER_FEMALE_MELISSA_2         652
#define TRAINER_SWIMMER_FEMALE_MELISSA_3         653
#define TRAINER_SWIMMER_FEMALE_MELISSA_4         654
#define TRAINER_SWIMMER_FEMALE_MELISSA_5         655
#define TRAINER_SWIMMER_FEMALE_NICOLE            656
#define TRAINER_SWIMMER_FEMALE_NICOLE_2          657
#define TRAINER_SWIMMER_FEMALE_NICOLE_3          658
#define TRAINER_SWIMMER_FEMALE_NICOLE_4          659
#define TRAINER_SWIMMER_FEMALE_NICOLE_5          660
#define TRAINER_SWIMMER_FEMALE_NORA              661
#define TRAINER_SWIMMER_FEMALE_SHIRLEY           662
#define TRAINER_SWIMMER_FEMALE_TIFFANY           663
#define TRAINER_SWIMMER_FEMALE_TISHA             664
#define TRAINER_SWIMMER_MALE_AXLE                665
#define TRAINER_SWIMMER_MALE_BARRY               666
#define TRAINER_SWIMMER_MALE_DARRIN              667
#define TRAINER_SWIMMER_MALE_DARRIN_2            668
#define TRAINER_SWIMMER_MALE_DARRIN_3            669
#define TRAINER_SWIMMER_MALE_DARRIN_4            670
#define TRAINER_SWIMMER_MALE_DARRIN_5            671
#define TRAINER_SWIMMER_MALE_DAVID               672
#define TRAINER_SWIMMER_MALE_DEAN                673
#define TRAINER_SWIMMER_MALE_DOUGLAS             674
#define TRAINER_SWIMMER_MALE_FINN                675
#define TRAINER_SWIMMER_MALE_FINN_2              676
#define TRAINER_SWIMMER_MALE_FINN_3              677
#define TRAINER_SWIMMER_MALE_FINN_4              678
#define TRAINER_SWIMMER_MALE_FINN_5              679
#define TRAINER_SWIMMER_MALE_GARRETT             680
#define TRAINER_SWIMMER_MALE_JACK                681
#define TRAINER_SWIMMER_MALE_JACK_2              682
#define TRAINER_SWIMMER_MALE_JACK_3              683
#define TRAINER_SWIMMER_MALE_JACK_4              684
#define TRAINER_SWIMMER_MALE_JACK_5              685
#define TRAINER_SWIMMER_MALE_JEROME              686
#define TRAINER_SWIMMER_MALE_LUIS                687
#define TRAINER_SWIMMER_MALE_MATTHEW             688
#define TRAINER_SWIMMER_MALE_MATTHEW_2           689
#define TRAINER_SWIMMER_MALE_MATTHEW_3           690
#define TRAINER_SWIMMER_MALE_MATTHEW_4           691
#define TRAINER_SWIMMER_MALE_MATTHEW_5           692
#define TRAINER_SWIMMER_MALE_MYMO                693
#define TRAINER_SWIMMER_MALE_REECE               694
#define TRAINER_SWIMMER_MALE_RICHARD             695
#define TRAINER_SWIMMER_MALE_ROLAND              696
#define TRAINER_SWIMMER_MALE_SAMIR               697
#define TRAINER_SWIMMER_MALE_SAMIR_2             698
#define TRAINER_SWIMMER_MALE_SAMIR_3             699
#define TRAINER_SWIMMER_MALE_SAMIR_4             700
#define TRAINER_SWIMMER_MALE_SAMIR_5             701
#define TRAINER_SWIMMER_MALE_SPENCER             702
#define TRAINER_SWIMMER_MALE_TOBY                703
#define TRAINER_SWIMMER_MALE_TONY                704
#define TRAINER_SWIMMER_MALE_TONY_2              705
#define TRAINER_SWIMMER_MALE_TONY_3              706
#define TRAINER_SWIMMER_MALE_TONY_4              707
#define TRAINER_SWIMMER_MALE_TONY_5              708
#define TRAINER_TAMER_COLE                       709
#define TRAINER_TAMER_EDGAR                      710
#define TRAINER_TAMER_EVAN                       711
#define TRAINER_TAMER_JASON                      712
#define TRAINER_TAMER_PHIL                       713
#define TRAINER_TAMER_VINCENT                    714
#define TRAINER_TEAM_ROCKET_ADMIN                715
#define TRAINER_TEAM_ROCKET_ADMIN_2              716
#define TRAINER_TEAM_ROCKET_GRUNT                717
#define TRAINER_TEAM_ROCKET_GRUNT_2              718
#define TRAINER_TEAM_ROCKET_GRUNT_3              719
#define TRAINER_TEAM_ROCKET_GRUNT_4              720
#define TRAINER_TEAM_ROCKET_GRUNT_5              721
#define TRAINER_TEAM_ROCKET_GRUNT_6              722
#define TRAINER_TEAM_ROCKET_GRUNT_7              723
#define TRAINER_TEAM_ROCKET_GRUNT_8              724
#define TRAINER_TEAM_ROCKET_GRUNT_9              725
#define TRAINER_TEAM_ROCKET_GRUNT_10             726
#define TRAINER_TEAM_ROCKET_GRUNT_11             727
#define TRAINER_TEAM_ROCKET_GRUNT_12             728
#define TRAINER_TEAM_ROCKET_GRUNT_13             729
#define TRAINER_TEAM_ROCKET_GRUNT_14             730
#define TRAINER_TEAM_ROCKET_GRUNT_15             731
#define TRAINER_TEAM_ROCKET_GRUNT_16             732
#define TRAINER_TEAM_ROCKET_GRUNT_17             733
#define TRAINER_TEAM_ROCKET_GRUNT_18             734
#define TRAINER_TEAM_ROCKET_GRUNT_19             735
#define TRAINER_TEAM_ROCKET_GRUNT_20             736
#define TRAINER_TEAM_ROCKET_GRUNT_21             737
#define TRAINER_TEAM_ROCKET_GRUNT_23             738
#define TRAINER_TEAM_ROCKET_GRUNT_24             739
#define TRAINER_TEAM_ROCKET_GRUNT_25             740
#define TRAINER_TEAM_ROCKET_GRUNT_26             741
#define TRAINER_TEAM_ROCKET_GRUNT_27             742
#define TRAINER_TEAM_ROCKET_GRUNT_28             743
#define TRAINER_TEAM_ROCKET_GRUNT_29             744
#define TRAINER_TEAM_ROCKET_GRUNT_30             745
#define TRAINER_TEAM_ROCKET_GRUNT_31             746
#define TRAINER_TEAM_ROCKET_GRUNT_32             747
#define TRAINER_TEAM_ROCKET_GRUNT_33             748
#define TRAINER_TEAM_ROCKET_GRUNT_34             749
#define TRAINER_TEAM_ROCKET_GRUNT_35             750
#define TRAINER_TEAM_ROCKET_GRUNT_36             751
#define TRAINER_TEAM_ROCKET_GRUNT_37             752
#define TRAINER_TEAM_ROCKET_GRUNT_38             753
#define TRAINER_TEAM_ROCKET_GRUNT_39             754
#define TRAINER_TEAM_ROCKET_GRUNT_40             755
#define TRAINER_TEAM_ROCKET_GRUNT_41             756
#define TRAINER_TEAM_ROCKET_GRUNT_42             757
#define TRAINER_TEAM_ROCKET_GRUNT_43             758
#define TRAINER_TEAM_ROCKET_GRUNT_44             759
#define TRAINER_TEAM_ROCKET_GRUNT_45             760
#define TRAINER_TEAM_ROCKET_GRUNT_46             761
#define TRAINER_TEAM_ROCKET_GRUNT_47             762
#define TRAINER_TEAM_ROCKET_GRUNT_48             763
#define TRAINER_TEAM_ROCKET_GRUNT_49             764
#define TRAINER_TEAM_ROCKET_GRUNT_50             765
#define TRAINER_TEAM_ROCKET_GRUNT_51             766
#define TRAINER_TUBER_ALEXIS                     767
#define TRAINER_TUBER_AMIRA                      768
#define TRAINER_TUBER_AMIRA_2                    769
#define TRAINER_TUBER_AMIRA_3                    770
#define TRAINER_TUBER_AMIRA_4                    771
#define TRAINER_TUBER_AMIRA_5                    772
#define TRAINER_TWINS_ELI_ANNE                   773
#define TRAINER_TWINS_ELI_ANNE_2                 774
#define TRAINER_TWINS_ELI_ANNE_3                 775
#define TRAINER_TWINS_ELI_ANNE_4                 776
#define TRAINER_TWINS_ELI_ANNE_5                 777
#define TRAINER_TWINS_JOY_MEG                    778
#define TRAINER_TWINS_JOY_MEG_2                  779
#define TRAINER_TWINS_JOY_MEG_3                  780
#define TRAINER_TWINS_JOY_MEG_4                  781
#define TRAINER_TWINS_JOY_MEG_5                  782
#define TRAINER_TWINS_KIRI_JAN                   783
#define TRAINER_TWINS_MIU_MIA                    784
#define TRAINER_YOUNG_COUPLE_EVE_JON             785
#define TRAINER_YOUNG_COUPLE_GIA_JES             786
#define TRAINER_YOUNG_COUPLE_GIA_JES_2           787
#define TRAINER_YOUNG_COUPLE_GIA_JES_3           788
#define TRAINER_YOUNG_COUPLE_GIA_JES_4           789
#define TRAINER_YOUNG_COUPLE_GIA_JES_5           790
#define TRAINER_YOUNG_COUPLE_LEA_JED             791
#define TRAINER_YOUNGSTER_ALLEN                  792
#define TRAINER_YOUNGSTER_BEN                    793
#define TRAINER_YOUNGSTER_BEN_2                  794
#define TRAINER_YOUNGSTER_BEN_3                  795
#define TRAINER_YOUNGSTER_BEN_4                  796
#define TRAINER_YOUNGSTER_BEN_5                  797
#define TRAINER_YOUNGSTER_CALVIN                 798
#define TRAINER_YOUNGSTER_CHAD                   799
#define TRAINER_YOUNGSTER_CHAD_2                 800
#define TRAINER_YOUNGSTER_CHAD_3                 801
#define TRAINER_YOUNGSTER_CHAD_4                 802
#define TRAINER_YOUNGSTER_CHAD_5                 803
#define TRAINER_YOUNGSTER_CORDELL                804
#define TRAINER_YOUNGSTER_DAN                    805
#define TRAINER_YOUNGSTER_DAVE                   806
#define TRAINER_YOUNGSTER_DESTIN                 807
#define TRAINER_YOUNGSTER_DESTIN_2               808
#define TRAINER_YOUNGSTER_DESTIN_3               809
#define TRAINER_YOUNGSTER_DESTIN_4               810
#define TRAINER_YOUNGSTER_DESTIN_5               811
#define TRAINER_YOUNGSTER_DILLON                 812
#define TRAINER_YOUNGSTER_EDDIE                  813
#define TRAINER_YOUNGSTER_JOEY                   814
#define TRAINER_YOUNGSTER_JOHNSON                815
#define TRAINER_YOUNGSTER_JOSH                   816
#define TRAINER_YOUNGSTER_NASH                   817
#define TRAINER_YOUNGSTER_TIMMY                  818
#define TRAINER_YOUNGSTER_TIMMY_2                819
#define TRAINER_YOUNGSTER_TIMMY_3                820
#define TRAINER_YOUNGSTER_TIMMY_4                821
#define TRAINER_YOUNGSTER_TIMMY_5                822
#define TRAINER_YOUNGSTER_TYLER                  823
#define TRAINER_YOUNGSTER_YASU                   824
#define TRAINER_YOUNGSTER_YASU_2                 825
#define TRAINER_YOUNGSTER_YASU_3                 826
#define TRAINER_YOUNGSTER_YASU_4                 827
#define TRAINER_YOUNGSTER_YASU_5                 828
#define TRAINER_ELITE_FOUR_LORELEI               829
#define TRAINER_ELITE_FOUR_LORELEI_2             830
#define TRAINER_ELITE_FOUR_BRUNO                 831
#define TRAINER_ELITE_FOUR_BRUNO_2               832
#define TRAINER_ELITE_FOUR_AGATHA                833
#define TRAINER_ELITE_FOUR_AGATHA_2              834
#define TRAINER_ELITE_FOUR_LANCE                 835
#define TRAINER_ELITE_FOUR_LANCE_2               836
#define TRAINER_CHAMPION_FIRST_SQUIRTLE          837
#define TRAINER_CHAMPION_REMATCH_SQUIRTLE        838
#define TRAINER_CHAMPION_FIRST_BULBASAUR         839
#define TRAINER_CHAMPION_REMATCH_BULBASAUR       840
#define TRAINER_CHAMPION_FIRST_CHARMANDER        841
#define TRAINER_CHAMPION_REMATCH_CHARMANDER      842
#define TRAINER_FRONTIER_BRAIN_ANABEL            843
#define TRAINER_FRONTIER_BRAIN_TUCKER            844
#define TRAINER_FRONTIER_BRAIN_SPENSER           845
#define TRAINER_FRONTIER_BRAIN_GRETA             846
#define TRAINER_FRONTIER_BRAIN_NOLAND            847
#define TRAINER_FRONTIER_BRAIN_LUCY              848
#define TRAINER_FRONTIER_BRAIN_BRANDON           849
#define TRAINER_STEVEN                      850
#define TRAINER_RED                         851
#define TRAINER_LEAF                        852
#define TRAINER_BRENDAN_PLACEHOLDER         853
#define TRAINER_MAY_PLACEHOLDER             854

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      855
#define MAX_TRAINERS_COUNT                  864

#endif  // GUARD_CONSTANTS_OPPONENTS_H
