#ifndef GUARD_CONSTANTS_SPECIES_H
#define GUARD_CONSTANTS_SPECIES_H

#define SPECIES_NONE                     0
#define SPECIES_BULBASAUR                1
#define SPECIES_IVYSAUR                  2
#define SPECIES_VENUSAUR                 3
#define SPECIES_CHARMANDER               4
#define SPECIES_CHARMELEON               5
#define SPECIES_CHARIZARD                6
#define SPECIES_SQUIRTLE                 7
#define SPECIES_WARTORTLE                8
#define SPECIES_BLASTOISE                9
#define SPECIES_CATERPIE                 10
#define SPECIES_METAPOD                  11
#define SPECIES_BUTTERFREE               12
#define SPECIES_WEEDLE                   13
#define SPECIES_KAKUNA                   14
#define SPECIES_BEEDRILL                 15
#define SPECIES_PIDGEY                   16
#define SPECIES_PIDGEOTTO                17
#define SPECIES_PIDGEOT                  18
#define SPECIES_RATTATA                  19
#define SPECIES_RATICATE                 20
#define SPECIES_SPEAROW                  21
#define SPECIES_FEAROW                   22
#define SPECIES_EKANS                    23
#define SPECIES_ARBOK                    24
#define SPECIES_PICHU                    25
#define SPECIES_PIKACHU                  26
#define SPECIES_RAICHU                   27
#define SPECIES_SANDSHREW                28
#define SPECIES_SANDSLASH                29
#define SPECIES_NIDORAN_F                30
#define SPECIES_NIDORINA                 31
#define SPECIES_NIDOQUEEN                32
#define SPECIES_NIDORAN_M                33
#define SPECIES_NIDORINO                 34
#define SPECIES_NIDOKING                 35
#define SPECIES_CLEFFA                   36
#define SPECIES_CLEFAIRY                 37
#define SPECIES_CLEFABLE                 38
#define SPECIES_VULPIX                   39
#define SPECIES_NINETALES                40
#define SPECIES_IGGLYBUFF                41
#define SPECIES_JIGGLYPUFF               42
#define SPECIES_WIGGLYTUFF               43
#define SPECIES_ZUBAT                    44
#define SPECIES_GOLBAT                   45
#define SPECIES_CROBAT                   46
#define SPECIES_ODDISH                   47
#define SPECIES_GLOOM                    48
#define SPECIES_VILEPLUME                49
#define SPECIES_BELLOSSOM                50
#define SPECIES_PARAS                    51
#define SPECIES_PARASECT                 52
#define SPECIES_VENONAT                  53
#define SPECIES_VENOMOTH                 54
#define SPECIES_DIGLETT                  55
#define SPECIES_DUGTRIO                  56
#define SPECIES_MEOWTH                   57
#define SPECIES_PERSIAN                  58
#define SPECIES_PSYDUCK                  59
#define SPECIES_GOLDUCK                  60
#define SPECIES_MANKEY                   61
#define SPECIES_PRIMEAPE                 62
#define SPECIES_GROWLITHE                63
#define SPECIES_ARCANINE                 64
#define SPECIES_POLIWAG                  65
#define SPECIES_POLIWHIRL                66
#define SPECIES_POLIWRATH                67
#define SPECIES_POLITOED                 68
#define SPECIES_ABRA                     69
#define SPECIES_KADABRA                  70
#define SPECIES_ALAKAZAM                 71
#define SPECIES_MACHOP                   72
#define SPECIES_MACHOKE                  73
#define SPECIES_MACHAMP                  74
#define SPECIES_BELLSPROUT               75
#define SPECIES_WEEPINBELL               76
#define SPECIES_VICTREEBEL               77
#define SPECIES_TENTACOOL                78
#define SPECIES_TENTACRUEL               79
#define SPECIES_GEODUDE                  80
#define SPECIES_GRAVELER                 81
#define SPECIES_GOLEM                    82
#define SPECIES_PONYTA                   83
#define SPECIES_RAPIDASH                 84
#define SPECIES_SLOWPOKE                 85
#define SPECIES_SLOWBRO                  86
#define SPECIES_SLOWKING                 87
#define SPECIES_MAGNEMITE                88
#define SPECIES_MAGNETON                 89
#define SPECIES_FARFETCHD                90
#define SPECIES_DODUO                    91
#define SPECIES_DODRIO                   92
#define SPECIES_SEEL                     93
#define SPECIES_DEWGONG                  94
#define SPECIES_GRIMER                   95
#define SPECIES_MUK                      96
#define SPECIES_SHELLDER                 97
#define SPECIES_CLOYSTER                 98
#define SPECIES_GASTLY                   99
#define SPECIES_HAUNTER                  100
#define SPECIES_GENGAR                   101
#define SPECIES_ONIX                     102
#define SPECIES_STEELIX                  103
#define SPECIES_DROWZEE                  104
#define SPECIES_HYPNO                    105
#define SPECIES_KRABBY                   106
#define SPECIES_KINGLER                  107
#define SPECIES_VOLTORB                  108
#define SPECIES_ELECTRODE                109
#define SPECIES_EXEGGCUTE                110
#define SPECIES_EXEGGUTOR                111
#define SPECIES_CUBONE                   112
#define SPECIES_MAROWAK                  113
#define SPECIES_TYROGUE                  114
#define SPECIES_HITMONLEE                115
#define SPECIES_HITMONCHAN               116
#define SPECIES_HITMONTOP                117
#define SPECIES_LICKITUNG                118
#define SPECIES_KOFFING                  119
#define SPECIES_WEEZING                  120
#define SPECIES_RHYHORN                  121
#define SPECIES_RHYDON                   122
#define SPECIES_CHANSEY                  123
#define SPECIES_BLISSEY                  124
#define SPECIES_TANGELA                  125
#define SPECIES_KANGASKHAN               126
#define SPECIES_HORSEA                   127
#define SPECIES_SEADRA                   128
#define SPECIES_KINGDRA                  129
#define SPECIES_GOLDEEN                  130
#define SPECIES_SEAKING                  131
#define SPECIES_STARYU                   132
#define SPECIES_STARMIE                  133
#define SPECIES_MR_MIME                  134
#define SPECIES_SCYTHER                  135
#define SPECIES_SCIZOR                   136
#define SPECIES_SMOOCHUM                 137
#define SPECIES_JYNX                     138
#define SPECIES_ELEKID                   139
#define SPECIES_ELECTABUZZ               140
#define SPECIES_MAGBY                    141
#define SPECIES_MAGMAR                   142
#define SPECIES_PINSIR                   143
#define SPECIES_TAUROS                   144
#define SPECIES_MAGIKARP                 145
#define SPECIES_GYARADOS                 146
#define SPECIES_LAPRAS                   147
#define SPECIES_DITTO                    148
#define SPECIES_EEVEE                    149
#define SPECIES_VAPOREON                 150
#define SPECIES_JOLTEON                  151
#define SPECIES_FLAREON                  152
#define SPECIES_ESPEON                   153
#define SPECIES_UMBREON                  154
#define SPECIES_PORYGON                  155
#define SPECIES_PORYGON2                 156
#define SPECIES_OMANYTE                  157
#define SPECIES_OMASTAR                  158
#define SPECIES_KABUTO                   159
#define SPECIES_KABUTOPS                 160
#define SPECIES_AERODACTYL               161
#define SPECIES_SNORLAX                  162
#define SPECIES_ARTICUNO                 163
#define SPECIES_ZAPDOS                   164
#define SPECIES_MOLTRES                  165
#define SPECIES_DRATINI                  166
#define SPECIES_DRAGONAIR                167
#define SPECIES_DRAGONITE                168
#define SPECIES_MEWTWO                   169
#define SPECIES_MEW                      170

#define SPECIES_EGG SPECIES_MEW + 1

#define NUM_SPECIES SPECIES_EGG

#endif  // GUARD_CONSTANTS_SPECIES_H
