#ifndef GUARD_CONSTANTS_TRAINER_TOWER_H
#define GUARD_CONSTANTS_TRAINER_TOWER_H

#define TRAINER_TOWER_1F       1
#define TRAINER_TOWER_2F       2
#define TRAINER_TOWER_3F       3
#define TRAINER_TOWER_4F       4
#define TRAINER_TOWER_ROOF     5
#define TRAINER_TOWER_LOBBY    6

#define TOWER_MODE_NORMAL  0
#define TOWER_MODE_VARIETY 1
#define TOWER_MODE_UNIQUE  2
#define TOWER_MODE_EXPERT  3
#define NUM_TRAINER_TOWER_MODES 4

#define NUM_TRAINER_TOWER_FLOORS    4
#define NUM_TRAINER_TOWER_FLOORS_JP 2

#define NUM_TRAINER_TOWER_PRIZE_LISTS 10

#define TRAINER_TOWER_FUNC_START                 0
#define TRAINER_TOWER_FUNC_GET_OWNER_STATE       1
#define TRAINER_TOWER_FUNC_GIVE_PRIZE            2
#define TRAINER_TOWER_FUNC_CHECK_FINAL_TIME      3
#define TRAINER_TOWER_FUNC_RESUME_TIMER          4
#define TRAINER_TOWER_FUNC_SET_LOST              5
#define TRAINER_TOWER_FUNC_GET_CHALLENGE_STATUS  6
#define TRAINER_TOWER_FUNC_GET_CHALLENGE_TIME    7
#define TRAINER_TOWER_FUNC_GET_ALL_FLOORS_USED   8
#define TRAINER_TOWER_FUNC_GET_IN_EREADER_MODE   9
#define TRAINER_TOWER_FUNC_IN_CHALLENGE          10
#define TRAINER_TOWER_FUNC_POST_BATTLE_TEXT      11
#define TRAINER_TOWER_FUNC_SET_ALL_TRAINER_FLAGS 12
#define TRAINER_TOWER_FUNC_GET_GAME_SAVED        13
#define TRAINER_TOWER_FUNC_SET_GAME_SAVED        14
#define TRAINER_TOWER_FUNC_CLEAR_GAME_SAVED      15
#define TRAINER_TOWER_FUNC_GET_WON               16
#define TRAINER_TOWER_FUNC_SET_MODE              17

#define TRAINER_TOWER_TEXT_INTRO        2
#define TRAINER_TOWER_TEXT_PLAYER_LOST  3
#define TRAINER_TOWER_TEXT_PLAYER_WON   4
#define TRAINER_TOWER_TEXT_AFTER        5

#define TOWER_TRAINERS_PER_FLOOR 2
#define NUM_TRAINER_TOWER_TRAINERS     (NUM_TRAINER_TOWER_FLOORS * TOWER_TRAINERS_PER_FLOOR)
#define NUM_TRAINER_TOWER_TRAINERS_JP  (NUM_TRAINER_TOWER_FLOORS_JP * TOWER_TRAINERS_PER_FLOOR)

// Values returned by TrainerTowerGetChallengeStatus
#define TRAINER_TOWER_PLAYER_STATUS_LOST 0
#define TRAINER_TOWER_PLAYER_STATUS_ECARD_SCANNED 1
#define TRAINER_TOWER_PLAYER_STATUS_NORMAL 2

#define TRAINER_TOWER_OTID 0x10000000

// The full map of each Trainer Tower floor is 16x21.
// The first 5x21 at the top is the entrance/exit area,
// and the remaining 16x16 is the randomized portion of
// the room where the trainers are.
#define TOWER_FLOOR_WIDTH         16
#define TOWER_FLOOR_HEIGHT_MAIN   16
#define TOWER_FLOOR_HEIGHT_MARGIN  5
#define TOWER_FLOOR_HEIGHT        (TOWER_FLOOR_HEIGHT_MAIN + TOWER_FLOOR_HEIGHT_MARGIN)

#endif
