SafariZone_North_RestHouse_MapScripts::
	.byte 0

SafariZone_North_RestHouse_EventScript_Fisher::
    msgbox SafariZone_North_RestHouse_Text_PrizeInDeepestPartOfSafariZone, MSGBOX_NPC
    end

SafariZone_North_RestHouse_EventScript_Scientist::
    msgbox SafariZone_North_RestHouse_Text_KeepAnyItemFoundOnSafari, MSGBOX_NPC
    end

SafariZone_North_RestHouse_EventScript_Gentleman::
    msgbox SafariZone_North_RestHouse_Text_MyEeveeEvolvedIntoFlareon, MSGBOX_NPC
    end

SafariZone_North_RestHouse_EventScript_BaldingMan::
    msgbox SafariZone_North_RestHouse_Text_KogaPatrolsSafariEverySoOften, MSGBOX_NPC
    end

SafariZone_North_RestHouse_Text_KeepAnyItemFoundOnSafari::
    .string "You can keep any item you find in\n"
    .string "the Safari Zone.\p"
    .string "But, you'll run out of time if you\n"
    .string "try for all of them at once.$"

SafariZone_North_RestHouse_Text_PrizeInDeepestPartOfSafariZone::
    .string "Go to the deepest part of the\n"
    .string "Safari Zone. You will win a prize!$"

SafariZone_North_RestHouse_Text_MyEeveeEvolvedIntoFlareon::
    .string "My Eevee evolved into Flareon.\p"
    .string "But, a friend's Eevee turned into a\n"
    .string "Vaporeon. I wonder why?$"

SafariZone_North_RestHouse_Text_KogaPatrolsSafariEverySoOften::
    .string "The Safari Zone's huge, wouldn't\n"
    .string "you say?\p"
    .string "Fuchsia's Gym Leader, Koga, \n"
    .string "patrols the grounds every so often.\p"
    .string "Thanks to him, we can play here\n"
    .string "knowing that we're safe.$"
