@ NOTE: The brailleformat macro in this file is leftover from RS.
@       The numbers are simply skipped over. If you'd like to omit
@       this macro you must also stop it from skipping over this
@       section by editing ScrCmd_braillemessage.

Braille_Text_Up::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "UP$"

Braille_Text_Down::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "DOWN$"

Braille_Text_Right::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "RIGHT$"

Braille_Text_Left::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "LEFT$"

Braille_Text_Cut::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "CUT$"

Braille_Text_ABC::
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "ABC$"

Braille_Text_GHI::
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "GHI$"

Braille_Text_MNO::
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "MNO$"

Braille_Text_TUV::
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "TUV$"

Braille_Text_DEF::
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "DEF$"

Braille_Text_JKL::
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "JKL$"

Braille_Text_PQRS::
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "PQRS$"

Braille_Text_WXYZ::
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "WXYZ$"

Braille_Text_Period::
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ".$"

Braille_Text_Comma::
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ",$"

Braille_Text_Everything::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "EVERYTHING$"

Braille_Text_HasMeaning1::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "HAS MEANING$"

Braille_Text_Existence::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "EXISTENCE$"

Braille_Text_HasMeaning2::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "HAS MEANING$"

Braille_Text_BeingAlive::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "BEING ALIVE$"

Braille_Text_HasMeaning3::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "HAS MEANING$"

Braille_Text_HaveDreams::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "HAVE DREAMS$"

Braille_Text_UsePower::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "USE POWER.$"

Braille_Text_LetTheTwo::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "LET THE TWO$"

Braille_Text_Glittering::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "GLITTERING$"

Braille_Text_Stones::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "STONES$"

Braille_Text_OneInRed::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "ONE IN RED$"

Braille_Text_OneInBlue::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "ONE IN BLUE$"

Braille_Text_ConnectThe::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "CONNECT THE$"

Braille_Text_Past::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "PAST.$"

Braille_Text_TwoFriends::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "TWO FRIENDS$"

Braille_Text_Sharing::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "SHARING$"

Braille_Text_PowerOpen::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "POWER OPEN$"

Braille_Text_AWindowTo::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "A WINDOW TO$"

Braille_Text_ANewWorld::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "A NEW WORLD$"

Braille_Text_ThatGlows::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "THAT GLOWS.$"

Braille_Text_TheNext::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "THE NEXT$"

Braille_Text_WorldWaits::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "WORLD WAITS$"

Braille_Text_ForYou::
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "FOR YOU.$"
