Text_PictureBookShelf:
    .string "There's a set of Pokémon picture books.$"

Text_BookShelf:
    .string "It's crammed full of Pokémon\n"
    .string "books.$"

Text_PokemonCenterBookShelf:
    .string "Pokémon magazines!\n"
    .string "Pokémon Pal…\p"
    .string "Pokémon Handbook…\n"
    .string "Adorable Pokémon…$"

Text_ATownMap:: @ 81C0DF1
    .string "A Town Map.$"

Text_PokeMartShelf:
    .string "Wow!\n"
    .string "Tons of Pokémon stuff!$"

Text_DishesPlatesNeatlyLinedUp::
    .string "Dishes and plates are neatly\n"
    .string "lined up.$"

Text_Kitchen::
    .string "It smells delicious!\n"
    .string "Somebody's been cooking here.$"

Text_Dresser::
    .string "It's a nicely made dresser.\n"
    .string "It will hold a lot of stuff.$"

Text_Snacks::
    .string "There's a pile of snacks here.$"
    
Text_PokemartSign::
    .string "Pokémon Mart\n"
    .string "All your item needs fulfilled!$"

Text_PokecenterSign::
    .string "Pokémon Center\n"
    .string "Heal Your Pokémon!$"

Text_Indigo_UltimateGoal::
    .string "Indigo Plateau\p"
    .string "The ultimate goal of trainers!\n"
    .string "Pokémon League HQ$"

Text_Indigo_HighestAuthority:: @ 81C0F59
    .string "Indigo Plateau\p"
    .string "The highest Pokémon authority!\n"
    .string "Pokémon League HQ$"

Text_Food::
    .string "It should be packed with all kinds\n"
    .string "of delicious things to eat.$"

Text_Blueprints::
    .string "It's a blueprint of some sort.\n"
    .string "It's filled with diagrams and text.$"

Text_Painting::
    .string "It's a pretty picture of a Pokémon.\n"
    .string "It looks like it's feeling good.$"

Text_Vase:
    .string "This vase looks expensive…\n"
    .string "Peered inside…\p"
    .string "But, it was empty.$"

Text_PowerPlantMachine::
    .string "What could this machine be?\n"
    .string "Better not mess around with it!$"

Text_Telephone::
    .string "It's a telephone.\n"
    .string "Better not use it.$"

Text_Computer::
    .string "It's all complicated words and\n"
    .string "numbers that make no sense…$"

Text_AdvertisingPoster::
    .string "It's an advertising poster about\n"
    .string "all kinds of products.$"

Text_TastyFood::
    .string "Oh, that smells tasty!\n"
    .string "It might get the stomach growling!$"

Text_TrashBin::
    .string "Inside this…\n"
    .string "……\p"
    .string "There's nothing here!$"

Text_Cup::
    .string "It's a cup with a Pokémon mark\n"
    .string "on it.$"

Text_PolishedWindow::
    .string "The window is very well polished.$"

Text_BeautifulSkyWindow::
    .string "Outside the window…\p"
    .string "The sky looks fantastically\n"
    .string "beautiful.$"

Text_BlinkingLights::
    .string "Lights in different colours are\n"
    .string "flashing on and off.$"

Text_NeatlyLinedUpTools::
    .string "All sorts of tools are lined up\n"
    .string "neatly.$"

Text_ImpressiveMachine::
    .string "It's a machine of some sort.\n"
    .string "It sure is impressive.$"

Text_VideoGame::
    .string "It's the latest video game!\n"
    .string "It sure looks fun!$"

Text_Burglary::
    .string "There are obvious signs of burglary\n"
    .string "here…$"
