EventTicket_Text_ShowOldSeaMap:
	.string "The ferry has…\p"
	.string "I beg your pardon?\n"
	.string "Can we sail to this place on the map?\p"
	.string "I know someone who will help you better.\n"
	.string "Please wait.$"

EventTicket_Text_ThatPass:
	.string "The ferry has…\p"
	.string "Oh?\n"
	.string "That Pass…$"

EventTicket_Text_SailHome:
	.string "Aye, right, then!\n"
	.string "Sail home we will!$"

EventTicket_Text_AsYouLike:
	.string "Aye, right, as you like, then.$"
