MatchCall_WildBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I saw this {STR_VAR_2} a while back\n"
	.string "but I couldn't catch it.\p"
	.string "It was so close, too!\n"
	.string "Well, see you again!$"

MatchCall_WildBattleText2::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I tried to catch a nice {STR_VAR_2}\n"
	.string "a little while ago.\p"
	.string "But, it got away.\n"
	.string "I was sure disappointed!\p"
	.string "Okay, bye!$"

MatchCall_WildBattleText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I just took a shot at catching\n"
	.string "this {STR_VAR_2}, but it took off.\p"
	.string "I came oh so close, too!\p"
	.string "It spoiled my day…\n"
	.string "All right, see you!$"

MatchCall_WildBattleText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "You know the Pokémon {STR_VAR_2}?\n"
	.string "I came close to getting one.\p"
	.string "It was just a while back.\n"
	.string "I thought I had it but it escaped.\p"
	.string "If I see it again, I'll get it for\n"
	.string "sure, though.\p"
	.string "Okay, catch you later.$"

MatchCall_WildBattleText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\l"
	.string "Catching any Pokémon lately?\p"
	.string "A little while ago I came close to\n"
	.string "nabbing one, but it got loose.\p"
	.string "Right, take care!$"

MatchCall_WildBattleText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "Caught any Pokémon lately?\p"
	.string "I nearly nabbed one the other day.\n"
	.string "But it evaded me somehow.\p"
	.string "You take care.$"

MatchCall_WildBattleText7::
	.string "…Uh, {PLAYER}{KUN}?\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "Oh, wait! Wait!\n"
	.string "I can catch this {STR_VAR_2}…\p"
	.string "Aaarrrgh! It bolted loose!\n"
	.string "That wasn't just close!$"

MatchCall_WildBattleText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "Have you had success catching\n"
	.string "Pokémon lately?\p"
	.string "I came very close a little while\n"
	.string "ago, but my target got free.\p"
	.string "I need to try harder!\n"
	.string "See you again!$"

MatchCall_WildBattleText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "So? Are you getting more Pokémon\n"
	.string "together?\p"
	.string "I'm having a rotten time of it!\n"
	.string "They all get away from me!\p"
	.string "See you!$"

MatchCall_WildBattleText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Listen, I came within a whisker of\n"
	.string "catching this {STR_VAR_2}…\p"
	.string "But, it gave me the slip…\p"
	.string "I need to try harder.\n"
	.string "See you around.$"

MatchCall_WildBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "How are things with you?\p"
	.string "I tried to catch a wild {STR_VAR_2}\n"
	.string "earlier, but it managed to flee.\p"
	.string "I feel defeated…$"

MatchCall_WildBattleText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you still catching Pokémon?\p"
	.string "I've been trying to catch them\n"
	.string "myself, but it's not so easy.\p"
	.string "The way of Pokémon is deep!$"

MatchCall_WildBattleText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "Have you been catching Pokémon?\p"
	.string "I've been trying to catch them\n"
	.string "myself, but with little success.\p"
	.string "The way of Pokémon is deep!$"

MatchCall_WildBattleText14::
	.string "Oh, hi, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Just now, I tried to catch a cute\n"
	.string "{STR_VAR_2}.\p"
	.string "It got away, though!\n"
	.string "Oh, you bet I was disappointed!\p"
	.string "Bye-bye!$"

MatchCall_WildBattleText15::
	.string "Hey, {PLAYER}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I've been thinking about trying\n"
	.string "to catch me some Pokémon.\p"
	.string "But I can't seem to find any.\n"
	.string "It's a real puzzler for me!\p"
	.string "I'm at my wit's end!\n"
	.string "See you around!$"

MatchCall_NegativeBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I tried battling another Trainer,\n"
	.string "but I lost.\p"
	.string "It was really disappointing.\n"
	.string "Well, see you again!$"

MatchCall_NegativeBattleText2::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I challenged someone else after\n"
	.string "we battled.\p"
	.string "I came close, but I ended up\n"
	.string "losing. Oh, well!$"

MatchCall_NegativeBattleText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I just got cleaned in a battle.\p"
	.string "I guess I need to raise my team\n"
	.string "some more!$"

MatchCall_NegativeBattleText4::
	.string "Hey, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I tried another battle yesterday,\n"
	.string "but I couldn't pull out the win.\p"
	.string "My team needs more raising.\n"
	.string "Okay, catch you later.$"

MatchCall_NegativeBattleText5::
	.string "Hiya, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "How are things with you?\p"
	.string "I've been battling on,\n"
	.string "but I haven't won very often.\p"
	.string "I can't get it together.\n"
	.string "Right, take care!$"

MatchCall_NegativeBattleText6::
	.string "Hey, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How's it going for you?\p"
	.string "I've been battling hard lately,\n"
	.string "but to little success.\p"
	.string "I can't get into the groove.\n"
	.string "You take care.$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1} here.\n"
	.string "How's it going lately?\p"
	.string "I lost a battle yesterday,\n"
	.string "and it's filled my thoughts.\p"
	.string "I have to devise a plan…\n"
	.string "See you.$"

MatchCall_NegativeBattleText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "How are your Pokémon doing?\n"
	.string "I lost a match the other day.\p"
	.string "I need to try harder!\n"
	.string "See you again!$"

MatchCall_NegativeBattleText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "Listen, listen, you have to hear\n"
	.string "this!\p"
	.string "I had a Pokémon battle earlier,\n"
	.string "but I lost at the last second.\p"
	.string "Oh, it burns me up!$"

MatchCall_NegativeBattleText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "A little earlier, I was in a battle.\n"
	.string "I lost, though.\p"
	.string "I need to raise my Pokémon more.\n"
	.string "See you around.$"

MatchCall_NegativeBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "How are your Pokémon?\p"
	.string "I just lost yet another battle.\p"
	.string "Well, see you!$"

MatchCall_NegativeBattleText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you still battling hard?\p"
	.string "As for me, I lost recently, so I've\n"
	.string "been training my team all over.\p"
	.string "Let's meet again.$"

MatchCall_NegativeBattleText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I hope you've been keeping well.\p"
	.string "I was in a battle just a little\n"
	.string "while before this.\p"
	.string "{PLAYER}{KUN}, try to be active like me.\n"
	.string "See you again!$"

MatchCall_NegativeBattleText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Are you doing good?\p"
	.string "You should go home every so often,\n"
	.string "though.\p"
	.string "Bye-bye!$"

MatchCall_PositiveBattleText1::
	.string "Hi! {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I battled another Trainer earlier.\n"
	.string "I won! I won!\p"
	.string "My {STR_VAR_2} really worked hard\n"
	.string "for me. This is so great!$"

MatchCall_PositiveBattleText2::
	.string "Hello, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}!\p"
	.string "I had a battle yesterday and\n"
	.string "I won! It's fantastic!$"

MatchCall_PositiveBattleText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}!\l"
	.string "How's your battling?\p"
	.string "Me, I had a battle the other day,\n"
	.string "and my {STR_VAR_2} came up huge!\p"
	.string "The next time I battle you,\n"
	.string "{PLAYER}, it won't be me losing!$"

MatchCall_PositiveBattleText4::
	.string "Hey, {PLAYER}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I had a match earlier.\n"
	.string "I managed to win, but it was close.\p"
	.string "My {STR_VAR_2} put on one\n"
	.string "inspired showing.$"

MatchCall_PositiveBattleText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "How are things with you?\n"
	.string "Battling much?\p"
	.string "I just won a while back!\n"
	.string "My {STR_VAR_2} was brilliant!\p"
	.string "You wait. I'm going to beat you\n"
	.string "next time! Right, take care!$"

MatchCall_PositiveBattleText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How's it going for you?\p"
	.string "I've been riding a hot streak.\n"
	.string "Why, I just won a battle.\p"
	.string "When we have our next battle,\n"
	.string "I'm sure not going to lose!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "My {STR_VAR_2} is a force!\n"
	.string "It won me another battle just now!\p"
	.string "I can't wait to have a rematch\n"
	.string "with you.$"

MatchCall_PositiveBattleText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "I hope you've been well.\n"
	.string "I wanted to tell you I just won.\p"
	.string "My {STR_VAR_2} worked especially\n"
	.string "hard to get the win.\p"
	.string "See you again!$"

MatchCall_PositiveBattleText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "How are your Pokémon holding up?\n"
	.string "Mine just won a battle!\p"
	.string "My {STR_VAR_2} was spectacular,\n"
	.string "I must say!\p"
	.string "I wish I could've shown you!\n"
	.string "See you again!$"

MatchCall_PositiveBattleText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "How has life been treating you?\p"
	.string "My Pokémon appear to be charged\n"
	.string "with energy.\p"
	.string "I just won a battle with them.\n"
	.string "See you around.$"

MatchCall_PositiveBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Been in any battles lately?\n"
	.string "I just won another one today!\p"
	.string "I'm on a roll! Gahahaha!\n"
	.string "Well, see you!$"

MatchCall_PositiveBattleText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I trust you've been well?\n"
	.string "I'm still bursting with life!\p"
	.string "Why, just now, I won another match.\n"
	.string "I'm not stepping aside to you\l"
	.string "youngsters yet!$"

MatchCall_PositiveBattleText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I hope you've been keeping well.\n"
	.string "I still have a bounce in my step!\p"
	.string "Why, I just won a battle yet again.\n"
	.string "Oh, I won't lose to young people\l"
	.string "quite yet!\p"
	.string "See you again!$"

MatchCall_PositiveBattleText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I was in a battle recently, and my\n"
	.string "{STR_VAR_2} was exceptional!\p"
	.string "I wish you could have seen it,\n"
	.string "{PLAYER}{KUN}. Bye-bye!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Hi! {PLAYER}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Huh? Wait, you're near\n"
	.string "{STR_VAR_2}?\p"
	.string "Oh, wow, we have to battle, then!\n"
	.string "I'll be waiting! See you!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Hello, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "Oh? You happen to be around\n"
	.string "{STR_VAR_2} right now?\p"
	.string "Would you like to battle now?\n"
	.string "I'll wait for you! See you!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "Oh, hey, are you near\n"
	.string "{STR_VAR_2} right now?\p"
	.string "How would you like to battle with\n"
	.string "me right now?\p"
	.string "I'm not losing again!\n"
	.string "I'll be waiting! Catch you soon!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "Whereabouts are you now?\n"
	.string "Huh? {STR_VAR_2}?\p"
	.string "Want to battle now?\n"
	.string "I'll wait for you. See you!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\l"
	.string "How are things with you?\p"
	.string "You're where now?\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, how about we have a quick\n"
	.string "rematch right away?\p"
	.string "I'll keep an eye out for you.\n"
	.string "See you soon!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "How are your Pokémon keeping?\p"
	.string "Oh, is that right? You're around\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, then, we'd better have\n"
	.string "a rematch.\p"
	.string "I can wait, sure.\n"
	.string "See you!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, you happen to be around\n"
	.string "{STR_VAR_2}?\p"
	.string "Then, let's battle.\n"
	.string "Right away, I mean.\p"
	.string "I'll show you my Pokémon.\n"
	.string "I'll wait for you.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "I hope you're doing well.\n"
	.string "Oh, you're near {STR_VAR_2}.\p"
	.string "Would you like to have a battle\n"
	.string "with me, then?\p"
	.string "I'll wait for you.\n"
	.string "See you soon!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "Are you keeping up?\n"
	.string "Oh, you're near {STR_VAR_2}?\p"
	.string "Oh, well, then don't you think we\n"
	.string "should battle?\p"
	.string "Don't keep me waiting too long!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "How are things with you?\n"
	.string "Oh, you're near {STR_VAR_2}.\p"
	.string "We should have a battle now, then.\p"
	.string "I'm ready and waiting.\n"
	.string "Be quick!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Ah, so where you are now is\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, then, we just have to have\n"
	.string "a battle, don't you think?\p"
	.string "I'll wait around for you!\n"
	.string "See you real quick!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Where might you be now?\p"
	.string "{STR_VAR_2}?\n"
	.string "That's quite close by!\p"
	.string "What do you say we have a battle\n"
	.string "now?\p"
	.string "I can wait.\n"
	.string "See you!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I hope you've been keeping well.\n"
	.string "Oh, you're near {STR_VAR_2}?\p"
	.string "Since that's not very far away,\n"
	.string "come see me for a battle.\p"
	.string "I'll wait for you.\n"
	.string "Bye for now.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You're what? …{STR_VAR_2}?\n"
	.string "That's very close.\p"
	.string "Don't you think we ought to have\n"
	.string "a battle?\p"
	.string "I'll be looking for you!\n"
	.string "Bye-bye!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Hi! {PLAYER}, hello!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "Want to have a battle with me?\p"
	.string "I'll be waiting for you around\n"
	.string "{STR_VAR_2}!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Hello, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "Would you like to have a battle\n"
	.string "with me again?\p"
	.string "You can find me around\n"
	.string "{STR_VAR_2}. I'll be waiting!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "My Pokémon have grown a lot\n"
	.string "tougher since last time.\p"
	.string "I want to see how strong they've\n"
	.string "become with your Pokémon, {PLAYER}.\p"
	.string "So, let's have a battle!\p"
	.string "I'll be waiting for you around\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "How are things with you?\p"
	.string "My Pokémon have grown pretty\n"
	.string "tough lately.\p"
	.string "Hey, how would you like to have\n"
	.string "another battle with me?\p"
	.string "Let's meet up around\n"
	.string "{STR_VAR_2}, okay?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "My Pokémon are growing up in\n"
	.string "decent ways.\p"
	.string "I'd really like to have another\n"
	.string "battle with you.\p"
	.string "I'll keep an eye out for you around\n"
	.string "{STR_VAR_2}. See you soon!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "I hope you're on top of things.\p"
	.string "I was thinking I'd like another\n"
	.string "battle with you. What do you say?\p"
	.string "If you feel like a battle,\n"
	.string "come to {STR_VAR_2}.\p"
	.string "See you!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\l"
	.string "So? Are your Pokémon growing?\p"
	.string "Mine sure got stronger.\n"
	.string "I'd like to show you.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Come see me for a match.\p"
	.string "See you around.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "I hope you're doing well.\n"
	.string "My Pokémon are very frisky.\p"
	.string "If you're ever in the area, please\n"
	.string "give me a rematch.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Until then, good-bye!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "How are your Pokémon doing?\p"
	.string "My Pokémon keep getting better.\n"
	.string "I'd like to show you, {PLAYER}{KUN}.\p"
	.string "I'm around {STR_VAR_2} now,\n"
	.string "so let's battle if you're close by.\p"
	.string "Hope I see you soon!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\l"
	.string "So, how are things with you?\p"
	.string "My Pokémon have grown much\n"
	.string "stronger than before.\p"
	.string "I'd love another battle with you,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Come see me if you're close.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "Where might you be now?\p"
	.string "My Pokémon are full of life.\n"
	.string "They appear to be looking forward\l"
	.string "to seeing your Pokémon, {PLAYER}{KUN}.\p"
	.string "I'm around {STR_VAR_2} now.\n"
	.string "I hope you'll seek us out.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I should tell you, my Pokémon have\n"
	.string "grown to be quite robust lately.\p"
	.string "I would like to see them in a battle\n"
	.string "with you, {PLAYER}{KUN}.\p"
	.string "We'll be around {STR_VAR_2}.\n"
	.string "Come see us anytime!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "Are your Pokémon keeping well?\p"
	.string "My Pokémon have been so healthy,\n"
	.string "they don't look capable of losing!\p"
	.string "I would surely love to have another\n"
	.string "battle with you.\p"
	.string "If you're near {STR_VAR_2},\n"
	.string "do come see us.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "Keeping well, I hope.\p"
	.string "Oh, yes! My Pokémon are\n"
	.string "much stronger than before.\p"
	.string "Don't you think we ought to have\n"
	.string "a battle, {PLAYER}{KUN}?\p"
	.string "We'll be waiting for you around\n"
	.string "{STR_VAR_2}.\p"
	.string "Come see us anytime, okay?$"

MatchCall_PersonalizedText1::
	.string "It's me, {STR_VAR_1}!\p"
	.string "Well, since we met, have you grown\n"
	.string "to appreciate the art of painting?\p"
	.string "You should see the progress I've\n"
	.string "made on my current piece!\p"
	.string "Next time, we'll meet somewhere\n"
	.string "around {STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "This is {STR_VAR_1}.\n"
	.string "Hello.\p"
	.string "I was just telling a new Trainer\n"
	.string "about you.\p"
	.string "I told her about a strong Trainer\n"
	.string "who raises Pokémon with care.\p"
	.string "I hope you'll become a Trainer\n"
	.string "that everyone will admire.\p"
	.string "I hope we meet again!$"

MatchCall_PersonalizedText3::
	.string "Hello! It's {STR_VAR_1}.\p"
	.string "I keep getting weird looks from\n"
	.string "creepy people who walk past.\p"
	.string "So, I'm training my Pokémon to\n"
	.string "become stronger to protect me.\p"
	.string "You better not stare next time\n"
	.string "we meet!$"

MatchCall_PersonalizedText4::
	.string "Hello, {PLAYER}!\n"
	.string "{STR_VAR_1} at your service!\p"
	.string "It seems that you're energetically\n"
	.string "travelling here and there.\p"
	.string "Have you discovered any new\n"
	.string "places to train?\l"
	.string "Please tell if you have!\p"
	.string "Now, if you'll excuse me,\n"
	.string "I have to get back to training!$"

MatchCall_PersonalizedText5::
	.string "It's {STR_VAR_1}!\p"
	.string "Know what I'm doing today?\n"
	.string "Looking at waves from the beach!\p"
	.string "Sigh… The waves are all sparkly.\n"
	.string "The sea is the prettiest from here.\l"
	.string "I'm getting hungry, so bye-bye!$"

MatchCall_PersonalizedText6::
	.string "Oh, hi, it's {STR_VAR_1}.\n"
	.string "We've had a lot of Trainers\l"
	.string "pass by Nugget Bridge recently.\p"
	.string "But none of them have beaten me\n"
	.string "as convincingly as you!$"

MatchCall_PersonalizedText7::
	.string "Hello, this is {STR_VAR_1}…\n"
    .string "I had this feeling you would call.\p"
	.string "How are your Pokémon doing?\n"
	.string "Mine are getting better every day.\p"
	.string "I should be going now.\n"
	.string "Be seeing you!$"

MatchCall_PersonalizedText8::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "How do you do?\p"
	.string "I've been raising my Pokémon with\n"
	.string "you as the target.\p"
	.string "I don't intend to lose when we\n"
	.string "battle again.$"

MatchCall_PersonalizedText9::
	.string "Hi, it's {STR_VAR_1}…\p"
	.string "I've been trying to get\n"
	.string "stronger but the Trainers\l"
	.string "around here are't that skilled.\p"
	.string "I should seek out strong Trainers\n"
	.string "like you if I want to get better!\p"
	.string "Talk to you soon!$"

MatchCall_PersonalizedText10::
	.string "This is {STR_VAR_1}.\n"
	.string "How do you do?\p"
	.string "Isn't it convenient that we can\n"
	.string "chat like this at a distance?\p"
	.string "Before, if I wanted to speak with\n"
	.string "anyone, I had to have my father\l"
	.string "drive me…\p"
	.string "I should be going now.\n"
	.string "I'm glad we had this chat.$"

MatchCall_PersonalizedText11::
	.string "It's {STR_VAR_1}!\n"
	.string "Will you listen to this?\p"
	.string "I've been trying out a new tactic\n"
	.string "I learned in school yesterday.\p"
	.string "Today, I've beaten three\n"
	.string "Trainers in a row!\p"
	.string "I guess Mom is right, going to\n"
	.string "school really is a good thing!\p"
	.string "You bet I'll be going to\n"
	.string "the Trainer's School tomorrow!\p"
	.string "Anyways, Catch you!$"

MatchCall_PersonalizedText12::
	.string "Hello, {STR_VAR_1} here.\n"
	.string "I have still been unable to\l"
	.string "win a battle!\p"
	.string "I can't shake the feeling that\n"
	.string "this world exists to punish me!\p"
	.string "Well… Be seeing you.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu…\n"
	.string "It's me, {STR_VAR_1}…\p"
	.string "Can you guess what I'm seeing?\n"
	.string "A pair of {STR_VAR_2} in a battle.\p"
	.string "I should make a bet on who wins…\n"
	.string "Or maybe I should try to\l"
	.string "catch the winner…\p"
	.string "Ufufufufufu…\p"
	.string "I… I'm kind of busy now.\n"
	.string "I have to go.$"

MatchCall_PersonalizedText14::
	.string "Oh, it's {STR_VAR_1}!\p"
	.string "I was just thinking its time\n"
	.string "for a work break so I'm glad\l"
	.string "you called.\p"
	.string "Work is such a drag, why\n"
	.string "don't you come see me soon?\p"
	.string "Be seeing you!$"

MatchCall_PersonalizedText15::
	.string "I'm {STR_VAR_1}!\n"
	.string "The man of the sea!\p"
	.string "You know what I think?\p"
	.string "The Trainers out at sea are\n"
	.string "the toughest of the tough!\p"
	.string "You should learn from me and train\n"
	.string "in the sea…\p"
	.string "Whoops, giant surf rising!\p"
	.string "It's a great training opportunity!\n"
	.string "Sorry, but I have to go!$"

MatchCall_PersonalizedText16::
	.string "It's {STR_VAR_1}! Listen, I've been\n"
	.string "teaching karate to my Pokémon.\p"
	.string "But now they're better than me!\n"
	.string "I've done nothing but lose to them!\p"
	.string "But even though I may lose to\n"
	.string "Pokémon, I won't lose to another\l"
	.string "Trainer, no sir!\p"
	.string "We have to battle again!\n"
	.string "Ugwaah!$"

MatchCall_PersonalizedText17::
	.string "It's me, {STR_VAR_1}.\n"
	.string "How're your travels unwinding?\p"
	.string "…Whoa, is that right?\n"
	.string "Sounds awfully stimulating!\p"
	.string "Me and my birds should write a\n"
	.string "song about one of your episodes.\p"
	.string "…Oh, hey, I'm feeling it.\n"
	.string "I hear the riffs in my head.\p"
	.string "I'd better get this tune properly\n"
	.string "written, so I've got to fly! Later!$"

MatchCall_PersonalizedText18::
	.string "This is {STR_VAR_1}…\n"
	.string "Hear my new bird song.\p"
	.string "Lalala, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "Why are you that {STR_VAR_2}?\l"
	.string "Why can't I be you, {STR_VAR_2}?\l"
	.string "Lala, {STR_VAR_2} and {STR_VAR_1},\l"
	.string "{STR_VAR_1} and {STR_VAR_2}…\p"
	.string "Repeat chorus, fade…$"

MatchCall_PersonalizedText19::
	.string "I'm {STR_VAR_1}, you know,\n"
	.string "the camping expert!\p"
	.string "When we battled, I couldn't help\n"
	.string "but lose to you.\p"
	.string "After all, my expertise is in\n"
	.string "camping.\p"
	.string "But win or lose, I like to battle\n"
	.string "when I'm camping.\p"
	.string "Battle with us again, okay?\n"
	.string "Oh, and let's go camping, too!$"

MatchCall_PersonalizedText20::
	.string "This is {STR_VAR_1}.\n"
	.string "Hello.\p"
	.string "I was just telling a new Trainer\n"
	.string "about you.\p"
	.string "I told her about a strong Trainer\n"
	.string "who raises Pokémon with care.\p"
	.string "I hope you'll become a Trainer\n"
	.string "that everyone will admire.\p"
	.string "I hope we meet again!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "It's {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "That's all today…$"

MatchCall_PersonalizedText22::
	.string "This is {STR_VAR_1}. Today, I had\n"
	.string "this feeling I would chat with you.\p"
	.string "My burning desire to defeat you\n"
	.string "builds by day and by night.\p"
	.string "You have a rival like that, yes?\n"
	.string "I wish it were me…\p"
	.string "I'm glad you heard me out.\n"
	.string "See you!$"

MatchCall_PersonalizedText23::
	.string "It's {STR_VAR_1}.\p"
	.string "When there's a strong Trainer\n"
	.string "nearby, I can sometimes sense that\l"
	.string "somehow.\p"
	.string "Did you pass close by, {PLAYER}{KUN}?\n"
	.string "Maybe it was you.\p"
	.string "I'll be waiting for your visit.\n"
	.string "Bye!$"

MatchCall_PersonalizedText24::
	.string "Hello, this is {STR_VAR_1}.\n"
	.string "You sound well, {PLAYER}{KUN}.\p"
	.string "I've traveled around the world,\n"
	.string "but I must say I've taken a great\l"
	.string "shine to this region.\p"
	.string "I plan to stay here a while.\n"
	.string "Perhaps we can meet again?\p"
	.string "I've not forgotten your dazzling\n"
	.string "techniques.\p"
	.string "I do hope for a rematch.$"

MatchCall_PersonalizedText25::
	.string "Hi, it's {STR_VAR_1}!\p"
	.string "I love spending time with\n"
	.string "my bird Pokémon!\p"
	.string "I don't know why anyone would\n"
	.string "choose any other type of Pokémon.\p"
	.string "What's your favourite thing\n"
	.string "about bird Pokémon?\p"
	.string "See you later!$"

MatchCall_PersonalizedText26::
	.string "It's {STR_VAR_1}!\p"
	.string "Trainers constantly come past\n"
	.string "wanting to battle…\p"
	.string "I just don't understand the craze,\n"
	.string "everyone else seems to be into it.\p"
	.string "You like Pokémon battling, don't you?\n"
	.string "Can you explain it to me sometime?\p"
	.string "I'd better go!$"

MatchCall_PersonalizedText27::
	.string "Hi, it's Eli! I'm with my twin\n"
	.string "Anne again today.\p"
	.string "Anne and I really love caring for\n"
	.string "our Pokémon. They're so cute!\p"
	.string "I wish I could look after them\n"
	.string "as if they were my siblings!\p"
	.string "Oh, hi, Anne!\n"
	.string "Did you get the buns?\p"
	.string "Huh? No, no, I'm not treating you\n"
	.string "like my personal slave!\p"
	.string "You lost the match, so you have\n"
	.string "to go buy the bread as punishment!\p"
	.string "I wouldn't treat you like a slave,\n"
	.string "Anne! You're too special to me!\p"
	.string "I have to go now.\n"
	.string "It's time for our snack!$"

MatchCall_PersonalizedText28::
	.string "Hi, {PLAYER}!\n"
	.string "It's {STR_VAR_1}!\p"
	.string "You have to hear this!\n"
	.string "My sweet Pokémon…\p"
	.string "Snort! Wahaha!\n"
	.string "I can't say any more! It's a secret!\l"
	.string "It's just too cute for words!\p"
	.string "Oh, my sweet {STR_VAR_2} is begging\n"
	.string "for a {POKEBLOCK}!\p"
	.string "It's the picture of cuteness!\p"
	.string "Sorry, but I can't talk now!\n"
	.string "You'll have to hear this next time!$"

MatchCall_PersonalizedText29::
	.string "{PLAYER}!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I love the roar my bike makes\n"
	.string "when I rev it loud!\p"
	.string "But, most people take a wide\n"
	.string "berth as they pass by!\p"
	.string "Joke's on them though\n"
	.string "I don't wanna be around people who\l"
	.string "don't love the sound of my bike!\p"
	.string "Well, I must be going.\n"
	.string "Bye, now! Wroooar!$"

MatchCall_PersonalizedText30::
	.string "Hi, cutie!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I was just thinking about all\n"
	.string "the Pokémon I've battled against.\p"
	.string "Your Pokémon are by far the most\n"
	.string "beautiful, not only in appearance\l"
	.string "but in the way they battle too!\n"
	.string "I hope to see you soon!$"

MatchCall_PersonalizedText31::
	.string "It's {STR_VAR_1}.\n"
	.string "I'm glad to chat with you!\p"
	.string "I am feeling alive and refreshed\n"
	.string "against this ocean breeze.\p"
	.string "I've been battling Trainers\n"
	.string "since we met, but you're still\l"
	.string "the best of the lot.\p"
	.string "You should drop by some time.$"

MatchCall_PersonalizedText32::
	.string "Yay! This is {STR_VAR_1}!\n"
	.string "What's up?\p"
	.string "I might be imagining this, but when\n"
	.string "I win battles, my shorts seem to\l"
	.string "feel, like, better. Materially.\p"
	.string "What do I mean by that?\n"
	.string "It's kind of hard to explain, but…\l"
	.string "How would I say this now…\l"
	.string "My shorts feel silkier!\p"
	.string "And when I battled you, {PLAYER}{KUN},\n"
	.string "my shorts felt icky and coarse.\p"
	.string "… … … … … …\n"
	.string "You didn't really believe that?\l"
	.string "Ehehehe, that's all! Bye now!$"

MatchCall_PersonalizedText33::
	.string "Ahoy!\n"
	.string "{STR_VAR_1} here!\p"
	.string "As always, I'm fishing with wild\n"
	.string "abandon!\p"
	.string "Are there other places I can fish\n"
	.string "than the sea and rivers?\p"
	.string "I get these powerful urges to\n"
	.string "fish just about anywhere!\p"
	.string "Oh, gosh, darn it!\n"
	.string "My line's tangled up!\p"
	.string "Gotta go!\n"
	.string "Find me some new fishing spots!$"

MatchCall_PersonalizedText34::
	.string "Hey, there! It's {STR_VAR_1}.\n"
	.string "Are you taking it casually?\p"
	.string "Ever since I was a kid, you know,\n"
	.string "I've always been placid, huh?\p"
	.string "I never was much for getting all\n"
	.string "stressed or rushing things.\p"
	.string "You just can't tell where life will\n"
	.string "take you, if you get my drift.\p"
	.string "You're a Trainer now, but who\n"
	.string "knows what the future holds, huh?\p"
	.string "Imagine yourself as a teacher,\n"
	.string "or maybe an artist. Cool, huh?\p"
	.string "But, hey, be cool. Take it casual.\n"
	.string "See you around.$"

MatchCall_PersonalizedText35::
	.string "This is {STR_VAR_1}!\n"
	.string "I'm on Cycling Road now.\p"
	.string "No one is a rebel like me!\n"
	.string "I just go on my own path!\p"
	.string "Not only with my bike but\n"
	.string "with my approach to life\p"
	.string "That doesn't sound much like a Biker.\n"
	.string "Forget I said that! See you!$"

MatchCall_PersonalizedText36::
	.string "Yo, this is {STR_VAR_1}!\p"
	.string "I just smacked my Bike into\n"
	.string "a damn lamp post!\p"
	.string "Damn, I cannot get used to the\n"
	.string "slopes on Cycling Road! Maybe\l"
	.string "I should go to a different route?\p"
	.string "Nah… What kind of Biker would I\n"
	.string "be then?\p"
	.string "See you later!$"

MatchCall_PersonalizedText37::
	.string "Hi, it's {STR_VAR_1}.\p"
	.string "All these cyclists think they're\n"
	.string "so great with their slim bodies!\p"
	.string "But nothing beats my bod, kiddo!\n"
	.string "Why would you waste all that\l"
	.string "energy when you can have this\l"
	.string "body with no effort at all!\p"
	.string "See you!$"

MatchCall_PersonalizedText38::
	.string "Hey, it's {STR_VAR_1}, hello.\p"
	.string "Us Bikers rule Cycling Road!\n"
	.string "People better not come down here\l"
	.string "or I'll show them what's what!$"

MatchCall_PersonalizedText39::
	.string "Hey, it's {STR_VAR_1}…\n"
	.string "Whoops!\p"
	.string "Splash!\p"
	.string "Blug-blug-blug-blug…\p"
	.string "Sploosh!\p"
	.string "Whiff-whiff! Whiff-whiff!\p"
	.string "Hey! Sorry about that!\n"
	.string "I just put on some suntan oil.\p"
	.string "So my Pokénav went whoopsy\n"
	.string "out of my hand into the water!\p"
	.string "But, boy, this Pokénav is built\n"
	.string "tough. It survived that dunking!\p"
	.string "Anyways, I'm busy sunbathing,\n"
	.string "so let's chat another time.$"

MatchCall_PersonalizedText40::
	.string "Koorukukukoo!\n"
	.string "Hello, this is {STR_VAR_1}.\p"
	.string "I've been practicing my birdcall\n"
	.string "by listening to my Pokémon.\p"
	.string "Do you think I'm getting better?\n"
	.string "Well, anyways, I better get back\l"
	.string "to my practice! Bye!$"

MatchCall_PersonalizedText41::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How are your Pokémon doing?\p"
	.string "My Bird Pokémon appear to be\n"
	.string "in peak form. Bye for now.$"

MatchCall_PersonalizedText42::
	.string "{STR_VAR_1} here.\p"
	.string "My {STR_VAR_2} has grown even more\n"
	.string "tough than that last time.\p"
	.string "I'm not going to lose again to you.\n"
	.string "You wait till next time!\p"
	.string "See you around!$"

MatchCall_PersonalizedText43::
	.string "It is {STR_VAR_1} here.\p"
	.string "There seems to be more people\n"
	.string "getting in my way while I'm riding\l"
	.string "than usual.\p"
	.string "Why won't that guard let them\n"
	.string "through the gate into Saffron!\p"
	.string "How am I suppose to hear my bike\n"
	.string "roar if I have to keep slowing down!\p"
	.string "Farewell!$"

MatchCall_PersonalizedText44::
	.string "This is {STR_VAR_1}.\n"
	.string "I kept up my training since we met.\p"
	.string "My {STR_VAR_2} is getting pretty\n"
	.string "tough.\p"
	.string "Training on the pier is effective,\n"
	.string "just as I thought. Bye now!$"

MatchCall_PersonalizedText45::
	.string "How do you do?\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I wonder when these Bikers will stop\n"
	.string "with this yucky smog?\p"
	.string "They're making my Pokémon cough…\n"
	.string "I wish they would go away!$"

MatchCall_PersonalizedText46::
	.string "Hi, {STR_VAR_1} here.\p"
	.string "Did you know that it's easier to\n"
	.string "float in the sea than a pool?\p"
	.string "Just by lying still, your body will\n"
	.string "float on its own.\p"
	.string "But if you float for too long,\n"
	.string "watch that you don't get carried\l"
	.string "off too far out.\p"
	.string "…Where am I, anyway?\n"
	.string "I'd better go!$"

MatchCall_PersonalizedText47::
	.string "Oh, {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I'm up in the mountains now.\p"
	.string "But the ground is too bumpy.\n"
	.string "I can't pitch my tent here…\p"
	.string "Oh, I had a brilliant idea!\p"
	.string "Maybe I can get my Pokémon to tamp\n"
	.string "the ground flat here!\p"
	.string "I'm going to try that!\n"
	.string "Bye-bye!$"

MatchCall_PersonalizedText48::
	.string "Oh, hi, hi, this is Mya!\p"
	.string "I'm raising Pokémon with Ron!\n"
	.string "We're trying very hard!\p"
	.string "If we try harder, can we become\n"
	.string "number one? Bye-bye!$"

MatchCall_PersonalizedText49::
	.string "{STR_VAR_1} here!\p"
	.string "I train with my Pokémon everyday,\n"
	.string "but I only see small improvements.\p"
	.string "It makes me wonder--maybe\n"
	.string "I should change my strategy?\p"
	.string "That's what I've been thinking\n"
	.string "while staring out across the waves.\p"
	.string "All right, next time!$"

MatchCall_PersonalizedText50::
	.string "It's {STR_VAR_1}.\n"
	.string "So? Get any more Pokémon?\p"
	.string "If you catch a new Pokémon,\n"
	.string "you have to come show me.\p"
	.string "I won't whine for it, honest.\n"
	.string "I'll be waiting. See you.$"

MatchCall_PersonalizedText51::
	.string "This is {STR_VAR_1}.\p"
	.string "Are you raising your Pokémon\n"
	.string "in the optimal way?\p"
	.string "The air is clean where I am.\n"
	.string "It's the perfect environment for\l"
	.string "raising Pokémon.\p"
	.string "If you're going to focus on raising\n"
	.string "Pokémon, you should come out to\l"
	.string "{STR_VAR_2}. Take care now.$"

MatchCall_PersonalizedText52::
	.string "Hi, this is {STR_VAR_1}.\p"
	.string "I gave a {POKEBLOCK} to my {STR_VAR_2}.\n"
	.string "It seemed to enjoy it very much.\p"
	.string "It looks like Pokémon have their\n"
	.string "likes and dislikes with {POKEBLOCK}S.\p"
	.string "I find that quite fascinating.\n"
	.string "Please do take care.$"

MatchCall_PersonalizedText53::
	.string "Hey, It's Mik here.\p"
	.string "If you cooperate with Pokémon,\n"
	.string "one can be comfortable in battle.\p"
	.string "Just like how when Kia and I\n"
	.string "cooperate we become a better duo!\p"
	.string "Everyone should realise that and\n"
	.string "cooperate with Pokémon more.\p"
	.string "That would be ideal.\n"
	.string "I really think so.\p"
	.string "I think you're on the right track!\n"
	.string "Catch you later!$"

MatchCall_PersonalizedText54::
	.string "Hi, it's {STR_VAR_1}. You know,\n"
	.string "the Trainer who's always prepared!\p"
	.string "{PLAYER}{KUN}, do you have enough items?\n"
	.string "Are your Pokémon fit for action?\p"
	.string "Keeping everything perfect around\n"
	.string "you all the time is the secret to\l"
	.string "keeping your journey going.\p"
	.string "I'd better go check my own\n"
	.string "supplies! Be vigilant!$"

MatchCall_PersonalizedText55::
	.string "It's {STR_VAR_1}!\n"
	.string "It's {STR_VAR_1}!\p"
	.string "{STR_VAR_2} is a very busy\n"
	.string "thoroughfare, so I get challenged\l"
	.string "by all kinds of Trainers every day.\p"
	.string "Today, I won five battles and lost\n"
	.string "only three!\p"
	.string "How did you do today?\n"
	.string "Tell me about it next time, okay?$"

MatchCall_PersonalizedText56::
	.string "It's me, {STR_VAR_1}.\p"
	.string "I'm popular because I have lots\n"
	.string "of Bug Pokémon, right?\p"
	.string "Well, I took a bunch of my fave\n"
	.string "bugs to school today.\p"
	.string "This girl I like started crying!\n"
	.string "Go ahead and laugh if you want.\p"
	.string "I have to try teaching her what\n"
	.string "makes Bug Pokémon so appealing.\p"
	.string "Snivel…\n"
	.string "See you!$"

MatchCall_PersonalizedText57::
	.string "Hah! Hah! Hah! Hah!\p"
	.string "Hi! It's {STR_VAR_1}! Hah! Hah!\p"
	.string "These cyclists tried to encroach\n"
	.string "on our turf, so I revved my engine\l"
	.string "to scare them off with the fumes!\l"
	.string "Hah! Hah!\p"
	.string "They said they were on their way\n"
	.string "to the Celadon Dept. Store but who\l"
	.string "believes that!\p"
	.string "Hah! Hah! Hah!$"

MatchCall_PersonalizedText58::
	.string "Oh, hi!\p"
	.string "I'm still searching for treasures\n"
	.string "with Lil!\p"
	.string "Maybe there isn't any treasure\n"
	.string "here at all…\p"
	.string "But the important thing is for me\n"
	.string "to search alongside Lil.\p"
	.string "Oh, hey, Lil!\n"
	.string "Wh-why are you angry?\p"
	.string "No, this isn't about getting\n"
	.string "you to exercise…\p"
	.string "…{PLAYER}, I have to go, bye!$"

MatchCall_PersonalizedText59:: 
	.string "Oh, it's {STR_VAR_1}, hello.\p"
	.string "I've been swimming a lot but I still\n"
	.string "can't seem to reach Seafoam Islands.\p"
	.string "Maybe I'm just going in circles.\p"
	.string "No, no, that can't be possible.\n"
	.string "Wahahaha.\l"
	.string "Take care!$"

MatchCall_PersonalizedText60::
	.string "Hello {PLAYER}!\p"
	.string "Wouldn't it be good if you had\n"
	.string "a partnership like ours?\p"
	.string "Of course, {PLAYER}{KUN}, you already\n"
	.string "enjoy the trust and companionship\l"
	.string "of your Pokémon now.\p"
	.string "You have the makings of long and\n"
	.string "enduring relationships already!\p"
	.string "Hahaha!\n"
	.string "Never be discouraged!$"

MatchCall_PersonalizedText61::
	.string "Hi, this is {STR_VAR_1}!\n"
	.string "We just won a battle!\p"
	.string "We don't win often, but it was this\n"
	.string "cute Tuber boy.\p"
	.string "My sister was steamed!\p"
	.string "She wanted to pretend that she\n"
	.string "was weak to make an impression!\p"
	.string "She always chews me out whether\n"
	.string "we win or lose!\p"
	.string "{PLAYER}{KUN}, can you say something\n"
	.string "to her next time?\p"
	.string "Okay, see you!$"

MatchCall_PersonalizedText62::
	.string "{STR_VAR_1} here, yes.\n"
	.string "I headed out to sea yesterday.\p"
	.string "I had been hoping to find a new\n"
	.string "place I could run!\p"
	.string "But the tides somehow seemed to\n"
	.string "carry me back where I started.\p"
	.string "I'm still weak at battling, too…\n"
	.string "Maybe if I spend less time running\l"
	.string "and more time training, my Pokémon\l"
	.string "would be strong enough so I can\l"
	.string "find a new place to run!\p"
	.string "That's all I have to say!\n"
	.string "Farewell for now!$"

MatchCall_PersonalizedText63::
	.string "Ahoy there!\n"
	.string "It's me, {STR_VAR_1}!\l"
	.string "I'm out on Route 21 now!\l"
	.string "In other words, where I always am!\p"
	.string "Today, a gorgeous Swimmer \n"
	.string "swam by me!\p"
	.string "So I startled her with a shout!\p"
	.string "And she gave me a nasty glare!\p"
	.string "That's all from Route 21!\n"
	.string "Brought to you by {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "It's {STR_VAR_1}!\p"
	.string "I'm kind of busy, but I figured\n"
	.string "I should let you know that I've\l"
	.string "beaten five Trainers again today.\p"
	.string "If I keep this pace up, I can\n"
	.string "probably beat you next time.\p"
	.string "I think we'll be good rivals,\n"
	.string "you and I. Good-bye for now!$"

MatchCall_PersonalizedText65::
	.string "Hey, it's {STR_VAR_1}!\p"
	.string "I was talking to my buddy\n"
	.string "and he was saying the reason\l"
	.string "I only catch Magikarp is\l"
	.string "because of my rod!\p"
	.string "But I could never part with\n"
	.string "my trusty fishing pole!\l"
	.string "I'm sure if we work hard enough\n"
	.string "I'll catch a strong Pokémon!\p"
	.string "Good-bye for now!$"

MatchCall_PersonalizedText66::
	.string "It's me, the mountain-loving\n"
	.string "{STR_VAR_1}!\p"
	.string "Well, since we met, have you grown\n"
	.string "to appreciate the mountains more?\p"
	.string "I rarely see you in the mountains…\p"
	.string "Next time, we'll meet somewhere\n"
	.string "around {STR_VAR_2}.$"

MatchCall_PersonalizedText67::
	.string "Hello, this is {STR_VAR_1}.\p"
	.string "I just love swimming!\n"
	.string "But if I stay in the sea too long,\l"
	.string "won't I get all prune-like?\p"
	.string "Ooh, swimming is such a grueling\n"
	.string "test of human endurance! Bye!$"

MatchCall_PersonalizedText68::
	.string "Ufufufufu…\n"
	.string "It's me, {STR_VAR_1}…\p"
	.string "Can you guess what I'm seeing?\n"
	.string "A pair of {STR_VAR_2} in a battle.\p"
	.string "Maybe I'll try catching the winner…\n"
	.string "Ufufufufufu…\p"
	.string "I… I'm kind of busy now.\n"
	.string "I have to go.$"

MatchCall_PersonalizedText69::
	.string "Hello! Thirty years of exploration,\n"
	.string "{STR_VAR_1} at your service!\p"
	.string "It seems that you're energetically\n"
	.string "traveling here and there.\p"
	.string "Have you discovered any new ruins?\n"
	.string "Please tell if you have!\p"
	.string "Now, if you'll excuse me,\n"
	.string "I have ruins to explore.$"

MatchCall_PersonalizedText70::
	.string "It's {STR_VAR_1}.\p"
	.string "When there's a strong Trainer\n"
	.string "nearby, I can sometimes sense that\l"
	.string "somehow.\p"
	.string "Did you pass close by, {PLAYER}{KUN}?\n"
	.string "Maybe it was you.\p"
	.string "I'll be waiting for your visit.\n"
	.string "Bye!$"

MatchCall_PersonalizedText71::
	.string "Hi, {STR_VAR_1} here.\p"
	.string "Did you know that it's easier to\n"
	.string "float in the sea than a pool?\p"
	.string "Just by lying still, your body will\n"
	.string "float on its own.\p"
	.string "But if you float for too long,\n"
	.string "watch that you don't get carried\l"
	.string "off too far out.\p"
	.string "…Where am I, anyway?\n"
	.string "I'd better go!$"

MatchCall_PersonalizedText72::
	.string "Hey, {PLAYER}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I usually get drawn to different\n"
	.string "places that emit strange\l"
	.string "Psychic energies!\p"
	.string "But my intuition tells me it's\n"
	.string "not yet time to leave this place!\p"
	.string "I wonder what are the mysteries\n"
	.string "of Seven Island!\p"
	.string "Goodbye!$"

MatchCall_PersonalizedText73::
	.string "Hey, it's {STR_VAR_1}.\p"
	.string "I sense that strong Trainers\n"
	.string "from all around will gather\l"
	.string "here at Seven Island!\p"
	.string "That's why I'm here, {PLAYER}!\n"
	.string "I'm not gonna miss this for\l"
	.string "anything... whatever it will be!\p"
	.string "I'm sure a strong Trainer like you\n"
	.string "will be here for it.\p"
	.string "I'll see you then!\n"
	.string "Bye!$"

MatchCall_PersonalizedText74::
	.string "Hello, {PLAYER}!\n"
	.string "This is {STR_VAR_1}.\p"
	.string "A strong Trainer like you\n"
	.string "must have a fan club!\p"
	.string "My fan club hasn't had\n"
	.string "anyone new join in a while.\p"
	.string "I wonder what I should do\n"
	.string "to get more members?\p"
	.string "What do you do to get more fans?\n"
	.string "Let me know next time you visit!\p"
	.string "Bye!$"

MatchCall_PersonalizedText75::
	.string "This is {STR_VAR_1}.\n"
	.string "Hello.\p"
	.string "I was just telling a new Trainer\n"
	.string "about you.\p"
	.string "I told her about a strong Trainer\n"
	.string "who raises Pokémon with care.\p"
	.string "I hope you'll become a Trainer\n"
	.string "that everyone will admire.\p"
	.string "I hope we meet again!$"

MatchCall_PersonalizedText76::
	.string "Hi, it's {STR_VAR_1}. You know,\n"
	.string "the Trainer who's always prepared!\p"
	.string "{PLAYER}{KUN}, do you have enough items?\n"
	.string "Are your Pokémon fit for action?\p"
	.string "Keeping everything perfect around\n"
	.string "you all the time is the secret to\l"
	.string "keeping your journey going.\p"
	.string "I'd better go check my own\n"
	.string "supplies! Be vigilant!$"

MatchCall_PersonalizedText77::
	.string "Hey {PLAYER}, it's {STR_VAR_1}!\p"
	.string "My Pokémon partner and I have\n"
	.string "been healing passerby's Pokémon!\p"
	.string "Are your Pokémon fit for action?\p"
	.string "You should always make sure they\n"
	.string "are ready for battle while\l"
	.string "on your journey!\p"
	.string "I'd better go check my own\n"
	.string "Pokémon! Be prepared!$"

MatchCall_PersonalizedText78::
	.string "It's {STR_VAR_1}!\p"
	.string "I'm kind of busy, but I figured\n"
	.string "I should let you know that I've\l"
	.string "beaten five Trainers again today.\p"
	.string "If I keep this pace up, I can\n"
	.string "probably beat you next time.\p"
	.string "I think we'll be good rivals,\n"
	.string "you and I. Good-bye for now!$"

MatchCall_PersonalizedText79::
	.string "Yahoo, it's {STR_VAR_1}!\n"
	.string "How do you do?\p"
	.string "I've been raising my Pokémon with\n"
	.string "you as the target.\p"
	.string "I don't intend to lose when we\n"
	.string "battle again.\p"
	.string "Isn't it great to have Trainer\n"
	.string "friends? Let's meet again!$"

MatchCall_BattleFrontierStreakText1::
	.string "Hi! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you did excellent at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It's awesome, {STR_VAR_3} straight wins?\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That's special! I should try\n"
	.string "harder, too! See you!$"

MatchCall_BattleFrontierStreakText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That is a big record, isn't it?\p"
	.string "I'd better get it together, too!\n"
	.string "Catch you soon!$"

MatchCall_BattleFrontierStreakText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. What's up?\p"
	.string "There's a rumour going around that\n"
	.string "you strung together {STR_VAR_3} straight\l"
	.string "wins at the {STR_VAR_2}.\p"
	.string "I'd better step it up, too.\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn't that something!\p"
	.string "I'd better work on my Pokémon more.\n"
	.string "See you soon!$"

MatchCall_BattleFrontierStreakText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you pulled off\n"
	.string "the feat of {STR_VAR_3} straight wins at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That inspires me to focus on\n"
	.string "raising my team.$"

MatchCall_BattleFrontierStreakText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, yeah, you were over at\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "And you won {STR_VAR_3} battles in a row.\p"
	.string "Oh, there goes a rare Pokémon!\n"
	.string "I have to go!$"

MatchCall_BattleFrontierStreakText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\p"
	.string "Oh, but, you are. I've heard that\n"
	.string "you won {STR_VAR_3} matches in a row at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That's very impressive!\n"
	.string "I hope you stay successful.$"

MatchCall_BattleFrontierStreakText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! Your {STR_VAR_3}-win streak at\n"
	.string "the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleFrontierStreakText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight battles at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} matches in\n"
	.string "a row?\p"
	.string "You're good, you.\n"
	.string "I wonder how many I can win?$"

MatchCall_BattleFrontierStreakText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "Someone passed on word about you.\n"
	.string "How you won {STR_VAR_3} straight battles\l"
	.string "at a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleFrontierStreakText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I heard about you!\n"
	.string "Didn't you just win {STR_VAR_3} battles in\l"
	.string "a row at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "Bye-bye!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Hi! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you did excellent at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It's awesome--{STR_VAR_3} straight wins?\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That's special! I should try\n"
	.string "harder, too! See you!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That is a big record, isn't it?\p"
	.string "I'd better get it together, too!\n"
	.string "Catch you soon!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. What's up?\p"
	.string "There's a rumour going around that\n"
	.string "you strung together {STR_VAR_3} straight\l"
	.string "wins at the {STR_VAR_2}.\p"
	.string "I'd better step it up, too.\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn't that something!\p"
	.string "Me? I'd say I'm coming along.\n"
	.string "See you soon!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you pulled off\n"
	.string "the feat of {STR_VAR_3} straight wins at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I'd better try harder myself!\n"
	.string "See you soon!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, yeah, you were over at\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "And you won {STR_VAR_3} battles in a row.\p"
	.string "Oh, there goes a rare Pokémon!\n"
	.string "I have to go!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\p"
	.string "Oh, but, you are. I've heard that\n"
	.string "you won {STR_VAR_3} matches in a row at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That's very impressive!\n"
	.string "I'd better work on my Pokémon, too!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! Your {STR_VAR_3}-win streak at\n"
	.string "the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight battles at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} matches in\n"
	.string "a row?\p"
	.string "You're good, you.\n"
	.string "I wonder how many I can win?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "Someone passed on word about you.\n"
	.string "How you won {STR_VAR_3} straight battles\l"
	.string "at a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you just win {STR_VAR_3} battles in\n"
	.string "a row at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "Bye-bye!$"

MatchCall_BattleDomeText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You became the champion at\n"
	.string "the {STR_VAR_2} {STR_VAR_3} times?\p"
	.string "It's awesome! I have to do better!\n"
	.string "See you!$"

MatchCall_BattleDomeText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}.\p"
	.string "That's super! I wonder if I can\n"
	.string "become a champion?$"

MatchCall_BattleDomeText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you won events {STR_VAR_3} times\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Make it one more next time!\n"
	.string "Catch you soon!$"

MatchCall_BattleDomeText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you became the champion\n"
	.string "at the {STR_VAR_2} {STR_VAR_3} times.\p"
	.string "Sounds like you're working hard.\n"
	.string "I'll try to keep up!$"

MatchCall_BattleDomeText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you won {STR_VAR_3} times\n"
	.string "outright at the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattleDomeText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you became\n"
	.string "the champion {STR_VAR_3} times at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I'd better raise my Pokémon before\n"
	.string "you pull farther ahead.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and became the champ {STR_VAR_3} times?\p"
	.string "That's neat. By the way, have you\n"
	.string "caught any rare Pokémon lately?\p"
	.string "Oh, is that right.\n"
	.string "Okay, bye.$"

MatchCall_BattleDomeText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you won {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I must raise my Pokémon like you.\n"
	.string "See you again.$"

MatchCall_BattleDomeText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You took the title\n"
	.string "{STR_VAR_3} times at the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleDomeText10::
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight times at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleDomeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} straight times\n"
	.string "now?\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattleDomeText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won {STR_VAR_3} events at a place\n"
	.string "named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleDomeText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} events\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleDomeText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you win {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_BattlePikeText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You got through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}!\p"
	.string "That's awesome!\n"
	.string "See you!$"

MatchCall_BattlePikeText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won your way through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "I have to try much harder!\n"
	.string "Bye!$"

MatchCall_BattlePikeText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you won through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Try to do even better next time!\n"
	.string "Catch you soon!$"

MatchCall_BattlePikeText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you blew through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I'd better train my Pokémon and\n"
	.string "try to keep up!$"

MatchCall_BattlePikeText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you got past {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattlePikeText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "I'd better raise my Pokémon before\n"
	.string "you pull further ahead.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way past {STR_VAR_3} rooms?\p"
	.string "That's wicked.\p"
	.string "Oh, there goes a rare Pokémon!\n"
	.string "Okay, bye.$"

MatchCall_BattlePikeText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you got through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "That's quite impressive!\n"
	.string "I must raise my Pokémon like you.\l"
	.string "See you again.$"

MatchCall_BattlePikeText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattlePikeText10::
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won your way past {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattlePikeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You got through, what, {STR_VAR_3} rooms?\n"
	.string "That's gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattlePikeText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won through {STR_VAR_3} rooms at\n"
	.string "a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattlePikeText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won in {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattlePikeText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you get through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_BattlePyramidText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "That's awesome!\n"
	.string "I should try that challenge.$"

MatchCall_BattlePyramidText2::
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "Wow, that's fantastic!\n"
	.string "I'd better raise my Pokémon, too!$"

MatchCall_BattlePyramidText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}!\p"
	.string "Try to do even better next time!\n"
	.string "Catch you soon!$"

MatchCall_BattlePyramidText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you scaled {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}.\p"
	.string "I'd better work hard and try\n"
	.string "to keep up!$"

MatchCall_BattlePyramidText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattlePyramidText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "I'd better raise my Pokémon before\n"
	.string "you pull further ahead.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way up {STR_VAR_3} floors?\p"
	.string "Neat. Were there any rare Pokémon\n"
	.string "there?\p"
	.string "No, huh?\n"
	.string "Okay, bye.$"

MatchCall_BattlePyramidText8::
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "That's quite impressive!\n"
	.string "I must raise my Pokémon like you.\l"
	.string "See you again.$"

MatchCall_BattlePyramidText9::
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattlePyramidText10::
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattlePyramidText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You rose through, what, {STR_VAR_3} floors?\n"
	.string "That's gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattlePyramidText12::
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won through {STR_VAR_3} floors in\n"
	.string "a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattlePyramidText13::
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattlePyramidText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you get through {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_Text_Mom1::
	.string "Mom: Your father and you…\n"
	.string "Everyone is captivated by Pokémon.\p"
	.string "What is the charm of Pokémon?\p"
	.string "Me?\n"
	.string "I adore Pokémon that help me with\l"
	.string "my everyday chores.$"

MatchCall_Text_Mom2::
	.string "Mom: Hi, {PLAYER}!\n"
	.string "How are your travels?\l"
	.string "Have you been eating properly and\l"
	.string "sleeping enough?\p"
	.string "You must be doing well,\n"
	.string "Professor Oak has been bouncing\l"
	.string "around town, praising the efforts\l"
	.string "of {RIVAL} and yourself!\p"
	.string "Well, I'm sure you want to get back\n"
	.string "to your adventures.\p"
	.string "Keep in touch {PLAYER}. Bye.$"

MatchCall_Text_Mom3::
	.string "Mom: {PLAYER}…\n"
	.string "Don't worry about me or the house.\p"
	.string "Wear those Running Shoes until\n"
	.string "they fall apart, honey!$"

MatchCall_Text_Brock1::
	.string "Brock: Oh, hello, {PLAYER}!\p"
	.string "I've been hard at work retraining\n"
	.string "since we met.\p"
	.string "I will still need some more time\n"
	.string "before I can reopen the gym.\p"
	.string "But when I do, please visit my gym\n"
	.string "for a rematch!$"

MatchCall_Text_Brock2::
	.string "Brock: Is this {PLAYER}?\n"
	.string "Congratulations!\l"
	.string "I've been hearing about you!\p"
	.string "As for me, I need some more time\n"
	.string "before I can reopen the gym.\p"
	.string "But when I do, please visit my gym\n"
	.string "for a rematch!$"

MatchCall_Text_Brock3::
	.string "Brock: {PLAYER}!\n"
	.string "My gym is ready!\p"
	.string "Please visit Pewter whenever\n"
	.string "you can!$"

MatchCall_Text_Brock4::
	.string "Brock: At the Pewter Gym,\n"
	.string "the fact that we battled, {PLAYER},\l"
	.string "is a matter of pride.$"

MatchCall_Text_Misty1::
	.string "Misty: Hey, there, {PLAYER}{KUN}!\p"
	.string "I learned a lot from the battle we\n"
	.string "had together.\p"
	.string "I intend to do my training over,\n"
	.string "then reopen the gym.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the gym again.\p"
	.string "But if I can reopen the gym,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Misty2::
	.string "Misty: Hey, {PLAYER}{KUN}!\n"
	.string "Congratulations!\p"
	.string "Word about your exploits is\n"
	.string "spreading wide!\p"
	.string "It appears as if I need to work on\n"
	.string "my training some more.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the gym again.\p"
	.string "But if I can reopen the gym,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Misty3::
	.string "Misty: Hey, {PLAYER}{KUN}!\n"
	.string "My gym's ready for action!\p"
	.string "Come back to Cerulean anytime\n"
	.string "for another challenge!$"

MatchCall_Text_Misty4::
	.string "Misty: {PLAYER}{KUN}, I don't think\n"
	.string "I'll ever get bored of battling you!$"

MatchCall_Text_LtSurge1::
	.string "Lt. Surge: Hey, kid!\p"
	.string "After you left, I've been redoing\n"
	.string "my training from scratch.\p"
	.string "I'm gonna need more\n"
	.string "time to reopen my gym.\p"
	.string "You'll have to wait till then!$"

MatchCall_Text_LtSurge2::
	.string "Lt. Surge: Hey, kid!\p"
	.string "You've really done it, haven't you?\n"
	.string "I've been getting word about you!\p"
	.string "It seems I need to retrain some\n"
	.string "more still.\p"
	.string "I'm gonna need more\n"
	.string "time to reopen my gym.\p"
	.string "You'll have to wait till then!$"

MatchCall_Text_LtSurge3::
	.string "Lt. Surge: Hey, kid!\n"
	.string "My gym's ready!\p"
	.string "Visit Vermilion anytime\n"
	.string "and show me your power!$"

MatchCall_Text_LtSurge4::
	.string "Lt. Surge: Hey, kid!\p"
	.string "A battle with you is always charged\n"
	.string "with shocking power!$"

MatchCall_Text_Erika1::
	.string "Erika: {PLAYER}…\p"
	.string "When we battled, I learned exactly\n"
	.string "how laid-back I took my training.\p"
	.string "But I'm not done yet!\p"
	.string "I'm going to redo my training and\n"
	.string "reopen the gym.\p"
	.string "When the time comes, {PLAYER},\n"
	.string "please challenge us again.$"

MatchCall_Text_Erika2::
	.string "Erika: Hello, {PLAYER}?\n"
	.string "Congratulations!\p"
	.string "Word of your success has reached\n"
	.string "us like the leaves in the wind!\p"
	.string "Our training is coming along very\n"
	.string "well here.\p"
	.string "When the gym's ready, a mark will\n"
	.string "appear beside my name in the\l"
	.string "Match Call list.$"

MatchCall_Text_Erika3::
	.string "Erika: Oh, {PLAYER}?\n"
	.string "Our gym's ready!\p"
	.string "Come to Celadon next time\n"
	.string "you want to challenge!$"

MatchCall_Text_Erika4::
	.string "Erika: {PLAYER}…\n"
	.string "The way you battle…\p"
	.string "So ferocious, yet always\n"
	.string "perfectly calm and in control…\p"
	.string "It's inspirational.$"

MatchCall_Text_Koga1::
	.string "Koga: Hello, {PLAYER}!\p"
	.string "Thanks to our battle, I've come\n"
	.string "to understand my weak points!\p"
	.string "When I reopen the gym, I won't go\n"
	.string "down in defeat again!$"

MatchCall_Text_Koga2::
	.string "Koga: You've done it, {PLAYER}!\p"
	.string "News about the new Champion\n"
	.string "has reached even us in Fuchsia!\p"
	.string "But… The next time we battle,\n"
	.string "it's not going to end the same way.$"

MatchCall_Text_Koga3::
	.string "Koga: Is this {PLAYER}?\n"
	.string "Our gym is back in operation!\p"
	.string "Us ninjas are waiting for\n"
	.string "you in Fuchsia!$"

MatchCall_Text_Koga4::
	.string "Koga: …You amaze me, {PLAYER}.\n"
	.string "How much higher will you rise?$"

MatchCall_Text_Sabrina1::
	.string "Sabrina: Hello, {PLAYER}!\p"
	.string "Thanks to our battle, I've come\n"
	.string "to appreciate the art of battling!\p"
	.string "When I reopen the Gym, I wish to\n"
	.string "re-battle you again!$"

MatchCall_Text_Sabrina2::
	.string "Sabrina: You've done it, {PLAYER}!\p"
	.string "Saffron is buzzing with the news\n"
	.string "about you becoming the new Champion!\p"
	.string "But… The next time we battle,\n"
	.string "it's not going to end the same way.$"

MatchCall_Text_Sabrina3::
	.string "Sabrina: Is this {PLAYER}?\n"
	.string "Our Gym is back in operation!\p"
	.string "You must come back to Saffron!$"

MatchCall_Text_Sabrina4::
	.string "Sabrina: {PLAYER}, the battle we\n"
	.string "had is an invaluable experience.\p"
	.string "It would be nice if we could\n"
	.string "battle again!$"

MatchCall_Text_Blaine1::
	.string "Blaine: Oh! You're {PLAYER}!\p"
	.string "We're in training again so we\n"
	.string "can reopen our Gym!\p"
	.string "When our Gym is ready a mark\n"
	.string "will appear by my name on\l"
	.string "the Match Call list.$"

MatchCall_Text_Blaine2::
	.string "Blaine: Hello, {PLAYER}?\n"
	.string "Congratulations!\p"
	.string "Word of your success has reached\n"
	.string "us like the heat of a volcano!\p"
	.string "Our training is coming along very\n"
	.string "well here.\p"
	.string "When the Gym's ready, a mark will\n"
	.string "appear beside my name in the\l"
	.string "Match Call list.$"

MatchCall_Text_Blaine3::
	.string "Blaine: Hah! {PLAYER}{KUN}!\n"
	.string "You've finally achieved your goal.\p"
	.string "My eye for appraising talent wasn't\n"
	.string "mistaken…\p"
	.string "I wish for another chance to meet\n"
	.string "you, for you have scaled the peak\l"
	.string "of power and prestige.$"

MatchCall_Text_Blaine4::
	.string "Blaine: {PLAYER}, the battle we had…\n"
	.string "Is an invaluable experience.\p"
	.string "It would be nice if we could\n"
	.string "battle again!$"

MatchCall_Text_Lorelei::
	.string "Lorelei: Hello, {PLAYER}.\p"
	.string "I trust you haven't become\n"
	.string "complacent with your power?\p"
	.string "If you feel the need to cool your\n"
	.string "hot emotions just a little, do come\l"
	.string "to the Pokémon League…$"

MatchCall_Text_Bruno::
	.string "Bruno: Yo, {PLAYER}!\p"
	.string "If you want to battle with me\n"
	.string "again, you come on back whenever\l"
	.string "you like to the Pokémon League.\p"
	.string "I'll always be here!\n"
	.string "I'll be waiting!$"

MatchCall_Text_Agatha::
	.string "Agatha: Hi, {PLAYER}!\p"
	.string "How about coming back here again\n"
	.string "sometime?\p"
	.string "I'd like to see how much tighter\n"
	.string "your bond has grown with your\l"
	.string "Pokémon.$"

MatchCall_Text_Lance::
	.string "Lance: That voice… {PLAYER}, is it?\n"
	.string "You sound well…\p"
	.string "I understand that there is now\n"
	.string "a facility called the Battle\l"
	.string "Frontier that tests the skills of\l"
	.string "Trainers.\p"
	.string "However, if you wish to have real\n"
	.string "battles, there is no substitute for\l"
	.string "the Pokémon League!\p"
	.string "Don't you agree, {PLAYER}?$"

MatchCall_Text_Daisy1::
	.string "Daisy: Oh? {PLAYER}{KUN}!\p"
	.string "How are your Pokémon?\n"
	.string "If they are in need of a massage,\l"
	.string "just come past for a visit!\p"
	.string "See you soon!$"

MatchCall_Text_Rival1::
	.string "{RIVAL}: Hey, It's {PLAYER}{KUN}!\p"
	.string "Are you still plodding behind\n"
	.string "as usual?\p"
	.string "I've headed for Vermilion City for\n"
	.string "a party on the famous S.S. Anne.\p"
	.string "Don't bother coming though,\n"
	.string "it's by invitation only for\l"
	.string "important people like me!\p"
	.string "Smell ya later!$"

MatchCall_Text_Rival2::
	.string "{RIVAL}: {PLAYER}{KUN}!\p"
	.string "Don't tell me you got lost\n"
	.string "after Vermilion City?\p"
	.string "That Pokémon only blocked one of\n"
	.string "the ways to Lavender Town!\p"
	.string "Every REAL Pokémon Trainer knows\n"
	.string "the path through Rock Tunnel.\p"
	.string "You get there by taking Route 9,\n"
	.string "just past Cerulean City.\p"
	.string "It's embarrassing that my rival\n"
	.string "is this incompetent of a Trainer!\p"
	.string "Smell ya, {PLAYER}!$"

MatchCall_Text_Rival3::
	.string "{RIVAL}: Hi, {PLAYER}{KUN}!\p"
	.string "I hope your not falling too\n"
	.string "far behind now!\p"
	.string "I've caught so many new strong\n"
	.string "Pokémon to add to my team!\p"
	.string "No one will stand a chance\n"
	.string "against me now!\p"
	.string "Smell ya!$"

MatchCall_Text_Rival4::
	.string "{RIVAL}: {PLAYER}{KUN}?\p"
	.string "Have you been to the Safari Zone yet?\n"
	.string "It's full of strong Pokémon to help\l"
	.string "strengthen your team!\p"
	.string "You'll definitely need to visit\n"
	.string "to stand a chance against me!\p"
	.string "Smell ya later!$"

MatchCall_Text_Rival5::
	.string "{RIVAL}: Hey, {PLAYER}{KUN}!\p"
	.string "Have you noticed the large amount\n"
	.string "of Rocket Grunts hanging around\l"
	.string "Saffron City?\p"
	.string "I don't understand how they can\n"
	.string "cause so much trouble with such\l"
	.string "weak Trainers\p"
	.string "Although, I have heard Boss Rocket\n"
	.string "is an incredibly strong Trainer!\p"
	.string "Anyways, smell ya, {PLAYER}!$"

MatchCall_Text_Rival6::
	.string "{RIVAL}: … … …{PLAYER}{KUN}?\n"
	.string "Is that you?\p"
	.string "I can't quite hear you against\n"
	.string "the sea winds!\p"
	.string "I'm on my way to Cinnabar Island.\n"
	.string "You just Surf from Fuchsia City.\p"
	.string "Don't fall too far behind now {PLAYER}!\n"
	.string "Smell ya later!$"

MatchCall_Text_Rival7::
	.string "{RIVAL}: {PLAYER}{KUN}?\p"
	.string "Why are you bothering me?\p"
	.string "I'm busy training my Pokémon and\n"
	.string "filling up my Pokédex for Gramps!\p"
	.string "You should be doing the same\n"
	.string "if you want to keep up with me!\p"
	.string "Smell ya later, {PLAYER}!$"

MatchCall_Text_Rival8::
	.string "{RIVAL}: {PLAYER}{KUN}!\p"
	.string "What are you dawdling around for?\n"
	.string "Have you not heard?\p"
	.string "The Viridian Gym Leader\n"
	.string "has returned!\p"
	.string "It means the Viridian Gym can\n"
	.string "be challenged again!\p"
	.string "How do you expect to be great like\n"
	.string "me if you don't pay attention!\p"
	.string "You better hurry to get the badge\n"
	.string "before the Leader leaves again!\p"
	.string "Smell ya later!$"

MatchCall_Text_Rival9::
	.string "{RIVAL}: {PLAYER}{KUN}?\p"
	.string "I heard you defeated all eight Gyms?\n"
	.string "I must say, I'm surprised someone\l"
	.string "at your level managed such a thing!\p"
	.string "Some of my talent must have finally\n"
	.string "rubbed off on you!\p"
	.string "I'm off to the Pokemon League to\n"
	.string "prove I'm the greatest Trainer,\l"
	.string "the Pokémon Champion!\p"
	.string "Maybe you should avoid the\n"
	.string "Pokémon League.\p"
	.string "The Trainers here are way too strong\n"
	.string "for someone at your level!\p"
	.string "Smell ya later, {PLAYER}!$"

MatchCall_Text_Rival10::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Hmm… … …\n"
	.string "{RIVAL} didn't answer the Pokénav.$"

MatchCall_Text_Scott1::
	.string "Scott: Howdy, {PLAYER}{KUN}!\p"
	.string "You know how Pokémon can be found\n"
	.string "everywhere?\p"
	.string "Like in the mountains, in the sea,\n"
	.string "in tall grass anywhere?\p"
	.string "Just like Pokémon, you can find\n"
	.string "Trainers everywhere, too.\p"
	.string "As a result, I have to hurry\n"
	.string "everywhere, too. Busy, busy!$"

MatchCall_Text_Scott2::
	.string "Scott: I'm on Route 119 right now.\n"
	.string "It's teeming with Trainers!\p"
	.string "It's also overgrown with tall grass\n"
	.string "everywhere, it seems.\p"
	.string "Walking around in shorts here\n"
	.string "makes me all ticklish!$"

MatchCall_Text_Scott3::
	.string "Scott: Hi, hi, {PLAYER}{KUN}!\p"
	.string "Have you had the chance to climb\n"
	.string "Mt. Pyre?\p"
	.string "The place is a memorial to Pokémon\n"
	.string "that have passed away.\p"
	.string "It's somewhere every Trainer\n"
	.string "should climb to the top of once.$"

MatchCall_Text_Scott4::
	.string "Scott: Hi, {PLAYER}{KUN}!\p"
	.string "I've been hearing about these odd\n"
	.string "gangs being a nuisance.\p"
	.string "Team Magma and Team Aqua,\n"
	.string "I think they were.\p"
	.string "I would think there'd be some\n"
	.string "skilled Trainers among them.\p"
	.string "…But if they're thugs…$"

MatchCall_Text_Scott5::
	.string "Scott: Oh, hi, {PLAYER}{KUN}.\p"
	.string "Might there be tough Trainers\n"
	.string "at the bottom of the sea?\p"
	.string "I can't go check for myself.\n"
	.string "I can't swim, for one.\l"
	.string "And I don't raise Pokémon…$"

MatchCall_Text_Scott6::
	.string "Scott: Hi, hi, {PLAYER}{KUN}!\p"
	.string "You know that you can challenge\n"
	.string "the Pokémon League when you've\l"
	.string "collected all the Gym Badges?\p"
	.string "With your talent, becoming the\n"
	.string "Champion isn't a pipe dream.\p"
	.string "But did you know?\n"
	.string "There's somewhere even better.\p"
	.string "But, that's all I'm willing to say\n"
	.string "for the time being.\p"
	.string "It's something you can look\n"
	.string "forward to.\p"
	.string "When you've won your way through\n"
	.string "the Pokémon League into the Hall\l"
	.string "of Fame!$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Scott appears to be out of\n"
	.string "the Pokénav's service area…$"

MatchCall_Text_Norman1::
	.string "DAD: In RUSTBORO, there's a man\n"
	.string "that goes by the odd name of\l"
	.string "the CUTTER.\p"
	.string "If you're in the area, you should\n"
	.string "pay him a visit.$"

MatchCall_Text_Norman2::
	.string "DAD: Hm… Little by little, but also\n"
	.string "very surely, you're getting\l"
	.string "tougher, {PLAYER}.\p"
	.string "The stronger you get, the farther\n"
	.string "and higher you soar from Mother\l"
	.string "and me…\p"
	.string "This feeling is hard to explain.$"

MatchCall_Text_Norman3::
	.string "DAD: I see…\n"
	.string "You've collected four GYM BADGES…\p"
	.string "There's no avoiding it now.\n"
	.string "We will battle like I promised.\p"
	.string "Come anytime.\n"
	.string "We'll all be waiting for you!$"

MatchCall_Text_Norman4::
	.string "DAD: {PLAYER}! You'd better go visit\n"
	.string "Mother every so often.\p"
	.string "I'm going to remain here and\n"
	.string "redouble my training.\p"
	.string "The way of battling is deep\n"
	.string "and unforgiving!$"

MatchCall_Text_Norman5::
	.string "DAD: Oh, hi, {PLAYER}!\p"
	.string "What's that? MAGMA EMBLEM?\n"
	.string "I don't know what that's about.\p"
	.string "But with a name like that, it may\n"
	.string "be somehow linked to a volcano!$"

MatchCall_Text_Norman6::
	.string "DAD: Hiyah! Haah! Dwah!\p"
	.string "…Oh? {PLAYER}!\p"
	.string "You caught me right in the middle\n"
	.string "of a POKéMON training session!$"

MatchCall_Text_Norman7::
	.string "DAD: {PLAYER}!\p"
	.string "Who would've thought you'd become\n"
	.string "the POKéMON LEAGUE CHAMPION…\p"
	.string "Okay!\n"
	.string "I won't be left behind!$"

MatchCall_Text_Norman8::
	.string "DAD: Hm? {PLAYER}?\n"
	.string "What good timing!\p"
	.string "This time, I'm going to challenge\n"
	.string "you to battle.\p"
	.string "I'm waiting in the PETALBURG GYM.\n"
	.string "Accept my challenge anytime!$"

MatchCall_Text_Norman9::
	.string "DAD: …You amaze me, {PLAYER}.\n"
	.string "How much higher will you soar?$"

MatchCall_Text_Steven1::
	.string "Steven: Hi, {PLAYER}{KUN}!\p"
	.string "Have you been to Mauville\n"
	.string "already?\p"
	.string "You should visit the Bike Shop\n"
	.string "and get a Mach Bike.\p"
	.string "Then, try exploring the Granite\n"
	.string "Cave thoroughly.\p"
	.string "You may make a new discovery\n"
	.string "there.$"

MatchCall_Text_Steven2:: @ 82B5C53
	.string "Steven: Hi, {PLAYER}{KUN}!\p"
	.string "I've met a lot of different\n"
	.string "Trainers so far.\p"
	.string "But you're one of a kind.\n"
	.string "You're not like anyone else.$"

MatchCall_Text_Steven3:: @ 82B5CC9
	.string "Steven: Hi, {PLAYER}{KUN}!\p"
	.string "When you're on an adventure with\n"
	.string "your Pokémon, what do you think?\p"
	.string "Do you consider them to be strong\n"
	.string "partners?\p"
	.string "Do you think of them as fun\n"
	.string "companions?\p"
	.string "Depending on how you think, your\n"
	.string "adventure's significance changes.$"

MatchCall_Text_Steven4:: @ 82B5DB4
	.string "Steven: Hello?\n"
	.string "{PLAYER}{KUN}?\p"
	.string "I'm involved in a spot of trouble\n"
	.string "at the Space Center.\p"
	.string "I'm sorry, but I can't talk now.\n"
	.string "Bye!$"

MatchCall_Text_Steven5:: @ 82B5E26
	.string "Steven: Oh!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "There's no need to talk.\n"
	.string "It's past time for talking.\p"
	.string "You have to believe in yourself\n"
	.string "and do what's right.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "Steven appears not to be getting\n"
	.string "the call…$"

MatchCall_Text_Steven7:: @ 82B5ED9
	.string "Steven: {PLAYER}{KUN}… Congratulations\n"
	.string "for entering the Hall of Fame.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "I hope we can meet again\n"
	.string "somewhere!$"
