MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "This move can be learned only\n"
	.string "once. Is that okay?$"

MoveTutor_Text_DreamEaterTeach::
    .string "Yawn!\n"
    .string "I must have dozed off in the sun.\p"
    .string "I had this weird dream about\n"
    .string "a Drowzee eating my dream.\p"
    .string "And…\n"
    .string "I learned how to eat dreams…\p"
    .string "Oogh, this is too spooky!\p"
    .string "Let me teach it to a Pokémon so\n"
    .string "I can forget about it!$"

MoveTutor_Text_DreamEaterDeclined::
    .string "…Snore…$"

MoveTutor_Text_DreamEaterWhichMon::
    .string "Which Pokémon wants to learn\n"
    .string "Dream Eater?$"

MoveTutor_Text_DreamEaterTaught::
    .string "…ZZZ…\n"
    .string "I…can't eat…anymore…$"

MoveTutor_Text_SeismicTossTeach::
    .string "The secrets of space…\n"
    .string "The mysteries of Earth…\p"
    .string "There are so many things about\n"
    .string "which we know so little.\p"
    .string "But that should spur us to study\n"
    .string "harder, not toss in the towel.\p"
    .string "The only thing you should toss…\p"
    .string "Well, how about Seismic Toss?\n"
    .string "Should I teach that to a Pokémon?$"

MoveTutor_Text_SeismicTossDeclined::
    .string "Is that so?\n"
    .string "I'm sure you'll be back for it.$"

MoveTutor_Text_SeismicTossWhichMon::
    .string "Which Pokémon wants to learn\n"
    .string "Seismic Toss?$"

MoveTutor_Text_SeismicTossTaught::
    .string "I hope you won't toss in the towel.\n"
    .string "Keep it up.$"

MoveTutor_Text_MegaPunchTeach::
    .string "A punch of roaring ferocity!\p"
    .string "Packed with destructive power!\p"
    .string "When the chips are down,\n"
    .string "Mega Punch is the ultimate attack!\l"
    .string "You agree, yes?\p"
    .string "Now!\n"
    .string "Let me teach it to your Pokémon!$"

MoveTutor_Text_MegaPunchDeclined::
    .string "You'll be back when you understand\n"
    .string "the worth of Mega Punch.$"

MoveTutor_Text_MegaPunchWhichMon::
    .string "Fine!\n"
    .string "Which Pokémon will learn it?$"

MoveTutor_Text_MegaPunchTaught::
    .string "Now, we are comrades in the way of\n"
    .string "punching!\p"
    .string "You should go before you're seen\n"
    .string "by the misguided fool who trains\l"
    .string "only his silly kicking over there.$"

MoveTutor_Text_MegaKickTeach::
    .string "A kick of brutal ferocity!\p"
    .string "Packed with destructive power!\p"
    .string "When you get right down to it,\n"
    .string "Mega Kick is the ultimate attack!\l"
    .string "Don't you agree?\p"
    .string "Okay!\n"
    .string "I'll teach it to your Pokémon!$"

MoveTutor_Text_MegaKickDeclined::
    .string "You'll come crawling back when you\n"
    .string "realize the value of Mega Kick.$"

MoveTutor_Text_MegaKickWhichMon::
    .string "All right!\n"
    .string "Which Pokémon wants to learn it?$"

MoveTutor_Text_MegaKickTaught::
    .string "Now, we are soul mates in the way\n"
    .string "of kicking!\p"
    .string "You should run before you're seen\n"
    .string "by the deluded nitwit who trains\l"
    .string "only simple punching over there.$"

MoveTutor_Text_RockSlideTeach::
    .string "When you're up on a rocky mountain\n"
    .string "like this, rockslides are a threat.\p"
    .string "Can you imagine?\n"
    .string "Boulders tumbling down on you?\p"
    .string "That'd be, like, waaaaaaaaaaah!\n"
    .string "Total terror!\p"
    .string "You don't seem to be scared.\n"
    .string "Want to try using Rock Slide?$"

MoveTutor_Text_RockSlideDeclined::
    .string "Oh, so you are scared after all.$"

MoveTutor_Text_RockSlideWhichMon::
    .string "Which Pokémon should I teach\n"
    .string "Rock Slide?$"

MoveTutor_Text_RockSlideTaught::
    .string "It might be scary to use it in this\n"
    .string "tunnel…$"

MoveTutor_Text_CounterTeach::
    .string "Oh, hi!\n"
    .string "I finally finished Pokémon.\p"
    .string "Not done yet? How about I teach\n"
    .string "you a good move?\p"
    .string "The move I have in mind is\n"
    .string "Counter.\p"
    .string "Not like the one I'm leaning on,\n"
    .string "mind you!$"

MoveTutor_Text_CounterDeclined::
    .string "You're not interested? Come see\n"
    .string "me if you change your mind.$"

MoveTutor_Text_CounterWhichMon::
    .string "Which Pokémon should I teach\n"
    .string "Counter to?$"

MoveTutor_Text_CounterTaught::
    .string "Are you using that Counter move\n"
    .string "I taught your Pokémon?$"

MoveTutor_Text_SoftboiledTeach::
    .string "Hello, there!\p"
    .string "I've seen you about, but I never\n"
    .string "had a chance to chat.\p"
    .string "It must be good luck that brought\n"
    .string "us together finally.\p"
    .string "I'd like to celebrate by teaching\n"
    .string "you the move Softboiled.$"

MoveTutor_Text_SoftboiledDeclined::
    .string "I'll always be keeping an eye out\n"
    .string "for you.\p"
    .string "I hope we can chat again.$"

MoveTutor_Text_SoftboiledWhichMon::
    .string "So, who's the Pokémon that gets\n"
    .string "the chance to learn Softboiled?$"

MoveTutor_Text_SoftboiledTaught::
    .string "I wish you the best of luck!$"

MoveTutor_Text_MimicTeach::
    .string "Oh wow!\n"
    .string "A Poké Doll!\p"
    .string "For me?\n"
    .string "Thank you!\p"
    .string "You know what?\n"
    .string "I can teach the move Mimic.$"

MoveTutor_Text_MimicDeclined::
    .string "Don't you like Mimic?$"

MoveTutor_Text_MimicWhichMon::
    .string "I really love Mimic!\n"
    .string "Who's going to learn it?$"

MoveTutor_Text_MimicTaughtMale::
    .string "{PLAYER}: Hi!\n"
    .string "Thanks for earlier!\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it that fun to mimic my\n"
    .string "every move?\p"
    .string "Copycat: You bet!\n"
    .string "It's a scream!$"

MoveTutor_Text_MimicTaughtFemale::
    .string "{PLAYER}: Hi!\n"
    .string "Thanks for what you did for us.\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it really that fun to\n"
    .string "copy what I say and do?\p"
    .string "Copycat: You bet!\n"
    .string "It's a scream!$"

MoveTutor_Text_ThunderWaveTeach::
    .string "Eeek!\n"
    .string "No! Stop! Help!\p"
    .string "Oh, you're not with Team Rocket.\n"
    .string "I'm sorry, I thought…\p"
    .string "Will you forgive me if I teach\n"
    .string "you the Thunder Wave technique?$"

MoveTutor_Text_ThunderWaveDeclined::
    .string "Oh…\n"
    .string "But Thunder Wave is convenient…$"

MoveTutor_Text_ThunderWaveWhichMon::
    .string "Which Pokémon should I teach\n"
    .string "Thunder Wave?$"

MoveTutor_Text_ThunderWaveTaught::
    .string "Thunder Wave causes paralysis in\n"
    .string "the target Pokémon.\p"
    .string "A paralyzed Pokémon may be unable\n"
    .string "to move in battle.\p"
    .string "It's an Electric-type move, so it\n"
    .string "won't work on some Pokémon.$"

MoveTutor_Text_SubstituteTeach::
    .string "Aww, I wish I was a Kangaskhan\n"
    .string "baby.\p"
    .string "I'd love to be a substitute for the\n"
    .string "baby…\p"
    .string "And snuggle in the mother\n"
    .string "Kangaskhan's belly pouch.\p"
    .string "But only Pokémon can use the\n"
    .string "technique Substitute…\p"
    .string "Want me to teach Substitute to\n"
    .string "one of your Pokémon?$"

MoveTutor_Text_SubstituteDeclined::
    .string "Oh, really?\n"
    .string "Substitute seems so fun…$"

MoveTutor_Text_SubstituteWhichMon::
    .string "Which Pokémon wants to learn\n"
    .string "Substitute?$"

MoveTutor_Text_SubstituteTaught::
    .string "Boy, what I'd give to crawl inside\n"
    .string "a Kangaskhan belly pouch…$"
    
MoveTutor_Text_MetronomeTeach::
    .string "Tch-tch-tch!\n"
    .string "I'll teach you a nifty move.\p"
    .string "Teach it to a Pokémon, and watch\n"
    .string "the fun unfold!\p"
    .string "It's a move called Metronome.\n"
    .string "Does it strike your fancy?$"

MoveTutor_Text_MetronomeDeclined::
    .string "I tell you, it's a lot of fun!$"

MoveTutor_Text_MetronomeWhichMon::
    .string "Okay!\n"
    .string "Which Pokémon should I teach?$"

MoveTutor_Text_MetronomeTaught::
    .string "Tch-tch-tch!\n"
    .string "That's the sound of a Metronome.\p"
    .string "It tweaks your Pokémon's brain into\n"
    .string "using moves it doesn't even know.$"
    
MoveTutor_Text_DoubleEdgeTeach::
    .string "You should be proud of yourself,\n"
    .string "having battled your way through\l"
    .string "Victory Road so courageously.\p"
    .string "In recognition of your feat,\n"
    .string "I'll teach you Double Edge.\p"
    .string "Would you like me to teach that\n"
    .string "technique?$"

MoveTutor_Text_DoubleEdgeDeclined::
    .string "I'll teach you the technique\n"
    .string "anytime.$"

MoveTutor_Text_DoubleEdgeWhichMon::
    .string "Which Pokémon should I teach\n"
    .string "Double Edge?$"

MoveTutor_Text_DoubleEdgeTaught::
    .string "Keep that drive going for the\n"
    .string "Pokémon League!\p"
    .string "Take a run at them and knock 'em\n"
    .string "out!$"

MoveTutor_Text_ExplosionTeach::
    .string "Can you imagine?\n"
    .string "If this volcano were to erupt?\p"
    .string "The explosion would be the end of\n"
    .string "us. How terrifying is that?\p"
    .string "While we're terrified, would you\n"
    .string "like me to teach Explosion?$"

MoveTutor_Text_ExplosionDeclined::
    .string "Yeah, you're right.\n"
    .string "It is too terrifying.$"

MoveTutor_Text_ExplosionWhichMon::
    .string "You're terribly brave!\p"
    .string "Which Pokémon should I teach\n"
    .string "Explosion?$"

MoveTutor_Text_ExplosionTaught::
    .string "Using Explosion while on this\n"
    .string "volcano…\p"
    .string "What a terrifying thrill!$"

MoveTutor_Text_BodySlamTeach::
    .string "Ready?\n"
    .string "Boing!\p"
    .string "We're having a Body Slam match\n"
    .string "to see who wimps out first.\p"
    .string "If you were to join us, you'd be\n"
    .string "squashed like a bug, though…\p"
    .string "How about I teach Body Slam to\n"
    .string "a Pokémon of yours instead?$"

MoveTutor_Text_BodySlamDeclined::
    .string "Come again!\n"
    .string "Boing!$"

MoveTutor_Text_BodySlamWhichMon::
    .string "Which Pokémon wants to learn how\n"
    .string "to Body Slam?$"

MoveTutor_Text_BodySlamTaught::
    .string "Boioing!$"

MoveTutor_Text_SwordsDanceTeach::
    .string "Not many people come out here.\p"
    .string "If I train here, I'm convinced that\n"
    .string "I'll get stronger and stronger.\p"
    .string "Yep, stronger and stronger…\p"
    .string "How would you like to learn a move\n"
    .string "like that? It's Swords Dance.$"

MoveTutor_Text_SwordsDanceDeclined::
    .string "Well, that's fine, too.$"

MoveTutor_Text_SwordsDanceWhichMon::
    .string "All right, pick which Pokémon\n"
    .string "I should teach it to.$"

MoveTutor_Text_SwordsDanceTaught::
    .string "If only we could keep getting\n"
    .string "stronger and stronger, eh?$"

MoveTutor_Text_UltimateMoveThatMon::
    .string "I perfected the ultimate move of\n"
    .string "its type…\p"
    .string "But will no one take it for\n"
    .string "future use?\p"
    .string "…Hm? Hmmm!\p"
    .string "Y-you…\n"
    .string "Th-that {STR_VAR_1}…$"

MoveTutor_Text_JustMistaken::
    .string "…No…\n"
    .string "I was just mistaken.$"

MoveTutor_Text_AllowMeToTeachMonUltimateMove::
    .string "Oh! This is the one!\n"
    .string "This is the Pokémon!\p"
    .string "This {STR_VAR_1} is worthy of\n"
    .string "learning my ultimate move!\p"
    .string "Will you allow it?\p"
    .string "Will you allow your {STR_VAR_1} to\n"
    .string "learn my {STR_VAR_2}?$"

MoveTutor_Text_YouRejectIt::
    .string "Gaah! You reject it?\n"
    .string "No, I won't be dissuaded!$"

MoveTutor_Text_LetMeConferUltimateMove::
    .string "You will allow it?\p"
    .string "Then, let me confer my ultimate\n"
    .string "{STR_VAR_2} on your {STR_VAR_1}.\p"
    .string "Ggggrah-awooo!$"

MoveTutor_Text_TaughtMove::
    .string "Gasp, gasp, gasp…\p"
    .string "I didn't think I could teach that\n"
    .string "move while I still lived…$"

MoveTutor_Text_MakeBestUseOfMove::
    .string "I implore you to make the best\n"
    .string "use of that move and gain power!$"

MoveTutor_Text_PassedOnEverythingIKnow::
    .string "Gasp, gasp, gasp…\p"
    .string "I have no regrets now.\n"
    .string "I've passed on everything I know.\p"
    .string "Now I can live out my life knowing\n"
    .string "my work is done.$"

MoveTutor_Text_FeelRejuvenated::
    .string "After I passed on my knowledge to\n"
    .string "you, I felt so much relief.\p"
    .string "In fact, I feel rejuvenated,\n"
    .string "as if I were younger again!$"

MoveTutor_Text_SwaggerTeach:
	.string "Heh! My Pokémon totally rules!\n"
	.string "It's cooler than any Pokémon!\p"
	.string "I was lipping off with a swagger in\n"
	.string "my step like that when the Chairman\l"
	.string "chewed me out.\p"
	.string "That took the swagger out of my step.\p"
	.string "If you'd like, I'll teach the move\n"
	.string "Swagger to a Pokémon of yours.$"

MoveTutor_Text_SwaggerDeclined:
	.string "What, no? Can't you get into\n"
	.string "the spirit of things?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "All right, which Pokémon wants to\n"
	.string "learn how to Swagger?$"

MoveTutor_Text_SwaggerTaught:
	.string "I'll just praise my Pokémon from now\n"
	.string "on without the swagger.$"

MoveTutor_Text_RolloutTeach:
	.string "Did you know that you can go from\n"
	.string "here a long way in that direction\l"
	.string "without changing direction?\p"
	.string "I might even be able to roll\n"
	.string "that way.\p"
	.string "Do you think your Pokémon will\n"
	.string "want to roll, too?\p"
	.string "I can teach one the move Rollout\n"
	.string "if you'd like.$"

MoveTutor_Text_RolloutDeclined:
	.string "You don't need to be shy about it.\n"
	.string "Let's roll!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, sure thing! It'd be great if\n"
	.string "the Pokémon looked like me.$"

MoveTutor_Text_RolloutTaught:
	.string "Rolling around in the grass makes me\n"
	.string "happy. Come on, let's roll!$"

MoveTutor_Text_FuryCutterTeach:
	.string "There's a move that gets stronger\n"
	.string "when you keep using it in a row.\p"
	.string "It's a Bug-type move, and it is\n"
	.string "wickedly cool.\p"
	.string "It's called Fury Cutter.\n"
	.string "Want me to teach it to a Pokémon?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "We're not on the same wavelength.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Yay!\n"
	.string "Show me which Pokémon I should teach.$"

MoveTutor_Text_FuryCutterTaught:
	.string "I get a thrill watching to see if\n"
	.string "the move keeps hitting in succession!$"

MoveTutor_MimicTeach:
	.string "Ah, young one!\p"
	.string "I am also a young one, but I mimic\n"
	.string "the styles and speech of the elderly\l"
	.string "folks of this town.\p"
	.string "What do you say, young one?\n"
	.string "Would you agree to it if I were to\l"
	.string "offer to teach the move Mimic?$"

MoveTutor_MimicDeclined:
	.string "Oh, boo! I wanted to teach MIMIC\n"
	.string "to your POKéMON!$"

MoveTutor_Text_MimicTaught:
	.string "Mimic is a move of great depth.\p"
	.string "Could you execute it to perfection\n"
	.string "as well as me…?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Humph! My wife relies on Hidden\n"
	.string "Power to stay awake.\p"
	.string "She should just take a nap like I do,\n"
	.string "and Sleep Talk.\p"
	.string "I can teach your Pokémon how to\n"
	.string "Sleep Talk instead. Interested?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, fine, fine. You want to stay awake\n"
	.string "with Hidden Power, too…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, an appreciative child!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_SleepTalkTaught:
	.string "I've never once gotten my wife's\n"
	.string "coin trick right.\p"
	.string "I would be happy if I got it right\n"
	.string "even as I Sleep Talk…$"

MoveTutor_Text_DynamicPunchTeach:
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a Fighting-type Trainer,\n"
	.string "so I can't win at the Mossdeep Gym\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Or do you want me to teach your\n"
	.string "Pokémon DynamicPunch?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Darn! You're even making fun of me?\n"
	.string "Punch! Punch! Punch!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "What? You do? You're a good person!\n"
	.string "Which Pokémon should I teach?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "I want you to win at the Mossdeep Gym\n"
	.string "using that DynamicPunch!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Sigh…\p"
	.string "Sootopolis's Gym Leader is really\n"
	.string "lovably admirable.\p"
	.string "But that also means I have many\n"
	.string "rivals for his attention.\p"
	.string "He's got appeal with a Double-Edge.\n"
	.string "I couldn't even catch his eye.\p"
	.string "Please, let me teach your Pokémon\n"
	.string "the move Double-Edge!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Even you rejected me…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Okay, which Pokémon should I teach\n"
	.string "Double-Edge?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "I won't live for love anymore!\n"
	.string "I'll become tough!$"

MoveTutor_Text_ExplosionTeach:
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge Explosion of popularity!\p"
	.string "If you overheard that, I'll happily\n"
	.string "teach Explosion to your Pokémon!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! You're turning me down because\n"
	.string "I live in the country?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Fine! An Explosion it is!\n"
	.string "Which Pokémon wants to blow up?$"

MoveTutor_Text_ExplosionTaught:
	.string "For a long time, I've taught Pokémon\n"
	.string "how to use Explosion, but I've yet\l"
	.string "to ignite my own Explosion…\p"
	.string "Maybe it's because deep down,\n"
	.string "I would rather stay here…$"
