gPokedexRating_Text_HowIsPokedexComingAlong::
	.string "Prof. Oak: Ah, {PLAYER}!\n"
    .string "How is your Pokédex coming along?\p"
    .string "Here, let me take a look.$"

gPokedexRating_Text_SeenXOwnedY::
    .string "The amount of progress you've made\n"
    .string "on your Pokédex is:\p"
    .string "{STR_VAR_1} Pokémon seen and\n"
    .string "{STR_VAR_2} Pokémon owned.$"

gPokedexRating_Text_LessThan10::
    .string "You still have lots to do.\p"
    .string "Go into every patch of grass you\n"
    .string "see and look for Pokémon!$"

gPokedexRating_Text_LessThan20::
    .string "It looks as if you're getting on\n"
    .string "the right track!\p"
    .string "I've given one of my Aides a Flash\n"
    .string "HM. Make sure you go get it!$"

gPokedexRating_Text_LessThan30::
    .string "Your Pokédex could use a bit more\n"
    .string "volume still!\p"
    .string "Try to catch other species of\n"
    .string "Pokémon!$"

gPokedexRating_Text_LessThan40::
    .string "Good, it's apparent that you're\n"
    .string "trying hard!\p"
    .string "I've given one of my Aides a\n"
    .string "Dowsing MCHN. Be sure to collect it!$"

gPokedexRating_Text_LessThan50::
    .string "Your Pokédex is coming along quite\n"
    .string "well!\p"
    .string "I've given one of my Aides an\n"
    .string "Amulet Coin. Be sure to get it!$"

gPokedexRating_Text_LessThan60::
    .string "Ah, you've finally topped 50\n"
    .string "species!\p"
    .string "I've given one of my Aides an EXP.\n"
    .string "Share. Be sure to go get it!$"

gPokedexRating_Text_LessThan70::
    .string "Hoho! This is turning into quite the\n"
    .string "respectable Pokédex!$"

gPokedexRating_Text_LessThan80::
    .string "Very good!\p"
    .string "I think you'll collect even more\n"
    .string "Pokémon by going fishing!$"

gPokedexRating_Text_LessThan90::
    .string "Wonderful! Let me guess… You\n"
    .string "like to collect things, don't you?$"

gPokedexRating_Text_LessThan100::
    .string "I'm impressed!\n"
    .string "It must have been difficult to do!$"

gPokedexRating_Text_LessThan110::
    .string "You've finally hit 100 species!\n"
    .string "I can't believe how good you are!$"

gPokedexRating_Text_LessThan120::
    .string "You even have the evolved forms\n"
    .string "of Pokémon! Super!$"

gPokedexRating_Text_LessThan130::
    .string "Excellent! Trade with friends to\n"
    .string "get some more!$"

gPokedexRating_Text_LessThan140::
    .string "Outstanding!\n"
    .string "You've become a real pro at this!$"

gPokedexRating_Text_LessThan150::
    .string "I have nothing left to say!\n"
    .string "You're the Pokémon Professor now!$"

gPokedexRating_Text_Complete::
    .string "Your Pokédex is entirely complete!\n"
    .string "Congratulations!!$"

gPokedexRating_Text_NationalDexSeenXOwnedY::
    .string "And your National Pokédex is:\p"
    .string "{STR_VAR_1} Pokémon seen and\n"
    .string "{STR_VAR_2} Pokémon owned.$"

gPokedexRating_Text_LookForwardToFilledNationalDex::
    .string "I'll be looking forward to seeing\n"
    .string "you fill the National Pokédex!$"

gPokedexRating_Text_YouveCompletedDex::
    .string "Finally…\p"
    .string "You've finally completed the\n"
    .string "Pokédex!\p"
    .string "It's magnificent!\n"
    .string "Truly, this is a fantastic feat!$"

gPokedexRating_Text_Wroooaaarrr::
    .string "Wroooooooaaaaaarrrr!$"

gPokedexRating_Text_ThankYouMadeDreamReality::
    .string "Thank you, {PLAYER}!\n"
    .string "Sincerely, thank you!\l"
    .string "You've made my dream a reality!$"

gPokedexRating_Text_LoveSeeingYourPokedex::
    .string "Oak: Ah, welcome!\p"
    .string "Tell me, how is your Pokédex\n"
    .string "coming along?\p"
    .string "Wahaha!\p"
    .string "Actually, I know how it is, but I\n"
    .string "love seeing it anyway!\p"
    .string "Let's see…$"
