Route3_Text_ColtonIntro::
    .string "Hey!\n"
    .string "I saw you in Viridian Forest!$"

Route3_Text_ColtonDefeat::
    .string "You beat me again!$"

Route3_Text_ColtonPostBattle::
    .string "There are other kinds of Pokémon\n"
    .string "than the ones you find in forests.$"

Route3_Text_ColtonRegister:
	.string "Huh? I'm so weak, but you're willing\n"
	.string "to register me in your Pokénav?$"

Route3_Text_ColtonRematchIntro::
    .string "Hey!\n"
    .string "I saw you in Viridian Forest!$"

Route3_Text_BenIntro::
    .string "Hi!\n"
    .string "I like shorts!\p"
    .string "They're delightfully comfy and\n"
    .string "easy to wear!$"

Route3_Text_BenDefeat::
    .string "I don't believe it!$"

Route3_Text_BenPostBattle::
    .string "Are you using a Pokémon Center's\n"
    .string "PC for storing your Pokémon?\p"
    .string "Each box can hold up to\n"
    .string "30 Pokémon.$"

Route3_Text_BenRegister:
	.string "I really like shorts!\n"
	.string "But, I also like Pokénavs.$"

Route3_Text_BenRematchIntro::
    .string "Hi! I like shorts!\n"
    .string "They're comfy and easy to wear!\p"
    .string "You should be wearing shorts, too!$"

Route3_Text_JaniceIntro::
    .string "Excuse me!\n"
    .string "You looked at me, didn't you?$"

Route3_Text_JaniceDefeat::
    .string "You're mean!$"

Route3_Text_JanicePostBattle::
    .string "You shouldn't be staring if you\n"
    .string "don't want to battle!$"

Route3_Text_JaniceRegister:
	.string "You're strong, but should I register\n"
	.string "you in my Pokénav?\l"
	.string "Maybe I shouldn't…\p"
	.string "Okay, sure, I will register you!$"

Route3_Text_JaniceRematchIntro::
    .string "Excuse me!\n"
    .string "You keep looking at me, don't you?$"

Route3_Text_GregIntro::
    .string "Are you a Trainer?\n"
    .string "Let's get with it right away!$"

Route3_Text_GregDefeat::
    .string "If I had new Pokémon, I would've\n"
    .string "won!$"

Route3_Text_GregPostBattle::
    .string "If a Pokémon Box on the PC gets\n"
    .string "full, just switch to another box.$"

Route3_Text_SallyIntro::
    .string "That look you gave me…\n"
    .string "It's so intriguing!$"

Route3_Text_SallyDefeat::
    .string "Be nice!$"

Route3_Text_SallyPostBattle::
    .string "You can avoid battles by not\n"
    .string "letting Trainers see you.$"

Route3_Text_CalvinIntro::
    .string "Hey! You're not wearing shorts!\n"
    .string "What's wrong with you?$"

Route3_Text_CalvinDefeat::
    .string "Lost!\n"
    .string "Lost! Lost!$"

Route3_Text_CalvinPostBattle::
    .string "I always wear shorts, even in\n"
    .string "winter. That's my policy.$"

Route3_Text_JamesIntro::
    .string "I'll battle you with the Pokémon\n"
    .string "I just caught.$"

Route3_Text_JamesDefeat::
    .string "Done like dinner!$"

Route3_Text_JamesPostBattle::
    .string "Trained Pokémon are stronger than\n"
    .string "the wild ones.$"

Route3_Text_RobinIntro::
    .string "Eek!\n"
    .string "Did you touch me?$"

Route3_Text_RobinDefeat::
    .string "That's it?$"

Route3_Text_RobinPostBattle::
    .string "Route 4 is at the foot of\n"
    .string "Mt. Moon.$"

Route4_Text_CrissyIntro::
    .string "I came to Mt. Moon in search of\n"
    .string "mushroom Pokémon.$"

Route4_Text_CrissyDefeat::
    .string "After all I did to catch them!$"

Route4_Text_CrissyPostBattle::
    .string "There might not be any more\n"
    .string "mushrooms here.\p"
    .string "I think I got them all.$"

Route6_Text_RickyIntro::
    .string "Who's there?\n"
    .string "Quit listening in on us!$"

Route6_Text_RickyDefeat::
    .string "I just can't win!$"

Route6_Text_RickyPostBattle::
    .string "Whisper…\n"
    .string "Whisper…$"

Route6_Text_RickyRegister:
	.string "I demand your number!\n"
	.string "One day I'll pay you back\l"
	.string "for interrupting us!$"

Route6_Text_RickyRematchIntro::
    .string "Oh! You're that nosy kid who\n"
    .string "eavesdropped on us!$"

Route6_Text_NancyIntro::
    .string "Excuse me!\n"
    .string "This is a private conversation!$"

Route6_Text_NancyDefeat::
    .string "Ugh!\n"
    .string "I hate losing.$"

Route6_Text_NancyPostBattle::
    .string "Whisper…\n"
    .string "Whisper…$"

Route6_Text_KeigoIntro::
    .string "There aren't many bugs out here.$"

Route6_Text_KeigoDefeat::
    .string "No!\n"
    .string "You're kidding!$"

Route6_Text_KeigoPostBattle::
    .string "I like bugs, so I'm going back to\n"
    .string "Viridian Forest.$"

Route6_Text_JeffIntro::
    .string "Huh?\n"
    .string "You want to talk to me?$"

Route6_Text_JeffDefeat::
    .string "This stinks…\n"
    .string "I couldn't beat your challenge…$"

Route6_Text_JeffPostBattle::
    .string "I should bring more Pokémon with\n"
    .string "me. I'll feel safer that way.$"

Route6_Text_JeffRegister:
    .string "Huh?\n"
    .string "You want to fight me again?$"

Route6_Text_JeffRematchIntro::
    .string "Huh?\n"
    .string "You want to go with me again?$"

Route6_Text_IsabelleIntro::
    .string "Me?\n"
    .string "Well, okay. I'll play!$"

Route6_Text_IsabelleDefeat::
    .string "Things just didn't work…$"

Route6_Text_IsabellePostBattle::
    .string "I want to get stronger.\n"
    .string "What's your secret?$"

Route6_Text_IsabelleRegister:
	.string "The only way I can get stronger\n"
	.string "is by battling strong Trainers\l"
	.string "like you!$"

Route6_Text_IsabelleRematchIntro::
    .string "Me?\n"
    .string "Well, okay. I'll play this once.$"

Route6_Text_ElijahIntro::
    .string "I've never seen you around.\n"
    .string "Are you good?$"

Route6_Text_ElijahDefeat::
    .string "You're too good!$"

Route6_Text_ElijahPostBattle::
    .string "Are my Pokémon weak?\n"
    .string "Or, am I just bad?\l"
    .string "Which do you think?$"

Route8_Text_AidanIntro::
    .string "You look good at Pokémon, but how\n"
    .string "is your chemistry grade?$"

Route8_Text_AidanDefeat::
    .string "Ow!\n"
    .string "Meltdown!$"

Route8_Text_AidanPostBattle::
    .string "I am better at school than this!$"

Route8_Text_StanIntro::
    .string "All right!\n"
    .string "Let's play a game!$"

Route8_Text_StanDefeat::
    .string "Drat!\n"
    .string "Came up short!$"

Route8_Text_StanPostBattle::
    .string "Things didn't work today.$"

Route8_Text_GlennIntro::
    .string "You should be informed.\n"
    .string "You need strategy to win at this!$"

Route8_Text_GlennDefeat::
    .string "It's not logical!$"

Route8_Text_GlennPostBattle::
    .string "Go with Grimer first…and…\n"
    .string "…and…then…$"

Route8_Text_PaigeIntro::
    .string "I like Nidoran, so I collect them!$"

Route8_Text_PaigeDefeat::
    .string "Why?\n"
    .string "Why??$"

Route8_Text_PaigePostBattle::
    .string "When Pokémon grow up, they get\n"
    .string "ugly! They shouldn't evolve.$"

Route8_Text_LeslieIntro::
    .string "School is fun, but so are Pokémon.$"

Route8_Text_LeslieDefeat::
    .string "You made it clear to me that\n"
    .string "I should stick with school.$"

Route8_Text_LesliePostBattle::
    .string "I was planning on getting some\n"
    .string "fresh air for a change, but…\p"
    .string "We're stuck here because of the\n"
    .string "gates at Saffron.$"

Route8_Text_AndreaIntro::
    .string "Meowth is so cute, meow, meow,\n"
    .string "meow!$"

Route8_Text_AndreaDefeat::
    .string "Meeeeyow!$"

Route8_Text_AndreaPostBattle::
    .string "I think Pidgey and Rattata are\n"
    .string "cute, too!$"

Route8_Text_MeganIntro::
    .string "We must look silly standing here\n"
    .string "like this.$"

Route8_Text_MeganDefeat::
    .string "Look what you did to my poor, cute\n"
    .string "Pokémon!$"

Route8_Text_MeganPostBattle::
    .string "Saffron's gatekeeper won't let us\n"
    .string "go through.\p"
    .string "I know he's doing his job, but I\n"
    .string "think he's mean.$"

Route8_Text_MeganRegister:
	.string "It looks like we're gonna be\n"
	.string "here for a while!\p"
	.string "Can you register me in your Pokénav?$"

Route8_Text_MeganRematchIntro::
    .string "We may look silly standing here\n"
    .string "like this, but I can still battle.$"

Route8_Text_RichIntro::
    .string "I'm a rambling, gambling dude!$"

Route8_Text_RichDefeat::
    .string "Missed the big chance!$"

Route8_Text_RichPostBattle::
    .string "Playing games and Pokémon are like\n"
    .string "eating peanuts! I just can't stop!$"

Route8_Text_RichRegister:
	.string "Next time the odds will be.\n"
	.string "in my favour!$"

Route8_Text_RichRematchIntro::
    .string "I'm a rambling, gambling dude!\n"
    .string "I'm on a winning streak!$"

Route8_Text_JuliaIntro::
    .string "What's a cute, round, and fluffy\n"
    .string "Pokémon?$"

Route8_Text_JuliaDefeat::
    .string "Stop!\p"
    .string "Don't be so mean to my Clefairy!$"

Route8_Text_JuliaPostBattle::
    .string "I read that Clefairy evolves when\n"
    .string "it's exposed to a Moon Stone.\p"
    .string "I read that in a Pokémon Journal.\n"
    .string "I wonder if it's true?$"

Route8_Text_EliIntro::
    .string "Eli: Twin power is fantastic.\n"
    .string "Did you know?$"

Route8_Text_EliDefeat::
    .string "Eli: But…\n"
    .string "We used our twin power…$"

Route8_Text_EliPostBattle::
    .string "Eli: I caught my Pokémon with\n"
    .string "Anne!$"

Route8_Text_EliAndAnneRegister:
	.string "Eli: We can't take this lying down!\n"
	.string "You will come back, won't you?$"

Route8_Text_EliRematchIntro::
    .string "Eli: Our twin power became even\n"
    .string "better!$"

Route8_Text_EliNotEnoughMons::
    .string "Eli: We can't battle if you don't\n"
    .string "have two Pokémon.$"

Route8_Text_AnneIntro::
    .string "Anne: We'll shock you with our twin\n"
    .string "power!$"

Route8_Text_AnneDefeat::
    .string "Anne: Our twin power…$"

Route8_Text_AnnePostBattle::
    .string "Anne: I'm raising Pokémon with\n"
    .string "Eli.$"

Route8_Text_AnneRematchIntro::
    .string "Anne: Our twin power powered up!$"

Route8_Text_AnneNotEnoughMons::
    .string "Anne: Hi, hi! Let's battle!\n"
    .string "But bring two Pokémon.$"

Route8_Text_RicardoIntro::
    .string "My bike's acting up, man.$"

Route8_Text_RicardoDefeat::
    .string "Aww, man.\n"
    .string "I'm not into this.$"

Route8_Text_RicardoPostBattle::
    .string "I got grass caught up in my\n"
    .string "spokes, man.$"

Route8_Text_JarenIntro::
    .string "Clear the way, or I'll run you\n"
    .string "down!$"

Route8_Text_JarenDefeat::
    .string "You for real, kid?$"

Route8_Text_JarenPostBattle::
    .string "Don't think you're all special and\n"
    .string "all just because of this.$"

Route8_Text_JarenRegister:
	.string "I can't let you get\n"
	.string "away with this!$"

Route8_Text_JarenRematchIntro::
    .string "Okay, kid!\n"
    .string "Don't expect mercy this time!$"

Route9_Text_AliciaIntro::
    .string "You have Pokémon with you!\n"
    .string "You're mine!$"

Route9_Text_AliciaDefeat::
    .string "You deceived me…$"

Route9_Text_AliciaPostBattle::
    .string "The tunnel coming up is pitch-black\n"
    .string "inside.\p"
    .string "You'll need Flash to get through\n"
    .string "there.$"

Route9_Text_ChrisIntro::
    .string "Who's that walking there with those\n"
    .string "good-looking Pokémon?$"

Route9_Text_ChrisDefeat::
    .string "Out like a light!$"

Route9_Text_ChrisPostBattle::
    .string "Keep walking!$"

Route9_Text_ChrisRegister:
	.string "I wish to see the beauty of\n"
	.string "your Pokémon again!$"

Route9_Text_ChrisRematchIntro::
    .string "I haven't forgotten you were with\n"
    .string "those good-looking Pokémon.$"

Route9_Text_DrewIntro::
    .string "I'm taking the Rock Tunnel to\n"
    .string "go to Lavender…$"

Route9_Text_DrewDefeat::
    .string "Can't measure up…$"

Route9_Text_DrewPostBattle::
    .string "Are you off to Rock Tunnel, too?$"

Route9_Text_CaitlinIntro::
    .string "Don't you dare patronise me!$"

Route9_Text_CaitlinDefeat::
    .string "No!\n"
    .string "You're too much.$"

Route9_Text_CaitlinPostBattle::
    .string "You're obviously talented.\n"
    .string "Good luck to you!$"

Route9_Text_CaitlinRegister:
	.string "Don't forget what you've done to me!\n"
	.string "I'll make it so you can't forget!$"

Route9_Text_CaitlinRematchIntro::
    .string "Don't you dare patronise me today!\n"
    .string "We're playing for keeps!$"

Route9_Text_JeremyIntro::
    .string "Bwahaha!\n"
    .string "Great! I was bored, eh!$"

Route9_Text_JeremyDefeat::
    .string "Keep it coming, eh!\p"
    .string "Oh wait.\n"
    .string "I'm out of Pokémon!$"

Route9_Text_JeremyPostBattle::
    .string "You sure had guts standing up to\n"
    .string "me there, eh?$"

Route9_Text_JeremyRegister::
	.string "You sure cured me of my boredom!\n"
	.string "We should do this again!$"

Route9_Text_JeremyRematchIntro::
    .string "Bwahaha!\n"
    .string "Great! I was bored again, eh!$"

Route9_Text_BriceIntro::
    .string "Hahaha!\n"
    .string "Aren't you a little toughie!$"

Route9_Text_BriceDefeat::
    .string "What's that?$"

Route9_Text_BricePostBattle::
    .string "Hahaha!\n"
    .string "Kids should be tough!$"

Route9_Text_BrentIntro::
    .string "I got up early every day to raise\n"
    .string "my Pokémon from cocoons!$"

Route9_Text_BrentDefeat::
    .string "WHAT?\p"
    .string "What a total waste of time!$"

Route9_Text_BrentPostBattle::
    .string "I have to collect more than bugs\n"
    .string "to get stronger…$"

Route9_Text_AlanIntro::
    .string "Hahahaha!\n"
    .string "Bring it on!$"

Route9_Text_AlanDefeat::
    .string "Hahahaha!\n"
    .string "You beat me fair!$"

Route9_Text_AlanPostBattle::
    .string "Hahahaha!\n"
    .string "Us hearty guys always laugh!$"

Route9_Text_ConnerIntro::
    .string "Go, my super Bug Pokémon!$"

Route9_Text_ConnerDefeat::
    .string "My bugs…$"

Route9_Text_ConnerPostBattle::
    .string "If you don't like Bug Pokémon,\n"
    .string "you bug me!$"

Route10_Text_MarkIntro::
    .string "Wow, you came all the way here?\n"
    .string "Maybe you're a Pokémaniac, too?\l"
    .string "Want to see my collection?$"

Route10_Text_MarkDefeat::
    .string "Humph.\n"
    .string "I'm not angry!$"

Route10_Text_MarkPostBattle::
    .string "I have more rare Pokémon at home!$"

Route10_Text_MarkRegister:
	.string "If you ever come back this way\n"
	.string "again, we should battle, okay?$"

Route10_Text_MarkRematchIntro::
    .string "Wow, you came here again?\n"
    .string "Maybe you're a Pokémaniac, too?\l"
    .string "Want to see my collection?$"

Route10_Text_ClarkIntro::
    .string "Ha-hahah-ah-ha!$"

Route10_Text_ClarkDefeat::
    .string "Ha-haha!\n"
    .string "Not laughing!\l"
    .string "Ha-hay fever! Haha-ha-choo!$"

Route10_Text_ClarkPostBattle::
    .string "Haha-ha-choo!\n"
    .string "Ha-choo!\l"
    .string "Snort! Snivel!$"

Route10_Text_HermanIntro::
    .string "Hi, kid!\n"
    .string "Want to see my Pokémon?$"

Route10_Text_HermanDefeat::
    .string "Oh, no!\n"
    .string "My Pokémon!$"

Route10_Text_HermanPostBattle::
    .string "I don't like you.\n"
    .string "I don't like anyone better than me!$"

Route10_Text_HermanRegister:
	.string "I must battle you again!\n"
	.string "No one can be better than me!$"

Route10_Text_HermanRematchIntro::
    .string "Hi, kid!\n"
    .string "Did I show you my Pokémon?$"

Route10_Text_HeidiIntro::
    .string "I've been out at a Pokémon Gym\n"
    .string "a few times.\p"
    .string "…But I always lose.$"

Route10_Text_HeidiDefeat::
    .string "Ohh!\n"
    .string "After all my training!$"

Route10_Text_HeidiPostBattle::
    .string "I noticed some Pokémaniacs\n"
    .string "prowling around.\p"
    .string "Can you imagine? Them?\n"
    .string "Up here in the mountains?$"

Route10_Text_TrentIntro::
    .string "Ah!\n"
    .string "This mountain air is delicious!$"

Route10_Text_TrentDefeat::
    .string "That cleared my head!$"

Route10_Text_TrentPostBattle::
    .string "I feel bloated on mountain air!$"

Route10_Text_TrentRegister:
	.string "If you ever want to share\n"
	.string "this mountain air again.$"

Route10_Text_TrentRematchIntro::
    .string "Ah!\n"
    .string "This mountain air is delicious!\l"
    .string "It's so good, I can't leave!$"

Route10_Text_CarolIntro::
    .string "I'm feeling a bit faint.\n"
    .string "I haven't hiked in some time.$"

Route10_Text_CarolDefeat::
    .string "I'm too tired.\n"
    .string "I wasn't up for it.$"

Route10_Text_CarolPostBattle::
    .string "The Pokémon here in the mountains\n"
    .string "are so chunky…\p"
    .string "I wish there were pink Pokémon\n"
    .string "with a floral pattern!$"

Route11_Text_HugoIntro::
    .string "Win, lose, or draw!$"

Route11_Text_HugoDefeat::
    .string "Atcha!\n"
    .string "Didn't go my way!$"

Route11_Text_HugoPostBattle::
    .string "Pokémon is life!\n"
    .string "And to live is to play games!$"

Route11_Text_JasperIntro::
    .string "Competition!\n"
    .string "I can't get enough!$"

Route11_Text_JasperDefeat::
    .string "I had a chance!$"

Route11_Text_JasperPostBattle::
    .string "You can't be a coward in the world\n"
    .string "of Pokémon!$"

Route11_Text_EddieIntro::
    .string "Let's go, but don't cheat!$"

Route11_Text_EddieDefeat::
    .string "Huh?\n"
    .string "That's not right!$"

Route11_Text_EddiePostBattle::
    .string "I did my best.\n"
    .string "I have no regrets.$"

Route11_Text_BraxtonIntro::
    .string "Careful!\n"
    .string "I'm laying down some cables!$"

Route11_Text_BraxtonDefeat::
    .string "That was electric!$"

Route11_Text_BraxtonPostBattle::
    .string "Spread the word to save energy!$"
    
Route11_Text_DillonIntro::
    .string "I just became a Trainer.\n"
    .string "But, I think I can win.$"

Route11_Text_DillonDefeat::
    .string "My Pokémon couldn't win…\n"
    .string "Haven't they grown enough?$"

Route11_Text_DillonPostBattle::
    .string "What now?\n"
    .string "Leave me alone!$"

Route11_Text_DirkIntro::
    .string "Fwahaha!\n"
    .string "I have never lost!$"

Route11_Text_DirkDefeat::
    .string "My first loss!$"

Route11_Text_DirkPostBattle::
    .string "You were just lucky, that's all.$"

Route11_Text_DarianIntro::
    .string "I have never won before…$"

Route11_Text_DarianDefeat::
    .string "I saw this coming…$"

Route11_Text_DarianPostBattle::
    .string "I was unlucky, as always.$"

Route11_Text_DarianRegister:
	.string "Hm?\n"
	.string "Ah, you have a Pokénav.\p"
	.string "I will gladly register you.\n"
	.string "Perhaps I will win next time…$"

Route11_Text_DarianRematchIntro::
    .string "I have never won before…\p"
    .string "Perhaps I am destined to remain\n"
    .string "that way…$"

Route11_Text_YasuIntro::
    .string "I'm the best in my class.\n"
    .string "I train every morning.$"

Route11_Text_YasuDefeat::
    .string "Darn!\n"
    .string "My Pokémon need to be stronger!$"

Route11_Text_YasuPostBattle::
    .string "There's a fat Pokémon that comes\n"
    .string "down from the mountains.\p"
    .string "I bet it'd be strong if you can\n"
    .string "catch it.$"

Route11_Text_YasuRegister:
	.string "I took it easy on you this time!\n"
	.string "It won't be that way the next time!$"

Route11_Text_YasuRematchIntro::
    .string "I'm the best in my class.\n"
    .string "I train every morning and night!$"

Route11_Text_BernieIntro::
    .string "Watch out for live wires!$"

Route11_Text_BernieDefeat::
    .string "Whoa!\n"
    .string "You spark plug!$"

Route11_Text_BerniePostBattle::
    .string "Well, better get back to work.$"

Route11_Text_BernieRegister:
	.string "I have to get back to work now,\n"
	.string "but we can talk later.$"

Route11_Text_BernieRematchIntro::
    .string "Keep your eyes out for live wires!$"

Route11_Text_DaveIntro::
    .string "I raised my Pokémon carefully.\n"
    .string "They should be ready by now!$"

Route11_Text_DaveDefeat::
    .string "Bye-bye!\n"
    .string "Thank you, and good-bye!$"

Route11_Text_DavePostBattle::
    .string "Tch…\n"
    .string "I better go find stronger ones!$"

Route12_Text_NedIntro::
    .string "Yeah!\n"
    .string "I got a bite here!$"

Route12_Text_NedDefeat::
    .string "Tch!\n"
    .string "Just a small fry…$"

Route12_Text_NedPostBattle::
    .string "Hang on!\n"
    .string "My line's snagged!$"

Route12_Text_ChipIntro::
    .string "Be patient.\n"
    .string "Fishing is a waiting game.$"

Route12_Text_ChipDefeat::
    .string "That one got away!$"

Route12_Text_ChipPostBattle::
    .string "With a better rod, I could catch\n"
    .string "better Pokémon…$"

Route12_Text_JustinIntro::
    .string "I'm searching for a Moon Stone.\n"
    .string "Have you found one?$"

Route12_Text_JustinDefeat::
    .string "Oww!$"

Route12_Text_JustinPostBattle::
    .string "I could have made my Pokémon\n"
    .string "evolve with a Moon Stone.\p"
    .string "I would have won then, I bet.$"

Route12_Text_LucaIntro::
    .string "Electricity is my specialty.\p"
    .string "I don't know a thing about Pokémon\n"
    .string "of the sea, though.$"

Route12_Text_LucaDefeat::
    .string "Unplugged!$"

Route12_Text_LucaPostBattle::
    .string "Water conducts electricity, so you\n"
    .string "should zap sea Pokémon.$"

Route12_Text_LucaRegister:
	.string "That was electric!\p"
	.string "You and I shall battle again!\n"
	.string "Let's see your Pokénav.$"

Route12_Text_LucaRematchIntro::
    .string "Electricity has always been my\n"
    .string "specialty.\p"
    .string "I don't know a thing about Pokémon\n"
    .string "of the sea, though.$"

Route12_Text_HankIntro::
    .string "The Fishing Fool versus Pokémon\n"
    .string "Kid!$"

Route12_Text_HankDefeat::
    .string "Touch too much!$"

Route12_Text_HankPostBattle::
    .string "I guess you get to be good at\n"
    .string "what you like.\p"
    .string "Well, you beat me at Pokémon,\n"
    .string "but you can't top me at fishing.$"

Route12_Text_ElliotIntro::
    .string "I love fishing, don't get me wrong.\p"
    .string "But it'd be best if I also had more\n"
    .string "work.$"

Route12_Text_ElliotDefeat::
    .string "It's not easy…$"

Route12_Text_ElliotPostBattle::
    .string "It's all right.\n"
    .string "Losing doesn't bug me anymore.$"

Route12_Text_ElliotRegister:
	.string "Fishing's great, but so is battling.\n"
	.string "If you don't mind, can we meet again?$"

Route12_Text_ElliotRematchIntro::
    .string "I love fishing, don't get me wrong.\n"
    .string "But, I wish I had more work…\l"
    .string "…It's hard to give up fishing!$"

Route12_Text_AndrewIntro::
    .string "What's catching?\p"
    .string "You never know what you could\n"
    .string "catch!$"

Route12_Text_AndrewDefeat::
    .string "Lost it!$"

Route12_Text_AndrewPostBattle::
    .string "What, Magikarp?\p"
    .string "I catch them all the time, sure.\n"
    .string "But, boy are they wimpy.$"

Route12_Text_JesIntro::
    .string "Jes: If I win, I'm going to\n"
    .string "propose to Gia.$"

Route12_Text_JesDefeat::
    .string "Jes: Oh, please, why couldn't you\n"
    .string "let us win?$"

Route12_Text_JesPostBattle::
    .string "Jes: Oh, Gia, forgive me,\n"
    .string "my love!$"

Route12_Text_JesRematchIntro::
    .string "Jes: I'll win here today and\n"
    .string "propose to my Gia.$"

Route12_Text_JesNotEnoughMons::
    .string "Jes: Gia and I, we'll be\n"
    .string "together forever.\p"
    .string "We won't battle unless you have\n"
    .string "two Pokémon of your own.$"

Route12_Text_JesRegister:
	.string "Jes: I need to beat you so\n"
	.string "I can propose to Gia.\p"
	.string "Will you battle with us again?$"

Route12_Text_GiaIntro::
    .string "Gia: Hey, Jes…\p"
    .string "If we win, I'll marry you!$"

Route12_Text_GiaDefeat::
    .string "Gia: Oh, but why?$"

Route12_Text_GiaPostBattle::
    .string "Gia: Jes, you silly!\n"
    .string "You ruined this!$"

Route12_Text_GiaRematchIntro::
    .string "Gia: Hey, Jes…\n"
    .string "I've been waiting a long time now.\p"
    .string "If we win today, I'll marry you!$"

Route12_Text_GiaNotEnoughMons::
    .string "Gia: I can't bear to battle\n"
    .string "without my Jes!\p"
    .string "Don't you have one more Pokémon?$"

Route13_Text_SebastianIntro::
    .string "My bird Pokémon want to battle\n"
    .string "with you!$"

Route13_Text_SebastianDefeat::
    .string "My Pidgey and Pidgeotto combo\n"
    .string "lost?$"

Route13_Text_SebastianPostBattle::
    .string "My Pokémon look happy even though\n"
    .string "they lost.$"

Route13_Text_SusieIntro::
    .string "I'm told I'm good for a kid.$"

Route13_Text_SusieDefeat::
    .string "Ohh!\n"
    .string "I lost!$"

Route13_Text_SusiePostBattle::
    .string "I want to become a good Trainer.\n"
    .string "I'll train hard, just watch.$"

Route13_Text_SusieRegister:
	.string "I would like to face you again.\n"
	.string "Is that okay with you?$"

Route13_Text_SusieRematchIntro::
    .string "I want to be the best Trainer \n"
    .string "while I'm a kid!$"

Route13_Text_ValerieIntro::
    .string "Wow!\n"
    .string "Your badges are too cool!$"

Route13_Text_ValerieDefeat::
    .string "Not enough!$"

Route13_Text_ValeriePostBattle::
    .string "You got those badges from Gym\n"
    .string "Leaders. I know!$"

Route13_Text_GwenIntro::
    .string "My cute Pokémon wish to make your\n"
    .string "acquaintance.$"

Route13_Text_GwenDefeat::
    .string "Good going!\n"
    .string "You totally won!$"

Route13_Text_GwenPostBattle::
    .string "You have to make Pokémon battle\n"
    .string "to toughen them up.$"

Route13_Text_AlmaIntro::
    .string "I found Carbos in a cave once\n"
    .string "while I was spelunking.$"

Route13_Text_AlmaDefeat::
    .string "Oh, too bad!\n"
    .string "I just messed up!$"

Route13_Text_AlmaPostBattle::
    .string "Carbos boosted the Speed of my\n"
    .string "Pokémon.$"

Route13_Text_PerryIntro::
    .string "I'm not going to lose.\n"
    .string "Not when the wind's blowing my way!$"

Route13_Text_PerryDefeat::
    .string "The wind turned!$"

Route13_Text_PerryPostBattle::
    .string "I'm beat.\n"
    .string "I guess I'll fly home.$"

Route13_Text_LolaIntro::
    .string "Sure, I'll play with you, sweetie.$"

Route13_Text_LolaDefeat::
    .string "Oh!\n"
    .string "You little beast!$"

Route13_Text_LolaPostBattle::
    .string "I wonder which is stronger, male or\n"
    .string "female Pokémon?$"

Route13_Text_SheilaIntro::
    .string "Do you want to battle some\n"
    .string "Pokémon with me?$"

Route13_Text_SheilaDefeat::
    .string "It's over already?$"

Route13_Text_SheilaPostBattle::
    .string "I don't know anything about\n"
    .string "Pokémon actually.\p"
    .string "The ones I use… I picked them\n"
    .string "for their looks!$"

Route13_Text_SheilaRegister:
	.string "You're really good at Pokémon.\n"
	.string "May I ask your advice sometime?$"

Route13_Text_SheilaRematchIntro::
    .string "Can't you forget that you battled\n"
    .string "with me?$"

Route13_Text_JaredIntro::
    .string "What're you lookin' at?$"

Route13_Text_JaredDefeat::
    .string "Dang!\n"
    .string "Stripped gears!$"

Route13_Text_JaredPostBattle::
    .string "Get lost!$"

Route13_Text_RobertIntro::
    .string "I always go with bird Pokémon.\n"
    .string "I've dedicated myself to them.$"

Route13_Text_RobertDefeat::
    .string "Out of power!$"

Route13_Text_RobertPostBattle::
    .string "I wish I could fly like Pidgey and\n"
    .string "Pidgeotto…$"

Route13_Text_RobertRegister:
	.string "Oh, wow! Isn't that a Pokénav?\n"
	.string "I have one, too! Please register me!$"

Route13_Text_RobertRematchIntro::
    .string "I always go with bird Pokémon.\n"
    .string "I've dedicated myself to them.$"
    
Route14_Text_CarterIntro::
    .string "You need to use TMs to teach good\n"
    .string "moves to Pokémon.$"

Route14_Text_CarterDefeat::
    .string "Not good enough quite yet.$"

Route14_Text_CarterPostBattle::
    .string "You have some HMs, right? Pokémon\n"
    .string "can't forget those moves easily.$"

Route14_Text_MitchIntro::
    .string "My bird Pokémon should be ready\n"
    .string "for battle.$"

Route14_Text_MitchDefeat::
    .string "Not ready yet!$"

Route14_Text_MitchPostBattle::
    .string "My bird Pokémon need to learn\n"
    .string "better moves.$"

Route14_Text_BeckIntro::
    .string "They have TMs on sale at the\n"
    .string "Celadon Dept. Store.\p"
    .string "TMs aren't really rare, but not\n"
    .string "many people have HMs.$"

Route14_Text_BeckDefeat::
    .string "Aww, bummer!$"

Route14_Text_BeckPostBattle::
    .string "Try teaching Pokémon a move that's\n"
    .string "the same type as it.\p"
    .string "That apparently boosts the power\n"
    .string "of the move.$"

Route14_Text_MarlonIntro::
    .string "Have you taught your bird Pokémon\n"
    .string "how to Fly?\p"
    .string "You'll be able to soar with it into\n"
    .string "the sky!$"

Route14_Text_MarlonDefeat::
    .string "Shot down in flames!$"

Route14_Text_MarlonPostBattle::
    .string "Bird Pokémon are my one true love.\n"
    .string "I don't want to raise anything else.$"

Route14_Text_MarlonRegister:
	.string "My bird Pokémon wish to battle again.\n"
	.string "Let's register each other!$"

Route14_Text_MarlonRematchIntro::
    .string "Have you taught your bird Pokémon\n"
    .string "how to Fly?\p"
    .string "You'll be able to soar with it into\n"
    .string "the sky! Give it a try.$"

Route14_Text_DonaldIntro::
    .string "Have you heard the legend of the\n"
    .string "winged mirages?$"

Route14_Text_DonaldDefeat::
    .string "Why?\n"
    .string "Why'd I lose?$"

Route14_Text_DonaldPostBattle::
    .string "Well, the winged mirages are the\n"
    .string "legendary bird Pokémon.\p"
    .string "There are three of them: Articuno,\n"
    .string "Zapdos, and Moltres.$"

Route14_Text_BennyIntro::
    .string "I'm not into it, but okay.\n"
    .string "Let's go!$"

Route14_Text_BennyDefeat::
    .string "I knew it!$"

Route14_Text_BennyPostBattle::
    .string "Winning, losing… It's insignificant\n"
    .string "under this huge sky.$"

Route14_Text_BennyRegister:
	.string "I'd like to register you in my Pokénav!$"

Route14_Text_BennyRematchIntro::
    .string "I'm really not into it, but okay.\n"
    .string "Let's go!$"

Route14_Text_LukasIntro::
    .string "C'mon, c'mon.\n"
    .string "Let's go, let's go, let's go!$"

Route14_Text_LukasDefeat::
    .string "Arrg!\n"
    .string "Lost! Get lost!$"

Route14_Text_LukasPostBattle::
    .string "What, what, what?\n"
    .string "What do you want still?$"

Route14_Text_LukasRegister:
	.string "That wasn't close to what I could\n"
	.string "do to show off my Pokémon.\p"
	.string "We must battle again!$"

Route14_Text_LukasRematchIntro::
    .string "Hey!\n"
    .string "I remember you!\p"
    .string "C'mon, c'mon.\n"
    .string "Let's go, let's go, let's go!$"

Route14_Text_IsaacIntro::
    .string "I need to burn some time.\n"
    .string "Shut up and battle.$"

Route14_Text_IsaacDefeat::
    .string "What?\n"
    .string "You!?$"

Route14_Text_IsaacPostBattle::
    .string "Raising Pokémon is a drag, man.$"

Route14_Text_GeraldIntro::
    .string "We ride out here because of the\n"
    .string "wide-open spaces.$"

Route14_Text_GeraldDefeat::
    .string "Wipeout!$"

Route14_Text_GeraldPostBattle::
    .string "It's cool you made your Pokémon so\n"
    .string "strong.\p"
    .string "Might is right!\n"
    .string "And you know it!$"

Route14_Text_MalikIntro::
    .string "Pokémon battle?\n"
    .string "Cool! Rumble!$"

Route14_Text_MalikDefeat::
    .string "Blown away!$"

Route14_Text_MalikPostBattle::
    .string "You know who'd win, you and me\n"
    .string "one-on-one!$"

Route14_Text_KiriIntro::
    .string "Kiri: Jan, let's try really,\n"
    .string "really hard together.$"

Route14_Text_KiriDefeat::
    .string "Kiri: Whimper…\n"
    .string "We lost, didn't we?$"

Route14_Text_KiriPostBattle::
    .string "Kiri: Did we lose because of me?$"

Route14_Text_KiriNotEnoughMons::
    .string "Kiri: We can battle if you have\n"
    .string "two Pokémon.$"

Route14_Text_JanIntro::
    .string "Jan: Kiri, here we go!\n"
    .string "We have to try hard!$"

Route14_Text_JanDefeat::
    .string "Jan: Eeeeh!\n"
    .string "No fair!$"

Route14_Text_JanPostBattle::
    .string "Jan: Kiri, don't cry!\n"
    .string "We'll just try harder next time.$"

Route14_Text_JanNotEnoughMons::
    .string "Jan: You want to battle?\n"
    .string "You don't have enough Pokémon.$"

Route15_Text_KindraIntro::
    .string "I just got some Pokémon in trades.\n"
    .string "Can I try them out on you?$"

Route15_Text_KindraDefeat::
    .string "Not good enough!$"

Route15_Text_KindraPostBattle::
    .string "You can't change the nickname of\n"
    .string "any Pokémon you get in a trade.\p"
    .string "Only the Original Trainer can get\n"
    .string "the nickname changed.$"

Route15_Text_BeckyIntro::
    .string "You look gentle, so I think I can\n"
    .string "beat you.\p"
    .string "I'll give it a go!$"

Route15_Text_BeckyDefeat::
    .string "No, wrong!$"

Route15_Text_BeckyPostBattle::
    .string "I'm afraid of Bikers. They look so\n"
    .string "ugly and mean!$"

Route15_Text_BeckyRegister:
	.string "You're not gentle but you are kind.\n"
	.string "You should come past again!$"

Route15_Text_BeckyRematchIntro::
    .string "You look gentle, so I think I can\n"
    .string "beat you.\p"
    .string "I'll give it one more go!$"

Route15_Text_EdwinIntro::
    .string "When I whistle, I can summon bird\n"
    .string "Pokémon.$"

Route15_Text_EdwinDefeat::
    .string "Ow!\n"
    .string "That's tragic!$"

Route15_Text_EdwinPostBattle::
    .string "Maybe I'm not cut out for battles.\n"
    .string "I'm not the right type, I guess.$"

Route15_Text_ChesterIntro::
    .string "Hmm? My birds are shivering!\n"
    .string "You're good, aren't you?$"

Route15_Text_ChesterDefeat::
    .string "Just as I thought!$"

Route15_Text_ChesterPostBattle::
    .string "This is so obvious, you should know\n"
    .string "this, but…\p"
    .string "Moves like Earthquake and Fissure\n"
    .string "have no effect on bird Pokémon.$"

Route15_Text_ChesterRegister:
	.string "My birds wish to battle you again!\p"
	.string "Please, come see me again for\n"
	.string "a rematch.$"

Route15_Text_ChesterRematchIntro::
    .string "Hmm? My birds are shivering!\n"
    .string "Wait, aren't you that Trainer…$"

Route15_Text_GraceIntro::
    .string "Oh, you're a little cutie!\n"
    .string "So like a darling Pokémon!$"

Route15_Text_GraceDefeat::
    .string "You looked so cute, too!$"

Route15_Text_GracePostBattle::
    .string "I forgive you.\n"
    .string "I can take it.\l"
    .string "I'm a big girl now.$"

Route15_Text_GraceRegister:
	.string "Your Pokêmon are cute too!\n"
	.string "Show them to me again soon.$"

Route15_Text_GraceRematchIntro::
    .string "Oh, you're a little cutie!\n"
    .string "So like a darling Pokémon!\l"
    .string "I remember you now!$"

Route15_Text_OliviaIntro::
    .string "I raise Pokémon for protection\n"
    .string "because I live alone.$"

Route15_Text_OliviaDefeat::
    .string "Pokémon isn't about winning or\n"
    .string "losing for me.$"

Route15_Text_OliviaPostBattle::
    .string "I love having my Pokémon greet me\n"
    .string "when I get home.\p"
    .string "It's so reassuring.$"

Route15_Text_ErnestIntro::
    .string "Hey, kid! C'mon!\n"
    .string "I just got these off some loser!$"

Route15_Text_ErnestDefeat::
    .string "Why not?$"

Route15_Text_ErnestPostBattle::
    .string "Life's too short.\n"
    .string "It's cool to live as an outlaw.\l"
    .string "Team Rocket rules!$"

Route15_Text_AlexIntro::
    .string "Fork over all your cash when you\n"
    .string "lose to me, kid!$"

Route15_Text_AlexDefeat::
    .string "That can't be true!$"

Route15_Text_AlexPostBattle::
    .string "I was just joking about the money.\n"
    .string "Don't take me all serious.$"

Route15_Text_CeliaIntro::
    .string "What's cool and happening?\n"
    .string "Trading Pokémon!$"

Route15_Text_CeliaDefeat::
    .string "I said trade!$"

Route15_Text_CeliaPostBattle::
    .string "I trade Pokémon with my friends\n"
    .string "all the time.$"

Route15_Text_YazminIntro::
    .string "Want to play with my Pokémon?$"

Route15_Text_YazminDefeat::
    .string "I was too impatient!$"

Route15_Text_YazminPostBattle::
    .string "I'll go train with weaker people.$"

Route15_Text_MyaIntro::
    .string "Mya: You're perfect.\n"
    .string "Help me train my little brother?$"

Route15_Text_MyaDefeat::
    .string "Mya: Ron, you have to focus!\n"
    .string "Concentrate on what you're doing!$"

Route15_Text_MyaPostBattle::
    .string "Mya: Okay, we'll turn it up.\n"
    .string "I'll add to our training menu!$"

Route15_Text_MyaRegister:
	.string "Mya: Really, we're a lot better…\n"
	.string "It's true! We'll show you next time!$"

Route15_Text_MyaRematchIntro::
    .string "Mya: Hi, we keep meeting,\n"
    .string "don't we?\p"
    .string "Help me train my little brother\n"
    .string "again?$"

Route15_Text_MyaNotEnoughMons::
    .string "Mya: Do you want to challenge us?\n"
    .string "You'll need two Pokémon, though.$"

Route15_Text_RonIntro::
    .string "Ron: My sister gets scary when we\n"
    .string "lose.$"

Route15_Text_RonDefeat::
    .string "Ron: Oh, no, no…\n"
    .string "Sis, I'm sorry!$"

Route15_Text_RonPostBattle::
    .string "Ron: Oh, bleah…\n"
    .string "I wish I had a nice sister…$"

Route15_Text_RonRematchIntro::
    .string "Ron: My sister's gotten more\n"
    .string "powerful…$"

Route15_Text_RonNotEnoughMons::
    .string "Ron: Did you want to battle with\n"
    .string "my sister and me?\p"
    .string "You need two Pokémon, then.$"

Route16_Text_LaoIntro::
    .string "What do you want?$"

Route16_Text_LaoDefeat::
    .string "Don't you dare laugh!$"

Route16_Text_LaoPostBattle::
    .string "We like just hanging here.\n"
    .string "What's it to you?$"

Route16_Text_LaoRematchIntro::
    .string "What do you want?$"

Route16_Text_KojiIntro::
    .string "Nice Bicycle!\n"
    .string "Hand it over!$"

Route16_Text_KojiDefeat::
    .string "Knockout!$"

Route16_Text_KojiPostBattle::
    .string "Forget it, who needs your bike!$"

Route16_Text_KojiRematchIntro::
    .string "Nice Bicycle!\n"
    .string "Hand it over quick!$"

Route16_Text_LukeIntro::
    .string "Come out and play, little mouse!$"

Route16_Text_LukeDefeat::
    .string "You little rat!$"

Route16_Text_LukePostBattle::
    .string "I hate losing!\n"
    .string "Get out of my face!$"

Route16_Text_LukeRematchIntro::
    .string "Come out and play, little mouse.\n"
    .string "I'll treat you right!$"

Route16_Text_HideoIntro::
    .string "Hey, you just bumped me!$"

Route16_Text_HideoDefeat::
    .string "Kaboom!$"

Route16_Text_HideoPostBattle::
    .string "We'll always be hanging around here\n"
    .string "even if you don't like it.\p"
    .string "You can detour to Vermilion from\n"
    .string "Fuchsia going along the coast.$"

Route16_Text_HideoRematchIntro::
    .string "Hey, wait a second!\n"
    .string "Don't call me and then run away!$"

Route16_Text_CamronIntro::
    .string "I'm feeling hungry and mean!\n"
    .string "I need a punching bag!$"

Route16_Text_CamronDefeat::
    .string "Bad, bad, bad!$"

Route16_Text_CamronPostBattle::
    .string "If I'm going to have Pokémon, they\n"
    .string "may as well be ferocious.\p"
    .string "I'd use them to leave my enemies\n"
    .string "in tatters.$"

Route16_Text_CamronRegister:
	.string "I only lost because I'm hungry!\n"
	.string "I will win next time!$"

Route16_Text_CamronRematchIntro::
    .string "I'm feeling hungry and mean!\n"
    .string "I really need a punching bag!$"

Route16_Text_RubenIntro::
    .string "Hey, there!\n"
    .string "Let's have ourselves a good time!$"

Route16_Text_RubenDefeat::
    .string "Don't make me mad!$"

Route16_Text_RubenPostBattle::
    .string "I get my kicks by harassing people\n"
    .string "with my stinking Pokémon.\p"
    .string "They're great for startling people.\n"
    .string "And, they bite, too.$"

Route16_Text_RubenRegister::
	.string "Register me in your Pokénav!\n"
	.string "I want to battle again!$"

Route16_Text_RubenRematchIntro::
    .string "Hey, there!\n"
    .string "We'll have ourselves a good time!$"

Route16_Text_JedIntro::
    .string "Jed: Our love knows no bounds.\n"
    .string "We're in love and we show it!$"

Route16_Text_JedDefeat::
    .string "Jed: Oh, no!\n"
    .string "My love has seen me as a loser!$"

Route16_Text_JedPostBattle::
    .string "Jed: Listen, Lea.\n"
    .string "You need to focus less on me.$"

Route16_Text_JedRematchIntro::
    .string "Jed: Are you here to see our\n"
    .string "love, which knows no bounds?$"

Route16_Text_JedNotEnoughMons::
    .string "Jed: You have just one Pokémon?\n"
    .string "Is there no love in your heart?$"

Route16_Text_LeaIntro::
    .string "Lea: Sometimes, the intensity of\n"
    .string "our love scares me.$"

Route16_Text_LeaDefeat::
    .string "Lea: Ohh! But Jed looks cool\n"
    .string "even in a loss!$"

Route16_Text_LeaPostBattle::
    .string "Lea: Ehehe, I'm sorry.\n"
    .string "Jed is so cool.$"

Route16_Text_LeaRematchIntro::
    .string "Lea: Sometimes, the intensity of\n"
    .string "our love scares me.$"

Route16_Text_LeaNotEnoughMons::
    .string "Lea: Oh, you don't have two\n"
    .string "Pokémon with you?\p"
    .string "Doesn't it feel lonely for you or\n"
    .string "your Pokémon?$"

Route17_Text_RaulIntro::
    .string "There's no getting rich quick in\n"
    .string "battling kids.$"

Route17_Text_RaulDefeat::
    .string "Burned out!$"

Route17_Text_RaulPostBattle::
    .string "You can find good stuff lying\n"
    .string "around on Cycling Road.\p"
    .string "There's good money in picking them\n"
    .string "up and selling them.$"

Route17_Text_IsaiahIntro::
    .string "I'm mighty proud of my bod, kiddo.\n"
    .string "Come on!$"

Route17_Text_IsaiahDefeat::
    .string "Whoo!$"

Route17_Text_IsaiahPostBattle::
    .string "I could belly-bump you outta\n"
    .string "here!$"

Route17_Text_IsaiahRegister:
	.string "You're good to train against.\p"
	.string "We should battle again so\n"
	.string "I can keep in shape!$"

Route17_Text_IsaiahRematchIntro::
    .string "I'm mighty proud of my bod, kiddo.\n"
    .string "Come on!$"

Route17_Text_VirgilIntro::
    .string "You heading to Fuchsia?$"

Route17_Text_VirgilDefeat::
    .string "Crash and burn!$"

Route17_Text_VirgilPostBattle::
    .string "I love racing downhill!$"

Route17_Text_BillyIntro::
    .string "We're Bikers!\n"
    .string "We rule the roads, man!$"

Route17_Text_BillyDefeat::
    .string "Smoked!$"

Route17_Text_BillyPostBattle::
    .string "Are you looking for adventure?$"

Route17_Text_NikolasIntro::
    .string "Let Voltorb electrify you!$"

Route17_Text_NikolasDefeat::
    .string "Grounded out!$"

Route17_Text_NikolasPostBattle::
    .string "I got my Voltorb at the abandoned\n"
    .string "Power Plant.$"

Route17_Text_ZeekIntro::
    .string "I leveled up my Pokémon, but it\n"
    .string "won't evolve. Why?$"

Route17_Text_ZeekDefeat::
    .string "Why, you!$"

Route17_Text_ZeekPostBattle::
    .string "Maybe some Pokémon need element\n"
    .string "stones to evolve.$"

Route17_Text_JamalIntro::
    .string "I need a little exercise!$"

Route17_Text_JamalDefeat::
    .string "Whew!\n"
    .string "Good workout!$"

Route17_Text_JamalPostBattle::
    .string "I'm sure I lost weight there!$"

Route17_Text_CoreyIntro::
    .string "Be a rebel!$"

Route17_Text_CoreyDefeat::
    .string "Aaaargh!$"

Route17_Text_CoreyPostBattle::
    .string "Be ready to fight for your beliefs!$"

Route17_Text_CoreyRegister:
	.string "Let's have a rematch on Cycling Road.$"

Route17_Text_CoreyRematchIntro::
    .string "Be a rebel!$"

Route17_Text_JaxonIntro::
    .string "Nice bike!\n"
    .string "How's it handle?$"

Route17_Text_JaxonDefeat::
    .string "Shoot!$"

Route17_Text_JaxonPostBattle::
    .string "The slope makes it hard to steer.$"

Route17_Text_JaxonRegister:
	.string "How would you like to battle again?$"

Route17_Text_JaxonRematchIntro::
    .string "Yep, that's a nice bike!\n"
    .string "How's it handle?$"

Route17_Text_WilliamIntro::
    .string "Get lost, kid!\n"
    .string "I'm bushed!$"

Route17_Text_WilliamDefeat::
    .string "Are you satisfied?$"

Route17_Text_WilliamPostBattle::
    .string "I need to catch a few z's!$"
    
Route18_Text_WiltonIntro::
    .string "I always check every grassy area\n"
    .string "for new Pokémon.$"

Route18_Text_WiltonDefeat::
    .string "Tch!$"

Route18_Text_WiltonPostBattle::
    .string "I wish I had a bike!$"

Route18_Text_RamiroIntro::
    .string "Kurukkoo!\n"
    .string "How do you like my birdcall?$"

Route18_Text_RamiroDefeat::
    .string "I had to bug you!$"

Route18_Text_RamiroPostBattle::
    .string "I collect sea Pokémon on weekends\n"
    .string "because the sea is so close.$"

Route18_Text_JacobIntro::
    .string "This is my turf!\n"
    .string "Get out of here!$"

Route18_Text_JacobDefeat::
    .string "Darn!$"

Route18_Text_JacobPostBattle::
    .string "This is my fave area for catching\n"
    .string "Pokémon.$"

Route18_Text_JacobRegister:
	.string "I'll call you for a rematch sometime.\n"
    .string "Koorukukukoo!$"

Route18_Text_JacobRematchIntro::
    .string "I warned you before, this is my\n"
    .string "turf!\p"
    .string "I don't want you coming around.$"

Route19_Text_RichardIntro::
    .string "I have to exercise and warm up\n"
    .string "before going out for a swim.$"

Route19_Text_RichardDefeat::
    .string "All warmed up!$"

Route19_Text_RichardPostBattle::
    .string "Thanks, kid!\n"
    .string "I'm ready for a swim.$"

Route19_Text_ReeceIntro::
    .string "Wait! Slow down!\n"
    .string "You'll have a heart attack!$"

Route19_Text_ReeceDefeat::
    .string "Ooh!\n"
    .string "That's chilly!$"

Route19_Text_ReecePostBattle::
    .string "Watch out for Tentacool.\n"
    .string "They sting so painfully.$"

Route19_Text_MatthewIntro::
    .string "I love swimming!\n"
    .string "What about you?$"

Route19_Text_MatthewDefeat::
    .string "Belly flop!$"

Route19_Text_MatthewPostBattle::
    .string "I can beat even marine Pokémon\n"
    .string "at swimming.$"

Route19_Text_MatthewRegister:
	.string "Yep, you're not bad at all!\n"
	.string "I'd like to get to know you more!$"

Route19_Text_MatthewRematchIntro::
    .string "I love swimming!\n"
    .string "I guess you're the surfing type.$"

Route19_Text_DouglasIntro::
    .string "What's beyond the horizon?$"

Route19_Text_DouglasDefeat::
    .string "Glub!$"

Route19_Text_DouglasPostBattle::
    .string "I see a couple of islands over\n"
    .string "yonder!$"

Route19_Text_DavidIntro::
    .string "I tried diving for Pokémon, but it\n"
    .string "was a no-go.$"

Route19_Text_DavidDefeat::
    .string "Help!$"

Route19_Text_DavidPostBattle::
    .string "I guess you have to fish for sea\n"
    .string "Pokémon.$"

Route19_Text_TonyIntro::
    .string "I look at the sea to forget all\n"
    .string "the bad things that happened.$"

Route19_Text_TonyDefeat::
    .string "Ooh!\n"
    .string "Traumatic!$"

Route19_Text_TonyPostBattle::
    .string "I'm looking at the sea to forget\n"
    .string "the bad thing that happened!$"

Route19_Text_TonyRegister:
	.string "I'll keep chugging on without stressing.\n"
	.string "Give me a shout if you're up to it.$"

Route19_Text_TonyRematchIntro::
    .string "I look at the sea to forget all\n"
    .string "the bad things that happened.\p"
    .string "…Like losing to you the last time!$"

Route19_Text_AnyaIntro::
    .string "Oh, I just love your ride!\n"
    .string "Can I have it if I win?$"

Route19_Text_AnyaDefeat::
    .string "Oh! I lost!$"

Route19_Text_AnyaPostBattle::
    .string "It's still a long way to go to\n"
    .string "Seafoam Islands…\p"
    .string "I want to go back to Fuchsia…$"

Route19_Text_AliceIntro::
    .string "Swimming's great!\n"
    .string "Sunburns aren't!$"

Route19_Text_AliceDefeat::
    .string "Shocker!$"

Route19_Text_AlicePostBattle::
    .string "My boyfriend wanted to swim to\n"
    .string "Seafoam Islands.$"

Route19_Text_AliceRegister:
	.string "I want to know more about your power.\n"
	.string "Let me register you in my Pokénav.$"

Route19_Text_AliceRematchIntro::
    .string "Swimming's great!\n"
    .string "Sunburns aren't!$"

Route19_Text_AxleIntro::
    .string "Ahoy, there!\n"
    .string "These waters are treacherous!$"

Route19_Text_AxleDefeat::
    .string "Ooh!\n"
    .string "Dangerous!$"

Route19_Text_AxlePostBattle::
    .string "M-my legs! They cramped up!\n"
    .string "Glub, glub…$"

Route19_Text_ConnieIntro::
    .string "I swam here with my friends…\n"
    .string "I'm tired…$"

Route19_Text_ConnieDefeat::
    .string "I'm exhausted…$"

Route19_Text_ConniePostBattle::
    .string "If I were to ride a Pokémon on\n"
    .string "the sea, I'd like a Lapras.\p"
    .string "Lapras is so big, I bet it\n"
    .string "would keep me dry on water.$"

Route19_Text_LiaIntro::
    .string "Lia: I'm looking after my brother.\n"
    .string "He just became a Trainer.$"

Route19_Text_LiaDefeat::
    .string "Lia: That's no way to treat my\n"
    .string "little brother!$"

Route19_Text_LiaPostBattle::
    .string "Lia: Do you have a younger\n"
    .string "brother?\p"
    .string "I hope you're teaching him all\n"
    .string "sorts of things.$"

Route19_Text_LiaNotEnoughMons::
    .string "Lia: I want to battle together\n"
    .string "with my little brother.\p"
    .string "Don't you have two Pokémon?$"

Route19_Text_LucIntro::
    .string "Luc: My big sis taught me how\n"
    .string "to swim and train Pokémon.$"

Route19_Text_LucDefeat::
    .string "Luc: Oh, wow!\n"
    .string "Someone tougher than my big sis!$"

Route19_Text_LucPostBattle::
    .string "Luc: My big sis is strong and nice.\n"
    .string "I think she's awesome!$"

Route19_Text_LucNotEnoughMons::
    .string "Luc: I don't want to if I can't\n"
    .string "battle you with my big sis.\p"
    .string "Don't you have two Pokémon?$"
    
Route20_Text_BarryIntro::
    .string "The water is shallow here.\n"
    .string "There are many people swimming.$"

Route20_Text_BarryDefeat::
    .string "Splash!$"

Route20_Text_BarryPostBattle::
    .string "I wish I could ride my Pokémon.\n"
    .string "I bet you're not tired.$"

Route20_Text_ShirleyIntro::
    .string "Seafoam is a quiet getaway.\n"
    .string "I'm vacationing here.$"

Route20_Text_ShirleyDefeat::
    .string "Quit it!$"

Route20_Text_ShirleyPostBattle::
    .string "There's a huge cavern underneath\n"
    .string "this island.$"

Route20_Text_TiffanyIntro::
    .string "I love floating with the fishes\n"
    .string "here among the waves.$"

Route20_Text_TiffanyDefeat::
    .string "Yowch!$"

Route20_Text_TiffanyPostBattle::
    .string "Want to float with me?$"

Route20_Text_IreneIntro::
    .string "Are you on vacation, too?$"

Route20_Text_IreneDefeat::
    .string "No mercy at all!$"

Route20_Text_IrenePostBattle::
    .string "Seafoam used to be a single island\n"
    .string "in the distant past.$"

Route20_Text_DeanIntro::
    .string "Check out my buff physique!$"

Route20_Text_DeanDefeat::
    .string "Wimpy!$"

Route20_Text_DeanPostBattle::
    .string "I should've been buffing up my\n"
    .string "Pokémon, not me!$"

Route20_Text_DarrinIntro::
    .string "Why are you riding a Pokémon?\n"
    .string "Can't you swim?$"

Route20_Text_DarrinDefeat::
    .string "Ouch!\n"
    .string "Torpedoed!$"

Route20_Text_DarrinPostBattle::
    .string "Riding a Pokémon sure looks fun!$"

Route20_Text_DarrinRegister:
	.string "We should battle again!$"

Route20_Text_DarrinRematchIntro::
    .string "Why are you riding a Pokémon?\n"
    .string "Haven't you learned to swim yet?$"

Route20_Text_RogerIntro::
    .string "I rode my bird Pokémon here.$"

Route20_Text_RogerDefeat::
    .string "Oh, no!\n"
    .string "Now what am I to do?$"

Route20_Text_RogerPostBattle::
    .string "My birds are exhausted.\n"
    .string "They can't Fly me back!$"

Route20_Text_NoraIntro::
    .string "My boyfriend gave me big pearls.$"

Route20_Text_NoraDefeat::
    .string "Oh, no!\n"
    .string "My pearls were in them!$"

Route20_Text_NoraPostBattle::
    .string "Will my pearls grow bigger inside\n"
    .string "Cloyster?$"

Route20_Text_MissyIntro::
    .string "I swam here from Cinnabar Island.\n"
    .string "It wasn't easy, I tell you.$"

Route20_Text_MissyDefeat::
    .string "I'm so disappointed!$"

Route20_Text_MissyPostBattle::
    .string "Pokémon have taken over an\n"
    .string "abandoned mansion on Cinnabar.\p"
    .string "They call it the Pokémon Mansion\n"
    .string "now.$"

Route20_Text_MissyRegister:
	.string "If ever you're near Cinnabar,\n"
	.string "I'd like to battle you again.$"

Route20_Text_MissyRematchIntro::
    .string "I swam here from Cinnabar Island.\n"
    .string "It wasn't easy, like I said.$"

Route20_Text_MelissaIntro::
    .string "Cinnabar, in the west, has a lab\n"
    .string "for Pokémon.\p"
    .string "My daddy works there.$"

Route20_Text_MelissaDefeat::
    .string "Wait!\n"
    .string "You're supposed to wait!$"

Route20_Text_MelissaPostBattle::
    .string "Cinnabar is a volcanic island.\p"
    .string "I heard it rose out of the sea\n"
    .string "when a volcano erupted.$"

Route20_Text_MelissaRegister:
	.string "Here, let me register you\n"
	.string "in my Pokénav.$"

Route20_Text_MelissaRematchIntro::
    .string "Cinnabar, in the west, has a lab\n"
    .string "for Pokémon.\p"
    .string "My daddy works there.$"

Route21_Text_RonaldIntro::
    .string "You want to know if the fish are\n"
    .string "biting?$"

Route21_Text_RonaldDefeat::
    .string "Dang!$"

Route21_Text_RonaldPostBattle::
    .string "I can't catch anything good.\n"
    .string "Not one good Pokémon to be had!$"

Route21_Text_WadeIntro::
    .string "I got a big haul!\n"
    .string "Wanna go for it?$"

Route21_Text_WadeDefeat::
    .string "Heheh, Magikarp just don't make\n"
    .string "the grade, do they?$"

Route21_Text_WadePostBattle::
    .string "I seem to only catch Magikarp!$"

Route21_Text_WadeRegister:
	.string "It's only on a whim, but maybe I'll get\n"
	.string "you to register me in your Pokénav.$"

Route21_Text_WadeRematchIntro::
    .string "I got a big haul again!\n"
    .string "Wanna go for it once more?$"

Route21_Text_SpencerIntro::
    .string "The sea cleanses my body and soul!$"

Route21_Text_SpencerDefeat::
    .string "Ayah!$"

Route21_Text_SpencerPostBattle::
    .string "The sea is great and all, but I\n"
    .string "like the mountains, too.$"

Route21_Text_JackIntro::
    .string "I caught my Pokémon at sea.$"

Route21_Text_JackDefeat::
    .string "Diver!!\n"
    .string "Down!!$"

Route21_Text_JackPostBattle::
    .string "Where'd you catch your Pokémon?$"

Route21_Text_JackRegister:
	.string "Will you ever be back in this area?\n"
	.string "If you do return, I'd like a rematch.$"

Route21_Text_JackRematchIntro::
    .string "I caught my Pokémon at sea.\n"
    .string "And that's where I train them.$"

Route21_Text_JeromeIntro::
    .string "Right now, I'm in a triathlon meet.$"

Route21_Text_JeromeDefeat::
    .string "Pant…\n"
    .string "Pant… Pant…$"

Route21_Text_JeromePostBattle::
    .string "I'm beat! But, I still have the\n"
    .string "bike race and marathon left!$"

Route21_Text_RolandIntro::
    .string "Ahh!\n"
    .string "Feel the sun and the wind!$"

Route21_Text_RolandDefeat::
    .string "Yow!\n"
    .string "I lost!$"

Route21_Text_RolandPostBattle::
    .string "I'm sunburnt to a crisp!$"

Route21_Text_ClaudeIntro::
    .string "Hey, don't scare away the fish!$"

Route21_Text_ClaudeDefeat::
    .string "Sorry! I'm just so frustrated from\n"
    .string "not catching anything.$"

Route21_Text_ClaudePostBattle::
    .string "Sheesh, I haven't caught a thing.\n"
    .string "Could this place actually be a\l"
    .string "giant pool or something?$"

Route21_Text_NolanIntro::
    .string "Keep me company till I get a hit.$"

Route21_Text_NolanDefeat::
    .string "That burned some time.$"

Route21_Text_NolanPostBattle::
    .string "Oh wait!\n"
    .string "I got a bite! Yeah!$"

Route21_Text_LilIntro::
    .string "Lil: Huh? A battle?\n"
    .string "Ian, can't you do it alone?$"

Route21_Text_LilDefeat::
    .string "Lil: Oh, see?\n"
    .string "We lost. Happy now?$"

Route21_Text_LilPostBattle::
    .string "Lil: I'm tired.\n"
    .string "Can't we go home already?$"

Route21_Text_LilRematchIntro::
    .string "Lil: Huh? A battle again?\n"
    .string "Ian, can't you do it alone?$"

Route21_Text_LilNotEnoughMons::
    .string "Lil: Huh? A battle?\n"
    .string "I can't be bothered to do it alone.\l"
    .string "Bring two Pokémon, won't you?$"

Route21_Text_IanIntro::
    .string "Ian: My sis doesn't get enough\n"
    .string "exercise, so I made her come.$"

Route21_Text_IanDefeat::
    .string "Ian: Awww, Sis!\n"
    .string "Get it together!$"

Route21_Text_IanPostBattle::
    .string "Ian: Come on, Sis!\p"
    .string "You're not going to lose weight\n"
    .string "like this!$"

Route21_Text_IanRegister:
	.string "Ian: Oh, you are good exercise!\n"
	.string "Can we battle you again?$"

Route21_Text_IanRematchIntro::
    .string "Ian: My sis is still a slob.\n"
    .string "Help me get her into shape!$"

Route21_Text_IanNotEnoughMons::
    .string "Ian: We want a two-on-two battle.\n"
    .string "So can you bring two Pokémon?$"

Route24_Text_ShaneIntro::
    .string "I saw your feat from the grass!$"

Route24_Text_ShaneDefeat::
    .string "I thought not!$"

Route24_Text_ShanePostBattle::
    .string "I hid because the people on the\n"
    .string "bridge frightened me.$"

Route24_Text_EthanIntro::
    .string "Okay! I'm No. 5!\n"
    .string "I'll stomp you!$"

Route24_Text_EthanDefeat::
    .string "Whoa!\n"
    .string "Too much!$"

Route24_Text_EthanPostBattle::
    .string "I did my best. I have no regrets!$"

Route24_Text_ReliIntro::
    .string "I'm No. 4!\n"
    .string "Getting tired?$"

Route24_Text_ReliDefeat::
    .string "I lost, too!$"

Route24_Text_ReliPostBattle::
    .string "I did my best, so I've no regrets!$"

Route24_Text_ReliRegister:
	.string "Will you battle with me again?\n"
	.string "But take it easy next time, okay?$"

Route24_Text_ReliRematchIntro::
    .string "You always look so busy…\n"
    .string "Aren't you getting tired?$"

Route24_Text_TimmyIntro::
    .string "Here's No. 3!\n"
    .string "I won't be easy!$"

Route24_Text_TimmyDefeat::
    .string "Ow!\n"
    .string "Stomped flat!$"

Route24_Text_TimmyPostBattle::
    .string "I did my best. I have no regrets!$"

Route24_Text_TimmyRegister:
	.string "You should come visit\n"
	.string "us again soon.$"

Route24_Text_TimmyRematchIntro::
    .string "You really must love coming to\n"
    .string "Nugget Bridge.$"

Route24_Text_AliIntro::
    .string "I'm second!\n"
    .string "Now it's serious!$"

Route24_Text_AliDefeat::
    .string "How could I lose?$"

Route24_Text_AliPostBattle::
    .string "I did my best. I have no regrets!$"

Route24_Text_CaleIntro::
    .string "People call this the Nugget\n"
    .string "Bridge!\p"
    .string "Beat us five Trainers and win\n"
    .string "a fabulous prize!\p"
    .string "Think you got what it takes?$"

Route24_Text_CaleDefeat::
    .string "Whoo!\n"
    .string "Good stuff!$"

Route24_Text_CalePostBattle::
    .string "I did my best. I have no regrets!$"

Route25_Text_JoeyIntro::
    .string "Local Trainers come here to\n"
    .string "practice.$"

Route25_Text_JoeyDefeat::
    .string "You're decent.$"

Route25_Text_JoeyPostBattle::
    .string "All Pokémon have weaknesses.\n"
    .string "Even the strongest ones.\p"
    .string "That's why it's best to raise\n"
    .string "Pokémon of different types.$"

Route25_Text_DanIntro::
    .string "Dad took me to a great party on\n"
    .string "the S.S. Anne at Vermilion City.$"

Route25_Text_DanDefeat::
    .string "I'm not mad!$"

Route25_Text_DanPostBattle::
    .string "On the S.S. Anne, I saw Trainers\n"
    .string "from around the world.$"

Route25_Text_FlintIntro::
    .string "I'm a cool guy.\n"
    .string "I've got a girlfriend!$"

Route25_Text_FlintDefeat::
    .string "Aww, darn…$"

Route25_Text_FlintPostBattle::
    .string "Oh, well.\n"
    .string "My girlfriend will cheer me up.$"

Route25_Text_KelseyIntro::
    .string "Hi!\n"
    .string "My boyfriend is cool!$"

Route25_Text_KelseyDefeat::
    .string "My conditioning isn't the best…$"

Route25_Text_KelseyPostBattle::
    .string "I wish my boyfriend was as good\n"
    .string "as you.$"

Route25_Text_KelseyRegister:
	.string "I wish I could become friends with\n"
	.string "more strong people like you!$"

Route25_Text_KelseyRematchIntro::
    .string "Hi!\n"
    .string "My boyfriend is cool!\l"
    .string "My conditioning's good today!$"

Route25_Text_ChadIntro::
    .string "I had this feeling…\n"
    .string "I knew I had to battle you!$"

Route25_Text_ChadDefeat::
    .string "I knew I'd lose, too!$"

Route25_Text_ChadPostBattle::
    .string "If your Pokémon gets confused,\n"
    .string "switch it out.\p"
    .string "That's a good tactic.$"

Route25_Text_ChadRegister:
	.string "I have this feeling…\n"
	.string "I must battle you again!$"

Route25_Text_ChadRematchIntro::
    .string "I had this feeling…\n"
    .string "I knew I had to battle you again!$"

Route25_Text_HaleyIntro::
    .string "My friend has many cute Pokémon.\n"
    .string "I'm so jealous!$"

Route25_Text_HaleyDefeat::
    .string "I'm not so jealous!$"

Route25_Text_HaleyPostBattle::
    .string "You came from Mt. Moon?\n"
    .string "May I have a Clefairy?$"

Route25_Text_FranklinIntro::
    .string "I just got down from Mt. Moon,\n"
    .string "but I've still got gas in the tank!$"

Route25_Text_FranklinDefeat::
    .string "You worked hard!$"

Route25_Text_FranklinPostBattle::
    .string "Drat!\n"
    .string "A Zubat bit me back in that cave.$"

Route25_Text_FranklinRegister:
	.string "That was total humiliation!\n"
	.string "I won't forget you…\l"
	.string "Hand over your Pokénav!$"

Route25_Text_FranklinRematchIntro::
    .string "I just trained up on Mt. Moon,\n"
    .string "but I've still got gas in the tank!$"

Route25_Text_NobIntro::
    .string "I'm off to see a Pokémaniac's\n"
    .string "collection at the cape.$"

Route25_Text_NobDefeat::
    .string "You done got me, and real good,\n"
    .string "too!$"

Route25_Text_NobPostBattle::
    .string "The Pokémaniac sure lives up to\n"
    .string "his name.\p"
    .string "His collection includes many rare\n"
    .string "species of Pokémon.$"

Route25_Text_WayneIntro::
    .string "You're going to see Bill?\n"
    .string "First, we battle!$"

Route25_Text_WayneDefeat::
    .string "You're something.$"

Route25_Text_WaynePostBattle::
    .string "The trail below is a shortcut to\n"
    .string "Cerulean City.$"

TreasureBeach_Text_AmaraIntro::
    .string "Lying back, rocked by the waves…\n"
    .string "It's exquisite.$"

TreasureBeach_Text_AmaraDefeat::
    .string "I lost…\n"
    .string "It feels awful.$"

TreasureBeach_Text_AmaraPostBattle::
    .string "The sea is pleasantly warm in these\n"
    .string "parts.$"

KindleRoad_Text_MariaIntro::
    .string "The weather's gorgeous!\n"
    .string "Perfect for a battle!$"

KindleRoad_Text_MariaDefeat::
    .string "Aiyeeeeh!$"

KindleRoad_Text_MariaPostBattle::
    .string "Please don't splash my face!\n"
    .string "You'll ruin the makeup.$"

KindleRoad_Text_AbigailIntro::
    .string "I'm beginning to get a sunburn…$"

KindleRoad_Text_AbigailDefeat::
    .string "Oh, you're so awful.$"

KindleRoad_Text_AbigailPostBattle::
    .string "I like that cap you have.\n"
    .string "Maybe I should wear one, too…$"

KindleRoad_Text_FinnIntro::
    .string "Seen from here, Mt. Ember towers\n"
    .string "into the sky.$"

KindleRoad_Text_FinnDefeat::
    .string "Well, aren't you tough?$"

KindleRoad_Text_FinnPostBattle::
    .string "The sky is immense around these\n"
    .string "parts.$"

KindleRoad_Text_FinnRegister:
	.string "I would like to see your Pokémon\n"
	.string "when they grow up some more…\p"
	.string "Please, I need to see your Pokénav.$"

KindleRoad_Text_FinnRematchIntro::
    .string "The fire bird's mountain casts\n"
    .string "a huge shadow…$"

KindleRoad_Text_GarrettIntro::
    .string "I took a break from swimming,\n"
    .string "only to have you challenge me?$"

KindleRoad_Text_GarrettDefeat::
    .string "Hey, what the…\n"
    .string "You're good, you!$"

KindleRoad_Text_GarrettPostBattle::
    .string "Instead of using Surf all the time,\n"
    .string "you should swim some.$"

KindleRoad_Text_TommyIntro::
    .string "Wait! Wait a second!\n"
    .string "I think I've hooked a big one!$"

KindleRoad_Text_TommyDefeat::
    .string "I've lost it all again…$"

KindleRoad_Text_TommyPostBattle::
    .string "Not only did I lose, the big one\n"
    .string "got away from me, too!$"

KindleRoad_Text_SharonIntro::
    .string "Could you help me out with my\n"
    .string "training?$"

KindleRoad_Text_SharonDefeat::
    .string "You were a cut above me.$"

KindleRoad_Text_SharonPostBattle::
    .string "It's clear that you're skilled.\n"
    .string "I like you!$"

KindleRoad_Text_SharonRegister:
	.string "I'm going to redouble my training.\n"
	.string "Would you come look in on us?$"

KindleRoad_Text_SharonRematchIntro::
    .string "You'll help me out with my\n"
    .string "training again?$"

KindleRoad_Text_TanyaIntro::
    .string "There isn't a day in which we don't\n"
    .string "train!$"

KindleRoad_Text_TanyaDefeat::
    .string "I'm such a fool!$"

KindleRoad_Text_TanyaPostBattle::
    .string "I'll train even harder from now on!$"

KindleRoad_Text_TanyaRegister:
	.string "I feel great after battling you!\n"
	.string "If you don't mind, can we meet again?$"

KindleRoad_Text_TanyaRematchIntro::
    .string "We haven't missed a single day of\n"
    .string "training yet!$"

KindleRoad_Text_SheaIntro::
    .string "Every morning, before breakfast,\n"
    .string "I swim around this island.$"

KindleRoad_Text_SheaDefeat::
    .string "Gasp…\n"
    .string "Gasp…$"

KindleRoad_Text_SheaPostBattle::
    .string "I lost because I'm pooped from all\n"
    .string "the running I did…$"

KindleRoad_Text_SheaRegister:
	.string "I'm glad I met a superb Trainer in you.\n"
	.string "I hope to see you again.$"

KindleRoad_Text_SheaRematchIntro::
    .string "Every morning, before breakfast,\n"
    .string "I swim around this island…\l"
    .string "Three times!$"

KindleRoad_Text_HughIntro::
    .string "Dress appropriately for battle!\n"
    .string "Lose that frivolous outfit!$"

KindleRoad_Text_HughDefeat::
    .string "Why me?!$"

KindleRoad_Text_HughPostBattle::
    .string "Even martial artists are becoming\n"
    .string "fashion conscious these days…$"

KindleRoad_Text_HughRegister:
	.string "Register me and I will help\n"
	.string "you with your fashion choice!$"

KindleRoad_Text_HughRematchIntro::
    .string "Dress appropriately for battle!\n"
    .string "Lose that frivolous outfit, I said!$"

KindleRoad_Text_BryceIntro::
    .string "You know, everything tastes great\n"
    .string "when you're out in the wild.$"

KindleRoad_Text_BryceDefeat::
    .string "Awww, blown!$"

KindleRoad_Text_BrycePostBattle::
    .string "The water in volcanic regions is\n"
    .string "delicious.$"

KindleRoad_Text_ClaireIntro::
    .string "My lunch filled us up, so will you\n"
    .string "battle us for some exercise?$"

KindleRoad_Text_ClaireDefeat::
    .string "That made me all sweaty.$"

KindleRoad_Text_ClairePostBattle::
    .string "What should I do?\n"
    .string "I feel famished again.$"

KindleRoad_Text_KiaIntro::
    .string "Kia: My big brother and I make\n"
    .string "an awesome combination!$"

KindleRoad_Text_KiaDefeat::
    .string "Kia: Huh?!\n"
    .string "I can't believe it!$"

KindleRoad_Text_KiaPostBattle::
    .string "Kia: How could there be anyone\n"
    .string "better than my big brother?$"

KindleRoad_Text_KiaRegister:
	.string "Kia: How did Mik and I lose to you!\n"
	.string "Can we have a battle again?$"

KindleRoad_Text_KiaRematchIntro::
    .string "Kia: My big brother and I make\n"
    .string "an awesome combination!\p"
    .string "We won't lose this time!$"

KindleRoad_Text_KiaNotEnoughMons::
    .string "Kia: If you want to battle with\n"
    .string "us, you have to bring at least two\l"
    .string "Pokémon with you.$"

KindleRoad_Text_MikIntro::
    .string "Mik: Together with Kia, I'm afraid\n"
    .string "of nothing!$"

KindleRoad_Text_MikDefeat::
    .string "Mik: Whoa!\n"
    .string "That's too much!$"

KindleRoad_Text_MikPostBattle::
    .string "Mik: How could my combination\n"
    .string "with Kia fail?$"

KindleRoad_Text_MikRegister:
	.string "Mik: How did Kia and I lose to you!\n"
	.string "Can we have a battle again?$"

KindleRoad_Text_MikRematchIntro::
    .string "Mik: Together with Kia, we're\n"
    .string "afraid of nothing!\p"
    .string "We'll prove it to you this time!$"

KindleRoad_Text_MikNotEnoughMons::
    .string "Mik: Hey, do you want to battle\n"
    .string "with us two?\p"
    .string "Bring two or more Pokémon with\n"
    .string "you, then.$"

BondBridge_Text_NikkiIntro::
    .string "The salty tang of the sea…\n"
    .string "It tickles my heart.$"

BondBridge_Text_NikkiDefeat::
    .string "…Sniff, sniff…\n"
    .string "Something smells unpleasant…$"

BondBridge_Text_NikkiPostBattle::
    .string "Perhaps that reek is your sweaty\n"
    .string "Pokémon's body odour…$"

BondBridge_Text_VioletIntro::
    .string "Where are you off to in such\n"
    .string "a hurry?$"

BondBridge_Text_VioletDefeat::
    .string "You're raising some wonderful\n"
    .string "Pokémon.$"

BondBridge_Text_VioletPostBattle::
    .string "If you keep going this way, you'll\n"
    .string "eventually reach Berry Forest.$"

BondBridge_Text_AmiraIntro::
    .string "My mommy said that I can't swim\n"
    .string "without my float ring.$"

BondBridge_Text_AmiraDefeat::
    .string "Waaah!\n"
    .string "Waaah!$"

BondBridge_Text_AmiraPostBattle::
    .string "This year, I'm going to finally\n"
    .string "learn how to swim!$"

BondBridge_Text_AmiraRegister:
	.string "Do you have a Pokénav?\n"
	.string "It's a must-have tool for any Trainer.\p"
	.string "Oh, you do have one!\n"
	.string "Let's register each other, then!$"

BondBridge_Text_AmiraRematchIntro::
	.string "I want to swim without my float\n"
	.string "ring soon.$"

BondBridge_Text_AlexisIntro::
    .string "Yay, yay!\n"
    .string "Pokémon!$"

BondBridge_Text_AlexisDefeat::
    .string "What happens now?$"

BondBridge_Text_AlexisPostBattle::
    .string "Did I just win?\n"
    .string "Or did I lose?$"

BondBridge_Text_TishaIntro::
    .string "Oh, no, don't come here!\n"
    .string "Please, stay away from me!$"

BondBridge_Text_TishaDefeat::
    .string "Okay, you've won!\n"
    .string "Now will you please go away?$"

BondBridge_Text_TishaPostBattle::
    .string "A Pokémon bit through my \n"
    .string "swimsuit.\p"
    .string "I can't get out of the water!$"

BondBridge_Text_JoyIntro::
    .string "Joy: We'll teach you what our\n"
    .string "favourite Pokémon is!$"

BondBridge_Text_JoyDefeat::
    .string "Joy: Ohh…\n"
    .string "Meg!$"

BondBridge_Text_JoyPostBattle::
    .string "Joy: Wasn't that fun?\n"
    .string "I hope we can battle again!$"

BondBridge_Text_JoyMegRegister:
	.string "Joy: Really, we're a lot better…\n"
	.string "It's true! We'll show you next time!$"

BondBridge_Text_JoyRematchIntro::
	.string "Joy: We've gotten stronger!\n"
	.string "Lots and lots!$"

BondBridge_Text_JoyNotEnoughMons::
    .string "Joy: I really want to battle with\n"
    .string "Meg.\p"
    .string "One Pokémon isn't enough.$"

BondBridge_Text_MegIntro::
    .string "Meg: We'll show you our favourite\n"
    .string "Pokémon.$"

BondBridge_Text_MegDefeat::
    .string "Meg: Ohh…\n"
    .string "Joy!$"

BondBridge_Text_MegPostBattle::
    .string "Meg: Joy, wasn't that fun?$"

BondBridge_Text_MegRematchIntro::
	.string "Meg: You can't beat us today!$"

BondBridge_Text_MegNotEnoughMons::
    .string "Meg: I want to battle together\n"
    .string "with Joy.\p"
    .string "One Pokémon isn't enough.$"

FiveIsland_Meadow_Text_Rocket1Intro::
    .string "This area's strictly off-limits!\n"
    .string "Out, out!$"

FiveIsland_Meadow_Text_Rocket1Defeat::
    .string "Is this for real?$"

FiveIsland_Meadow_Text_Rocket1PostBattle::
    .string "You don't have any business here!\n"
    .string "Go home!$"

FiveIsland_Meadow_Text_Rocket2Intro::
    .string "There's nothing past here except\n"
    .string "our Warehouse.\p"
    .string "So what brings you here?$"

FiveIsland_Meadow_Text_Rocket2Defeat::
    .string "That wasn't supposed to happen…$"

FiveIsland_Meadow_Text_Rocket2PostBattle::
    .string "You're wanting to know what's inside\n"
    .string "this Warehouse?\p"
    .string "It's better you didn't know.\n"
    .string "For your own sake, I mean.$"

FiveIsland_Meadow_Text_Rocket3Intro::
    .string "You'd be wasting time even if you\n"
    .string "were to get by me.$"

FiveIsland_Meadow_Text_Rocket3Defeat::
    .string "Oh, that makes me furious!$"

FiveIsland_Meadow_Text_Rocket3PostBattle::
    .string "You won't be able to get in without\n"
    .string "the passwords anyway.$"

MemorialPillar_Text_MiloIntro::
    .string "I'm the eldest of the Bird\n"
    .string "Brothers.\p"
    .string "The best thing about birds…\n"
    .string "It has to be the beak.$"

MemorialPillar_Text_MiloDefeat::
    .string "Oh, so sharp!$"

MemorialPillar_Text_MiloPostBattle::
    .string "You can fly to Four Island from\n"
    .string "here.$"

MemorialPillar_Text_MiloRegister::
	.string "You're strong, I should register\n"
	.string "you in my Pokénav!$"

MemorialPillar_Text_MiloRematchIntro::
    .string "I'm the eldest of the Bird\n"
    .string "Brothers. Remember me?\p"
    .string "That's right, I'm the one who loves\n"
    .string "birds for their beaks!$"

MemorialPillar_Text_ChazIntro::
    .string "I'm the middle kid of the Bird\n"
    .string "Brothers.\p"
    .string "The best thing about birds…\n"
    .string "It has to be the wings.$"

MemorialPillar_Text_ChazDefeat::
    .string "Flap, flap!$"

MemorialPillar_Text_ChazPostBattle::
    .string "There was a really somber guy\n"
    .string "over that way.$"

MemorialPillar_Text_ChazRegister::
	.string "I want a rematch when my Bird\n"
	.string "Pokémon grow up!\p"
	.string "I'm registering you in my Pokénav!$"

MemorialPillar_Text_ChazRematchIntro::
    .string "I'm the middle kid of the Bird\n"
    .string "Brothers.\p"
    .string "I'm the one that loves wings.\n"
    .string "Let's battle again!$"

MemorialPillar_Text_HaroldIntro::
    .string "I'm the youngest of the Bird\n"
    .string "Brothers.\p"
    .string "The best thing about birds…\n"
    .string "It has to be the down.$"

MemorialPillar_Text_HaroldDefeat::
    .string "Down is so comfy…\n"
    .string "It makes me drowsy…$"

MemorialPillar_Text_HaroldPostBattle::
    .string "It fills me with happiness when\n"
    .string "bird Pokémon beg playfully…$"

WaterLabyrinth_Text_AlizeIntro::
    .string "This is an excellent environment\n"
    .string "for raising Pokémon.$"

WaterLabyrinth_Text_AlizeDefeat::
    .string "Your Pokémon are growing up\n"
    .string "admirably well!$"

WaterLabyrinth_Text_AlizePostBattle::
    .string "You know, I think you have the\n"
    .string "talent to be a good Breeder.$"

WaterLabyrinth_Text_AlizeRegister:
	.string "I'm glad I met a superb Trainer in you.\n"
	.string "I hope to see you again.$"

WaterLabyrinth_Text_AlizeRematchIntro::
	.string "Oh, hello!\p"
	.string "Are you raising your Pokémon in a\n"
	.string "good environment?$"

ResortGorgeous_Text_DaisyIntro::
    .string "With these hands, I will create\n"
    .string "my victory!$"

ResortGorgeous_Text_DaisyDefeat::
    .string "The shame of this…\n"
    .string "I'm red-faced…$"

ResortGorgeous_Text_DaisyPostBattle::
    .string "Uh-oh, my paint tubes have\n"
    .string "scattered everywhere!$"

ResortGorgeous_Text_CelinaIntro::
    .string "Excuse me!\n"
    .string "I'm trying to paint.\l"
    .string "Please keep out of my sight!$"

ResortGorgeous_Text_CelinaDefeat::
    .string "This loss…\n"
    .string "I feel like I'm whiting out…$"

ResortGorgeous_Text_CelinaPostBattle::
    .string "Gillian?\n"
    .string "Please tilt your head slightly…\l"
    .string "There! That's the look I want!$"

ResortGorgeous_Text_RaynaIntro::
    .string "Hmm…\n"
    .string "The angle, it is not quite there…$"

ResortGorgeous_Text_RaynaDefeat::
    .string "Oh…\n"
    .string "My feelings, they are blue…$"

ResortGorgeous_Text_RaynaPostBattle::
    .string "The sky and the sea…\n"
    .string "They are so fickle.\p"
    .string "Their changing expressions make\n"
    .string "them difficult to capture.$"

ResortGorgeous_Text_RaynaRegister:
	.string "Your battling inspires me!\n"
	.string "Let me register you in my Pokénav.$"

ResortGorgeous_Text_RaynaRematchIntro::
	.string "I haven't made any progress…\n"
	.string "I still can't get the right angle…$"

ResortGorgeous_Text_JackiIntro::
    .string "I am visiting my friend's retreat,\n"
    .string "if you must know.$"

ResortGorgeous_Text_JackiDefeat::
    .string "Oh, my, so strong.$"

ResortGorgeous_Text_JackiPostBattle::
    .string "I find it pleasurable to leisurely\n"
    .string "battle in the gentle sea breeze.$"

ResortGorgeous_Text_GillianIntro::
    .string "I'm thinking of having a pool\n"
    .string "made specially for Pokémon.$"

ResortGorgeous_Text_GillianDefeat::
    .string "Oh, my goodness gracious!$"

ResortGorgeous_Text_GillianPostBattle::
    .string "A pool would be nice, but I must\n"
    .string "say, a sun-room may be sublime.$"

ResortGorgeous_Text_DestinIntro::
    .string "I'm a good runner.\n"
    .string "I'm really fast!$"

ResortGorgeous_Text_DestinDefeat::
    .string "Oops!\n"
    .string "I rushed things!$"

ResortGorgeous_Text_DestinPostBattle::
    .string "When I run with the wind, it feels\n"
    .string "like I could fly!$"

ResortGorgeous_Text_DestinRegister:
	.string "We should race sometime!\n"
	.string "Register you in my Pokénav.$"

ResortGorgeous_Text_DestinRematchIntro::
	.string "I'm a good runner.\n"
	.string "I've gotten even faster!$"

ResortGorgeous_Text_TobyIntro::
    .string "I say, this marine life here at\n"
    .string "this resort agrees with me.$"

ResortGorgeous_Text_TobyDefeat::
    .string "That's a shocker!\n"
    .string "You must be joking.$"

ResortGorgeous_Text_TobyPostBattle::
    .string "Getting so serious over this…\n"
    .string "How nonsensical.$"

WaterPath_Text_RoseIntro::
    .string "I let a pleasant breeze lead me\n"
    .string "all the way here.$"

WaterPath_Text_RoseDefeat::
    .string "Giggle… You're so cute when you're\n"
    .string "determined.$"

WaterPath_Text_RosePostBattle::
    .string "I want to go to the woods over\n"
    .string "there, but…\p"
    .string "There are lots of Bug Pokémon.\n"
    .string "They scare me a little.$"

WaterPath_Text_EdwardIntro::
    .string "I'm practicing in secret so no one\n"
    .string "can see me.$"

WaterPath_Text_EdwardDefeat::
    .string "Nobody saw me losing, right?$"

WaterPath_Text_EdwardPostBattle::
    .string "As a performer, I don't want people\n"
    .string "to know about the effort I put in.$"

WaterPath_Text_SamirIntro::
    .string "What, you're suggesting that you're\n"
    .string "sick of seeing Swimmers like me?\p"
    .string "Aww, don't be hatin'!$"

WaterPath_Text_SamirDefeat::
    .string "Oh, no, no, no.$"

WaterPath_Text_SamirPostBattle::
    .string "I couldn't lift the stigma of being\n"
    .string "a Swimmer…$"

WaterPath_Text_SamirRegister:
	.string "Give me another chance to prove\n"
	.string "the worth of Swimmers!$"

WaterPath_Text_SamirRematchIntro::
	.string "What, you're sick of seeing\n"
	.string "Swimmers like me?\p"
	.string "Aww, don't be hatin'!\n"
	.string "Battle with me again.$"

WaterPath_Text_DeniseIntro::
    .string "My boyfriend's always busy, so I\n"
    .string "come swimming by myself.$"

WaterPath_Text_DeniseDefeat::
    .string "Awww, I knew this would happen!$"

WaterPath_Text_DenisePostBattle::
    .string "When I can't be with my boyfriend,\n"
    .string "I spend time with the Pokémon he\l"
    .string "gave me.$"

WaterPath_Text_EarlIntro::
    .string "Tell me, where are the mountains\n"
    .string "around these parts?$"

WaterPath_Text_EarlDefeat::
    .string "I lost my way while I was busy\n"
    .string "battling!$"

WaterPath_Text_EarlPostBattle::
    .string "Aren't there any mountains around\n"
    .string "these parts?$"

WaterPath_Text_EarlRegister:
	.string "You impress me! Give me a rematch\n"
	.string "after I redo my training!$"

WaterPath_Text_EarlRematchIntro::
	.string "Come on, tell me, where are the\n"
	.string "mountains around these parts?$"

WaterPath_Text_MiuIntro::
    .string "Miu: Hello, Pokémon!\n"
    .string "It's time to play!$"

WaterPath_Text_MiuDefeat::
    .string "Miu: Oh, no!\n"
    .string "Mommy!$"

WaterPath_Text_MiuPostBattle::
    .string "Miu: It makes me all sad inside\n"
    .string "when we lose…$"

WaterPath_Text_MiuNotEnoughMons::
    .string "Miu: Mia and I are Twins.\n"
    .string "We want to battle together.$"

WaterPath_Text_MiaIntro::
    .string "Mia: Hello, Pokémon!\n"
    .string "It's time to battle!$"

WaterPath_Text_MiaDefeat::
    .string "Mia: You're mean!\n"
    .string "You're bad for winning!$"

WaterPath_Text_MiaPostBattle::
    .string "Mia: Ohh…\n"
    .string "I'm sorry, my Pokémon…$"

WaterPath_Text_MiaNotEnoughMons::
    .string "Mia: Oh, you only have one\n"
    .string "Pokémon?\p"
    .string "Don't you feel lonesome?$"

RuinValley_Text_StanlyIntro::
    .string "There appear to be many secrets\n"
    .string "still unsolved in this world.$"

RuinValley_Text_StanlyDefeat::
    .string "Hmm…$"

RuinValley_Text_StanlyPostBattle::
    .string "I suggest to you that you, too,\n"
    .string "give a thought to the secrets and\l"
    .string "mysteries of our world once a day.$"

RuinValley_Text_FosterIntro::
    .string "I'm curious, what compelled you to\n"
    .string "come here?$"

RuinValley_Text_FosterDefeat::
    .string "It's been so long since I battled,\n"
    .string "my instincts are off.$"

RuinValley_Text_FosterPostBattle::
    .string "There are several ruins on the\n"
    .string "Sevii Islands.\p"
    .string "The majority of them date back\n"
    .string "a long way.$"

RuinValley_Text_LarryIntro::
    .string "It's been said that there are\n"
    .string "mysterious stones on this island.\p"
    .string "I suspect it has something to do\n"
    .string "with the ruins here.$"

RuinValley_Text_LarryDefeat::
    .string "Oh, interesting.$"

RuinValley_Text_LarryPostBattle::
    .string "Those ruins over there…\p"
    .string "I haven't had any luck in finding\n"
    .string "how I can get inside.$"

RuinValley_Text_LarryRegister:
	.string "I haven't been searching for any\n"
	.string "tough Pokémon.\p"
	.string "But, for some reason, I sure do like\n"
	.string "Pokénavs.$"

RuinValley_Text_LarryRematchIntro::
    .string "It's been said that there are\n"
    .string "mysterious stones on this island.\p"
    .string "Have you discovered anything since\n"
    .string "we last met?$"

RuinValley_Text_DarylIntro::
    .string "A battle with you, so high up!$"

RuinValley_Text_DarylDefeat::
    .string "Oh, the heartbreak of losing so\n"
    .string "easily to you!$"

RuinValley_Text_DarylPostBattle::
    .string "Experience the joy of climbing!$"

RuinValley_Text_HectorIntro::
    .string "I'm pretty familiar with the land\n"
    .string "around these parts.$"

RuinValley_Text_HectorDefeat::
    .string "You don't need to be so pushy.\n"
    .string "I'll be happy to tell you.$"

RuinValley_Text_HectorPostBattle::
    .string "The door to the ruins…\n"
    .string "It has these strange patterns\l"
    .string "engraved on the outside.\p"
    .string "I don't know what they mean,\n"
    .string "though.$"

RuinValley_Text_HectorRegister:
	.string "Don't forget what you've done to me!\n"
	.string "I'll make it so you can't forget!$"

RuinValley_Text_HectorRematchIntro::
    .string "I'm pretty familiar with the land\n"
    .string "around these parts.$"

GreenPath_Text_JaclynIntro::
    .string "…Huh?\p"
    .string "I was envisioning my house, but\n"
    .string "this is where I Teleport?$"

GreenPath_Text_JaclynDefeat::
    .string "Big boo-boo!$"

GreenPath_Text_JaclynPostBattle::
    .string "I am so scatterbrained!\p"
    .string "I need to focus so I can Teleport\n"
    .string "properly to my house!$"

GreenPath_Text_JaclynRegister:
	.string "I would like to face you again.\n"
	.string "Is that okay with you?$"

GreenPath_Text_JaclynRematchIntro::
	.string "…Huh?\p"
	.string "I envision my house, but Teleport\n"
	.string "always brings me here!$"

OutcastIsland_Text_RocketIntro::
    .string "There're no rare Pokémon around\n"
    .string "these parts! Not a one!\p"
    .string "That burns me up, man.\n"
    .string "I'll take it out on you!$"

OutcastIsland_Text_RocketDefeat::
    .string "…Huh?$"

OutcastIsland_Text_RocketPostBattle::
    .string "So listen, you haven't seen any\n"
    .string "rare Pokémon, have you?$"

OutcastIsland_Text_TylorIntro::
    .string "I'm having no luck at all.\n"
    .string "A battle'd be a change of pace!$"

OutcastIsland_Text_TylorDefeat::
    .string "Nope, no luck at all…$"

OutcastIsland_Text_TylorPostBattle::
    .string "I can't very well go home without\n"
    .string "catching something, though.$"

OutcastIsland_Text_MymoIntro::
    .string "Gasp… Gasp…\p"
    .string "I swam here from Six Isle Port\n"
    .string "in one go.$"

OutcastIsland_Text_MymoDefeat::
    .string "Gasp…\n"
    .string "Gasp…$"

OutcastIsland_Text_MymoPostBattle::
    .string "I'm only at the halfway point…\n"
    .string "I'm beat…$"

OutcastIsland_Text_NicoleIntro::
    .string "It's not so easy sending Pokémon\n"
    .string "out while swimming, you know?$"

OutcastIsland_Text_NicoleDefeat::
    .string "I didn't lose to you at swimming.\n"
    .string "This doesn't bother me.$"

OutcastIsland_Text_NicolePostBattle::
    .string "Are you headed for the island up\n"
    .string "past here?\p"
    .string "I didn't see anything interesting\n"
    .string "there.$"

OutcastIsland_Text_NicoleRegister:
    .string "It's only on a whim, but maybe I'll get\n"
    .string "you to register me in your Pokénav.$"

OutcastIsland_Text_NicoleRematchIntro::
    .string "You always come along while I'm\n"
    .string "swimming.$"

OutcastIsland_Text_AvaIntro::
    .string "Ava: Let's have a two-on-two\n"
    .string "marine battle!$"

OutcastIsland_Text_AvaDefeat::
    .string "Ava: Oh, you're amazing!\n"
    .string "Even better, you're on your own!$"

OutcastIsland_Text_AvaPostBattle::
    .string "Ava: You know, I do prefer the\n"
    .string "sea over any pool.$"

OutcastIsland_Text_AvaNotEnoughMons::
    .string "Ava: You're challenging us to\n"
    .string "a battle?\p"
    .string "You'll need at least two Pokémon\n"
    .string "if you want to do that.$"

OutcastIsland_Text_GebIntro::
    .string "Geb: Big Sister, help!\n"
    .string "Please battle with me!$"

OutcastIsland_Text_GebDefeat::
    .string "Geb: Wow, Big Sister, this person's\n"
    .string "really good!$"

OutcastIsland_Text_GebPostBattle::
    .string "Geb: I'm hanging onto my sister\n"
    .string "because I can't touch the bottom.$"

OutcastIsland_Text_GebNotEnoughMons::
    .string "Geb: Please battle against me and\n"
    .string "my sister!\p"
    .string "…Oh, you don't have two Pokémon?$"
    
TrainerTower_Exterior_Text_DarioIntro::
    .string "I sensed your approach.$"

TrainerTower_Exterior_Text_DarioDefeat::
    .string "Give up…$"

TrainerTower_Exterior_Text_DarioPostBattle::
    .string "In your future, I sense that you\n"
    .string "will meet many others.\p"
    .string "I think you will be linked to each\n"
    .string "other by a strange power.$"

TrainerTower_Exterior_Text_DarioRegister:
	.string "You have a strange power emanating\n"
	.string "from your bag!\p"
	.string "Oh! It's a Pokénav!\n"
	.string "Let's register each other!$"

TrainerTower_Exterior_Text_DarioRematchIntro::
    .string "I sensed your approach.$"

TrainerTower_Exterior_Text_RodetteIntro::
    .string "Somewhere on this island, peculiar\n"
    .string "Pokémon are sleeping.$"

TrainerTower_Exterior_Text_RodetteDefeat::
    .string "What an amazing Trainer!$"

TrainerTower_Exterior_Text_RodettePostBattle::
    .string "Somewhere on this island, peculiar\n"
    .string "Pokémon are sleeping.\p"
    .string "Could it be that they're waiting\n"
    .string "for you?$"

TrainerTower_Exterior_Text_RodetteRegister:
	.string "I envisage facing you again.\n"
	.string "Let's register each other!$"

TrainerTower_Exterior_Text_RodetteRematchIntro::
    .string "Somewhere on this island, peculiar\n"
    .string "Pokémon are sleeping.$"

SevaultCanyon_Entrance_Text_MiahIntro::
    .string "Kyahaha!\n"
    .string "I'll flick you away effortlessly!$"

SevaultCanyon_Entrance_Text_MiahDefeat::
    .string "Tch!\n"
    .string "Too strong for me!$"

SevaultCanyon_Entrance_Text_MiahPostBattle::
    .string "What's that?\n"
    .string "I don't act the way I look?\p"
    .string "Heh, that's a part of my strategy!$"

SevaultCanyon_Entrance_Text_MasonIntro::
    .string "Howdy!\n"
    .string "Are you a member of my fan club?$"

SevaultCanyon_Entrance_Text_MasonDefeat::
    .string "Oh, so you're not a fan…\p"
    .string "Well, I can change that.\n"
    .string "Let me sing for you!$"

SevaultCanyon_Entrance_Text_MasonPostBattle::
    .string "Lalalah…\n"
    .string "My Pokémon, I send them out,\l"
    .string "all the girls scream and shout!$"

SevaultCanyon_Entrance_Text_MasonRegister:
    .string "You're such a tough Trainer!\n"
    .string "Please let me register you!$"

SevaultCanyon_Entrance_Text_MasonRematchIntro::
    .string "Howdy! You're a member of my\n"
    .string "fan club, isn't that right?$"

SevaultCanyon_Entrance_Text_NicolasIntro::
    .string "This island is too spread out…\n"
    .string "It's not easy patrolling the place.$"

SevaultCanyon_Entrance_Text_NicolasDefeat::
    .string "Uh-huh…$"

SevaultCanyon_Entrance_Text_NicolasPostBattle::
    .string "Trainers like you from cities,\n"
    .string "they sure are tough.\p"
    .string "You'll be headed for the tower,\n"
    .string "won't you?$"

SevaultCanyon_Entrance_Text_NicolasRegister:
    .string "I would like to see your Pokémon\n"
    .string "when they grow up some more…\p"
    .string "Please, I need to see your Pokénav.$"

SevaultCanyon_Entrance_Text_NicolasRematchIntro::
    .string "This island is too spread out…\n"
    .string "Patrolling the place is a drag…$"

SevaultCanyon_Entrance_Text_MadelineIntro::
    .string "I punish people who abuse\n"
    .string "Pokémon!$"

SevaultCanyon_Entrance_Text_MadelineDefeat::
    .string "You don't seem to be a problem\n"
    .string "Trainer.$"

SevaultCanyon_Entrance_Text_MadelinePostBattle::
    .string "If you treat your Pokémon with\n"
    .string "kindness, they'll understand.$"

SevaultCanyon_Entrance_Text_MadelineRegister:
    .string "Do you have a Pokénav?\n"
    .string "It's a must-have tool for any Trainer.\p"
    .string "Oh, you do have one!\n"
    .string "Let's register each other, then!$"

SevaultCanyon_Entrance_Text_MadelineRematchIntro::
    .string "I don't forgive people who abuse\n"
    .string "Pokémon!$"

SevaultCanyon_Entrance_Text_EveIntro::
    .string "Eve: I'll team up with Jon and\n"
    .string "battle together.$"

SevaultCanyon_Entrance_Text_EveDefeat::
    .string "Eve: Me and Jon, we lost.\n"
    .string "Ehehe.$"

SevaultCanyon_Entrance_Text_EvePostBattle::
    .string "Eve: I'm going to work harder with\n"
    .string "Jon.$"

SevaultCanyon_Entrance_Text_EveNotEnoughMons::
    .string "Eve: I want to team up with Jon\n"
    .string "when I battle you.\p"
    .string "Come back with two Pokémon, okay?$"

SevaultCanyon_Entrance_Text_JonIntro::
    .string "Jon: When I'm with Eve, it feels\n"
    .string "like we could never lose.$"

SevaultCanyon_Entrance_Text_JonDefeat::
    .string "Jon: When I'm with Eve,\n"
    .string "it doesn't feel like I've lost!$"

SevaultCanyon_Entrance_Text_JonPostBattle::
    .string "Jon: When I'm with Eve, I feel\n"
    .string "giddy whether I win or lose.\p"
    .string "It's magical!$"

SevaultCanyon_Entrance_Text_JonNotEnoughMons::
    .string "Jon: If it's with Eve, I'll be\n"
    .string "happy to battle with you.\p"
    .string "So, I'd like to make it a\n"
    .string "two-on-two battle, if I may.$"

SevaultCanyon_Text_CyndyIntro::
    .string "My conditioning's in top form!$"

SevaultCanyon_Text_CyndyDefeat::
    .string "Huh?\n"
    .string "Something's not right…$"

SevaultCanyon_Text_CyndyPostBattle::
    .string "The way I am now, I may have to\n"
    .string "hold off on Trainer Tower…$"

SevaultCanyon_Text_EvanIntro::
    .string "It doesn't matter if you happen to\n"
    .string "have the strongest Pokémon…\p"
    .string "It doesn't mean a thing if you don't\n"
    .string "know how to use them properly!$"

SevaultCanyon_Text_EvanDefeat::
    .string "You're a master at this.$"

SevaultCanyon_Text_EvanPostBattle::
    .string "You see them every so often,\n"
    .string "Trainers with awesome Pokémon\l"
    .string "who have no idea what to do.\p"
    .string "Before training Pokémon, Trainers\n"
    .string "themselves need to grow up.$"

SevaultCanyon_Text_JacksonIntro::
    .string "I work to protect the environment.\n"
    .string "In turn, nature protects me!$"

SevaultCanyon_Text_JacksonDefeat::
    .string "Whoa! You're tough!\n"
    .string "How about protecting me?$"

SevaultCanyon_Text_JacksonPostBattle::
    .string "From far out among the stars, our\n"
    .string "planet is just a drop of water.\p"
    .string "But we want to protect that drop\n"
    .string "of water for everyone.$"

SevaultCanyon_Text_KatelynIntro::
    .string "Those shoes you have are pretty\n"
    .string "snazzy.$"

SevaultCanyon_Text_KatelynDefeat::
    .string "You're hot stuff in spite of your\n"
    .string "cute looks.$"

SevaultCanyon_Text_KatelynPostBattle::
    .string "Your mom bought those snazzy\n"
    .string "Running Shoes for you?\p"
    .string "She must adore you.$"

SevaultCanyon_Text_KatelynRegister:
	.string "Do you have a Pokénav?\n"
	.string "It's a must-have tool for any Trainer.\p"
	.string "Oh, you do have one!\n"
	.string "Let's register each other, then!$"

SevaultCanyon_Text_KatelynRematchIntro::
    .string "Every time we meet, you have those\n"
    .string "snazzy shoes on.$"

SevaultCanyon_Text_LeroyIntro::
    .string "You look strong.\n"
    .string "Let me battle you, please!$"

SevaultCanyon_Text_LeroyDefeat::
    .string "I knew it!\n"
    .string "You're as tough as I thought!$"

SevaultCanyon_Text_LeroyPostBattle::
    .string "The way you battle has given me\n"
    .string "a lot of useful data.\p"
    .string "Thanks so much!$"

SevaultCanyon_Text_LeroyRegister:
	.string "That was total humiliation!\n"
	.string "I won't forget you…\l"
	.string "Hand over your Pokénav!$"

SevaultCanyon_Text_LeroyRematchIntro::
    .string "You must have gotten tougher.\n"
    .string "Let me battle you, please!$"

SevaultCanyon_Text_MichelleIntro::
    .string "I was given the best possible\n"
    .string "education to become this strong.\p"
    .string "I don't want to lose to anyone!$"

SevaultCanyon_Text_MichelleDefeat::
    .string "Thank you. I feel like I've been\n"
    .string "set free by losing to you.$"

SevaultCanyon_Text_MichellePostBattle::
    .string "For some reason, I get furious\n"
    .string "over the slightest thing.\p"
    .string "I'll calm myself by breathing\n"
    .string "deeply.$"

SevaultCanyon_Text_MichelleRegister:
	.string "I wish I could become friends with\n"
	.string "more strong people like you!$"

SevaultCanyon_Text_MichelleRematchIntro::
    .string "I was given the best possible\n"
    .string "education to become this strong.\p"
    .string "I won't lose this time.\n"
    .string "Absolutely not!$"

SevaultCanyon_Text_LexIntro::
    .string "Lex: My darling Nya, together\n"
    .string "we could win!$"

SevaultCanyon_Text_LexDefeat::
    .string "Lex: I seem to have been too\n"
    .string "careless…$"

SevaultCanyon_Text_LexPostBattle::
    .string "Lex: I think it was a good\n"
    .string "experience for Nya.\p"
    .string "You have my gratitude.$"

SevaultCanyon_Text_LexNotEnoughMons::
    .string "Lex: May I ask you to battle the\n"
    .string "both of us at the same time?$"

SevaultCanyon_Text_NyaIntro::
    .string "Nya: I'll do my best so I won't\n"
    .string "drag down my mentor, Lex!$"

SevaultCanyon_Text_NyaDefeat::
    .string "Nya: Oh, no…\n"
    .string "I'm so sorry, I…$"

SevaultCanyon_Text_NyaPostBattle::
    .string "Nya: I think I'm going to need\n"
    .string "much more seasoning and tutoring\l"
    .string "under Lex…\p"
    .string "…So, Lex, please, may I stay with\n"
    .string "you like this?$"

SevaultCanyon_Text_NyaNotEnoughMons::
    .string "Nya: I'm sorry, but may we battle\n"
    .string "in two-on-two style?$"

TanobyRuins_Text_BrandonIntro::
    .string "Do you know anything about this\n"
    .string "stone chamber?$"

TanobyRuins_Text_BrandonDefeat::
    .string "That was uncalled for.\n"
    .string "You didn't have to be so rough.$"

TanobyRuins_Text_BrandonPostBattle::
    .string "The Tanoby Ruins date back at\n"
    .string "least 1,500 years.\p"
    .string "But it's a baffling mystery as to\n"
    .string "why it was built in the first place.$"

TanobyRuins_Text_BenjaminIntro::
    .string "A mystic Pokémon is said to sleep\n"
    .string "inside here.$"

TanobyRuins_Text_BenjaminDefeat::
    .string "I'm not much good in battle.$"

TanobyRuins_Text_BenjaminPostBattle::
    .string "I hear there are other ruins like\n"
    .string "the one here.\p"
    .string "Might they be the resting places\n"
    .string "of other mystic Pokémon?$"

TanobyRuins_Text_EdnaIntro::
    .string "Clifford is teaching me how to\n"
    .string "paint.$"

TanobyRuins_Text_EdnaDefeat::
    .string "We might get in trouble for being\n"
    .string "noisy here.$"

TanobyRuins_Text_EdnaPostBattle::
    .string "I said that I wanted to paint an\n"
    .string "old building.\p"
    .string "So Clifford brought me here.$"

TanobyRuins_Text_CliffordIntro::
    .string "Today, in addition to our lesson,\n"
    .string "we came to see the chamber.$"

TanobyRuins_Text_CliffordDefeat::
    .string "My, how extraordinary.$"

TanobyRuins_Text_CliffordPostBattle::
    .string "Ah, so you are studying Pokémon\n"
    .string "on your own…\p"
    .string "Yes, you certainly are quite the\n"
    .string "extraordinary person, indeed.$"

Route120_Text_ColinIntro:
	.string "Do you have any moves that can strike\n"
	.string "a flying POKéMON?$"

Route120_Text_ColinDefeat:
	.string "You soared above me!$"

Route120_Text_ColinPostBattle:
	.string "The move FLY is convenient,\n"
	.string "don't you think?\p"
	.string "While the POKéMON is flying,\n"
	.string "almost no moves can strike it.$"

Route120_Text_RobertIntro:
	.string "My POKéMON is strong!\n"
	.string "How about yours?$"

Route120_Text_RobertDefeat:
	.string "Your POKéMON were stronger…$"

Route120_Text_RobertPostBattle:
	.string "A POKéMON that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_RobertRegister:
	.string "You can be counted on to get better.\n"
	.string "I'd like to register you in my POKéNAV!$"

Route120_Text_RobertRematchIntro:
	.string "A POKéMON that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_RobertRematchDefeat:
	.string "Your POKéMON are seriously strong.$"

Route120_Text_RobertPostRematch:
	.string "My POKéMON are growing stronger.\n"
	.string "I have to grow stronger, too.$"

Route120_Text_LorenzoIntro:
	.string "I'll check your POKéMON and see if\n"
	.string "they're fit for the outdoors.$"

Route120_Text_LorenzoDefeat:
	.string "With POKéMON that strong, you're in\n"
	.string "no danger of needing rescue!$"

Route120_Text_LorenzoPostBattle:
	.string "To travel wherever your heart desires\n"
	.string "with POKéMON…\l"
	.string "That's the joy of being a TRAINER.$"

Route120_Text_JennaIntro:
	.string "How's your physical fitness?\n"
	.string "If you're not fit, you could have a\l"
	.string "rough time in critical situations.$"

Route120_Text_JennaDefeat:
	.string "I'm totally fit, but…$"

Route120_Text_JennaPostBattle:
	.string "Fitness training is in my routine.\n"
	.string "I always run with my POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Want to battle?$"

Route120_Text_JeffreyDefeat:
	.string "Lost it…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll try harder…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Do you have a POKéNAV…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Want to battle again?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "I lost again…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll try harder…\l"
	.string "For my precious BUG POKéMON…$"

Route120_Text_JenniferIntro:
	.string "POKéMON have many special abilities.\n"
	.string "If you want to become a first-class\l"
	.string "TRAINER, learn about them.$"

Route120_Text_JenniferDefeat:
	.string "You're obviously thinking.$"

Route120_Text_JenniferPostBattle:
	.string "The special abilities of POKéMON\n"
	.string "will make battle styles change.$"

Route120_Text_ChipIntro:
	.string "Who might you be?\p"
	.string "Are you perhaps searching for ancient\n"
	.string "ruins that are rumoured to possibly\l"
	.string "exist according to legend?$"

Route120_Text_ChipDefeat:
	.string "What a disgraceful setback…$"

Route120_Text_ChipPostBattle:
	.string "That giant rock… I would like to\n"
	.string "believe it may indeed contain ancient\l"
	.string "ruins. But I see no entrance.$"

Route120_Text_ClarissaIntro:
	.string "Why am I carrying this parasol?\p"
	.string "I'll tell you if you can win against me.$"

Route120_Text_ClarissaDefeat:
	.string "A parasol can't ward off POKéMON\n"
	.string "attacks…$"

Route120_Text_ClarissaPostBattle:
	.string "I don't think strong sunlight is good\n"
	.string "for my POKéMON.\l"
	.string "So I shield them with my parasol.$"

Route120_Text_AngelicaIntro:
	.string "Me, POKéMON, and my parasol…\p"
	.string "If any one of them is missing,\n"
	.string "the picture of beauty will be ruined.$"

Route120_Text_AngelicaDefeat:
	.string "You've completely ruined my beauty…$"

Route120_Text_AngelicaPostBattle:
	.string "A parasol wouldn't suit you at all.\p"
	.string "Why, something like this would only\n"
	.string "get in your way.$"

Route120_Text_KeigoIntro:
	.string "I will adopt the movements of POKéMON\n"
	.string "and create new ninja techniques.$"

Route120_Text_KeigoDefeat:
	.string "The creation of new ninja techniques\n"
	.string "is but a distant dream…$"

Route120_Text_KeigoPostBattle:
	.string "Perhaps I ought to apprentice under\n"
	.string "a ninja sensei.$"

Route120_Text_RileyIntro:
	.string "We ninja conceal ourselves under our\n"
	.string "camouflage cloaks.\l"
	.string "I bet you didn't know where I was!$"

Route120_Text_RileyDefeat:
	.string "I lost!\n"
	.string "I should camouflage my shame!$"

Route120_Text_RileyPostBattle:
	.string "Our camouflage cloaks are all\n"
	.string "handmade.$"

Route120_Text_CallieIntro:
	.string "If you don't pay attention,\n"
	.string "you could get hurt!$"

Route120_Text_CallieDefeat:
	.string "Ouch!\n"
	.string "I was the one to get hurt.$"

Route120_Text_CalliePostBattle:
	.string "I wonder… Should I evolve my POKéMON?\n"
	.string "They're cute the way they are, though.$"

Route120_Text_LeonelIntro:
	.string "Your party POKéMON…\n"
	.string "Do you have different types?$"

Route120_Text_LeonelDefeat:
	.string "I've seen your policy in action!$"

Route120_Text_LeonelPostBattle:
	.string "I think it's awesome you're so strong\n"
	.string "battling with your favorite POKéMON.$"

Route121_Text_VanessaIntro:
	.string "Will you play with my delightfully\n"
	.string "pretty POKéMON?$"

Route121_Text_VanessaDefeat:
	.string "This isn't what I meant!$"

Route121_Text_VanessaPostBattle:
	.string "I'm going to a CONTEST in LILYCOVE.\p"
	.string "My POKéMON should have no problem\n"
	.string "sweeping the MASTER CLASS.$"

Route121_Text_WalterIntro:
	.string "With my POKéMON, I have traveled\n"
	.string "to the world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_WalterDefeat:
	.string "Ah, well played.$"

Route121_Text_WalterPostBattle:
	.string "I would like to circle the globe once\n"
	.string "again with my POKéMON.$"

Route121_Text_WalterRegister:
	.string "Your POKéMON prowess is remarkable.\n"
	.string "Allow me to register you as a memento.$"

Route121_Text_WalterRematchIntro:
	.string "With my POKéMON, I have traveled\n"
	.string "to the world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, well played.$"

Route121_Text_WalterPostRematch:
	.string "Your POKéMON and you…\p"
	.string "Your prowess together will be\n"
	.string "considered strong, even overseas.$"

Route121_Text_TammyIntro:
	.string "There are powers beyond our\n"
	.string "understanding in the world…$"

Route121_Text_TammyDefeat:
	.string "I have lost…$"

Route121_Text_TammyPostBattle:
	.string "MT. PYRE…\n"
	.string "There is a mysterious power\l"
	.string "at work there…$"

Route121_Text_KateIntro:
	.string "KATE: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_KateDefeat:
	.string "KATE: I blew it in front of my junior\n"
	.string "student partner…$"

Route121_Text_KatePostBattle:
	.string "KATE: When someone's relying on me,\n"
	.string "I get this urge to look cool in front\l"
	.string "of them…$"

Route121_Text_KateNotEnoughMons:
	.string "KATE: If you've only got one POKéMON,\n"
	.string "we can't battle with you.\p"
	.string "That would be bullying.$"

Route121_Text_JoyIntro:
	.string "JOY: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_JoyDefeat:
	.string "JOY: Please forgive me, KATE!$"

Route121_Text_JoyPostBattle:
	.string "JOY: Ehehe, I'll have to train with KATE,\n"
	.string "my senior student partner, again.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY: You need at least two POKéMON\n"
	.string "if you're going to challenge us!$"

Route121_Text_JessicaIntro:
	.string "Stop! Have a good look at my precious\n"
	.string "POKéMON!$"

Route121_Text_JessicaDefeat:
	.string "Oh, how dare you!\n"
	.string "Don't take it so seriously!$"

Route121_Text_JessicaPostBattle:
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_JessicaRegister:
	.string "I took it easy on you this time!\n"
	.string "It won't be that way the next time!$"

Route121_Text_JessicaRematchIntro:
	.string "My precious POKéMON grew!\n"
	.string "Have a good look!$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, how dare you!\n"
	.string "You still won't take it easy!$"

Route121_Text_JessicaPostRematch:
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_CristinIntro:
	.string "I have this routine.\n"
	.string "Defeat five TRAINERS a day.\l"
	.string "Guess what? You're number five!$"

Route121_Text_CristinDefeat:
	.string "No!\n"
	.string "You're horrid!$"

Route121_Text_CristinPostBattle:
	.string "I didn't expect to lose this easily…\n"
	.string "I'll win next time!$"

Route121_Text_CristinRegister:
	.string "That was total humiliation!\n"
	.string "I won't forget you…\l"
	.string "Hand over your POKéNAV!$"

Route121_Text_CristinRematchIntro:
	.string "I have this new routine.\n"
	.string "Defeat ten TRAINERS a day.\l"
	.string "Guess what? You're number ten!$"

Route121_Text_CristinRematchDefeat:
	.string "Wait! That's nasty!\n"
	.string "I demand a rematch!$"

Route121_Text_CristinPostRematch:
	.string "An opponent I just can't beat…\n"
	.string "Snivel…\l"
	.string "I can't believe this is happening…$"

Route121_Text_CaleIntro:
	.string "Can't you see that I have all this\n"
	.string "stuff with me?\p"
	.string "Despite that, you still insist that\n"
	.string "we battle?$"

Route121_Text_CaleDefeat:
	.string "Of course I lost!\n"
	.string "I'm holding stuff in both hands!$"

Route121_Text_CalePostBattle:
	.string "I bought too much stuff at\n"
	.string "the LILYCOVE DEPT. STORE.\p"
	.string "It's up the road from here.\n"
	.string "I wish I had a BAG like yours.$"

Route121_Text_MylesIntro:
	.string "There's nothing I love more than\n"
	.string "checking out other people's POKéMON!$"

Route121_Text_MylesDefeat:
	.string "Super awesome!$"

Route121_Text_MylesPostBattle:
	.string "They're great, your POKéMON!\n"
	.string "How do you raise them?$"

Route121_Text_PatIntro:
	.string "I want everybody to see the POKéMON\n"
	.string "I've raised!$"

Route121_Text_PatDefeat:
	.string "Wow!\n"
	.string "Spectacular!$"

Route121_Text_PatPostBattle:
	.string "I raise every POKéMON with the same\n"
	.string "love and care--I don't pick favorites.$"

Route121_Text_MarcelIntro:
	.string "My POKéMON have never tasted defeat!\n"
	.string "On their next win, I'm entering them\l"
	.string "in CONTESTS.$"

Route121_Text_MarcelDefeat:
	.string "Oh, now what happened here?$"

Route121_Text_MarcelPostBattle:
	.string "I may have to train my gang some more\n"
	.string "before entering any CONTEST.$"

Route123_Text_WendyIntro:
	.string "Want to determine how strong you are?\n"
	.string "I'll be the test!$"

Route123_Text_WendyDefeat:
	.string "You passed with flying colours!$"

Route123_Text_WendyPostBattle:
	.string "To best even me…\n"
	.string "Your strength is marvelous!$"

Route123_Text_BraxtonIntro:
	.string "You seem to have a big collection\n"
	.string "of GYM BADGES.\p"
	.string "Let me see if you're actually worthy of\n"
	.string "those BADGES!$"

Route123_Text_BraxtonDefeat:
	.string "Oh, you're worthy, all right!$"

Route123_Text_BraxtonPostBattle:
	.string "You did your BADGES proud in that\n"
	.string "match!$"

Route123_Text_VioletIntro:
	.string "They say that good times are filled\n"
	.string "with good aromas.$"

Route123_Text_VioletDefeat:
	.string "Oh…\n"
	.string "I smell the bitter scent of misery…$"

Route123_Text_VioletPostBattle:
	.string "The BERRY MASTER's garden is filled\n"
	.string "with uplifting fragrances.$"

Route123_Text_CameronIntro:
	.string "Being a psychic is about willpower.\p"
	.string "I've willed myself not to lose to\n"
	.string "anyone. That makes me strong!$"

Route123_Text_CameronDefeat:
	.string "I feel sad…$"

Route123_Text_CameronPostBattle:
	.string "Being a psychic is about willpower.\n"
	.string "I thought I wouldn't lose to you…$"

Route123_Text_CameronRegister:
	.string "I sense it!\n"
	.string "You and I shall battle again!\l"
	.string "I can't tell if I'll win, though…\p"
	.string "Let's see your POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "I've convinced myself that I won't\n"
	.string "lose anymore. That makes me strong!$"

Route123_Text_CameronRematchDefeat:
	.string "I feel sad…$"

Route123_Text_CameronPostRematch:
	.string "I should train at MT. PYRE…\n"
	.string "I'll never beat you this way…$"

Route123_Text_JackiIntro:
	.string "Don't be too happy if your POKéMON\n"
	.string "develop psychic powers.\p"
	.string "You need to refine those powers to\n"
	.string "make them really useful.$"

Route123_Text_JackiDefeat:
	.string "Overwhelmed!$"

Route123_Text_JackiPostBattle:
	.string "We all have psychic powers.\n"
	.string "We've just forgotten how to use them.$"

Route123_Text_JackiRegister:
	.string "I would like to face you again.\n"
	.string "Is that okay with you?$"

Route123_Text_JackiRematchIntro:
	.string "Have you awoken the psychic powers\n"
	.string "within you?$"

Route123_Text_JackiRematchDefeat:
	.string "Astounding!$"

Route123_Text_JackiPostRematch:
	.string "Your power with POKéMON…\n"
	.string "That could be a psychic power, too.$"

Route123_Text_MiuIntro:
	.string "MIU: Hello, TRAINER. I hope your\n"
	.string "POKéMON won't cry when they lose.$"

Route123_Text_MiuDefeat:
	.string "MIU: Uh-oh, we lost.$"

Route123_Text_MiuPostBattle:
	.string "MIU: TRAINER, your POKéMON are\n"
	.string "strong because you are friends.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: Okay!\n"
	.string "We're beating the TRAINER's POKéMON!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Uh-oh, we lost.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: Why are you so strong?\n"
	.string "We've never lost before.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_KindraIntro:
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\l"
	.string "Will your POKéMON sleep?$"

Route123_Text_KindraDefeat:
	.string "Overflowing with vitality…$"

Route123_Text_KindraPostBattle:
	.string "MT. PYRE…\n"
	.string "Where the spirits of POKéMON sleep…\p"
	.string "It must overflow with a power that\n"
	.string "soothes spirits…$"

Route123_Text_FernandoIntro:
	.string "I'll turn your lights out while\n"
	.string "I rip through this tune!$"

Route123_Text_FernandoDefeat:
	.string "Hey, hold it!\n"
	.string "I was still playing the intro!$"

Route123_Text_FernandoPostBattle:
	.string "You're rock steady.\n"
	.string "I'd like to write a tune about you.$"

Route123_Text_FernandoRegister:
	.string "The next time, lend your ears to\n"
	.string "the full tune, will you?$"

Route123_Text_FernandoRematchIntro:
	.string "Today's the day I'm going to do it!\n"
	.string "I'll turn out your lights before\l"
	.string "I finish singing my song!$"

Route123_Text_FernandoRematchDefeat:
	.string "Hey, hold it!\n"
	.string "I haven't even hit the chorus!$"

Route123_Text_FernandoPostRematch:
	.string "I thought you'd be so enthralled\n"
	.string "by my tune, you'd lose.$"

Route123_Text_DavisIntro:
	.string "This is my awesome BUG POKéMON!\n"
	.string "My big brother got it for me.$"

Route123_Text_DavisDefeat:
	.string "Waaaah!\n"
	.string "You meanie!$"

Route123_Text_DavisPostBattle:
	.string "Don't tell my brother I lost.\n"
	.string "You have to keep it a secret!$"

Route123_Text_JazmynIntro:
	.string "My confidence will get a boost by\n"
	.string "beating someone obviously strong!$"

Route123_Text_JazmynDefeat:
	.string "There goes my confidence…$"

Route123_Text_JazmynPostBattle:
	.string "They say that you can't judge a person\n"
	.string "by their appearance.\p"
	.string "But often, their looks don't lie…$"

Route123_Text_FrederickIntro:
	.string "Hello, child!\n"
	.string "Can you spare some time?$"

Route123_Text_FrederickDefeat:
	.string "Ah, a mighty capable child!\n"
	.string "Let me contribute to your allowance.$"

Route123_Text_FrederickPostBattle:
	.string "Contribute to your allowance?\n"
	.string "Wasn't the prize money enough?$"

Route123_Text_AlbertoIntro:
	.string "I have to tell you, BIRD POKéMON\n"
	.string "are my obsession!\p"
	.string "Birds are cool!\n"
	.string "They're the best!$"

Route123_Text_AlbertoDefeat:
	.string "Even in defeat, BIRD POKéMON are cool!$"

Route123_Text_AlbertoPostBattle:
	.string "I gather BIRD POKéMON feathers that\n"
	.string "scatter during battles.\p"
	.string "I'm going to make a hat with\n"
	.string "BIRD POKéMON feathers.$"

Route123_Text_EdIntro:
	.string "When there are no TRAINERS around,\n"
	.string "I let my POKéMON battle each other.\l"
	.string "I watch them.$"

Route123_Text_EdDefeat:
	.string "I kind of like your POKéMON.$"

Route123_Text_EdPostBattle:
	.string "Hehe, I'm swiping your battling ideas!\n"
	.string "I think they'll make me better.$"

Route123_Text_JonasIntro:
	.string "I lay in ambush, and a TRAINER has\n"
	.string "landed in my trap!$"

Route123_Text_JonasDefeat:
	.string "If you don't lose, how am I supposed\n"
	.string "to have fun playing ninja?$"

Route123_Text_JonasPostBattle:
	.string "I'm going to ambush a weaker-looking\n"
	.string "TRAINER next time.$"

Route123_Text_KayleyIntro:
	.string "I just bought this parasol.\n"
	.string "My cuteness should be up by a third!$"

Route123_Text_KayleyDefeat:
	.string "You're better than me by about\n"
	.string "five times!$"

Route123_Text_KayleyPostBattle:
	.string "Using accessories effectively is\n"
	.string "the secret behind fashion appeal.$"

Route124_Text_SpencerIntro:
	.string "Hey, are you lost at sea?\p"
	.string "If you can beat my POKéMON,\n"
	.string "I can serve as your pilot.$"

Route124_Text_SpencerDefeat:
	.string "I lost my bearings in battle!$"

Route124_Text_SpencerPostBattle:
	.string "Many people lose their bearings at sea.\p"
	.string "If you're that sort, you should refer\n"
	.string "to the POKéNAV's MAP.$"

Route124_Text_RolandIntro:
	.string "Hm! You're riding a POKéMON instead\n"
	.string "of swimming yourself…\p"
	.string "I am envious!$"

Route124_Text_RolandDefeat:
	.string "Oh!\n"
	.string "I can't…$"

Route124_Text_RolandPostBattle:
	.string "I'm getting chilled…\n"
	.string "I've been in the water too long…\p"
	.string "I wish I could ride a POKéMON like you…$"

Route124_Text_JennyIntro:
	.string "If you just float in the sea like\n"
	.string "this, POKéMON come around to play.$"

Route124_Text_JennyDefeat:
	.string "Oh, darn.\n"
	.string "I've gone and lost.$"

Route124_Text_JennyPostBattle:
	.string "While swimming, I noticed that some\n"
	.string "POKéMON attack, and some just watch.\p"
	.string "I guess POKéMON have personalities\n"
	.string "of their own.$"

Route124_Text_JennyRegister:
	.string "It's only on a whim, but maybe I'll get\n"
	.string "you to register me in your POKéNAV.$"

Route124_Text_JennyRematchIntro:
	.string "If you just float in the sea like this,\n"
	.string "TRAINERS challenge you!$"

Route124_Text_JennyRematchDefeat:
	.string "That's strange…\n"
	.string "I lost again…$"

Route124_Text_JennyPostRematch:
	.string "This has nothing to do with anything,\n"
	.string "but maybe I'll visit the TRICK HOUSE.$"

Route124_Text_GraceIntro:
	.string "I'm growing bored of swimming…\n"
	.string "How about a battle?$"

Route124_Text_GraceDefeat:
	.string "I had no idea that you were\n"
	.string "this strong!$"

Route124_Text_GracePostBattle:
	.string "All the effort you put in must have\n"
	.string "made you this strong.$"

Route124_Text_ChadIntro:
	.string "Fufufufu… I dive deep underwater\n"
	.string "to go deep under cover.\l"
	.string "Plumbing the depths is where I excel!$"

Route124_Text_ChadDefeat:
	.string "Glub, glub, glub…\n"
	.string "I'm sinking…$"

Route124_Text_ChadPostBattle:
	.string "I have it on good authority that\n"
	.string "there's a DIVE spot around here.\p"
	.string "It gives me the urge to go deep\n"
	.string "again…$"

Route124_Text_LilaIntro:
	.string "LILA: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Let's battle so I won't have to dwell\n"
	.string "on that!$"

Route124_Text_LilaDefeat:
	.string "LILA: ROY! It's your fault we lost!\n"
	.string "You're in for it later!$"

Route124_Text_LilaPostBattle:
	.string "LILA: Sigh…\p"
	.string "If only it wasn't my little brother\n"
	.string "next to me, but a nice boyfriend…$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA: You're planning to battle us?\n"
	.string "Not unless you have two POKéMON.$"

Route124_Text_RoyIntro:
	.string "ROY: My big sister is tough at POKéMON!\p"
	.string "Don't cry when you lose!$"

Route124_Text_RoyDefeat:
	.string "ROY: Uh-oh…\n"
	.string "My big sister will chew me out…$"

Route124_Text_RoyPostBattle:
	.string "ROY: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "That's why she doesn't have a\n"
	.string "boyfriend.$"

Route124_Text_LilaRoyRegister:
	.string "ROY: Will you battle with us again?\n"
	.string "But take it easy next time, okay?$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY: Did you want to battle us?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_LilaRematchIntro:
	.string "LILA: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Oh, hi, it's been a while. Let's battle\n"
	.string "so I won't have to dwell on things!$"

Route124_Text_LilaRematchDefeat:
	.string "LILA: ROY!\n"
	.string "It's your fault we lost again!\p"
	.string "We're having a training session later!$"

Route124_Text_LilaPostRematch:
	.string "LILA: Sigh…\p"
	.string "If I had a nice boyfriend, we'd beat\n"
	.string "anyone with lovely combinations…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA: You're planning to battle us?\n"
	.string "Not unless you have two POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "ROY: If we lose, I'll catch heck.\n"
	.string "I'm going to go totally all out!$"

Route124_Text_RoyRematchDefeat:
	.string "ROY: Uh-oh…\n"
	.string "My big sister will chew me out again.$"

Route124_Text_RoyPostRematch:
	.string "ROY: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "She's going to make me train really\n"
	.string "hard with POKéMON later…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY: Did you want to battle us?\n"
	.string "Bring two POKéMON, then.$"

Route124_Text_DeclanIntro:
	.string "Here I am swimming by my lonesome\n"
	.string "on this wide, beautiful sea.\p"
	.string "There's no other word for it.\n"
	.string "This is pathetic!$"

Route124_Text_DeclanDefeat:
	.string "I'm feeling blue.\n"
	.string "Blue as the sky…$"

Route124_Text_DeclanPostBattle:
	.string "I should chat up lady SWIMMERS\n"
	.string "and invite them on a long swim.$"

Route124_Text_IsabellaIntro:
	.string "I'm not going to lose to some\n"
	.string "surfer TRAINER.$"

Route124_Text_IsabellaDefeat:
	.string "I've only got sweat in my eyes!\n"
	.string "I am not crying!$"

Route124_Text_IsabellaPostBattle:
	.string "You can find pretty coloured shards\n"
	.string "of things around here.$"

Route125_Text_NolenIntro:
	.string "I heard you approaching, so I hung\n"
	.string "around for you!$"

Route125_Text_NolenDefeat:
	.string "I surrender!$"

Route125_Text_NolenPostBattle:
	.string "Sound travels faster in water than\n"
	.string "it does through air.$"

Route125_Text_StanIntro:
	.string "Hey, there!\n"
	.string "Check out my sweet POKéMON!$"

Route125_Text_StanDefeat:
	.string "I floundered…$"

Route125_Text_StanPostBattle:
	.string "I was blown away by HORSEA's charm,\n"
	.string "so I started swimming, too.$"

Route125_Text_TanyaIntro:
	.string "I'm tired of swimming.\n"
	.string "Are you up for a battle with me?$"

Route125_Text_TanyaDefeat:
	.string "You're too much!$"

Route125_Text_TanyaPostBattle:
	.string "Whew…\n"
	.string "Which way is it to MOSSDEEP CITY?$"

Route125_Text_SharonIntro:
	.string "How would you like to take on the\n"
	.string "WATER-type POKéMON I raised?$"

Route125_Text_SharonDefeat:
	.string "Lost it…$"

Route125_Text_SharonPostBattle:
	.string "Your power… You're the real deal.\n"
	.string "I'm amazed!$"

Route125_Text_ErnestIntro:
	.string "Ahoy! I'm a buff, tough SAILOR!\n"
	.string "I've braved the world's seas!$"

Route125_Text_ErnestDefeat:
	.string "Gwrroooar!\n"
	.string "I couldn't win!$"

Route125_Text_ErnestPostBattle:
	.string "The tide ebbs and flows inside the\n"
	.string "SHOAL CAVE.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Did you know?$"

Route125_Text_ErnestRegister:
	.string "Register me in your POKéNAV,\n"
	.string "and I'll tell you something good.$"

Route125_Text_ErnestRematchIntro:
	.string "It's high time I get my payback\n"
	.string "from you! Come on, we're battling!$"

Route125_Text_ErnestRematchDefeat:
	.string "I couldn't win!\n"
	.string "I flat out couldn't win!$"

Route125_Text_ErnestRematchPostBattle:
	.string "The SHOAL CAVE…\p"
	.string "There are places you can and can't\n"
	.string "get to depending on the rise and fall\l"
	.string "of the tide.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Don't forget!$"

Route125_Text_KimIntro:
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE. Someone told me.\l"
	.string "Are you going to see him, too?$"

Route125_Text_KimDefeat:
	.string "KIM: I thought we would win.$"

Route125_Text_KimPostBattle:
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE, doesn't he?\p"
	.string "Let's go see him, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: No, no, no! You need two POKéMON,\n"
	.string "or it's just no good!$"

Route125_Text_IrisIntro:
	.string "IRIS: KIM, can you tell me what we're\n"
	.string "looking for out here?$"

Route125_Text_IrisDefeat:
	.string "IRIS: Oh, we came sort of close.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: KIM, are we really going into\n"
	.string "the SHOAL CAVE?\l"
	.string "We'll get all wet.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Oh, we could never, ever do\n"
	.string "anything like a 2-on-1 battle.$"

Route125_Text_PresleyIntro:
	.string "Why would a BIRDKEEPER like me\n"
	.string "come out to the sea?$"

Route125_Text_PresleyDefeat:
	.string "Okay.\n"
	.string "I'll tell you why I'm here.$"

Route125_Text_PresleyPostBattle:
	.string "I put a message in a bottle and put\n"
	.string "it out to sea.\p"
	.string "I'm sure that a girl SWIMMER will\n"
	.string "find it!$"

Route125_Text_AuronIntro:
	.string "Hey! Was it you throwing garbage\n"
	.string "into the sea?$"

Route125_Text_AuronDefeat:
	.string "Oh, you weren't throwing trash into\n"
	.string "the sea.$"

Route125_Text_AuronPostBattle:
	.string "I found an unsightly bottle bobbing\n"
	.string "in the waves earlier.\p"
	.string "It angers me that someone would\n"
	.string "pollute the sea!$"

Route126_Text_BarryIntro:
	.string "Swimming is a full-body workout!\n"
	.string "You will get fit!$"

Route126_Text_BarryDefeat:
	.string "I admit it!\n"
	.string "You win!$"

Route126_Text_BarryPostBattle:
	.string "Thanks to my daily swimming routine…\n"
	.string "Look! Feast your eyes on this physique!$"

Route126_Text_DeanIntro:
	.string "This towering white mountain of rock\n"
	.string "is SOOTOPOLIS CITY.$"

Route126_Text_DeanDefeat:
	.string "I was done in?$"

Route126_Text_DeanPostBattle:
	.string "I can't find the entrance to\n"
	.string "SOOTOPOLIS. Where could it be?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu!\n"
	.string "I'm a mermaid!$"

Route126_Text_NikkiDefeat:
	.string "My fantasy burst as if it were a bubble!\n"
	.string "Blub, blub, blub…$"

Route126_Text_NikkiPostBattle:
	.string "You thrashed me… I want to\n"
	.string "disappear in a wave of despair…$"

Route126_Text_BrendaIntro:
	.string "Hello, kiddo!\n"
	.string "Want a battle with me?$"

Route126_Text_BrendaDefeat:
	.string "Oh, noooooh!$"

Route126_Text_BrendaPostBattle:
	.string "I love frolicking with POKéMON in\n"
	.string "the sea like this!$"

Route126_Text_PabloIntro:
	.string "Check out this sculpted body!\n"
	.string "I'm more cut than a BLACK BELT!$"

Route126_Text_PabloDefeat:
	.string "Whoops! Too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_PabloPostBattle:
	.string "Losing to you stimulated my senses!\n"
	.string "I'll train myself and POKéMON harder!$"

Route126_Text_PabloRegister:
	.string "Yep, you're not bad at all!\n"
	.string "I'd like to get to know you more!$"

Route126_Text_PabloRematchIntro:
	.string "Check out this beautiful body!\n"
	.string "I'm more shapely than a SWIMMER!$"

Route126_Text_PabloRematchDefeat:
	.string "Whoops! Really too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_PabloPostRematch:
	.string "I'm going to train even harder!\n"
	.string "You're a great motivator!\l"
	.string "You have to come back again!$"

Route126_Text_LeonardoIntro:
	.string "I couldn't even swim last year,\n"
	.string "but now I'm a decent SWIMMER.\p"
	.string "I think I'm capable of anything now.$"

Route126_Text_LeonardoDefeat:
	.string "Sheesh, getting greedy didn't do\n"
	.string "a thing for me.$"

Route126_Text_LeonardoPostBattle:
	.string "If you practice at something,\n"
	.string "you will get better at it.\p"
	.string "You're young--don't be afraid to\n"
	.string "try all sorts of things!$"

Route126_Text_IsobelIntro:
	.string "If seawater gets up your nose,\n"
	.string "doesn't it feel terrible?$"

Route126_Text_IsobelDefeat:
	.string "Ack! Why, you…\n"
	.string "Glub!$"

Route126_Text_IsobelPostBattle:
	.string "Ooh, I choked on some water!\n"
	.string "It's bitter! It's salty!!$"

Route126_Text_SiennaIntro:
	.string "I'm throwing my whole heart\n"
	.string "into this!$"

Route126_Text_SiennaDefeat:
	.string "You had more heart!$"

Route126_Text_SiennaPostBattle:
	.string "I need to cool down now…\n"
	.string "I think I'll go for a dive.$"

Route130_Text_RodneyIntro:
	.string "What a surprise! I didn't expect to\n"
	.string "see a TRAINER out in the sea.\p"
	.string "I think we should battle!$"

Route130_Text_RodneyDefeat:
	.string "This kid's awfully tough…$"

Route130_Text_RodneyPostBattle:
	.string "Your eyes have that look of someone\n"
	.string "who's experienced harsh challenges\l"
	.string "and won. It suits you well!$"

Route130_Text_KatieIntro:
	.string "In the deep blue sea,\n"
	.string "my shattered blue heart finds\l"
	.string "comfort among waves.$"

Route130_Text_KatieDefeat:
	.string "Like the vast blue sea,\n"
	.string "the world of POKéMON spans\l"
	.string "depths beyond belief.$"

Route130_Text_KatiePostBattle:
	.string "The world's children dream\n"
	.string "of one day becoming\l"
	.string "the POKéMON CHAMPION.$"

Route130_Text_SantiagoIntro:
	.string "Floating on the open sea like this…\n"
	.string "It's peaceful.$"

Route130_Text_SantiagoDefeat:
	.string "I needed to be a little less peaceful!$"

Route130_Text_SantiagoPostBattle:
	.string "Swimming and battling like this…\n"
	.string "I'm one happy guy…$"

Route131_Text_RichardIntro:
	.string "The sea is teeming with POKéMON.\n"
	.string "It's not easy swimming, I tell you.$"

Route131_Text_RichardDefeat:
	.string "POKéMON raised by TRAINERS are\n"
	.string "seriously tough…$"

Route131_Text_RichardPostBattle:
	.string "Gasp… Gasp…\n"
	.string "I'm wiped out…\p"
	.string "The going's easy. It's the leaving\n"
	.string "that's the hard part.\p"
	.string "Will I have any energy left to make\n"
	.string "the return trip?$"

Route131_Text_HermanIntro:
	.string "The sea… The sea… The sea…\n"
	.string "The sea as far as these eyes can see!\l"
	.string "I'm sick and tired of the sea!$"

Route131_Text_HermanDefeat:
	.string "Bleah!$"

Route131_Text_HermanPostBattle:
	.string "Bored I am by the sea, but swim I must.\p"
	.string "I'm a born swimmer!\n"
	.string "That's what I am.$"

Route131_Text_SusieIntro:
	.string "Hi, sweetie, wait!\n"
	.string "We should battle, you and I!$"

Route131_Text_SusieDefeat:
	.string "You're tough in spite of the way\n"
	.string "you look!$"

Route131_Text_SusiePostBattle:
	.string "Did you see a guy over there who whines\n"
	.string "that he's bored of the sea?\p"
	.string "That's all talk.\n"
	.string "He's hopelessly in love with the sea!$"

Route131_Text_KaraIntro:
	.string "Why do men love bathing suits so much?\p"
	.string "They all ogle me!$"

Route131_Text_KaraDefeat:
	.string "I'm out of my depth!$"

Route131_Text_KaraPostBattle:
	.string "Maybe it's not my bathing suit that\n"
	.string "makes men look. It must be my beauty!$"

Route131_Text_ReliIntro:
	.string "RELI: We'll work together as siblings\n"
	.string "to take you on!$"

Route131_Text_ReliDefeat:
	.string "RELI: We couldn't win even though we\n"
	.string "worked together…$"

Route131_Text_ReliPostBattle:
	.string "RELI: The people of PACIFIDLOG are\n"
	.string "together with the sea and POKéMON from\l"
	.string "the time they are born.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI: You don't have two POKéMON?\n"
	.string "We can't enjoy a battle, then.$"

Route131_Text_IanIntro:
	.string "IAN: I'm doing my best together with\n"
	.string "my sis!$"

Route131_Text_IanDefeat:
	.string "IAN: I did my best with my sis,\n"
	.string "but we still couldn't win…$"

Route131_Text_IanPostBattle:
	.string "IAN: You know how PACIFIDLOG is\n"
	.string "a floating town?\p"
	.string "So, wherever there is the sea,\n"
	.string "that's a part of PACIFIDLOG!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: If you have two POKéMON,\n"
	.string "we'll take you on!$"

Route131_Text_TaliaIntro:
	.string "If you can beat me, I'll give you some\n"
	.string "great information!$"

Route131_Text_TaliaDefeat:
	.string "Oh?\n"
	.string "Did I lose?$"

Route131_Text_TaliaPostBattle:
	.string "There is an odd place nearby.\n"
	.string "There's a huge tower there.\l"
	.string "Why don't you go take a look?$"

Route131_Text_KevinIntro:
	.string "The people of PACIFIDLOG are\n"
	.string "a peaceful bunch.\p"
	.string "They never get angry.\n"
	.string "That goes for me, too.$"

Route131_Text_KevinDefeat:
	.string "Oops!$"

Route131_Text_KevinPostBattle:
	.string "Tch! …Oh, wait.\n"
	.string "I'm not angry. Honestly!\p"
	.string "But, boy, you're strong!\n"
	.string "Hahaha!$"

Route132_Text_GilbertIntro:
	.string "I used to catch colds all the time as\n"
	.string "a kid, but I became totally fit after\l"
	.string "I started swimming.$"

Route132_Text_GilbertDefeat:
	.string "I crave more power…$"

Route132_Text_GilbertPostBattle:
	.string "TRAINERS travel the fields and\n"
	.string "mountains, so they must be fit, too.$"

Route132_Text_DanaIntro:
	.string "I try not to swim where the currents\n"
	.string "are too strong.$"

Route132_Text_DanaDefeat:
	.string "Oh, please, no!$"

Route132_Text_DanaPostBattle:
	.string "If I get swept away, I'll lose all my\n"
	.string "sense of place…$"

Route132_Text_RonaldIntro:
	.string "Win or lose, you'll never know until\n"
	.string "you try!$"

Route132_Text_RonaldDefeat:
	.string "Waah!\n"
	.string "I sank in defeat!$"

Route132_Text_RonaldPostBattle:
	.string "I never battle when I know I'll win.\n"
	.string "I like to battle at the razor's edge of\l"
	.string "victory and defeat!$"

Route132_Text_KiyoIntro:
	.string "I contemplate POKéMON 24 hours a day.\n"
	.string "How could you possibly beat me?$"

Route132_Text_KiyoDefeat:
	.string "I lose.\n"
	.string "I will concede defeat.$"

Route132_Text_KiyoPostBattle:
	.string "Urggh…\n"
	.string "You're a POKéMON fanatic, aren't you?\p"
	.string "You must contemplate POKéMON 24 hours\n"
	.string "a day, don't you?$"

Route132_Text_MakaylaIntro:
	.string "I'm always with my husband,\n"
	.string "but I can win even without him.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, I guess I wasn't good enough.$"

Route132_Text_MakaylaPostBattle:
	.string "That young man over there looks just\n"
	.string "like my husband when he was young.\p"
	.string "He's making me blush!$"

Route132_Text_JonathanIntro:
	.string "Someone's been watching me intently.\n"
	.string "Was it you?$"

Route132_Text_JonathanDefeat:
	.string "Wow!\n"
	.string "That's pretty strong, all right!$"

Route132_Text_JonathanPostBattle:
	.string "I can't shake this feeling that\n"
	.string "someone's watching me.\p"
	.string "I can't concentrate!$"

Route132_Text_PaxtonIntro:
	.string "Now where could my wife have gone?\n"
	.string "I'm always with her.\l"
	.string "I wonder if I can win on my own.$"

Route132_Text_PaxtonDefeat:
	.string "Ah, I see that I couldn't manage\n"
	.string "to win on my own after all.$"

Route132_Text_PaxtonPostBattle:
	.string "My wife must be looking for me.\n"
	.string "I'd best go find her right away.$"

Route132_Text_DarcyIntro:
	.string "I liked training here by myself.\n"
	.string "It's awful that all these people came!$"

Route132_Text_DarcyDefeat:
	.string "Okay! I won't complain about other\n"
	.string "people being here.$"

Route132_Text_DarcyPostBattle:
	.string "I suppose I can partner up with that\n"
	.string "old man and challenge that other team.$"

Route133_Text_FranklinIntro:
	.string "Did the currents carry you here, too?\n"
	.string "This must have been fated.\l"
	.string "Let's battle!$"

Route133_Text_FranklinDefeat:
	.string "Strong!\n"
	.string "Too much so!$"

Route133_Text_FranklinPostBattle:
	.string "It's just my luck that a tough TRAINER\n"
	.string "like you would drift here…\l"
	.string "I must be cursed…$"

Route133_Text_DebraIntro:
	.string "I've led a life of woe and misery…\n"
	.string "I've been cast away, and this is where\l"
	.string "I've drifted…$"

Route133_Text_DebraDefeat:
	.string "Another loss…$"

Route133_Text_DebraPostBattle:
	.string "A life adrift…\n"
	.string "I don't want it anymore!$"

Route133_Text_LindaIntro:
	.string "Welcome!\n"
	.string "I've been expecting you!$"

Route133_Text_LindaDefeat:
	.string "No! Please!$"

Route133_Text_LindaPostBattle:
	.string "A strong child TRAINER…\n"
	.string "That's so annoying!$"

Route133_Text_WarrenIntro:
	.string "I want to win like everyone else, but I\n"
	.string "won't raise POKéMON like everyone else.$"

Route133_Text_WarrenDefeat:
	.string "Darn it!\n"
	.string "My way is still too slack!$"

Route133_Text_WarrenPostBattle:
	.string "It's way more fun to do things the way\n"
	.string "I want than to be like everybody else.\l"
	.string "I mean, that's obvious!$"

Route133_Text_BeckIntro:
	.string "I came all the way out here with my\n"
	.string "BIRD POKéMON.$"

Route133_Text_BeckDefeat:
	.string "You…\n"
	.string "You're stunningly cool!$"

Route133_Text_BeckPostBattle:
	.string "I'd like to go back to FORTREE,\n"
	.string "but I've grown to like this place, too.$"

Route133_Text_MollieIntro:
	.string "I must have battled thousands\n"
	.string "of times. I've lost count.$"

Route133_Text_MollieDefeat:
	.string "I may have lost thousands of times,\n"
	.string "but a loss still stings.$"

Route133_Text_MolliePostBattle:
	.string "Keep at this, youngster. So you can\n"
	.string "become like my husband and me.$"

Route133_Text_ConorIntro:
	.string "Young people are too happy to go with\n"
	.string "the flow. They're without direction.$"

Route133_Text_ConorDefeat:
	.string "You have a firm sense of purpose.$"

Route133_Text_ConorPostBattle:
	.string "Don't let others lead you astray.\n"
	.string "Don't lose direction as you grow older.$"

Route134_Text_JackIntro:
	.string "Even those POKéMON that can swim are\n"
	.string "carried along by the rapid currents.$"

Route134_Text_JackDefeat:
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:
	.string "I think POKéMON enjoy the fast-running\n"
	.string "currents around these parts.$"

Route134_Text_LaurelIntro:
	.string "My LUVDISC are looking for a fun\n"
	.string "match. Will you join us?$"

Route134_Text_LaurelDefeat:
	.string "Oopsie!$"

Route134_Text_LaurelPostBattle:
	.string "There's a collector who's after\n"
	.string "the SCALES of LUVDISC.$"

Route134_Text_AlexIntro:
	.string "Okeydokey! That's enough rest, gang!\n"
	.string "It's time for a match!$"

Route134_Text_AlexDefeat:
	.string "Tuckered out again…$"

Route134_Text_AlexPostBattle:
	.string "My BIRD POKéMON get tired quickly after\n"
	.string "a long flight…$"

Route134_Text_HitoshiIntro:
	.string "You're a POKéMON TRAINER.\n"
	.string "No need for words. We battle now.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "It was I who challenged you, and yet\n"
	.string "I lost. I am deeply shamed…$"

Route134_Text_AaronIntro:
	.string "The savage tide in this area serves to\n"
	.string "make us stronger than ever.$"

Route134_Text_AaronDefeat:
	.string "I willingly concede defeat.$"

Route134_Text_AaronPostBattle:
	.string "We will return for more training at\n"
	.string "METEOR FALLS.\p"
	.string "If you'd like, you should go, too.\n"
	.string "It will definitely toughen you up!$"

Route134_Text_KelvinIntro:
	.string "O-our boat!\n"
	.string "The tide carried it away!$"

Route134_Text_KelvinDefeat:
	.string "Awawawawah!\n"
	.string "Please, stop! Please!$"

Route134_Text_KelvinPostBattle:
	.string "If we can't SURF, how are we supposed\n"
	.string "to get home?\p"
	.string "Actually, I know a fainted POKéMON\n"
	.string "can still SURF, but it feels wrong.$"

Route134_Text_MarleyIntro:
	.string "Can your POKéMON dodge our\n"
	.string "lightning-quick attacks?$"

Route134_Text_MarleyDefeat:
	.string "I never knew such a technique existed!\n"
	.string "You've defeated us thoroughly.$"

Route134_Text_MarleyPostBattle:
	.string "I haven't lost my passion for speed.\n"
	.string "I will try harder.$"

Route134_Text_ReynaIntro:
	.string "My POKéMON can't be taken down\n"
	.string "easily!$"

Route134_Text_ReynaDefeat:
	.string "You're kidding!\n"
	.string "Explain how I lost!$"

Route134_Text_ReynaPostBattle:
	.string "Haha!\n"
	.string "You won, all right!\p"
	.string "I'll work my way back up by taking on\n"
	.string "TRAINERS I happen to meet!$"

Route134_Text_HudsonIntro:
	.string "Listen, have you seen another SAILOR\n"
	.string "around here?$"

Route134_Text_HudsonDefeat:
	.string "Now, that's something!$"

Route134_Text_HudsonPostBattle:
	.string "Our boat drifted out to sea.\p"
	.string "My buddy's a timid fellow, so I'm\n"
	.string "worried about him.$"
