gTrickHouse_Mechadoll_Caterpie::
	.string "Caterpie$"

gTrickHouse_Mechadoll_Weedle::
	.string "Weedle$"

gTrickHouse_Mechadoll_Beedrill::
	.string "Beedrill$"

gTrickHouse_Mechadoll_Pidgey::
	.string "Pidgey$"

gTrickHouse_Mechadoll_Rattata::
	.string "Rattata$"

gTrickHouse_Mechadoll_Spearow::
	.string "Spearow$"

gTrickHouse_Mechadoll_Zubat::
	.string "Zubat$"

gTrickHouse_Mechadoll_Paras::
	.string "Paras$"

gTrickHouse_Mechadoll_Meowth::
	.string "Meowth$"

gTrickHouse_Mechadoll_Golduck::
	.string "Golduck$"

gTrickHouse_Mechadoll_Abra::
	.string "Abra$"

gTrickHouse_Mechadoll_Drowzee::
	.string "Drowzee$"

gTrickHouse_Mechadoll_Goldeen::
	.string "Goldeen$"

gTrickHouse_Mechadoll_Starmie::
	.string "Starmie$"

gTrickHouse_Mechadoll_Magikarp::
	.string "Magikarp$"

gTrickHouse_Mechadoll_BurnHeal::
	.string "Burn Heal$"

gTrickHouse_Mechadoll_SodaPop::
	.string "Soda Pop$"

gTrickHouse_Mechadoll_SamePrice::
	.string "Same price$"

gTrickHouse_Mechadoll_50Yen::
	.string "¥50$"

gTrickHouse_Mechadoll_100Yen::
	.string "¥100$"

gTrickHouse_Mechadoll_Nothing::
	.string "Nothing$"

gTrickHouse_Mechadoll_CostMore::
	.string "They will cost more.$"

gTrickHouse_Mechadoll_CostLess::
	.string "They will cost less.$"

gTrickHouse_Mechadoll_Male::
	.string "Male$"

gTrickHouse_Mechadoll_Female::
	.string "Female$"

gTrickHouse_Mechadoll_Neither::
	.string "Neither$"

gTrickHouse_Mechadoll_SameNumber::
	.string "Same number$"

gTrickHouse_Mechadoll_None::
	.string "None$"

gTrickHouse_Mechadoll_One::
	.string "1$"

gTrickHouse_Mechadoll_Two::
	.string "2$"

gTrickHouse_Mechadoll_Three::
	.string "3$"

gTrickHouse_Mechadoll_Five::
	.string "5$"

gTrickHouse_Mechadoll_Six::
	.string "6$"

gTrickHouse_Mechadoll_Seven::
	.string "7$"

gTrickHouse_Mechadoll_Fourteen::
	.string "14$"

gTrickHouse_Mechadoll_Fifteen::
	.string "15$"

gTrickHouse_Mechadoll_Sixteen::
	.string "16$"
